### ISSUE TITLE
Distinct error state for encoding vs infrastructure

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1004]
Currently, there i one combined error message in the player if there is either kind of problem: `The media could not be loaded, either because the server or network failed or because the format is not supported`. This is confusing both to the end user and to curators and storage workers trying to figure out easily what is going on, for example in a support scenario. Can we make these to errors distinct?

- [x] #1007
- [ ] Prepare designs for each specific case
- [ ] Implement designs for specific cases

**Comment by kdembler** [comment]
@bedeho Did some digging around and it's not looking that promising. What we can tell for sure is if the storage provider fails to respond to the request for the asset and we already do that. However, the HTML Media standard doesn't support reporting different types of issues with video playback. So it seems we won't be able to differentiate between invalid codec and storage provider failing to provide file, it's the same error in standard (media unplayable). So I'm unsure what exactly we want to do about this

**Comment by bedeho** [comment]
If we can tell that the storage provider is sending _something_, which I presume should be possible... if only by doing a separate download request outside the player even - just for error decoding purposes, then any failure to playback in the player  could be attributed to corrupt data, which means bad encoding, or junk data or whatever. Shouldnt that work?

**Comment by kdembler** [comment]
That should mostly work. We already do a separate request outside of the player, but we can't for sure tell that SP acts the same on subsequent request. They should though, so we can assume that's the case. If we're fine with putting those types of corrupt data into a single category then I guess we're fine. I'm not sure what we should present to the user though. If the storage provider fails to respond, we won't show an error because we will try again with a different one. So it seems that, in terms of what we present to the user, the only case left is corrupted data and I think our generic message works for that? (`The video could not be loaded because of an error. Please try again later. If the issue persists, reach out to our community on Discord.`)

**Comment by bedeho** [comment]
I agree, good point, I would clarify that the encoding was not playable, or the data was corrupt, as it gives more direct and precise information.

**Comment by kdembler** [comment]
Sure, we can do that

**Comment by kdembler** [comment]
@drillprop adding it to your milestone, let's update the error message. Let's try: `The video could not be played because the data is corrupted or the encoding is not supported. This issue has been logged. If you need support, reach out to our community on Discord.`
