### ISSUE TITLE
Refreshing right after upload

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1063]
This issue is related to second scenario from : https://github.com/Joystream/atlas/issues/1108

> ### Refreshing right after upload

> right after the upload is finished, query node will still report the asset as PENDING - not finished. When Atlas loads, it asks the query node for all unfinished uploads and presents them to the user as failed and waiting for upload resume. If the user refreshed right after the upload finished, Atlas will ask query node and get information that this asset has failed, even though it's just waiting for processing. This can give the user impression that something didn't work properly. If the user waits a couple seconds and refresh again, the asset will disappear from the missing list.

This issue is meant to deal with improving the UI to better represent states : uploading, processing and done to address the above scenario.

**Comment by KubaMikolajczyk** [comment]
After our discussion we met together with Klaudiusz to come up with solution for the problem.

### **Problem:**
 users tend to refresh right after getting notified that the upload is finished and often what they see is an error on the file - its because the file is still being processed and when user refreshes we deliver a message about an error.

### **Solution:** 
Introduce the processing state for both individual asset states & upload status group as a whole 

### **Links:**

Prototype (It autoplays itself dont click anything, if you want you can restart the prototype using "r" button) : [Link to prototype](https://www.figma.com/proto/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?page-id=12476%3A326798&node-id=12515%3A332222&viewport=1515%2C764%2C0.6417851448059082&scaling=min-zoom&starting-point-node-id=12515%3A332222)

Figma file: [Link to file](https://www.figma.com/file/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?node-id=12515%3A332222)

**Comment by KubaMikolajczyk** [comment]
https://user-images.githubusercontent.com/31144205/128531529-5833a83f-c9dc-4126-8cc0-3b813739ba6b.mov

**Comment by bedeho** [comment]
> users tend to refresh right after getting notified that the upload is finished and often what they see is an error on the file - its because the file is still being processed and when user refreshes we deliver a message about an error.

Isn't the core problem here that we are notifying users about an event which does not coincide with what the genuinely care about, no different to the original sin of notifyng users about the original extrinsic being being mined? The event users care about, so much so that we should draw their attention to it, is really: `your video is now ready to be viewed`

Here are some thoughts.

1. I assume/hope these changes are only part of the solution to the overall upload flow problem? I think the misleading success dialog on the transaction getting mined & the registration getting picked up by the query node, is also a big part of the problem here. Arguably there should be no success dialog at all. Also, there must be some handling of this state on the playback page. Lastly, how snackbars are used to signal certain events is also relevant.

Is there an integrated plan for how to use, or not use, all of these in the final upload flow?

2. Overall I think the changes to the uploading screen are a step in the right direction, but I the visual representation of each upload still is not as effective as it could be in representing the key information of interest to the user at any given time. The major two states we need to distinguish between for an entire upload are _uploading_, _processing_, _finished_. Right now, this distinction is only captured by some low contrast text on the far right of each upload, and also uploading is emphasized a bit with the low contrast background progressbar. I think we can do better. Each of the state needs to be much more distinct from the other. For example a major high contrast indicator/animation that catches the eye, no less than what we have for the assets in each upload. The current large static icon showing the video is doing very little productive in a critical visual location which arguably should hold something like this. We should probably also have some very clear transitions between the different stages, in particular into _finished_, to distinguish it as being the actual final relevant milestone. If we are going to have anything in the snackbar, I would limit it to this one event when the user is not on the upload screen. Arguably, I don't even think we should have the detailed asset dropdown visible for a new upload by default, its too much information for most users most of the time - it does not help them do anything.

**Comment by KubaMikolajczyk** [comment]
Just to answer feedback above 👆 

> Isn't the core problem here that we are notifying users about an event which does not coincide with what the genuinely care about, no different to the original sin of notifyng users about the original extrinsic being being mined? The event users care about, so much so that we should draw their attention to it, is really: your video is now ready to be viewed

I agree with that!

> 1.I assume/hope these changes are only part of the solution to the overall upload flow problem? I think the misleading success dialog on the transaction getting mined & the registration getting picked up by the query node, is also a big part of the problem here. Arguably there should be no success dialog at all. Also, there must be some handling of this state on the playback page. Lastly, how snackbars are used to signal certain events is also relevant.

Yes it was only a minor part of improving the whole uploading flow - I renamed this issue to deal only with that part of the problem - to better match the solutions presented here - all other issues are separate and included in the milestone

>  2.Overall I think the changes to the uploading screen are a step in the right direction, but I the visual representation of each upload still is not as effective as it could be in representing the key information of interest to the user at any given time. The major two states we need to distinguish between for an entire upload are uploading, processing, finished. Right now, this distinction is only captured by some low contrast text on the far right of each upload, and also uploading is emphasized a bit with the low contrast background progressbar. I think we can do better. Each of the state needs to be much more distinct from the other. For example a major high contrast indicator/animation that catches the eye, no less than what we have for the assets in each upload. The current large static icon showing the video is doing very little productive in a critical visual location which arguably should hold something like this. We should probably also have some very clear transitions between the different stages, in particular into finished, to distinguish it as being the actual final relevant milestone. If we are going to have anything in the snackbar, I would limit it to this one event when the user is not on the upload screen. Arguably, I don't even think we should have the detailed asset dropdown visible for a new upload by default, its too much information for most users most of the time - it does not help them do anything.

I agree with the feedback - thank you for such detailed description! I will iterate on that and make each of the phases much more distinct. If it comes to the fact that the details of the asset group were visible from the start - its because at this point I only visualised that final expanded part of the flow - but I hear you - in the more holistic aproach to the flow that I'm working on right now I will show the collapsed version as well and it should definitelly be the default one when a user enters my uploads page.
