### ISSUE TITLE
Autoplay not working when you go to the video through link or refresh the site

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#1114]
This might need some investigation but If you go to any video through the link for example to https://atlas-dev.netlify.app/video/1168 autoplay, for some reason, not always working. 
The same situation is happening when you refresh the site. 
We shouldn't change mobile behavior, though. I've discussed this with the designer and we decided to leave this as it is.

**Comment by kdembler** [comment]
This isn't really a bug but a browser behaviour. For some time now, pages are not allowed to play videos (with sound on) automatically, unless the user interacts with the document first. That's why if you go to home page and click a video, it will play automatically, because you've already interacted with the site. When you open via link, no interaction was done so video will not autoplay.

You can check out how Chrome handles these scenarios: https://developer.chrome.com/blog/autoplay/ TLDR, the browser keeps an index of your engagement with specific sites. If you go to `play.josytream.org` often and play video with sound, at some point, the browser will allow autoplay without interaction.

So, given above, not sure what the action for this issue would be.

cc @drillprop @toiletgranny

**Comment by drillprop** [comment]
> You can check out how Chrome handles these scenarios: https://developer.chrome.com/blog/autoplay/ TLDR, the browser keeps an index of your engagement with specific sites. If you go to `play.josytream.org` often and play video with sound, at some point, the browser will allow autoplay without interaction. 

Wow, didn't know that! We can safely close this issue, then.
