### ISSUE TITLE
Featured Category Card component

### ISSUE THREAD

**Issue by eldiegod** [Joystream/atlas#1229]

**Comment by toiletgranny** [comment]
@eldiegod, as I said, overall this looks very good and I really like the treatment of the border disappearing on hover! 

There are some minor details that don't quite match the designs. Here they are:
1. **AS IS:** The video background is being played all the time. It's not looped.
**TO BE:** The video should be played upon hovering only. Should be looped.
2. **AS IS:** Color of the `Featured video` label is currently set to `Neutral / 300`. There's no distance between the label and the title of the video below.
**TO BE:** Color of the `Featured video` label should be set to `Neutral / 200`, and there should be `4px` of distance between it and the title below.
3. **AS IS:** It seems like the "Science & Technology" icon has been exported without the surrounding `24x24` container around it.
**TO BE:** All icons should be exported with the `24x24` container so that they are positioned based on this wrapper.

Other than this: 👌👌
