### ISSUE TITLE
General Category Card component

### ISSUE THREAD

**Issue by eldiegod** [Joystream/atlas#1230]

**Comment by toiletgranny** [comment]
@eldiegod, as with the Featured Category Card, this one looks stunning, too!

There are also some minor details that don't quite match the designs. Here they are:
1. **AS IS:** The pie chart is not centered vertically with the "123 videos" label.
**TO BE:** It should be vertically centered. I think `align-items: center` on the `.VideosNumberContainer` should do the trick.
2. **AS IS:** The grayscale filter on the cover image doesn't animate on hover.
**TO BE:** If possible, the grayscale filter should be animated with the same timing and easing as all the other parameters on hover.
3. **AS IS:** It seems like the blue-ish color overlay is missing on the cover image, the image is just grayscale.
**TO BE:** In Figma, I have this additional "Color overlay" rectangle applied on top of the cover image. Its color is set to `Neutral / 800` and blending mode to `Color`. If possible, it would be great to have this in implementation as well. Happy to jump on a quick call to discuss details around this.
4. **AS IS:** _(It's the same comment as in the Featured Category Card component)_ It seems like the "Science & Technology" icon has been exported without the surrounding `24x24` container around it.
**TO BE:** All icons should be exported with the `24x24` container so that they are positioned based on this wrapper.
