### ISSUE TITLE
Upload flow improvement

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1249]
This issue is meant to be a shared space to post design updates & discuss feedback to all issues from upload flow improvements milestone. 👉  https://github.com/Joystream/atlas/milestone/10

**Comment by KubaMikolajczyk** [comment]
Video update about multiple issues can be found here 👇 
https://play.joystream.org/video/6000

**Comment by bedeho** [comment]
# Feedback

## Prelude

- First off, brilliant work, very impressive. Really appreciate how comprehensive the improvements are, and how the whole journey has been improved in an integrated way 👍 . 
- Second, this actually went well outside of the scope of what I was expecting, in particular the emphasis on the first WYSIWYG screen. I think the work is excellent, but I think we actually probably need a better process for agreeing on sprint scope up front, so I will suggest something about this the next weekly standup. Even good work has to be done at the optimal time, due to prioritization ;). 
- Remember to use ecological assets :D 

## Details

1. This screen where you show  `Correct file`, `Wrong File`, `Storage limit hit`, was that part of the app, or just a panel in the demo? That was a bit confusing
2. Is it possible to provide default values both for category and language to also avoid users to deal with those? or at least language at least?
3. The state indicator for each upload seems to have a spinner that is coupled with the overall upload progress. I think that spinner could be more effective as just a liveness indicator, same as the variation you use in the `processing` stage. When the upload is stuck or very very slow, that would be a great way to communicate to the user that the app is not frozen or anything, and the progress indication is already handled by the background indicator anyway..
4. I don't actually agree that the finalization of the first sequence of dialogs actually does not communicate a success event, I still think it does. The user could easily still conclude that the video should at that point already be consumable. I think a remedy would be to introduce some sort of `processing` like indicator on the preview of the video itself in the `My videos` view that you are sent to directly. That way the transaction success indicator is not confused with a publishing success indicator, and it would also work well if the user refreshed the screen and came back to failed uploading of those videos, which then they would have to be reminded to re-initiate again by going to `My Uplaods` and finding the interrupted upload.
5. The publishing success snackbar was just brilliant! Love it. How will they work if you get many of those at once, do they stack?

**Comment by KubaMikolajczyk** [comment]
To respond to above feedback: 

### Prelude
- Thank you! I'm glad you liked it :)
- Yes I agree, Im looking forward to discuss the suggestion of better scoping for sprints
- Did I say something about "ecological components" in my update? :D Oh boy

### Details
1. Yes, this screen is just a helper to create a gateway for the prototype to different scenarios
2. Thats something I would advice against because if we make a default category we would favour one above the other and this can influence what users choose (additionally it would be highly unlikely we would guess correct the topic of the video), unfortunatelly this goes the same for language - we cannot say that publisher will record by default in english because there is a high chance that this won't be true (Klaudiusz suggested that we could detect the default language of the browser and set it this way but still user can be from england but record natively in russian) - maybe we should just let users choose that by themselves?
3. Thats a great idea I will change it to the same one we use in processing stage!
4. So the idea you introduce here is to design a uniform video tile which would appear in my videos and show that the video is still processing/ uploading? I like it!
5. Currently they would just stack - but as soon as we approach the sprint where we would more carefully define the experiance connected with snackbars - their stacked formes, when they dissapear, their motion - we will think about this particular scenario as well and maybe introduce something much more elegant than just simple stacking.
