### ISSUE TITLE
Designs for the new search experience

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1331]
Based on https://github.com/Joystream/atlas/issues/1320, the scope of this task is to create and document flows for the new search experience, including:
- A new search box, as part of a new top navigation bar,
- A new bottom navigation bar (mobile devices only)
- A new search results page

**Comment by toiletgranny** [comment]
@bedeho Below you can find links to prototypes with the new search experience along with video updates to learn all about it.

## Desktop
- [Video walkthrough on Loom](https://www.loom.com/share/977b0c6d88b64ca9a3cde3bdccfd91ab) (5 min)
- [Searchbar prototype on Figma](https://www.figma.com/proto/oPS9fUKfmX5LNreZoveuZn/Page-Search?node-id=270%3A73084&viewport=283%2C48%2C0.02&scaling=scale-down&starting-point-node-id=270%3A73090&show-proto-sidebar=1)
- [Search results prototype on Figma](https://www.figma.com/proto/oPS9fUKfmX5LNreZoveuZn/Page-Search?node-id=270%3A73084&viewport=283%2C48%2C0.02&scaling=scale-down&starting-point-node-id=287%3A9795&show-proto-sidebar=1)

## Mobile
- [Video walkthrough on Loom](https://www.loom.com/share/4874d37180e143ff83311726705e5b80) (3 min)
- [Searchbar prototype on Figma](https://www.figma.com/proto/oPS9fUKfmX5LNreZoveuZn/Page-Search?node-id=270%3A73084&viewport=283%2C48%2C0.02&scaling=scale-down&starting-point-node-id=418%3A28819&show-proto-sidebar=1)
- [Search results prototype on Figma](https://www.figma.com/proto/oPS9fUKfmX5LNreZoveuZn/Page-Search?node-id=270%3A73084&viewport=283%2C48%2C0.02&scaling=scale-down&starting-point-node-id=388%3A81458&show-proto-sidebar=1)

## Notes
> [...] telling a story about what you tried and why makes it 10x easier to understand what problems you are trying to solve and why.

Bedeho, I remember you appreciated it when I included some additional context and mentioned some other solutions I've been experimenting with in [my previous video update](https://github.com/Joystream/atlas/issues/1132#issuecomment-901031717). I wanted to do the same here, but I figured this would make my video updates 10x as long, and I really wanted to keep them short and concise this time, out of respect for everyone's time. In case you're interested in knowing more about how we came to present the solutions showcased above, you can check out [some of our earlier explorations in Figma](https://www.figma.com/file/oPS9fUKfmX5LNreZoveuZn/Page-Search?node-id=205%3A838). If you'd like to get some commentary on this, please let me know — I'd be happy to record another video. :)

Also, this time I gave Loom a try to record video updates. We've been wanting to do this for some time with @KubaMikolajczyk. It was a lot easier and faster for me. Let me know if you like it, perhaps we could start using it more often. You can also leave your comments directly on Loom.

**Comment by bedeho** [comment]
# Context

- When I look at the search experience, the main thing I am looking for is if we are successfully allowing users to extremly quickly fire off searches and review the primary findings to see if they match the subject matter in mind.
- If I expect something to be rarely used, I will almost always err on the side of removing, even if it's not that salient on its own, as the cumulative effect of many small things that are infrequently used can be significant, and it also adds to the total workload of the tech team.

# Feedback

## Desktop

### Search Bar

- What will be the policy for when to display other recen searches above actual content, in the search drop box? I ask, because we need to be extremly careful to only show this if there is a very strong match to the prior search. If we dont, we will risk very frequently wasting the most precious visual space on results that are not what the user is looking for. So how sure are we that we can really accurately, as technical matter, discern extremly good vs OK prior searches? If not, then I think we should drop it.
- The icon used to the left of each search phrase in the dropdown does not appear to communciate anything, hence I suggest we drop it.
- I don't I can actually even write `/` with a single key on my keyboard, I would need to do shift+7. Not sure how reliable this would be, or how frequently it would be used.
- Showing preview images of videos in the dropdown, while nice, may very likely end up being too slow, as rendering the actual images always has lots of extra delay. This will end up making the search experience much slower, as the user invariably will often wait for assets to render before they do anything.
- Show all x (videos, channels), inline in the dropdown, again feels to me like it will not be used frequently.

### Results Page

- Overall the top section, basically everything before the actual content, takes up a lot of space, and the actual primary content, that is the videos, too far down. Using so much space ot simply reiterate the search search query is not aligned with user goals in my opinion. We should try to really compress this space. Even the tabs & filters, which also take space, in particular when you add the vertical margins, are not entirely trivial to justify in my opinion.
- My assumption is that when someone is seraching, they already know whether they are looking for a channle or for a video or videos. If they are looking for a channel, I assume they are looking for a specific channel, like `Joe Rogan Podcast`, while when looking for a video, they could be looking for a specific video, like `Joe Rogan speaks to Mike Tyson episode 1000`, or for videos on a general subject, like `Cooking pancakes`. If this hypothesis is correct, then I think its inadvisable to mix channels and videos in a single results page by showing everyihng in the same grid, as you are likely to annoy users with either objective above, since the search results will not follow the described objective, it will almost always show a mix. You probably instead want to segment the two kinds of content, and only show 1-x (low number) of channels, and then the rest being all videos.
- Be aware that we cannot actually show the kind of loading state you show from the instant the search is triggered, because it takes some amount of time to just get the result from the search itself, and without this result you cannot know how many channels and how many videos, and in what order, you will have. Its only when you have this result that you can show the loading states for actually fetching the assets (avatars + previews). This means another global loading state is needed for the time between sending the search query and getting a baseline result.

## Mobile

- Very good observation on the navigation ;)
- I think the vertical space issue is even more severe here.

**Comment by toiletgranny** [comment]
@bedeho thanks for your feedback and the additional context! I addressed all your comments below, preserving the order. There are 3 items awaiting your response (marked with "Action required"), the rest of it you can skip. :)

### Search Bar
- The policy for displaying recent searches above the actual content would be very similar to other sections: **exact match, sorted by date (most recent searches at the top), top 3 results displayed in the dropdown**. Because it's only 3 top results, I'm not worried about this taking too much of the vertical space, honestly. The reason for considering **not** dropping this section would be the [Google effect](https://er.educause.edu/blogs/2015/10/the-internet-is-changing-the-way-we-remember): 
   >_A recent study looked at the effect Google has on cognitive memory. Turns out, we're becoming less likely to remember specific facts, **but more likely to remember where to find them**._

  In our case, as an example, you might have found an interesting `Cooking pancakes` video recipe recently but forgot the title of the video, the channel it was uploaded by, and the search phrase you used to find it. The only way for you to retrieve it would be to retrace the steps you took the last time. That's where I imagine the recent searches section being extremely useful, especially if it can be _filtered_ using search terms. **Action required: let me know if these arguments convince you to leave this section.**
- If you mean the clock icon, next to recent searches list items, I'd highly recommend not to drop. I believe it's vital for the user to be able to quickly distinguish "organic" search results (videos, channels) from last searches. **Action required: please, let me know if you'd like to remove it anyway.**
- That's interesting, can I ask what is your keyboard layout? As far as I know, in most common keyboard layouts (UK, US, Russian) the `/` character has its own dedicated key, usually paired with `?`. And the forward-slash key for activating the search is an emerging pattern in the modern interaction design, which can be found on apps and services such as GitHub, Storybook, Slack, or even your browser: Firefox. **Action required: let me know if you'd like to drop it anyway.**
  ![CleanShot 2021-09-14 at 11 48 15](https://user-images.githubusercontent.com/35307309/133235705-bebdcc31-543e-436a-92b6-d215ebb9d91a.png)
- That's a good point, although I'm not sure about the "user invariably will often wait for assets to render before they do anything" part. Even if this turns out to be true with some of the users, I believe the value of having previews might exceed the hypothetical costs. I'll see dig into it some more to see what else we can do about it, potentially without giving up on images.
- You might be correct, I'll most likely drop these.

### Results Page
- While this is not something I would be especially concerned about, I see your point, especially on mobile. I'll iterate on that, but I also want to preserve consistency in the way we display headers on other pages (margins, text sizes, components, etc.). It's worth keeping in mind that the reasonable amount of "white space" isn't necessarily a bad thing, as the lack of it oftentimes makes it for the impression of a cluttered space. 
- That's a very interesting point. I'm not 100% convinced whether your assumption is always true, but I can easily imagine this being the case most of the time. And yes, I do agree this might call for a different treatment for channels and videos. I'll iterate on that.
- That's correct and I'm aware of that. I was hoping to finalize this part after getting in touch with Klaudiusz to discuss details, before his vacation, but I didn't make it on time. I'll talk to someone else on our tech team, but you can totally expect this part of the prototype to end up looking slightly different in the next iteration.

**Comment by bedeho** [comment]
> In our case, as an example, you might have found an interesting Cooking pancakes video recipe recently but forgot the title of the video, the channel it was uploaded by, and the search phrase you used to find it. The only way for you to retrieve it would be to retrace the steps you took the last time. That's where I imagine the recent searches section being extremely useful, especially if it can be filtered using search terms. Action required: let me know if these arguments convince you to leave this section.

Ok, an exact match on a prior search is a reasonably high bar I guess.

**Conclusion: Ok, leave section.**

> If you mean the clock icon, next to recent searches list items, I'd highly recommend not to drop. I believe it's vital for the user to be able to quickly distinguish "organic" search results (videos, channels) from last searches. 

I was actually thinking only about the screen before the user started typing, at that point, all entries are just prior searches, and the icon is not doing any work, per say. But I agree, on the other screens you are mixing videos and channels and prior searches, so there it makes sense. I guess the easiest then is just to keep it consistent across all cases and just use the icon.

**Conclusion: Ok**

> If you mean the clock icon, next to recent searches list items, I'd highly recommend not to drop. I believe it's vital for the user to be able to quickly distinguish "organic" search results (videos, channels) from last searches. 

I have one all the way over on my numpad actually, hardly use it. I guess if its very normal to have it, we can go with it, but I have a feeling I would not use this on my setup.

**Conclusion: Ok**

> That's a good point, although I'm not sure about the "user invariably will often wait for assets to render before they do anything" part. Even if this turns out to be true with some of the users, I believe the value of having previews might exceed the hypothetical costs. I'll see dig into it some more to see what else we can do about it, potentially without giving up on images.

I think the only way to really get the feeling is to have a working product with this, but I am quite sure about the hypothesis.

**Comment by toiletgranny** [comment]
Hey @bedeho, here's another iteration for you to review. :) Please note, that this time I'm sharing simplified prototypes, showcasing only the parts that have changed after your feedback. The links I shared above, a couple of days ago, remain valid.

- [Video walkthrough on Loom (8 min)](https://www.loom.com/share/dc9eb0dc79024a568de6c283da42ceae?sharedAppSource=team_library)
- [Desktop prototype on Figma](https://www.figma.com/proto/oPS9fUKfmX5LNreZoveuZn/[Page]-Search?page-id=504%3A26863&node-id=504%3A26869&viewport=367%2C48%2C0.3&scaling=min-zoom&starting-point-node-id=504%3A26869&)
- [Mobile prototype on Figma](https://www.figma.com/proto/oPS9fUKfmX5LNreZoveuZn/[Page]-Search?page-id=527%3A141810&node-id=527%3A148016&viewport=367%2C48%2C0.55&scaling=min-zoom&starting-point-node-id=527%3A147983)

**Comment by bedeho** [comment]
# Feedback

Excellent overview, love that you always start your base explanation from the last iteration, sets context really nicely. I hope hose animations don't take too much time, they look awesome, and really clarify how things are different, but I would hate for it to become a big time drain.

Overall, I love everything, but I am going to have to stick to my guns on the mixed channel & video view. I think there i more order to what you showed now, but it still occupies an amount of space and in a premium location, which is not congruent with the underlying statistics of what the user is trying to do. In other words, at least if I take myself as a baseline, I probably want to explore beyond the first 4-5 videos of a search result about 10-100x more frequently than when I want to find a channel during a search, let a lone when there would be multiple plausible hits for a channel. I also think the fact that the filters do not apply to the channels becomes a bit surprising, I would not have thought of that as a user.

I understand you may not accept this point of view, but I think I just have to stick to my guns here. I think the easiest to work around would be to just relegate channels to it's own tab, and perhaps highlight that tab in cases where there are no video hits, but there are search hits. If there is some other way to detect that an individual channel is a better hit than any video, we could also use this condition.

**Comment by toiletgranny** [comment]
@bedeho I'm super glad you liked it and I see your point with the mixed videos/channels view. I'll remove channels from the "Videos" tab altogether, and we'll take the user to the Channels tab in case there are no videos matching the search term (that is, of course, if there are some channels in results).

I'd love to keep it open for discussion in the future, once we have some thoughts based on actually using the new experience. 

If you have no other comments, I'll close this issue and proceed with developer handoff & documentation. :)

---

>  I hope hose animations don't take too much time [...] I would hate for it to become a big time drain.

Figma animations are fairly quick to produce and I'm showing them to you as a by-product of my design process (as I'm validating ideas in front of myself), so there's no additional time drain you should be concerned about. :)
