### ISSUE TITLE
Don't overly truncate channel names

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1391]
As (correctly IMO) reported by a community member, we overly truncate channel titles when those are being displayed in a various contexts. Example of this:

![](https://cdn.discordapp.com/attachments/859752198166282280/888054931850932264/atlasbug2.jpg)

![](https://cdn.discordapp.com/attachments/859752198166282280/888055114177327154/atlasbug3.jpg)

I think the design should provide examples of longer channel titles for both of those cases and then we should improve the implementation.

**Comment by toiletgranny** [comment]
@kdembler I went through the app and, using Chrome inspect tools, "stress-tested" all places in which a channel name is being displayed. Keeping in mind that there's a global characters limit for a channel name (40 chars), my recommendations are as follows:

### Channel page / Membership profile
1. AS IS: The channel name itself has the following CSS properties:  `white-space: nowrap`, `text-overflow: ellipsis`, `overflow: hidden`, `max-width: 600px`.
2. TO BE: Channel name should be allowed to wrap if too lengthy, no max-width is necessary. I updated Figma designs for both the [Channel](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=510%3A31266) and the [Membership profile](https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?node-id=919%3A130033) pages so that when inspecting **Figma layer constraints**, you can see the recommendation is to let the channel title be displayed with no constraints whatsoever.

![CleanShot 2022-02-03 at 11 10 03](https://user-images.githubusercontent.com/35307309/152322400-e75e4c57-4e02-49c4-85c3-479241b8c6fa.png)

### Browse channels page
1. AS IS: Under the "Discover new channels" section, channel names themselves have the following CSS properties: `white-space: nowrap`, `text-overflow: ellipsis`, `overflow: hidden`, `max-width: 200px`.
2. TO BE: Channel names should be allowed to wrap if too lengthy, no max-width is necessary. Please find and inspect **Figma layer constraints** in [historic designs for this page](https://www.figma.com/file/Vk2Z4QOiVa5bB6q3cBIG5J/Joystream-Atlas?node-id=8408%3A3917) to see that this has been the assumption from the beginning. 
![CleanShot 2022-02-03 at 11 14 12](https://user-images.githubusercontent.com/35307309/152323097-95ae4a83-872c-4a81-a371-ebf90acf8270.png)

---

As per other places in which the channel name is mentioned, either no unnecessary text constraints are present in the current implementation, or the constraints are reasonable, hence **no action is required**. This includes, but is not limited to, places such as:
1. The video page and the channel name displayed under the video player or in the player itself (once the video is finished),
2. Video tile & Channel card components, in which channel names are limited to one-line only (which is okay),
3. Side navigation and the "Followed channels" section.

**Comment by kdembler** [comment]
Great analysis Adam, thanks, we'll take care of those differences
