### ISSUE TITLE
Move fullscreen button to right hand end of the video player

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#142]
Currently its placed immediately to the right of the volume control, and there is a bad interaction in the transition

![Screenshot 2020-12-10 at 10 59 36](https://user-images.githubusercontent.com/437292/101757388-62820580-3ad7-11eb-86a4-d69268ecf1c6.png)

Instead do it like this

https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=1009%3A1927

**Comment by kdembler** [comment]
Oh that's very strange because that's how it looks for me:

<img width="1276" alt="Screenshot 2020-12-14 at 09 57 57" src="https://user-images.githubusercontent.com/12646744/102060780-e814f680-3df2-11eb-870d-704173400c08.png">

I've tried Chrome, Firefox, Safari and mobile and it works for me fine across all these. Can you share more details about when you've encountered that? Things like the browser and the OS. Could you also maybe try a different browser/incognito mode to see if it persists?

**Comment by kdembler** [comment]
Update: I was able to see it on Firefox after all
