### ISSUE TITLE
Poor new content visibility 

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1507]
#### Objective

Introduce changes to New section of the App called "New and noteworthy"

- [x] Add new content section "Recently uploaded" to the top of "New" Top menu category
- [x] By Default show two rows of videos (up to 12) sorted desc by date added
- [x] Add Show more button loading two more rows of videos
> Upon clicking “Show more videos”, a new set of videos should be loaded, with the number matching the currently visible amount of videos. For example: if there are 8 videos displayed by default (2 rows, 4 videos each), clicking the “Show more videos” button should load another 2 rows of videos.

**Out of scope**
- [ ] Introduction of Playlists
- [ ] Adding tabs for different content types (Playlists, NFTs)

#### Designs

> Link to Figma 

#### Context
We are continuously seeing new content, lots of it every day, but its not really surfaced in any effective way on Atlas. The part of the app that comes closest is the `New` screen, but it basically has looked like this for the past 3 months

![Screenshot 2021-10-20 at 14 04 14](https://user-images.githubusercontent.com/437292/138089182-2c56a9ad-c923-45f1-8222-35f6f02d6b63.png)

Part of the problem here is certainly that `Videos worth watching` are not being updated by those responsible for featuring, but I think even if they really actively managed it, there probably should be much more prominence given to just exposing the last N uploads to the system. I think a super easy fix which could enhance what we have now would be to just add a section for the last N uploads, which could have a `Show more videos` type button if the user wants to expose more. The flow of new videos is so high that even if someone uploaded some really low quality stuff with bad metadat or previews, they would quickly disappear. Right now I have a really hard time understanding who is creating new content and channels, and this seems to solve that easier than any other intervention I can think of.

**Comment by toiletgranny** [comment]
@bedeho, @dmtrjsg, @kdembler I added a "Recently uploaded" section featuring all videos uploaded to Atlas, sorted by their upload date, newest to oldest. A few things worth noting:
- My suggestion is to add this section at the top of the page, above the current "Videos worth watching" and "Promising new channels" sections. The reasoning behind this is: having all other Atlas pages being primarily focused on promoting high-quality, hand-curated content, this page, for a change, is focused on promoting the new content. By moving the "Recently uploaded" section to the top, we increase the chances of welcoming users with new & fresh content every time they land over there, thus creating an image of Atlas being a platform that's very much alive and which has a very active community (it's true!).
- By default, only a certain amount of video tiles is visible (just like with other sections, this changes based on the viewport size) with a "Show more videos "button at the bottom, 
- Clicking on the "Show more videos" button adds a new set of videos (the exact number, again, is dependent on the viewport size) to the bottom of the section,
- There is no limit as to how many videos can be loaded this way.
- Since it's not human-curated content, there's an optional language selector, as with some of our other sections, so that the newly uploaded content can be easily filtered based on the user's language preferences.

Designs and docs for the updated New & noteworthy page [can be found here](https://www.figma.com/file/3ZEvWj0l15Jgm9jqsheVrK/New-%26-noteworthy-page?node-id=0%3A1).

![image](https://user-images.githubusercontent.com/35307309/152984104-f398f53b-96a9-4a12-9c1e-2108c9816bcf.png)

---

A few other notes:
- As we haven't updated this page's designs since adopting the new Figma file structure, I had to create a new Figma file, update colors, text styles & components to match the most recent changes in the design system, and create new RWD visualizations.
- We did some other quick explorations internally, and while we have explored other improvements ideas (regarding matters such as infinite loading vs on-click loading, or advanced filtering options, just like on video category pages), in order to be aligned with the initially anticipated 1-2 days for this task, I decided to park those for now, and perhaps revisit in https://github.com/Joystream/atlas/issues/2031.

**Comment by dmtrjsg** [comment]
@toiletgranny excellent work, thanks a mil!

**Comment by kdembler** [comment]
Do we still keep `All content` on the bottom of home page in that case? It's the same content, recently uploaded videos

**Comment by dmtrjsg** [comment]
While I have little trust in efficacy of content discoverability which placed down the bottom of the page, I don't see much harm in keeping it there as well.  Perhaps we can revisit the question of Homepage as part of #2031? 

In terms of the filters and sorting, I think it would make sense to add them to all "modules" of the app, including Homepage and New. But as I understand this is in scope for 2031..
