### ISSUE TITLE
Squished video tiles in numbered carousels

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1595]
I think we could potentially improve the presentation of content in numbered carousels. I think the number of views broken into 2 lines doesn't look great. Also in general, seems like not enough horizontal space is given to those tiles, maybe we should rethink the sizing/positioning of numbers?
<img width="1090" alt="Screenshot 2021-11-16 at 13 58 28" src="https://user-images.githubusercontent.com/12646744/141993150-d2851af8-9be3-46b6-b31f-64c0e3865d3a.png">

**Comment by toiletgranny** [comment]
### Number tile component

The designs and the documentation for the updated Number tile component [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=5164%3A153589). 

![image](https://user-images.githubusercontent.com/35307309/151562820-36c5920c-c3cd-478e-969f-40709419c422.png)

### Carousels responsiveness

On top of that, I reviewed the responsiveness of carousels in the current implementation, compared that to the historic designs we had for them, and came up with a combination of (hopefully) the best of two worlds. The temporary documentaion of new rules for responsiveness of carousels [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=5178%3A259806). The key thing to notice is that the number of Number tile components that end up being displayed in a row changes depending on whether there's a Video tile or a Channel card component nested inside.

![responsiveness](https://user-images.githubusercontent.com/35307309/151563090-fa4c9db7-4d44-44f0-bfb1-b0da81a96b9e.jpg)

### Text wrapping in the Video tile component

Finally, there's also a minor misalignment between the designs and the most recent implementation of the Video tile component, which also contributes to the above problem. I created a separate issue to track the progress of this: https://github.com/Joystream/atlas/issues/2030

![image](https://user-images.githubusercontent.com/35307309/151567079-511d3963-cdf0-4a1d-890d-31b142876ea7.png)

--- 

### Additional context

This one turned out to be a lot trickier than it seemed. Basically, the problem that Klaudiusz is describing has many roots, some of them being: 
- incorrect implementation of historic designs, 
- unclear "Number tile", "Carousels", "Sections" (and many more) components structure both in the Figma and the codebase,
- the way this set of components looks and works varies between the designs and the codebase drastically,
- and more. 

The trick here was to find a sweet spot in addressing the above-described issue without spending weeks on reworking and refactoring the entire foundation behind things like: how many tiles do we display in a row on different breakpoints, how does it affect the variants of the components nested inside, do we treat all carousels the same, regardless of the contents inside (channels cards or videos), and more.

And so while I focused on solving one problem at a time in this issue, I created another one for all the things I mentioned above https://github.com/Joystream/atlas/issues/2031 to be addressed in a near future.
