### ISSUE TITLE
NFT MVP

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1610]
## Context

Overarching Epic (group of user stories) to encapsulate the scope of introducing NFTs to Joystream platform.

✏️   [Design Brief and Discussion Thread](#1329 )

 ## Design

[Final Designs Folder ](https://www.figma.com/files/project/33106318/%E2%9C%85-Final?fuid=1039560990590227876)

[Designs in progress](https://www.figma.com/files/project/33106300/%F0%9F%9A%A7-Work-in-progress?fuid=1039560990590227876)

**Design Epics:**
- [ ] #1496 
- [ ]  #1784 
- [ ] #1506 
- [x] #1498 
- [x] #1497 
- [ ] #1506 

 ## Delivery

- [x] #1750 
- [x] #1802 
- [x] #1801 
- [x] #1864 
- [x] #1725 
- [x] #1872 
- [x] #1736

**Comment by TCzechowski** [comment]
Hi @bedeho, I’m creating this discussion here as it was an action item from one of our meetings:

What exactly is a time block? How much time is 1 time block? Is it a fixed amount of time or does it change? Can it be converted to minutes, seconds or hours? 

I am asking because the concept of “time block” is kind of abstract and some of us still don’t fully understand it. 

In my case (bid placing flow) you said that “the user will be able to withdraw their bid after certain amount of blocks” - but do we know after how many blocks? Can we convert them into “real” time unit and show it to the user? Because we have that information in bottom-left corner (see below) and I am afraid that if we tell the user “you will be able to withdraw your bid after X blocks” then they won’t understand it. 

Also, we will display that “Ending in:” timer on English auctions, but are we able to show the EXACT time there?

Also mentioning @KubaMikolajczyk as I know he also wanted to talk about this when he’s back from his absence.

![image](https://user-images.githubusercontent.com/22870059/145306829-90e9fd44-fd4b-414e-9b37-fd178a79e448.png)

**Comment by bedeho** [comment]
> What exactly is a time block?

I am not sure I have used this exact term, but let me try to explain. Joystream is implemented on a blockchain, and in such a system, the way it evolves is by having blocks of operations, called transactions typically, being committed, one after the other, to a public ledger. These operations are things like "issue NFT" or "publish video", and so on. Now on our system, the clock time between blocks is stochastic, not deterministic, but on average, it is supposed to take 6 seconds. So for 10 blocks to pass, it would take, on average, 60 seconds. Now all notions of time in the blockchain, as we use it, are in terms of block numbers, not clock time. So when when the user selects some duration in Atlas, like say "I want to have bidding for up to 50 days", what is happening under the hood in the app - before anything goes to the blockchain, is that 50 days is converted into 50 days * 24 hours/day * 60 min/hour * 60 seconds/min = 4320000 seconds, which then is converted to a total number of blocks by doing 4320000 seconds/6 = 720000 blocks. This value is actually sent to the blockchain, and the business logic in the blockchain only computes and stores these kinds of notions of time. Conversely, when Atlas is to display clock time to a user, based on what is stored in the chain at a given time, it has to do the reverse calculation.

> Also, we will display that “Ending in:” timer on English auctions, but are we able to show the EXACT time there?

When referring to events in the future, then no, because the time between blocks is stochastic, so you can really only display expected time, but the error should not be that substantial, however it probably increases with duration of the interval. In pioneer this sort of thing has been solved by displaying both clock time and actual blocks, so people focus on whatever is most important to them, but most people dont have a problem with the small degree of unpredictability in milestone times.

![Screenshot 2021-12-09 at 11 25 19](https://user-images.githubusercontent.com/437292/145379035-f550a431-1ecb-40a0-a8ee-58ee0e7236d5.png)

I hope this helps, if not then I think @kdembler can easily sort this out on your next call.

**Comment by kdembler** [comment]
@bedeho We already mostly talked about what you described above, although I think it's great to have this in a written form for a future reference, great explanation!

I think we should be mostly fine with showing times in the future. What I'm a bit worried about are the auction endings. For example, should we show a counter in the UI down to the last second? It likely won't be super accurate, there may be some latency before we actually get block number update, etc. Maybe we could just say "Ending soon" or similar when it gets down to final 10 seconds or something?

I think the approach with showing both blocks and time left is a great way to give user some more understanding. I think [SuperRare](https://superrare.com/artwork-v2/jazz-token-7-15597) is doing good job explaining this:
<img width="364" alt="Screenshot 2021-12-09 at 11 36 29" src="https://user-images.githubusercontent.com/12646744/145380928-13a21abb-b991-4932-af5a-5dc8ff736b6a.png">
