### ISSUE TITLE
Playlist Design

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1648]
### Context

Epic to encapsulate the design of Playlist feature.

Channel Owner - Creating and editing playlists
Content Viewer - Discovering and consuming playlists

✏️  [Link to Detailed Brief ](https://github.com/Joystream/atlas/issues/1819)

### Channel Owner

Creating & editing playlists

1. As a channel owner, I want to create playlists by adding previously uploaded videos, setting up a name and a description, and a category (optional?), and specifying its visibility.
2. As a channel owner, I want to edit previously created playlists.
3. As a channel owner, I want to delete previously created playlists.

🔧  [Link to Epic Details > ](https://github.com/joystream/atlas/issues/2002)

### Content Viewer

Discovering and consuming playlists

1. As a content viewer, I want to discover playlists created by a specific channel.
2. As a content viewer, I want to discover playlists based on the category they're assigned to.
2. As a content viewer, I want to search through playlists based on their name and/or description.
3. As a content viewer, I want to see the details and the contents of the playlist.
4. As a content viewer, I want to watch videos being part of a playlist in the order specified in the playlist.
5. As a content viewer, I want to see the details and the contents of the playlist when watching a video being part of that playlist.
6. As a content viewer, I want to share a link to a playlist.

⛔ Out of scope

1. As a content viewer, I want to follow/bookmark a playlist.
2. As a content viewer, I want to see all playlists I've followed/bookmarked historically.

 🔧  [Link to Epic Detils >](https://github.com/joystream/atlas/issues/2002)

**Comment by bedeho** [comment]
See here => https://github.com/Joystream/atlas/issues/1819

**Comment by toiletgranny** [comment]
> See here => #1819

Left my comments/questions there.

**Comment by toiletgranny** [comment]
@dmtrjsg Based on the #1819, I added a list of user stories in the first message in this thread so that it can serve as a base for further discussion and refinements. 

A reminder that together with @bedeho we agree to drop the following from the scope right now:
1. Issuing NFTs for playlists,
2. Series,
3. Creating playlists by content viewers.

@kdembler Let us know if you're aware of any technological constraints we should be mindful of from the start, or if you have any other thoughts on the proposed list of user stories.

@KubaMikolajczyk @Lenorette @TCzechowski Your thoughts on the above user stories would be super welcome. Let me know which user stories sound too vague or too specific to you and whether there's anything you'd like to add or drop from the list.

**Comment by kdembler** [comment]
Looks good to me. I'm not fully sure about search though, we need to be careful with the known limitations, but we should be able to do something basic
