### ISSUE TITLE
Idea: Make it super easy for Atlas operator/community to manage set of categories in Discover view

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1659]
**Is your feature request related to a problem? Please describe.**

Currently, we have selected a rather random set of categories for videos in the `Discover` tab, probably just borrowed from YT. This is a fine start, but really the category menu in Atlas should be tailored to the content catalogue we have at any given time. 

![Screenshot 2021-11-25 at 12 41 00](https://user-images.githubusercontent.com/437292/143435343-1b0683c1-375d-42fc-a1db-b19578453733.png)

**Describe the solution you'd like**

Ideally, the Atlas operator (read Gateway) should control this, and we can give our content curators control of this, just like they now have control of what content to actually feature. This means the would select what categories to display there, and provide the colors & assets needed to for the presentation. Ideally, making these changes would not require any downtime of the app, and can be done without touching any source files.

**Additional context**

This change may require a possible one-time change to the query layer, it would be good if the Atlas devs could identify this.

**Comment by kdembler** [comment]
To continue on our discussion, we could probably store the `category_id => (color, icon, thumbnail)` mapping in Orion instead of Atlas so that would make changes slightly easier (no PR, just Orion request by community). However, the categories still reside in the chain and I think it may be tricky to make the categories list dynamic while ensuring all the old content doesn't break.

Potentially, Orion could also hold a list of categories that we want to consider "active". Then chain would hold info on all the categories (also old ones, that we don't "want" anymore). So all the old videos would work, editing would work but only the "active" categories would show up in `Discover` and when publishing new videos. I think we wouldn't even need to change query node or chain, just Orion and Atlas.

**Comment by bedeho** [comment]
> Potentially, Orion could also hold a list of categories that we want to consider "active". Then chain would hold info on all the categories (also old ones, that we don't "want" anymore). So all the old videos would work, editing would work but only the "active" categories would show up in Discover and when publishing new videos. I think we wouldn't even need to change query node or chain, just Orion and Atlas.

Sounds like a great idea!

**Comment by kdembler** [comment]
Superseded by #3004
