### ISSUE TITLE
Snackbar notification update

### ISSUE THREAD

**Issue by Lenorette** [Joystream/atlas#1660]
### Description

When there is more than 1 line of text, layout of this component breaks. 

### Figma link

https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=216%3A2717

### How urgent this is?

Not a blocker, but still worth considering

**Comment by KubaMikolajczyk** [comment]
Those tasks should be handled to cover the second similar issue:

In detail define the toast behaviour:

time constrain
motion
Additionally make them more personalised, instead of saying just an asset, what and how we can say to the user to be more descriptive.
https://github.com/Joystream/atlas/issues/868

**Comment by KubaMikolajczyk** [comment]
![image](https://user-images.githubusercontent.com/31144205/149471296-3439ba26-10f2-442e-92e0-86fc648228ea.png)
Designs for this component can be found here:
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=4606%3A140876

I highly recommend catching up on Tandem with the assigned developer(s) before the implementation of snackbar begins.
