### ISSUE TITLE
Fetching NFT Notifications

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1740]
To fetch notification we will need to read QN queries that correspond to low-level events emitted by the blockchain. First, we will need to compile a list of kinds of notification we may want to display (initial list is [here](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?node-id=922%3A54970), but will likely need an update). Then, for each of those, we need to figure out how to get data for it. 

**Example:**

_Example here_

**Comment by kdembler** [comment]
### Intro

I did a preliminary research into this and it is _tricky™_. First, here's the list of notifications the designs have envisioned for the NFT experience:
- Somebody bid on an NFT I'm selling
- Somebody purchased (BuyNow or buyNowPrice in an auction) an NFT I'm selling
- Somebody withdrew their bid from an open auction for an NFT I'm selling (I think we should skip this one, doesn't provide much value and creates unnecessary noise, I'm gonna ignore this in further analysis)
- Somebody outbid me in an english auction I'm participating in (I was the top bid, now somebody else is)
- A bid that I placed in an open auction became withdrawable (bid lock duration has passed)
- A bid that I placed in an open auction has been accepted by the seller (I'm the owner now)
- An english auction I participated in has expired (is past it's end block) and I won (I need to settle the auction to become the owner)

### Problems

- **Somebody bid on an NFT I'm selling**
- **Somebody purchased (BuyNow or buyNowPrice in an auction) an NFT I'm selling**
- **A bid that I placed in an open auction has been accepted by the seller (I'm the owner now)**
1. Let's use first notification as an example - "Somebody bid on an NFT I'm selling". The relevant event can be queried from the query node - `auctionBidMadeEvents` provides events for all the bids that were placed for an auction. However, we need those events only for NFTs the user was selling, not all the NFTs. This is how the filter could look like: `auctionBidMadeEvents(where: { video: { nft: { ownerMember: { id_eq: "user" } } } })`. This uses 3 levels of nested filters while the query node only supports filters that go a single level deep. It's not possible to filter those events in a desired way
2. Let's continue with example from above. Even if the desired filtering was possible and we could run `auctionBidMadeEvents(where: { video: { nft: { ownerMember: { id_eq: "user" } } } })`, this actually still doesn't do what we want it to. Since `video` field on those event objects is a dynamic relation, the query would fetch events for all the NFTs that I own **currently.** If I owned an NFT in the past, I will not be able to access historical notifications for them.

---

- **Somebody outbid me in an english auction I'm participating in (I was the top bid, now somebody else is)**
Slightly similar to problems mentioned above but a bit different. To properly filter events, we would need to know who was the top bidder, _before_ this event occurred. So some kind of historical data would be necessary. Or the emitted blockchain event would need to identify who was the top bidder before the new bid.

---

- **A bid that I placed in an open auction became withdrawable**
- **An english auction I participated in has expired**
Those are especially hard because both of those don't have any blockchain event associated with them. For both of those notifications, the "event" takes places once a specific block number is reached. That means that there is no change of state in blockchain or the query node. Those would need to be somehow handled purely by the client, which would be hard, especially for historic notifications.

### Solutions

I don't have many ideas at this time. Some of the problems could probably be solved by including additional information in the emitted events. The last issue could be solved by adding some kind of functionality to the query node that could trigger some kind of change of state, or query-node-specific event, triggered by specific block passing.

### Conclusions?

It seems in the current state none of the specified notifications can be easily implemented using QN event queries. All the ideas that come to my head involve tons of overfetching and a lot of client-side logic. This seems like a bad direction, considering we want to add more (and more rich) notifications in the future. I checked out the code in Pioneer responsible for fetching the notifications, but it seems that the usecases there are much simpler and none of the problems mentioned above apply there. I would love for somebody to tell me I'm wrong, please do so 😅 In terms of how we proceed, I'm not sure yet, will try to come up with some ideas tomorrow, for now would like to get input from other people on this. One idea would be to drop support for historical notifications and only present users with notifications about the present, although this also doesn't solve all the problems.

**Comment by bedeho** [comment]
1. Could you link to the exact input schema being used here? hard to fully grok the event problems without it. But I think you are basically right about having to change the event, however, I would have expected the natural event schema to have what you need in these specific cases by default, so I would love to see.
2. I think your solution on the English auction side is also totally sensible.
4. Could you make an exact list of what events need their fields flattened? That way @zeeshanakram3 @ondratra can give quick feedback on how much time that would take.
5. The non-event ones are indeed very hard, I don't see a good solution to this that is purely client side. These sort of notifications may need to go into Orion in the future. Luckily, these are not _essential_, so I would just have us skip those for now.

**Comment by bedeho** [comment]
# Call Summary

- 1+2: add nullable reference to nullable owner, which can be either a member or a curator group, at the time of the NFT event (bid, buynow, accept,...): https://github.com/Joystream/joystream/issues/3470
- 3: add extra information to both runtime & QN event: https://github.com/Joystream/joystream/issues/3471
