### ISSUE TITLE
POC of social media previews

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1780]
#### Problem

For the description of the problem we're trying to solve, check out the epic: #1785

#### Proposed solution

To solve the problem mentioned in the issue linked above, I propose this solution:

1. First off, we create a preview server that will be capable of generating `index.html` with necessary meta tags based on the requested resource. For example, if you request `video/1234` from the preview server, it should do the following:
    1. Fetch video with ID `1234` from the Query Node.
    2. (in the future, outside of POC scope) resolve any assets that the video uses and generate URLs for them
    3. Generate `index.html` with all the meta tags supplied via info from query node (+ in the future with image URLs)
    4. Return the generated `index.html`

2. We create an `nginx` configuration that splits the incoming traffic:
    a) if the user-agent of the incoming request matches one of the social media crawlers, redirect the request to the preview server
    b) if not, return static app files from a regular build

3. We pack the built app, `nginx` and preview server into a single docker image that anyone can run.

4. Profit

I don't see any major problems that could come up with this approach although we're doing POC to find out.

#### Feedback

Of course, I'm open to any feedback and suggestions to this, let me know what you think

**Comment by eldiegod** [comment]
I wonder is this something that will be easy to maintain and is this something that we will have to be careful when working on the app to not break it

**Comment by kdembler** [comment]
> is this something that will be easy to maintain

What exactly do you mean by that? As far as I can tell, the only changes would be needed to the preview server only when the query node schema changes which is very rare. Do you see any other kind of maintenance required?

> is this something that we will have to be careful when working on the app to not break it

Hmm not sure how we could make it break, it's not really connected to other parts of Atlas. I guess the only thing we could break I forsee is changing the routes of `channel` or `video` views but at this point I think they're mostly set in stone. Do you have any other possible issues in mind?

**Comment by eldiegod** [comment]
> you have any other possible issues in mind?
> Do you see any other kind of maintenance required?

No, I was trying to understand the implications, then, it sounds like a pretty good solution so far

**Comment by bedeho** [comment]
I have a question here w.r.t. the future of gateways being the way this work. Suppose you want to be embed a video preview which is playable on social media, like Discord or Twitter. This obviosuly requires user device to access underlying media on some host, which in our case would be distributors. However, you obviously need someone who is happy to pay the bill for this because it somehow generates a benefit for them, and likewise would apply the associated anti abuse and consumption metering, so that would be gateways in our case. This means the user really has to get some sort ot authorization from the gateway in question, under the hood, and then this authorization allows the distributor to securely provide access, e.g. by checking some token or something. But for this to work, the embed has to frist dial out to the gateway, do the authorization, and then go to the distributor: is this possible using normal constraints of these embeds? If not we need to think more carefully about what sort of adaptations are needed for mainnet to allow embeds to really work under realistic constraints.

**Comment by kdembler** [comment]
Hmm, is this problem really unique to embedding? Maybe it's just a symptom of a more general problem. Even if we don't do embeds, how do we solve that? Assuming I go to Atlas instance hosted by some gateway, what's stopping me from grabbing a link to the underlying media file and just posting that on Twitter directly, generating bandwidth cost for the distributor?
Maybe we need to think about this more broadly, one quick thought I have is that distributors could possibly require authentication. We could use some tokens that are generated by gateways that you need to use to access the content. This way distributors could identify which gateway the request originated from. Gateways could proxy all asset requests from clients, adding necessary auth. In this system, you don't need to trust gateways to properly report their usage as this could be measured directly by the storage system. You could potentially make the keys signed with some private key that has associated public key registered on-chain to make the consumption metrics fully verifiable. This for sure has some unforeseen problems but potentially promising anyway. WDYT?

**Comment by bedeho** [comment]
- First off, we should keep in mind that its not clear how big of a problem this would be even if gateways had to pay this bill, perhaps this bill will be tiny because its really worth it to the platform to give cheap low friction access, and make up the up the money through other channels. Case in point being how you on YT currently can effectively consume the content without ads using Adblock and no account, despite the platform being otherwise quite poorly monetised. It seems this cost is not substantial enough be a critical issue for the offering.
- I do think there is a difference between scenarios where the user cannot dial out and authenticate with the gateway, either because they cannot (hypothetical embed) or wont (your link scenario), and those where it can.  The most obvious distinction is that distributors - even without any shared state among each other, can easily shut down these scenarios because of obviously irregular consumption patterns that do not match a single user. Moreover, perhaps there is something you can do with adding source IP commitment to authentication tokens to block it outright, but that likely has issues. Looking into some different authentication schemes will probably give some clues.

I agree that we should revisit this when we design autheorization & authentication layer for distributors.

**Comment by traumschule** [comment]
> what's stopping me from grabbing a link to the underlying media file and just posting that on Twitter directly, generating bandwidth cost for the distributor?

For reference: This was also discussed [here](https://discord.com/channels/811216481340751934/813361923172335648/920238175237046273). I found [IPFS](https://www.freecodecamp.org/news/technical-guide-to-ipfs-decentralized-storage-of-web3/?__cf_chl_f_tk=8msIky9mNBtGVm4Fl_qX9P05Mf6k388IB2b1GsSDzTo-1642160295-0-gaNycGzNCJE#how-to-persist-content-from-the-p2p-network) a great choice because the bar to access and replicate content is quite low. However it was mentioned that it might be replaced by something else. @bedeho is there an issue?
