### ISSUE TITLE
Playlists (& Series) design brief

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1819]
I was going to do do a full brief, but doing something brief like this felt more productive, since the playlist form factor is so familiar.

**Note on Series**

Series are meant to capture large scale episodic content which _must_ be consumed in a given context only, unlike playlists where a given video can live in different playlists simultaneously. YouTube has had this concept, but limited only for verified accounts (https://support.google.com/youtube/answer/6084043?hl=en&ref_topic=9257512). The motivation for us to have it is that we want to inspire creation and funding of deeper, longer form and more ambitious content, something both creators and the DAO are much better positioned to do than on YT. Series can be treated different both in discovery, and presentation, for example having a dedicated page.

That being said: I think we should omit this work in this Epic, we will learn from doing playlists, and as I am already alluding, the requirements likely will be different from plain vanilla playlists.

**Tech:**
- Keep in mind that while playlists exist, in some reduced form, in the runtime, they should be implemented as metaprotocol by tech team, by overloading the on-chain video entity, as described
here https://github.com/Joystream/joystream/issues/2739.
- There is therefore obviously no query node support for this now.
- What metadata should a playlist have? I think simply a name+description is sufficient and ordered list of contained videos is fine?
- As a result of the prior point, one will _technically_ be able to issue NFTs against playlists, as distinct from possible NFTs on the individual videos in the list. I think we should follow the same mutation rules as for proper videos: if there is an NFT issued, all metadata is immutable, hence it means title and contained video order and videos cannot be updated by channel operator.
- Playlist can only hold videos from the same channel, and, if the video is deleted, the playlist still exists,
- A video can be part of more than one playlist.

**Design:**
- Be aware that some partial work has already been done on this
- How are playlists treated in search results/search drop down?
- Should playlists be given a separate tab on the public channel view?
- As pointed out above, playlists will inherently have NFT features associated with them, but it should we explicitly support this in Atlas? To me this is a matter of priority, it depends on how much extra work this would require.
- Be aware that a playlist can in principle hold videos that no longer exits, so there needs to be some graceful way to handle this on both the publisher and consumer end.
- A user attempting to delete a video in publisher mode probably should get a warning if the video exits as part of one or more playlists.

**Comment by toiletgranny** [comment]
This is super helpful, thank you, Bedeho! To comment on some of your points:

>  What metadata should a playlist have? I think simply a name+description is sufficient and ordered list of contained videos is fine?

Unless that falls under the umbrella of "obvious metadata", the things that instantly popped into my head were: channel created, member created, date created, and date last modified. Not saying we should be rendering all of this in the UI, but storing this data might be helpful in the future (thinking about sorting, etc.)

> Be aware that some partial work has already been done on this

FYI (@dmtrjsg, @Lenorette, @TCzechowski), some design work has already been done on playlists by @KubaMikolajczyk a few months ago. None of that has been implemented though. [Figma designs can be found here](https://www.figma.com/file/Vk2Z4QOiVa5bB6q3cBIG5J/Joystream-Atlas?node-id=6345%3A151414).

> As a result of the prior point, one will technically be able to issue NFTs against playlists, as distinct from possible NFTs on the individual videos in the list. I think we should follow the same mutation rules as for proper videos: if there is an NFT issued, all metadata is immutable, hence it means title and contained video order and videos cannot be updated by channel operator.

> - As pointed out above, playlists will inherently have NFT features associated with them, but it should we explicitly support this in Atlas? To me this is a matter of priority, it depends on how much extra work this would require.
> - Be aware that a playlist can in principle hold videos that no longer exits, so there needs to be some graceful way to handle this on both the publisher and consumer end.
> - A user attempting to delete a video in publisher mode probably should get a warning if the video exits as part of one or more playlists.

Wow, wouldn't have thought of it myself. An interesting concept! Also, a challenging one to grasp for the non-web3-proficient type of users, I would assume? Of course, all of that would need to be properly validated through research, but my gut feeling is telling me it could cause some confusion if not properly explained, eg.:
- What does it mean for me to _own_ a playlist? Am I the owner of the videos inside as well?
- What happens if a video on the playlist I own gets deleted, hidden, or altered in any other way? Is the playlist I bought still worth the money I paid for it?

Perhaps we could focus on developing & delivering "classic playlists" first so that it's easier for us to figure out how the experience of issuing an NFT for a playlist, or just _owning_ a playlist could feel like in Atlas, as a next step?

---

Other than this, my only question, for now, would be: have we considered creating playlists by content viewers, and not _just_ the channel owners?

**Comment by bedeho** [comment]
> Unless that falls under the umbrella of "obvious metadata", the things that instantly popped into my head were: channel created, member created, date created, and date last modified. Not saying we should be rendering all of this in the UI, but storing this data might be helpful in the future (thinking about sorting, etc.)

Yes so by metadata I meant stuff the user can explicitly provide values for, rather than being implied, so I think most of that is implied, but they are all useful as you say.

> Perhaps we could focus on developing & delivering "classic playlists" first so that it's easier for us to figure out how the experience of issuing an NFT for a playlist, or just owning a playlist could feel like in Atlas, as a next step?

Agreed.

> Other than this, my only question, for now, would be: have we considered creating playlists by content viewers, and not just the channel owners?

These would be entirely private, so not part of the public state of the system, otherwise we would technically _have to_ create a channel for the user, as that is the only way to publish. It is however possible to somehow designate these channels as somehow being different, e.g. being "consumer channels", so that the Atlas consumer experience does not display and surface them in the same way. All in all I would say this road is not worth going down.

**Comment by dmtrjsg** [comment]
✅  Brief is taken to work [Link to Design Epic > ](https://github.com/Joystream/atlas/issues/1648)

**Comment by kdembler** [comment]
@bedeho you said `Keep in mind that while playlists exist, in some reduced form, in the runtime, they should be implemented as metaprotocol by tech team`. Which tech team would carry out that work, would it be Atlas team? Regardless of the first answer, what's the timeline on these changes? Seems like there's some runtime/metadata work to be done but we already have started designs on Atlas side. I'm afraid this may create some uncertainties of technical details of playlists.

**Comment by bedeho** [comment]
Not yet determined, but probably needs @ondratra in there to supervise and help, and then perhaps someone on the Atlas team for some knowledge transfer, but lets revisit that when `Olympia` is out.
