### ISSUE TITLE
Comments and Reactions Design

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1870]
### Reactions
1. As a content viewer, I want to express my reaction to a video I'm watching.
2. As a content viewer, I want to change my previously expressed reaction to a video I'm watching.
3. As a content viewer, I want to undo expressing my reaction to a video I'm watching.
4. As a content viewer, I want to sort videos based on reactions associated with them.

⛔  Out of scope
1. As a content viewer, I want to see the list of all videos I reacted to historically.

### Comments
1. As a content viewer, I want to see other people's comments under a video I'm watching.
2. As a content viewer, I want to react to other people's comments under a video I'm watching.
3. As a content viewer, I want to sort other people's comments under a video I'm watching.
4. As a content viewer I want to leave a comment under a video I'm watching.
5. As a content viewer, I want to reply to other people's comments under a video I'm watching.
6. As a content viewer, I want to get notified about replies to my comments.
7. As a channel owner, I want to get notified about new comments under my videos.
8. **New** As a content viewer, I want to delete the comments I left in the past.
9. **New** As a content viewer, I want to edit the comments I left in the past.
10. **New** As a content viewer, I want to see the edit history of comments that were edited in the past.
11. **New** As a channel owner, I want to delete comments under my videos.
12. **New** As a channel owner, I want to enable or disable the comments section for my videos, separately.

⛔  Out of scope
1. As a channel owner, I want to reply to other people's comments under my videos from one place, ~~on behalf of my channel (not as a member)~~.

**Comment by toiletgranny** [comment]
First thoughts:
1. Was the above scope reviewed & approved by both Bedeho and the Tech team?
2. It would be beneficial to have a design <> tech sync prior to the design phase in order to explore and discuss possible technical limitations we might encounter (eg. if, as a member, I hit a like button under a specific video, is this information stored locally on my browser [doesn't make much sense, I know, but it's kind of what we've been getting used to so far], or will I be able to see this information on another browser/device?)
3. If there's anything we would need to drop from the above scope (for any reason), my recommendations would be (in the following order):
   - Content viewer | reply to other people's comments under videos.
   - Content viewer | mention other people in comments under videos.
   - Content viewer | like (or dislike) comments under videos.
4. We might want to give the "disliking" aspect more thought given YouTube's recent bold decision about removing the dislikes count.
5. Some ideas on things we might consider adding to the above scope now or in the near future:
    - Content viewer | see the list of videos I liked historically. (this could be also used as a bookmarking system)
    - Content viewer | see the most liked videos within a given video category.
    - Channel owner | hide or delete comments under videos I uploaded.
    - Channel owner | review and reply to comments under all my videos from one place.
6. Food for thought during our next meeting's discussion: validating/creating user stories based on in-depth user interviews conducted by a UX designer/researcher.

**Comment by dmtrjsg** [comment]
Thanks @toiletgranny, great questions!
1. Yes, broadly. Happy to be more design-driven here. e.g. let's explore what would make likeable product, since engagement is key and then take a view on development phases. The scope for design can be extended for this.
2. Totally, that was one of the items for todays meeting.
3. Community collaboration in DAOs is central for growth, so here from my perspective the scope for design is likely to remain if not increase. Noted, however, and not against for this to guide our research.
4. Afaik that was done to drive certain outcomes, specific to youtube model and strategic agenda. I'd even suggest to explore  a richer set of reactions, with some benchmarking against community-driven products like reddit and discord. 
5. Great idea, we certainly need to explore how users actions impact content discoverability. 
6. Let's do it! Thats a great start! 🚀

**Comment by toiletgranny** [comment]
Thanks for your answers, @dmitry! Based on the above and what we agreed on earlier today, I updated the updated list of user stories in your message, for us to serve as a base for further discussion and refinements.

@kdembler I would appreciate your perspective on the above and letting us know if there are specific technical constraints the design team needs to be aware of when addressing user stories.

@KubaMikolajczyk @Lenorette @TCzechowski Your thoughts on the above user stories would be super welcome. Let me know which user stories sound too vague or too specific to you and whether there's anything you'd like to add or drop from the list.

**Comment by kdembler** [comment]
> As a content viewer, I want to see the list of all videos I reacted to historically.
As a content viewer, I want to sort videos based on reactions associated with them.
As a content viewer, I want to get notified about replies to my comments.
As a channel owner, I want to get notified about new comments under my videos.

I would say those would be low priority, possibly as a second phase to stay focused on the core functionality first? What do you think @dmtrjsg

> As a content viewer, I want to rate other people's comments under a video I'm watching.

Just to clear up, that would be `react` instead of `rate`?

> As a channel owner, I want to reply to other people's comments under my videos from one place, on behalf of my channel (not as a member).

I don't know the constraints of the system yet but if I had to guess I would say that this isn't possible from technical perspective, I guess all comments need to come from members. We could showcase that given member is the owner of a channel that published the video, though. Will try to confirm that

**Comment by TCzechowski** [comment]
> I would say those would be low priority, possibly as a second phase to stay focused on the core functionality first?

I was thinking the same thing. Are we now discussing only the "MVP/MLP" scope or thinking of all of the possible userstories and we will prioritise them later?

**Comment by toiletgranny** [comment]
> Just to clear up, that would be `react` instead of `rate`?

@kdembler Yeah, I agree that `rate` might not the best word. Will change.


>As a channel owner, I want to reply to other people's comments under my videos from one place, on behalf of my channel (not as a member).

> I don't know the constraints of the system yet but if I had to guess I would say that this isn't possible from technical perspective, I guess all comments need to come from members. We could showcase that given member is the owner of a channel that published the video, though. Will try to confirm that

Ok, good to know, will wait for your confirmation. Perhaps the phrasing of this story is too specific for the time being (implying that a comment sent from the Studio _must_ be displayed as written by a channel, while we haven't verified whether it's actually useful to have). I will drop the "on behalf of my channel (not as a member)" part from it. 

Just out of my curiosity though, regardless of whether it makes sense or not: even if, _technically_, a comment is always sent by a member, do you sense there would be a technical blocker from letting users choose which channel (out of the ones they own) should be _displayed_ as the comment's author?

**Comment by kdembler** [comment]
> Just out of my curiosity though, regardless of whether it makes sense or not: even if, technically, a comment is always sent by a member, do you sense there would be a technical blocker from letting users choose which channel (out of the ones they own) should be displayed as the comment's author?

Probably yes. If the "backend" only allows having member as an author, then the chosen channel would likely need to live inside the comment itself, as some kind of magic string that would be interpreted by Atlas.

**Comment by toiletgranny** [comment]
Hey @dmtrjsg! Moving this epic, along with #1986, to "Design Review", as all designs have been handed over to developers and are ready to be reviewed in their respective issues.
