### ISSUE TITLE
Subtitles Design

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1871]
## Context

Design Epic encapsulating the scope of adding and consuming subtitles

### Adding subtitles
1. As a channel owner, I want to upload a video subtitles file when adding a new video.
2. As a channel owner, I want to upload a video subtitles file when editing a previously added video.
3. As a channel owner, I want to upload a video subtitles file when editing a previously added video, for which an NFT has been issued.
4. As a channel owner, I want to assign uploaded subtitles to a language from a predefined list.
5. As a channel owner, I want to mark subtitles as [closed captions](https://www.ai-media.tv/knowledge-base/what-is-the-difference-between-captions-and-subtitles/#:~:text=Closed%20Captioning%20vs%20Subtitles,-Some%20people%20refer&text=Closed%20captions%20are%20created%20to,or%20notifications%20for%20speaker%20changes.).
6. As a channel owner, I want to download previously uploaded subtitles back to my computer.

🔧  [Link to Design Epic](https://github.com/Joystream/atlas/issues/2003)

### Consuming videos with subtitles
1. As a content viewer, I want to enable and disable subtitles/closed captions when watching a video.
2. As a content viewer, I want to choose a language of subtitles/closed captions when watching a video.
3. As a content viewer, I want my subtitles preferences (on/off state, language) to be preserved (when possible) when watching different videos.
4. As a content viewer, I want to see which video comes with subtitles from video listing views (in other words: subtitles icon in the Video tile component).
5. As a content viewer, I want to have quick access to the most popular subtitles and playback speed preferences in the video settings menu.
6. **Playback speed controls (Bonus)**:
    a. As a content viewer, I want to change the playback speed to be one of the predefined options.
    b. As a content viewer, I want my playback speed preferences to be preserved when watching different videos.

🔧  [Link to Design Epic](https://github.com/Joystream/atlas/issues/2003)

---

~Subtitling: There is no way to display subtitles in content, or allow control of. As a result of the lack of post-processing, there is also no way to have subtitles automatically extracted.~

**Comment by bedeho** [comment]
**Extracted from RICE scoring:**

There are really two parts here, one is automatic subtitling, and the second is just being able to have subtitling metadata associated to content, and have it displayed on playback. I will only concern myself with the latter, as the former requires a lot more work, and it depends on the latter anyway. On the design side, we would need to introduce some new part of the upload/editing flow for content for associating subtitle metadata, and we also need to adopt some off-the-shelf standard for this. I did some basic review and SRT seems to be the most popular format, and it also is compatible with YT, so when we do YT-synch, perhaps we get that format coming out already:

https://support.google.com/youtube/answer/2734698#zippy=%2Cbasic-file-formats

Payload needs to be stored as separate assets in storage system. The playback side has already been designed. On the tech side, changes would be limited to accommodate this. User obviously has to be able to provide subtitles for different languages over time, and one has to be able to efficiently download subtitles for only a single language at a time, as well as discover set of currently supported languages. This means that each subtitle probably has to be its own storage asset, and that the metadata for each video carries semantics around which language corresponds to which asset.

**Comment by toiletgranny** [comment]
> On the design side, we would need to introduce some new part of the upload/editing flow for content for associating subtitle metadata [...] 

Wondering how would that work if there already is an NFT associated with the video in the context of the recent decision to disable video editing. I totally get it how changing the video's title or thumbnail might affect the perceived value of an NFT which had already been sold/transferred, this it's not allowed, but adding or updating subtitles? Should that be disabled as well? **I would strongly vote for no**, as — to me — subtitles on a video with an NFT is not a matter of a perceived value but making the content accessible to all audiences out there. Would love to learn your thoughts on this (cc @KubaMikolajczyk, @kdembler).

> [...] we also need to adopt some off-the-shelf standard for this. I did some basic review and SRT seems to be the most popular format, and it also is compatible with YT, so when we do YT-synch, perhaps we get that format coming out already:

Research on this subject and tech team consultations are definitely required before tackling this. I would imagine the design team leading this.

> The playback side has already been designed.

This is correct, [Figma designs can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=216%3A83252). A quick question to @kdembler: since enabling/disabling and changing subtitles would be the first time we need to _implement_ the "settings" side of the player, would it make sense not to have the whole "settings" dropdown just for controlling subtitles and perhaps... implement the playback speed controls (hoping that it's a super easy thing, from a technical standpoint) as we go? 
![CleanShot 2022-01-11 at 12 17 00](https://user-images.githubusercontent.com/35307309/148933378-9e9f88a2-4afa-4be9-a4fb-9aa7218dc31d.png)

**Comment by bedeho** [comment]
> Wondering how would that work if there already is an NFT associated with the video in the context of the recent decision to disable video editing. I totally get it how changing the video's title or thumbnail might affect the perceived value of an NFT which had already been sold/transferred, this it's not allowed, but adding or updating subtitles? Should that be disabled as well? I would strongly vote for no, as — to me — subtitles on a video with an NFT is not a matter of a perceived value but making the content accessible to all audiences out there. Would love to learn your thoughts on this (cc @KubaMikolajczyk, @kdembler).

I agree, this can be an exception.

**Comment by kdembler** [comment]
> Should that be disabled as well? I would strongly vote for no

Agreed, we can make an exception for that

>>    [...] we also need to adopt some off-the-shelf standard for this. I did some basic review and SRT seems to be the most popular format, and it also is compatible with YT, so when we do YT-synch, perhaps we get that format coming out already:
>
> Research on this subject and tech team consultations are definitely required before tackling this. I would imagine the design team leading this.

Not fully sure if I agree, I think the technical side of this research will certainly need to be handled by the dev team.

> This is correct, Figma designs can be found here. A quick question to @kdembler: since enabling/disabling and changing subtitles would be the first time we need to implement the "settings" side of the player, would it make sense not to have the whole "settings" dropdown just for controlling subtitles and perhaps... implement the playback speed controls (hoping that it's a super easy thing, from a technical standpoint) as we go?

Yes, agreed, let's use this occasion for playback speed control as well 👍

**Comment by toiletgranny** [comment]
Thanks for your answers, @bedeho, @kdembler! Based on the above, I added a list of user stories in the first message in this thread, so that it can serve as a base for further discussion and refinements, @dmtrjsg.

@KubaMikolajczyk @Lenorette @TCzechowski Your thoughts on the above user stories would be super welcome. Let me know which user stories sound too vague or too specific to you and whether there's anything you'd like to add or drop from the list.

**Comment by bedeho** [comment]
> Yes, agreed, let's use this occasion for playback speed control as well 

YAY! Need this so badly.

**Comment by KubaMikolajczyk** [comment]
> Wondering how would that work if there already is an NFT associated with the video in the context of the recent decision to disable video editing. I totally get it how changing the video's title or thumbnail might affect the perceived value of an NFT which had already been sold/transferred, this it's not allowed, but adding or updating subtitles? Should that be disabled as well? I would strongly vote for no, as — to me — subtitles on a video with an NFT is not a matter of perceived value but making the content accessible to all audiences out there. Would love to learn your thoughts on this (cc @KubaMikolajczyk, @kdembler).

I totally understand this point of view - and it could be a bummer to be a creator who tends to add subtitles to his/her videos - and forgets to do this before selling (even though we mention it clearly that editing will be disabled after issuing). On the other hand, I have to disagree that this is not a matter of perceived value - everything that is changed in NFT after it was sold increases or decreases its value - I can see the same potential risk as with changing thumbnails after the sale - if creator really dislikes owner, or likes to see the world burn, nothing will stop him/her from uploading a lot of harmful msgs that can be not even related to the actual content of the video. With that said maybe we shouldn't worry about it, but just keep in mind that it can happen. I just think that when a video becomes NFT - it sort of primarily becomes an investment asset rather than a simple piece of content and I would advise being careful in that matter. I vote for disabling adding subtitles after issuing as NFT.

**Comment by kdembler** [comment]
👆 This is a really valid point IMO, I think I may be leaning more towards disabling editing completely.

**Comment by bedeho** [comment]
There are two sources of error

1. Creator changes subtitles in a way that undermines the original intent or content of the work in a way that reduces its value to the current owner.
2. The creator is blocked from updating subtitles in a way that is valuable both to the audience and even possibly the current owner, and creator.

To me (2) seems much more likely to occur if we adopt this new scheme. If someone is the creator, they already are credible in some way if third parties are buying the asset, and the ability to rely on the creator to not sabotage is important for future issuances. Moreover, I would assume that _most_ content that becomes quite popular could benefit from subtitles in multiple languages which will not all be present at the time the content is published or NFT issued. 

If (1) becomes an actual issue I would rather we later add a system where the creator has to get opt-in from the current owner for any metadata change.
