### ISSUE TITLE
Idea: Frontend optimisation - use thumb images for video preview

### ISSUE THREAD

**Issue by VlodkoMr** [Joystream/atlas#1906]
Serve images that are appropriately-sized to save cellular data and improve load time. 

Each video preview image can have small thumb version that can be used for video preview. 
It can save more than 2Mb on full page load, for example this one image can be resized to 500x280px (to support retina displays) and save more than 60% of the size:
https://ipfs.joystreamstats.live/storage/asset/v0/5EnVSkcMgEHnYUr4UpqCkn4iLSg1KYCMNEuxs7a7uL9bTNU7

Another (simpler) option: add lazy-loading for video images preview.

**Comment by kdembler** [comment]
We have planned this for quite some time and this is happening in Giza release which will be next week most likely. All the old content will be resized during migration and we also changed what Atlas cropping outputs. See [`18c819e` (#1893)](https://github.com/Joystream/atlas/pull/1893/commits/18c819e03a36cbae72ffa0c71e0502a4eb4c0d60)

Since this has already been tackled I'm closing. If you disagree, let me know
