### ISSUE TITLE
Reactions Design: Video page

### ISSUE THREAD

**Issue by Lenorette** [Joystream/atlas#1985]
### User stories

- As a content viewer, I want to express my reaction to a video I'm watching.
- As a content viewer, I want to change my previously expressed reaction to a video I'm watching.
- As a content viewer, I want to undo expressing my reaction to a video I'm watching.

### Sub-issues
- [x] #2000
- [x] #2025
- [x] #2046

### Figma designs
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1445%3A84558

**Comment by dmtrjsg** [comment]
Comments after grooming with the dev team:

Overall, there is a suggestion to minimise the reliance (visually) on the transaction signing flow, before updating the reaction component itself. E.g. user clicks Like, we show step 1 transaction toaster, then user signs and reaction component is updated already, while the processes of  transaction validation "happen in the background".

Namely:

1. Suggestion to only show minimised transaction flow toaster messages to Step 1 (when signing transaction via JS ext) and last step 4, but _ONLY_ if transaction failed (due to some tech issues). So  - click on reaction - popup modal to sign transaction - user signs - we don't show any progress or confirmation toasters at all if transaction was successful. Drop the in-progress and Success Toasters>
<img width="331" alt="Screenshot 2022-02-07 at 14 11 24" src="https://user-images.githubusercontent.com/93924525/152804218-2838801b-6c09-4d2f-96da-af3126f58eab.png">
<img width="300" alt="Screenshot 2022-02-07 at 14 11 27" src="https://user-images.githubusercontent.com/93924525/152804225-de654b1c-81db-47e4-8d58-2e115ff4e9db.png">

2. This shade of red colour chosen for Dislikes is a little too visible and in your face. We'd need to tune it down a notch - update the colour to be less bright? 
<img width="195" alt="Screenshot 2022-02-07 at 14 12 37" src="https://user-images.githubusercontent.com/93924525/152804299-559b4395-25a9-4601-a77a-f673bc146c3f.png">

3. Snackbar notifications need to have less generic copy - need to update the Failed Transaction toaster notiff:

<img width="580" alt="Screenshot 2022-02-07 at 14 11 10" src="https://user-images.githubusercontent.com/93924525/152804163-9b6ee9c2-1f4d-432d-9295-f7ccfca76681.png">

4. After user clicked Like, how do we handle an attempt to immediately dislike (thumbs down) the video or un-like (second click on like) before the transaction is signed. Change of component state and hover tooltip? tbd

**Comment by toiletgranny** [comment]
To-do:
1. Make the change, say you agree,
2. Make 3 visualizations, recommends brightening the color,
3. Make the change, say you agree,
4. Propose an idle state for the Reactions component.

**Comment by toiletgranny** [comment]
Hey Dmitry! Great observations, thank you! I addressed all of them in a Loom video which you can [check out over here](https://www.loom.com/share/e17699fe02594630835da708735946e5). Also, [here's the prototype](https://www.figma.com/proto/EzJmuVoYrIEuUZ8VhqEBdH/Video-page%3A-Reactions-%26-Comments?page-id=1660%3A79463&node-id=1662%3A81418&viewport=402%2C48%2C0.08&scaling=scale-down&starting-point-node-id=1662%3A81418&show-proto-sidebar=1) I used when recording the video, in case you want to play with it yourself.

What I'm going to need from you right now is, at the very least, either a green or red light to let me know if I can start moving all of my recommendations into the final Figma designs and documenting them for the engineering team.

@kdembler your input on the above would be also very much appreciated, especially on the idea of a locked/idle state for the Reaction component, and also whether it would be possible to pull that thumb icon animation off **while still using the Button component for Likes/Dislikes**. Regarding the animation itself, the way I can see it is we could either do it using a simple CSS animation (I can provide the code), or we could use a .json Lottie file instead of regular SVG icons.

**Comment by dmtrjsg** [comment]
Loving absolutely loving the treatment of points 4 and 1. 
Shade of red, also good with me.

Thank you Sir, good to get into dev preps from my pov, but we need @kdembler  to confirm for the quorum ;)

**Comment by kdembler** [comment]
Agreed with all your suggestions @toiletgranny, great stuff! Regarding the like animation, may be tricky but we'll figure it out, no worries, I think CSS will be fine

**Comment by toiletgranny** [comment]
Ok, it's all done!

1. I updated user stories in Figma to reflect the changes proposed and discussed above in regards to snack bar notifications,
2. I added a loading/idle state for the "Reaction stepper" component to prevent the user from clicking on another reaction when the transaction for the previous one is still processing in the background,
3. I added & [documented thumb icon animations](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1434%3A92515) (CSS keyframe animations and JSfiddle links included),
4. I updated the design token for the color of "error text" to be brighter in the [JSON file](https://github.com/Joystream/atlas-resources/blob/main/design_tokens/colors.token.json) and in the Figma foundation library file (cc @drillprop),
5. I made a few slight adjustments to the thumbs up/down icons, so that they're outlined when not selected (so that we don't rely solely on colors to indicate a currently selected reaction, due to accesability reasons).

![image](https://user-images.githubusercontent.com/35307309/153601573-e83e3d54-25b2-415e-a326-20859601c891.png)

**Comment by dmtrjsg** [comment]
@toiletgranny  Based on our conversation yesterday on comments and @kdembler assurance that async is possible, we'd probably need to remove blocking the elements while transaction is finished (but keep the animation of the "running" bar)? One to discuss  again today perhaps..

**Comment by kdembler** [comment]
I think for this component we should still block. Here the reason is slightly different - video reactions (like/dislike) are meant to be exclusive, so we will want to block user from liking and disliking the video at the same time. We can discuss today

**Comment by toiletgranny** [comment]
Because the agenda for today's meeting seems to be quite dense already, maybe we can try coming to an agreement on this here?

I'm with @kdembler on this one. These are opposite actions, you can either like or dislike the video, not both. If I, as a user, select the wrong reaction by accident and I'm allowed to click on the other one right away, I'll probably end up having two Polkadot transactions waiting for me to be signed, not really knowing which one was the misclick.

**Comment by dmtrjsg** [comment]
Guys you are both correct, and thank you for providing the reasoning behind this approach <3
