### ISSUE TITLE
Comments Design

### ISSUE THREAD

**Issue by Lenorette** [Joystream/atlas#1986]
### User stories

1. As a content viewer, I want to see other people's comments under a video I'm watching.
2. As a content viewer, I want to react to other people's comments under a video I'm watching.
3. As a content viewer, I want to sort other people's comments under a video I'm watching.
4. As a content viewer I want to leave a comment under a video I'm watching.
5. As a content viewer, I want to reply to other people's comments under a video I'm watching.
6. As a content viewer, I want to get notified about replies to my comments.
7. As a channel owner, I want to get notified about new comments under my videos.
8. **New** As a content viewer, I want to delete the comments I left in the past.
9. **New** As a content viewer, I want to edit the comments I left in the past.
10. **New** As a content viewer, I want to see the edit history of comments that were edited in the past.
11. **New** As a channel owner, I want to delete comments under my videos.
12. **New** As a channel owner, I want to enable or disable the comments section for my videos, separately.

⛔ Out of scope

1. As a channel owner, I want to reply to other people's comments under my videos from one place, on behalf of my channel (not as a member).

**Comment by toiletgranny** [comment]
FYI @bedeho, @kdembler, and @dmtrjsg: I'm about to begin working on this epic in the scope described in the above-listed user stories.

This potentially includes things like:
1. Adding Discord-like reactions to comments (emojis),
2. Sorting based on the date added and the number of reactions underneath a comment,
3. Because of replies: creating threads of comments, and/or mentioning other members in comments,
4. Getting notifications about comments under my videos, or about replies to my comments.

If there's anything missing, or worth dropping for now, or if there are any other technical constraints we should be aware of from the get-go, I think now is a perfect moment to talk about this.

**Comment by dmtrjsg** [comment]
Thanks @toiletgranny for raising the questions!

From my POV all the basics are covered. There are a few comments on how we wanted to handle the reactions wrt the signing transaction modals, that will 100% impact the comments flow> https://github.com/Joystream/atlas/issues/1985 So I suggest to first review the latest feedback from the dev grooming on1985 and proceed to comments epic, afterwards.

One thing to be aware of re comments, is that the length of the comment will impact the transaction fee of posting it. We have a similar item in the backlog for Pioneer https://github.com/Joystream/pioneer/issues/1553, but looks like Atlas team will be pioneering this feature :P 

From my perspective, we can simply display a benchmark values for say 100characters as a placeholder text/ tooltip, rather than calculate precise fee on-the-flight.

**Comment by toiletgranny** [comment]
Hey @dmtrjsg! Moving this epic, along with #1870, to "Design Review", as all designs have been handed over to developers and are ready to be reviewed in their respective issues.
