### ISSUE TITLE
Privacy policy/ Cookies consent banner for Atlas

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2037]
## Context

Community member flagged two cookies not listed in the privacy https://github.com/Joystream/joystream-org/issues/438.

## Design Scope

We need a simple privacy policy banner with only "Accept" button and _view details_, opening the page (slider panel from the bottom) showing the same info as on this page:(https://www.joystream.org/privacy-policy)

## Dev scope

- [ ] Add cookie policy banner as seen here: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components (copy needs to be updated)
- [ ] Read more points to https://www.joystream.org/privacy-policy
- [ ] We store some flag in local storage that says whether the user has accepted cookies. We only enable livesession and usersnap if the flag is set to true

ℹ️ 

.org pp page update ticket - https://github.com/Joystream/joystream-org/issues/483

**Comment by TCzechowski** [comment]
Hi guys @dmtrjsg @toiletgranny @kdembler @KubaMikolajczyk, I'm coming back with some questions & also propositions of a cookies banner.

# Questions 
1. Is the user going to be able to change the cookies preferences? So they can choose which cookies they do accept and which they don't. I think we talked about that and the outcome was that they **won't** be able to do that, but just want to confirm.
2. Is the user going to be able to opt out from collecting data? Or is it mandatory to accept them in order to use the website?

## Propositions
I've prepared 3 propositions of possible banners, in both variants: **with** and **without** the option to decline them. Of course, the illustration in the third proposition is just a placeholder to show you how it could look like, but if we decide to go with this option, I will need to prepare a new illustration (of... a cookie, I guess? :))
![image](https://user-images.githubusercontent.com/22870059/159284710-9dfa35ec-8b46-462f-a2c4-c69902ed87d3.png)
### Banner placement
![image](https://user-images.githubusercontent.com/22870059/159284951-1c74c0a9-9601-44c4-9954-9625ec340028.png)

### Cookies mandatory to use the website
And, of course, there is also a scenario where we don't let the user use the platform unless they accept the cookies (when they are crucial for our platform to work)
![image](https://user-images.githubusercontent.com/22870059/159456720-c5fc4f3e-0782-4f62-a7ae-dd7ea90bfdcc.png)


You can also find those designs here:
[Figma link](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6441%3A128624)

What are your thoughts?

**Comment by TCzechowski** [comment]
As discussed on our yesterday's Design <> Tech sync, we've decided to go with a simple banner with a subtle option for the user to opt-out from collecting cookies.

Preview:
![image](https://user-images.githubusercontent.com/22870059/159903533-eb2e0e39-c477-4f6d-a0df-62fcd6f1c12b.png)


Figma link:
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6511%3A194029
