### ISSUE TITLE
All videos displayed as uploaded 7 days ago

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2061]
**Describe the bug**

All videos uploaded later than 7 days ago are labeled as uploaded "7 days ago".

**To Reproduce**

1. Go to https://play.joystream.org/channel/773,
2. Notice how all video tiles mention "7 days ago", as upload date, even though these videos have been uploaded back in 2021,
3. Open up a sample video, eg. https://play.joystream.org/video/9937
4. Notice how the "7 days ago" is also present over there.

**Expected behavior**

Ideally, timestamps showing the date uploaded are... well, truthful.

**Screenshots**

![image](https://user-images.githubusercontent.com/35307309/152147150-f0341451-55a7-4ad9-8a04-f4ff43845790.png)

**Comment by kdembler** [comment]
This is a known consequence of the content migration we did as part of the Giza upgrade. All the old content was deleted and some of it was created anew, that's why you're seeing those dates - all the content currently on the network cannot be older than 7 days. We will have to accept that. Closing the issue as there's no actionable item
