### ISSUE TITLE
Table component

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#2130]
A new global component was created to support tables in Joystream.

https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=5710%3A178068

Before implementing I highly advise a sync with the designer.

**Comment by kdembler** [comment]
Looks good, 3 questions:
1. I see that header row also contains a checkbox when rows are selectable. How does that work, what happens when I click it?
2. Is left/right alignment decided on per-column basis? In other words, can I assume that both header and all cells in a single column will be aligned the same way?
3. Won't this component require some adjustments for display on smaller breakpoints?

**Comment by KubaMikolajczyk** [comment]
@kdembler sorry for missing this last week. Here are my responses:
1. The checkboxes were added here to see if we should implement multiselect at this stage, but after short exploration it looks like "select all, or many" and delete them would be the only option in case of multi managing playlists - so we dropped this idea, maybe there will be a future use case but for now checkbox version of the table shouldn't be implemented.
2. Yes - right alignment is used mostly for columns with number values in them - eg. num of videos in playlists case - so if values are aligned to right or left the headers will be aligned with them.
3. Yes - it definitely will require some work on RWD side - but this work will be tackled in RWD issue - if you have a preferred way to treat tables on mobile, please share :)

**Comment by kdembler** [comment]
This will be done in #3417
