### ISSUE TITLE
Update the Dialog crop component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2173]
**AC:**

- [ ] Implement all the design changes mentioned below with this exception: The "Delete" button should be configurable via some prop. If it's not enabled (for example if the user uploads the image for the first time), the button should be hidden, not disabled.

---

There are old "crop & position" dialogs which need to be adjusted to be fully funcionable in new context of setting playlist thumbnails.

**Comment by KubaMikolajczyk** [comment]
![image](https://user-images.githubusercontent.com/31144205/156398051-948dc53e-cc10-4bfe-a71b-e41a8feecc8f.png)
Old crop and position dialogs were just updated due to new user stories, but their functionality and style should be adjusted for all their usages.
Link to dialogs: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=216%3A60182
Link to playlist channel owner user story: https://www.figma.com/file/XfKZ5ZSavt88rVfiKf0tBv/Playlist%3A-Channel-owner-(Final)?node-id=970%3A16745

Changes:
- Adjusted padding - now its 24px on all sides
- moved buttons below the scale slider
- Button size changed from medium to large
-  Added 2 more buttons - one for deleting selected thumbnail, and one to cancel operation
(Delete button should be disabled when selecting a thumbnail for the first time but when we edit it this button should be enabled to allow user to remove it easily)

**Comment by kdembler** [comment]
@KubaMikolajczyk 3 points:
1. The component is called "Dialog crop **(Deprecated)**", I don't think it's deprecated though?
2. Is there value in showing the user a disabled "Delete" button? You will be able to delete the thumbnail only in the playlist flow, if you already have a thumbnail set. In all the other flows, it will not be usable so maybe better just hide it?
3. I think we need some responsive variant with the delete button visible

**Comment by KubaMikolajczyk** [comment]
@kdembler 
1. Its called like that because it's the old version of dialog and it will be moved to a new version but moving it eventually will take time to document a new type of dialog and do this properly and double-check the whole functionality (even if it's only documenting what is already implemented here) - so, for now, to deliver fast only a few changes done in this old component.
2. I updated the flow for selecting and positioning the thumbnail for the video workspace as well - the flow is here: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=2118%3A70005
3. Alright I will do the responsive version for those crop and position dialogs. On it

**Comment by KubaMikolajczyk** [comment]
Link to mobile version of dialogs:
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=216%3A60182

**Comment by kdembler** [comment]
Let's remove the delete button when not used please, I don't want users confused when they are uploading the image for the first time

**Comment by KubaMikolajczyk** [comment]
OK! I'm on it

**Comment by KubaMikolajczyk** [comment]
Corrected ✅  When selecting thumbnail for the first time the button is hidden.
Link to component: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=216%3A60182
Link to playlist user story: https://www.figma.com/file/XfKZ5ZSavt88rVfiKf0tBv/Playlist%3A-Channel-owner?node-id=970%3A16745
Link to video workspace user story: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=2118%3A70005

**Comment by toiletgranny** [comment]
> Its called like that because it's the old version of dialog and it will be moved to a new version but moving it eventually will take time to document a new type of dialog and do this properly and double-check the whole functionality (even if it's only documenting what is already implemented here) - so, for now, to deliver fast only a few changes done in this old component.

FYI, I've just recreated this window using the Dialog component in Figma, so that the designs are true to the implementation in this regard. Thanks to this, this component is no longer "Deprecated" in Figma.

![image](https://user-images.githubusercontent.com/35307309/158605638-11f07b9e-da2e-4d9c-8ef5-88da3c6c66ac.png)

**Comment by kdembler** [comment]
Lovely 😊
