### ISSUE TITLE
Idea: User feature request list

### ISSUE THREAD

**Issue by MindsGaming** [Joystream/atlas#2191]
Hello, I have recently joined your platform and Matrix chat with a few friends. These are our first impressions on what could be improved on the platform. We are aware of the upcoming UI update and we may add to this list  with any suggestions or  issues with the update. If you would like individual logs on the follow please inform us and we will make them and link them to the associated request as we can.

- [x] #2953
As I was recommend to your platform by a musician (eclipsingbinary) our first request is audio files like .mp3 & .ogg for music and podcast uploads. 
- [x] Mobile Access 
A good percentage of web users access the internet via mobile devices. 
- [x] #2954
Allow profiles to work together to make content and split the rewards by percentages.
- [x] Comments on videos
Allow users to comment on videos
- [x] Follow Profile
I like a creator and want to be informed of new channels and all content they post. I think a good way to do this is allow profile subscriptions that have these type of notifications. 
- [x] View Followers
Who is following me and what type of content do they make? This is a great way to build a fan base and strong following.
- [x] Channel posts
Allow channel posts for released albums or upcoming projects for your followers.
- [x] Add content policy/Gitlab 
The left side sidebar on play.joystream.org should include links to the user content policy and Gitlab for easy access for users and developers, 
- [x] Video Preview
A image and name of the video when you share a link.
- [x] Public Roadmap
Maybe you already have this but we couldn't find it.
- [x] Marketing Term "Users"
I think the term you are looking for is "community member" as a user is anyone who access the site as a community member is someone how interacts inside the site.
![joystreamUSERS](https://user-images.githubusercontent.com/19932832/155812487-1ca68fff-653c-4410-bd56-83b64743c0f4.png)

These are the basic things we noticed and think would be helpful after joining and exploring play.joystream.org  for a short amount of time. We haven't listed any joining issues as we are waiting for the update to see how the new process for new community members works.

**Comment by MindsGaming** [comment]
@mochet

**Comment by mochet** [comment]
Thank you for for this feedback, I am going to tag @bedeho in here as well, since he is the CEO of the project and will probably be interested to see what new users to the platform are interested in when it comes to features and functionality.

I very much understand how much technical stuff is involved with the project and one thing I would really recommend reading, or at least glancing at is the following issue, to get a really good idea of where the project is at when it comes to the plan for mainnet launch. There are a lot of things that have already been coded but haven't been implemented just yet and the project is going through a very rapid phase of things being added, information is all over the place, but this is sort of the "core plan" right now: https://github.com/Joystream/joystream/issues/2949

Just to explain a little:
- This repo `Atlas` is purely for the design of the UI for the consumer video experience, as shown here: https://play.joystream.org/
	- Changes to this part of things are somewhat easier than system level changes. 
- When it comes to functions that are based upon the underlying blockchain (`the runtime`) and other aspects there is another repo: https://github.com/Joystream/joystream
	- Changes to the `runtime` require a lot more work. So while suggested changes may theoretically be possible, we are quite close to launching and unfortunately it is somewhat unlikely any major changes would happen right now. HOWEVER, after mainnet launch the community can upgrade and improve the `runtime` as they want to.
- Don't worry about having created this here--in my answer I'll attempt to explain how this works which will maybe help in showing what various things would require in terms of changes.


* Audio Files
	* I believe this is technically possible without many changes. It has been discussed previously, I can't remember the outcome though.
	* On the UI front, it would require `Atlas` to have some changes to allow audio files to be uploaded.
	* On the `runtime` side I think there would maybe need to be small adjustments, but I am not exactly sure.
		* I've created an issue to get an answer for this here: https://github.com/Joystream/joystream/issues/3321
* Mobile Access
	* This has been discussed previously and hasn't been a priority just yet, I am not sure what the current status or effort towards mobile users is just yet.
	* Crypto projects, including those based on Polkadot and Ethereum have a somewhat uphill battle for mobile users. This is because for full functionality a mobile user would need to be able to manage accounts and submit transactions to the network and there are very limited options currently available for this.
		* It is likely that in the near future the Polkadot ecosystem will develop improvements in this area which we can utilize in the future to deliver a better experience to mobile users.
* Cooperative Splits
	* The way videos are rewarded on our project is via `Channel Payouts` which are basically payments decided by the council (these are not payments that are done for each and every channel individually, but rather a set of payments that reward `ALL` channels at a certain point in time):
		* A technical description of this is here: https://github.com/Joystream/atlas/issues/1813
		* I don't believe there is a way for these rewards to be split between cooperating users automatically. While it would be really nice to have, it would probably require huge changes to the `runtime`.
	* So this is going to be somewhat possible via `Creator Tokens` which are tokens that a `Channel` can issue.
		* A technical description of this is here: https://github.com/Joystream/joystream/issues/2362
		* Some videos also explained this concept:
			* Community Call 3 spoke about creator tokens: https://play.joystream.org/video/9763 -- sorry, I don't have an exact timecode handy right now.
			* There is a short video here talking about creator tokens: https://play.joystream.org/video/9763
* Comments on videos
	* This is already developed and deploying some time soon.
* Follow Profile
	* So this does exist, however it is not as easy or convenient as what you might expect. It exists on `Atlas` within the user state (cookies and browser storage) but it does not exist `on-chain`.
		* Making it happen `on-chain` isn't going to happen prior to launch (to the best of my knowledge).
* View Followers
	* Because of what is described above, this isn't possible at this stage sadly.
* Channel Posts
	* I really don't know what the status of this is, I am pretty sure it has at least been discussed at one stage, but I am clueless of whether it exists or is planned.
	* This would be a `runtime` feature, but it probably wouldn't be the biggest deal to implement.
		* I've created an issue just for this feature, I think it definitely has value and may be achievable (if it isn't implemented already): https://github.com/Joystream/joystream/issues/3320
* Add content policy/Gitlab
	* I sort of explained this in the chat earlier, but our content policy likely will not be hosted on any 3rd party service, but instead be an on-chain piece of information (the `constitution`) that can be updated by the community + council.
	* There's a description/discussion of the `constitution` function here: https://github.com/Joystream/joystream/issues/799
	* I definitely agree that this should be shown on Atlas somehow--but this feature hasn't been deployed yet and is part of that "major upgrade" so its a bit of a chicken and egg problem!
		* Have created an issue just for this suggestion: https://github.com/Joystream/atlas/issues/2192
* Video Preview
	* So if I understand this correctly, this would be like how Twitter will automatically get data about a video from YouTube when you share a video link?
		* If so, this is being worked on right now: https://twitter.com/JoystreamDAO/status/1491388914183122945!
		* If you have any particular services you'd like to support this kind of functionality, please share them.
* Marketing Term "Users"
	* I definitely agree with this, as I shared earlier in the chat there hasn't been a huge focus on marketing just yet. There is a repo just for the project's website here: https://github.com/Joystream/joystream-org and there are some design changes being worked on at the moment.
	* There is somewhat of a deeper meaning to this description which is worth pointing out, which relates to the much bigger picture of video content and how it is consumed and is a good answer to ``"What exactly is Joystream?"``
		* `Users` in this context is probably referring to those that actually have accounts, submit transactions and participate. So just like not all viewers of YouTube have accounts while still heavily consuming its videos on a daily basis, the same applies to Joystream.
			* So just as you mentioned how complex this project is to understand, there are basically a significant chunk of YouTube users who don't understand YouTube at all. They don't participate, upload, like, comment or share and so I will call them `consumers`.
			* The value in addressing what `consumers` are, is that it means Joystream's userbase isn't just restricted to those that have very high technical knowledge or who are capable of uploading content, but can go FAR beyond the kind of audience a cryptocurrency project would typically have.
				* It allows us to really go far beyond  this very real restriction and be technically capable of reaching people in living rooms--all without them having to understand anything technical at all about the project.
		* There is a complex aspect of our project which I won't explain in detail here, but essentially people can run their own customized copies of `Atlas` (or whatever front end they want to) for a profit and can basically serve JUST the platform's video content, its actually a "job" on the platform! Because of this, some people may really just be nothing more than `consumers` of content and not actually participate at all directly on our blockchain ever, nor see any proposal, so they wouldn't be `users`.
			* To some users they think we may be a "YouTube alternative" and to other users we might be a "Netflix alternative". What we actually are capable of being is a bit of both! and the distinction between the two is quite nuanced.
				* YouTube users may create channels, comment on videos and subscribe, but a good percentage of YT viewers don't do any of that.
					* In 2019, `250 million hours` of video content were consume via TV screens (https://invideo.io/blog/youtube-statistics/). TV users aren't going to be commenting or uploading videos.
					* In 2018, 97% of YouTube channels didn't generate enough views to make money. The number of channels that actually produce content regularly and get decent viewership is very low (https://observer.com/2018/02/study-youtube-stars-earnings-us-median-income/). So basically the 1-2% of "successful" channels are what users consume.
				* Netflix is practically a 100% video consumer experience
					* No comments, limited tools, no way to upload videos.
					* Even without any of the features that YouTube has, Netflix has more than 200 million subscribers and huge viewership.
			* So as a very basic example, someone might create an app for TVs that serves Joystream's content to TVs directly and not at all require those users to sign up or participate at all. The app might generate income via advertising in this use case, or charge people a subscription fee (which is done completely outside of Joystream, so users might decide to pay for access via a mobile phone payment)
				* We will basically have a system to incentivize this kind of use case.
		* If you really, really want to understand this concept more fully, then it is called a `gateway` but I warn you that it is a lot more technically complex than everything I've shown so far: https://github.com/Joystream/joystream/issues/2089

**Comment by mochet** [comment]
Hey @MindsGaming so I have a few updates--its not the best news, but I also included a way this can be changed after launch ):

* For Audio and Podcasts: on the `runtime` side of things this works, however the design of `atlas` doesn't support audio files and unfortunately there isn't enough time to add support for audio files (https://github.com/Joystream/joystream/issues/3321)
* For channel blog posts: This feature was designed in the form of a channel `subreddit` but it will be removed (https://github.com/Joystream/joystream/issues/3320)

So for the first issue essentially the biggest factor right now is purely time and since we're launching relatively soon it isn't feasible to introduce changes. For the audio features it would basically just be a cosmetic update as I understand.

For channel blog posts, I am sure you'll find it very weird that the feature was designed and is now being removed. I don't know the specific reason for this (unless @bedeho wants to chime in!) but it could be for any number of reasons (and probably also relates to time)...
- The most likely reason is that the code of the `runtime` needs to be finalized quite soon (ahead of the actual project's launch by 2 or 3 months) so that it can be audited by a 3rd party firm, it can't really change once it has been sent for auditing. The timing of the code audit is a very critical factor in everything right now.

As the project is going to launch as a `fully decentralized` platform, its basically critical that the code within the `runtime` has been thoroughly checked.

This doesn't mean any of the above is actually `final` though because after mainnet launch, the `council` (who are elected) can vote to fund design, development & testing of features like these. So the platform has inbuilt capability (in more than one way) to fund improvements exactly like these.


### "How do things like this get funded?"
I know that in the Matrix chat the concept of "how do things like this get funded?" wasn't that understandable.
A somewhat similar example I've used in the past to explain this concept is how larger ships far out at sea have their own workshop with a lathe, something like this: https://www.reddit.com/r/EngineeringPorn/comments/73k8p2/lathe_on_the_uss_missouri/
These are used on ships to fabricate parts that have been damaged or to keep replacements in stock. Basically a ship can stay out at sea and *technically* speaking can not only maintain itself but also "upgrade" itself (*technically* because the lathe still requires raw materials to fabricate things)

If we skip past the specifics of Joystream entirely, this is basically what we have--a very shiny, very precise lathe that can fabricate upgrades.

It is just a way for someone to ask a question and receive an answer (the answer in this case being funding):
* **Question**: *"I would like to code this improvement and it will cost 50000 JOY tokens"*
	(`question` then goes to the council, who vote to either approve or deny it)
* **Answer**: *"Ok we had a vote, its approved, here is your money"*

You could use the exact same thing to ask *"I want 50000 JOY to buy a ferrari"* and while the council would probably reject it, there is nothing to stop you from asking it. You can request funding for anything and if it is approved, the funds get `printed` and sent to your address `immediately` the moment the final vote is cast. 

Here is an example of that exact process: https://pioneer.joystreamstats.live/#/proposals/1209

There are a few more moving parts than that, but at its core it is really just a question and answer system. If you want to know more about it feel free to ask, I just wanted to ensure you had a bit more of a comprehensible way of understanding it!

**Comment by dmtrjsg** [comment]
@MindsGaming thank you for raising this. Just before closing the issue adding a few comments wrt to some points raised. The rest are sufficiently covered by @mochet.

Mobile access is always on the watch, so as soon as has good support form the ecosystem we are diving in to it. For the time being we are moving ahead with this:
 - https://github.com/Joystream/atlas/issues/2903
 
 Cooperative Splits
 - Revenue split between channel and community will be covered by revenue split feature as part of #2402 Epic which is now in the design phase. Collaboration between channels and revenue split is an interesting idea and I will raise it for the backlog. 
 
Notifications for Following Channels 
- We've paved the way into notifications for the NFT epic, and overall topic will certainly need to be a

Add content policy/Gitlab
- content policy, constitution and NFTs licensing info is in the pipe for mainnet

Public roadmap will be available folowing stabilisation period after mainnet launch.
- in the meantime you may choose to use label:mainnet; label:post-mainnet; label:urgent-post-mainnet to have a view on priorities in the short to mid run.
