### ISSUE TITLE
NFT Widget history integration

### ISSUE THREAD

**Issue by eldiegod** [Joystream/atlas#2217]
What should (and can) we support as entries for the Nft widget history?

what I have thought of so far:

Current auction bids
State changes i.e -> nft put on sale/auction/idle
Previous owners
Minting

**Comment by eldiegod** [comment]
cc @kdembler

**Comment by kdembler** [comment]
Do we show all the past auctions, even if they were cancelled? What do you mean by `Previous owners`? Maybe we could do full list of all types of entries?

@toiletgranny Would appreciate your input here as well.

**Comment by eldiegod** [comment]
`Previous owners` I mean every time the NFT transferred ownership, so there is a history of who owned it at some point.
For me, past auctions wouldn't be as important.

**Comment by toiletgranny** [comment]
So @Lenorette put together a list of all possible entries we can have in an NFT history back when she was working on the Video page, and I just wanted to make sure if you guys had a chance to review that? You [can find it here, in Figma]
(https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1264%3A122420).  
![CleanShot 2022-03-07 at 16 48 24](https://user-images.githubusercontent.com/35307309/157068205-dde20e96-ad5e-4727-943f-7dfc295ca86b.png)

The idea behind the NFT history section was to show _all entries_, so that would include canceled auctions as well.
