### ISSUE TITLE
Subtitles:Adding. Research & Discovery

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#2261]
# What we want to test
We want to see if the designed solution for adding subtitles to a video is easy to use by publisher users & catch any potential bugs / bad logic in this experience.

# How we want to test it
We will conduct moderated user sessions.

# How we will measure results
We will draw conclusions from users' thoughts, actions & mistakes.

**Comment by KubaMikolajczyk** [comment]
The prototype was created to test the usability of adding subtitles feature and short video overview of it is also attached down below 👇
Prototype link: https://www.figma.com/proto/9ahrOSqPdyGfZmpKrtUpFn/Subtitles%3A-Publisher?page-id=702%3A5376&node-id=751%3A15731&viewport=490%2C48%2C0.3&scaling=min-zoom&starting-point-node-id=744%3A29183
Video overview: https://www.loom.com/share/99c4ae9905ac4873a32c15349595fb6d

**Comment by bedeho** [comment]
# Feedback

- This looks very promising, love the nice large buttons and clear state indicators.
- What sort of error information will you be providing if someone selects and invalid file (e.g. empty, corrupt format), and what will this variation looks like?
- Depending on how this information is organised in storage system and video metadata, accurately displaying what subtitles actually are available for a given video may take some time, and you may need some loading state for this. Likewise also allowing downloading of an individual existing file when editing and existing video, may take some time, requiring a loading state. This download may even in principle fail, but I suggest we just deal with it in a naive way of just having Atlas retry and download again from another distributor.

# Question

- Do you have any idea how large these sorts of files typically are? I ask, because if we are going to compress them or otherwise do something fancy, it may possibly require some sort of progress indicator for this processing.

# Note

- You probably want to have @kdembler in the loop about how this information is going to be bundled and stored as an asset, and likewise retreived for the purposes of the player. Remember that this subtitle information is not going to be stored on the blockchain itself, but rather as a standalone asset, just like images & video media.

**Comment by kdembler** [comment]
> Depending on how this information is organised in storage system and video metadata, accurately displaying what subtitles actually are available for a given video may take some time, and you may need some loading state for this. 

I would expect QN to "understand" subtitles and offer metadata about them without any additional loading. 

> Likewise also allowing downloading of an individual existing file when editing and existing video, may take some time, requiring a loading state. This download may even in principle fail, but I suggest we just deal with it in a naive way of just having Atlas retry and download again from another distributor.

I don't think this download needs to be handled in any way in the UI, we could just use browser-native download

> Do you have any idea how large these sorts of files typically are? I ask, because if we are going to compress them or otherwise do something fancy, it may possibly require some sort of progress indicator for this processing.

~150kB max for a 2-hour movie, I don't think we need any compression

**Comment by KubaMikolajczyk** [comment]
# Adding subtitles 23.03.22
1️⃣ During this test, we were checking the usability of the current solution for adding subtitles publisher experience. 
2️⃣ We conducted moderated usability test with 5 participants:
    I: A person who added subtitles in the past to videos ✅ and does not know what closed captions are ❌ and didn't hear about webvtt format ❌
    II: A person who added subtitles in the past to videos ✅ and does not know what closed captions are ❌ and didn't hear about webvtt format ❌
    III: A person who added subtitles in the past to videos ✅ and knows what closed captions are ✅ and didn't hear about webvtt format ❌
    IV: A person who added subtitles in the past to videos ✅ and does not know what closed captions are ❌ and didn't hear about webvtt format ❌
    V: A person who added subtitles in the past to videos ✅ and knows what closed captions are ✅ and knows about webvtt format ✅

# Testers to pay
5EqVuvYEyzCa7xuEZYw9FM5Vkd7FaTcq5CKKN2LuSNqqv8FP
5HVxLAskxQZiQMJwfMWDGQfK4beevP17zjYm8PAaA7GTZqdW
5CfjBwVfBxrGxNF6PWt9Fh5A6KicPMptbR3AQ9MUUFkzsMSm
5E9ZTTBh4p7vvrkJczqtYVMggimVhW3KJ83SdtBPy3TenANs
5CaDmoBUtV2ebxiFY3YVaK1k2k8bo9wcxGVTjKPhBSxXLuoH

#Results
✅  All users completed test scenarios successfully and with no noticeable problems
✅  All users knew how to add, remove, mark as closed captions and reselect the file
✅  All users knew how to add multiple subtitles

How was it for you to add subtitles that way:
- It’s really really easy. Everyone should be able to do it.
- It's ok for me but I would consider adding an option to add subtitles online
- Awesome its very easy to find and convenient to use

Because no major issues were spotted during the tests - my recommendation would be to proceed with the current version of this experience and finalize it in its current form.

**Comment by dmtrjsg** [comment]
@kdembler  is there a way to detect the language from the file uploaded using a lib of some sort? Just thinking if that is the case,  [seemingly] could be a more fluid experience, starting with a file-drop, and _then_ once uploaded, user can add meta-data saving a few clicks where we just filedrop and switch to audible in 1 click (saving whole 3 clicks :) ).

**Comment by kdembler** [comment]
Oh, that would require some very heavy lib to work properly, doesn't seem like a good candidate for the first implementation
