### ISSUE TITLE
Remove Last video 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2269]
### Context

Removing last video from the edit playlist view

### Scope

- [ ] Disable "publish" CTA for playlists with no videos

### Design

[Figma url](https://www.figma.com/file/XfKZ5ZSavt88rVfiKf0tBv/Playlist%3A-Channel-owner?node-id=1013%3A30904)

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk pls can you cross check with youtube how this is handled? We were debating with majority of views in favour of allowing to publish empty playlist (But exclude it from indexing so users dont click into empty ones during discovery)

**Comment by KubaMikolajczyk** [comment]
Youtube allows doing this but it's worth mentioning that they do not publish or unpublish anything all of the actions are saved automatically so the fact that they do not block it can be also a matter of the fact their app is built on web2.0 architecture. Maybe it would be even harder in their case to prevent user from having empty playlists.

But our case is a little bit different as we have this stage of submitting and making a transaction and therefore we have an option to prevent having an empty playlist. 

It's a matter of deciding whether we want users to be able to create an empty playlist by removing videos from it + if we do we should allow users to be able to publish empty playlists normally - because now there has to be at least one video to publish it. (talking now about different scenario where user tries to publish new empty playlist)

Wdyt?

**Comment by dmtrjsg** [comment]
Let's prevent from publishing it. Assuming discovering empty playlists for content viewers bears negative value and designing around it on viewers side will require some effort let's move fwd with disabling publish cta on empty playlists.

..do we have a special case with "Cancel" if the most recent action was deleting a video 🤔  @KubaMikolajczyk @kdembler

**Comment by kdembler** [comment]
I would say there's still value in creating an empty playlist. You can create it as a placeholder to add videos later. We can filter empty playlists out in the viewer experience so it doesn't bring negative value
