### ISSUE TITLE
Update to work with final base token supply & $JOY denomination

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2277]
## Context

We are going to make this change: https://github.com/Joystream/joystream/issues/3390
which have non-trivial design implications for display & input fields, possibly also some internal numerical representations.

## Scope
..after more clarification and agreement achieved on Design weekly the scope is greatly reduced to updating the current "number" component to contain info about denomination in the tooltip.

- We only display fees in BDH (currency name is TBC)
- For tooltips that display fees add information about relation of tBDH to tJOY, which will be easily updated to (BDH to tJOY) upon mainnet launch

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202171857680459) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
Working note: a tooltip with an explanation for BDH = tJOY/JOY.

**Comment by toiletgranny** [comment]
@dmtrjsg @bedeho @kdembler Is this really necessary to explicitly surface in the UI, as opposed to converting fees to JOYs on the fly and displaying those instead?

As a UX designer, I'm concerned about the number of tokens/currencies we force end-users to process mentally during one flow. We already have JOY tokens, US dollar conversions, and local currencies which most of our users also need to take into account. And now we're adding BDH to the mix (and to the UI), which makes me worried about how it's all getting really mixed up in the context of, for example, a simple like I want to add for a video and the fee that's involved with it.

For this reason, I wonder whether this would be technically feasible to stick to JOY tokens for displaying fee amounts?

**Comment by kdembler** [comment]
We could stick to JOYs, the issue is that values for fees will likely be super small. Displaying something like `0.00000001 JOY` as the fee value may not really be optimal. It's also an existing pattern. When you interact with Ethereum web3 apps, it's a standard behaviour to display all values in ETH but all the fees in (g)wei.

**Comment by toiletgranny** [comment]
> It's also an existing pattern. When you interact with Ethereum web3 apps, it's a standard behaviour to display all values in ETH but all the fees in (g)wei.

This sounds interesting! Can you name some specific examples? The ones I stumbled upon actually used ETH for displaying fees (like Rarible, an NFT marketplace, screenshot below), which gave me the additional confidence to suggest dropping BDH from UI.

<img width="529" alt="CleanShot 2022-06-14 at 16 41 09@2x" src="https://user-images.githubusercontent.com/35307309/173605673-80d62eb1-1840-47c2-af3e-1df4c06d1dcc.png">

Here's a Metamask screenshot: 
<img width="340" alt="CleanShot 2022-06-14 at 16 46 48@2x" src="https://user-images.githubusercontent.com/35307309/173607055-af1f2fcc-77fb-4a1b-92de-932c59afd502.png">

**Comment by kdembler** [comment]
Okay sorry, my mistake here, fees are in fact displayed in ETH, you are right. Gas prices are usually in gwei, that's what got me confused. There is still this issue of fees being possibly very small values when displayed in JOY, but I actually really liked your approach from the video you've send in the other issue (https://github.com/Joystream/atlas/issues/2815#issuecomment-1155280382). So just displaying something like `< 0.01 JOY` when the value is really small. With the current estimates 1 JOY may be around 0.06$ on launch so if you don't get super accuracy for your fraction of a cent you probably won't care.

So I agree, let's display fees in JOY too

**Comment by toiletgranny** [comment]
Well, if we have an agreement on this, then @dmtrjsg, I believe this issue can be now closed, as there are no design changes.

**Comment by dmtrjsg** [comment]
@toiletgranny 

1️⃣  **Comments:**

Overall I would opt in for showing actual fee in JOY and tooltip icon next to it (rather than line of text insinuating same info). On tooltip click, we serve a popup encapsulating this copy:

"We store all records, including assets metadata, comments and reactions on blockchain, transaction fees apply to cover for the computational costs of adding such records to the block and processing it. Tap or click on the transaction fee to view full accurate precise representation of transaction fees." (hover is not mobile-friendly)

So when number is clicked you see:

"Transaction Fee of 1 JOY and 123556646 BDH* applies
($USD 0.00006)
*1 JOY = 1000000 BDH".


2️⃣  **Reactions**

I think we only include info about reactions fees to the initial screen (once) and not bother on showing tooltip for reaction hover as this makes it less engaging to use and fees will be without variation for all transactions and very insignificant. 

3️⃣  **Footer of modals:**

- Similarly to comments section above, I would just put all text explainers to a tooltip and only show the actual fee 
- Liking the <0.01 JOY approach 🙌  
- The fees label -> Transaction fee: (rather than just fee)
- Do we need to repeat transaction fees on both modal footer AND confirmation screen list ? There are no inputs at this stage so no fees variation, so thinking we show on all modal steps apart from last one?

Lastly:
- Would be good to see numbers component and fees updated tooltips on the same figma page, so that we can "copy-paste" this to Pioneer and ensure same approach, if that's not too much to ask 😇
