### ISSUE TITLE
Atlas product animation — NFT publisher side

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2288]
The goal of this task is to create a short product animation for social media to advertise NFT functionalities being added to Atlas, focusing on the publisher experience.

1. Animation length: `30-60s`,
2. Animation resolution: `1080 x 1080`,
3. Sound: `no`,
4. Animation style: https://github.com/Joystream/atlas/issues/1844#issuecomment-1026853545
5. Content on mockups: `100% fake`,
6. Example scope of the animation contents:
   - [My videos page](https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page), with a particular focus minting an NFT from a video tile level,
   - [Video workspace view](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace), with a particular focus on the flow of uploading a new video and minting it as an NFT,
   - [NFT workspace view](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace), with a particular focus on the flow of putting an NFT on sale/auction.
   - [Video page](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=0%3A1) with a particular focus on the NFT widget from the perspective of an NFT owner.

See also: https://github.com/Joystream/atlas/issues/2287

**Comment by toiletgranny** [comment]
_👇 🔉  sound on_

https://user-images.githubusercontent.com/35307309/161092415-671672af-b868-497e-899e-c69619da1b98.mp4

@bedeho @mrexpat the second animation is ready for you guys to be reviewed! 🚀 A reminder, that this one focuses more on the publisher's experience and the process of putting an NFT on sale.

I'm using the same content as in https://github.com/Joystream/atlas/issues/2287, so that it's easier for viewers to map different parts of NFT functionalities based on watching two videos.

Robert, I'd especially appreciate your recommendations on text screens in the animation. 🙏

**Comment by dmtrjsg** [comment]
@mrexpat @bedeho awaiting feedback on this one..

**Comment by mrexpat** [comment]
Alrighty!

Another amazing production @toiletgranny - the main issue is things move a little bit too fast and some things need better context..

00:00 - change copy to "Selling your video content as NFTs" - be mindful of how much time on screen the scene gets. make sure you look at any screen that has copywriting with fresh eyes where you actually read the text yourself (its easy to get blind to it), to gauge whether it's sufficient time on screen or not. every video editor ive ever worked with doesnt give enough time on screen for the copy ;) but then we lose context for the viewer

00:05 - change copy to "Quick & intuitive listing process" - again, check the time on screen, for now it's too short to read & comprehend

00:06 - the cut here on the "choose listing type" frame happened very fast and i didn't even realize it was actually cutting to a closer look of the same frame. i was under the impression that i had missed something. perhaps do a zoom in here instead of the cut, in order to not leave the viewer feeling they missed something, and disrupting the flow

00:10 same thing here actually.. the aggressive cut made me think i was looking at a new frame, and that i was missing something, as it again happened very quickly. i think a quick zoom job would prevent this feeling

00:16 when we click Publish on this "Accept listing terms" frame id love to see a zoom job on the publish button before it gets clicked as well.. this video will be so small on social media they won't rly see much otherwise

00:21 "Explore multiple sale types" - i am not sure what this refers to, or what the video sequence is attempting to show.. pls clarify

00:24 The copy is on screen for too short of a time period again.. not enough time to read it

also, the video that follows shows bids coming in.. I would either want to a) change it to show the person choosing their Royalty in the listing process, or perhaps even better, keep the current sequence, and add some visible text every time when a new bid comes in saying smth along the lines of "Royalty earned: $100" -> new higher bid comes in "Royalty earned: $200" etc etc..

Great job with the production

**Comment by toiletgranny** [comment]
Thank you for the thorough feedback, @mrexpat! Looking at the other tasks I have on my plate at the moment, in order to help us sort out the priorities, I need to ask if there's a specific date you have in mind for when you need this video to be ready?

**Comment by mrexpat** [comment]
Whenever we launch RHodes.. so @dmtrjsg prob most up to speed on that.. With this in mind I believe both videos end with "Launching soon" or smth along those lines.. you'd need to change that to "Live now" instead, as we'll post the video once Rhodes upgrade is done

**Comment by toiletgranny** [comment]
@mrexpat Based on the above and our follow-up conversation on Slack, you can find the revised version of the animation below. If you're happy with the outcome, a reminder that all product animations, in full resolution (I think GitHub compresses videos in discussions), can be found in the design repo on GitHub [in this folder.](https://github.com/Joystream/design/tree/master/social-media/product-animations/atlas)

https://user-images.githubusercontent.com/35307309/167156276-d1322d55-f3b7-4399-aaba-6599fa88af39.mp4

**Comment by mrexpat** [comment]
hey @toiletgranny - great work.

only issue imo is 00:24 - 00:26 earn royalties... and then viewer has no idea what they're looking at, we do not show anything that has to do with royalties/secondary sales.. 

imo just get rid of this clip

**Comment by toiletgranny** [comment]
Got it, @mrexpat! Here's the new file! :) https://github.com/Joystream/design/blob/master/social-media/product-animations/atlas/2_nft_publisher/_render/1_nft_publisher_rev_02c.mp4
