### ISSUE TITLE
Video page right side layout loading state - (Nft Widget related)

### ISSUE THREAD

**Issue by eldiegod** [Joystream/atlas#2330]
Are we ok with a layout shift on the right side where the Nft widget lives if the video has an nft and we make the nft widget appear?

or do we want a general loading state for this area as we wait for the nft data? 

cc @kdembler  @toiletgranny

**Comment by toiletgranny** [comment]
Thanks for bringing this up, Diego! To answer your first question: no, of course, we're not ok with that. But, well, what options do we have?

You suggested a general loading state for the area reserved for the NFT data, which initially sounds like a good idea, but:
1. At its best, it merely _mitigates_ the problem of the shift in the layout, because we can't really predict exactly how tall the NFT widget will turn out to be upon loading.
2. At worst, if it turns out there's no NFT for a video, it creates a huge and unnecessary shift in the layout of the left-hand sidebar, which is even worse on mobile devices, where everything is stacked in one column.

The best thing that comes into my mind right now would be to just _ease_ the pain for the users when the layout shift occurs by applying some animation to this transition, like in the below example. The good thing about this is that if the transition isn't too fast, it helps the user keep a visual track of what's changing and in which direction.

https://user-images.githubusercontent.com/35307309/159518372-59c83415-71c8-45b0-bc6f-e374e98c085e.mp4

I'm sure this would involve some trickery to get it right, but would it be impossible? Performance is something we should probably also keep an eye on when considering this as a solution. 

But yes, ultimately, this would be my recommendation. Either this or doing nothing as it still sounds like a better solution assuming that most videos will not be minted as NFTs.

**Comment by dmtrjsg** [comment]
Discussed with Klaudiusz, too small to focus on it in any of the teams, so closing for now.
