### ISSUE TITLE
Creator Rewards: Research & Discovery

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2362]
This phase can include activities such as debriefing, desk research, competitor analysis, booking and conducting discovery in-depth interviews, or performing moderated usability tests on existing competitors' products.

The expected outcome is a brief report on key findings & conclusions, a link to Figma moodboards, screenshots from the competitor analysis, etc.

**Comment by TCzechowski** [comment]
FINDINGS:
The only web3 product that uses similar (but not exactly the same) concept is Mirror (https://mirror.xyz/dashboard/splits). There is not much documentation on that though, and I couldn’t go through the full process as they don’t have any test environment and I couldn’t afford the transaction fee paid in ETH. 

I’ve gone through some web2/crypto apps to see how their dashboard / revenue screens look like ([link](https://www.figma.com/file/c4TB1l0dcftQNlHtE3VDEl/Payouts?node-id=716%3A5346)), but there is not much we could re-use. It looks like we are going to be pioneers with that feature and will need to rely on iterating and user testing.

**Comment by dmtrjsg** [comment]
@TCzechowski  we've discussed looking at the Sports Betting apps for the balances accrual/ withdrawals. I think they may have more relevant info to offer on the layout of account wallet mgt.. Perhaps not too late to revisit this point.

**Comment by TCzechowski** [comment]
@dmtrjsg I've done some quick research and for the sports bettings apps, I've gone through Bet365, Betway, DraftKings, Bovada, Betfan (Polish). The access to those was very limited (had to use VPN and give my personal data, which I couldn't in some cases because they required documents that I do not own 😅 , but I tried to get some insights from youtube videos/articles e tc). For the crypto staking apps it was PancakeSwap and AQRU (something new that was launched this year).

Most of the sports betting apps use similar patterns:

**Comment by TCzechowski** [comment]
@dmtrjsg I've done some quick research and for the sports bettings apps, I've gone through Bet365, Betway, DraftKings, Bovada, Betfan (Polish). The access to those was very limited (had to use VPN and give my personal data, which I couldn't in some cases because they required documents that I do not own 😅 , but I tried to get some insights from youtube videos/articles e tc). For the crypto staking apps it was PancakeSwap, UniSwap and AQRU (something new that was launched this year).

Most of the sports betting apps use similar patterns:
1. Users balance is placed directly in the navigation bar (so they don't use a separate screen for account balance etc.)
2. To withdraw money, you need to click "Withdraw" in the navigation bar (top right corner), which takes you to a withdrawal process where you need to type in password and the amount (in some cases you need to choose the payment method etc)
3. For accruals - Everything is placed in a table (separate screen) with a "Cash out" button.
4. One thing that stood out for me is how BOVADA displays "withdrawable" money. Maybe we can use similar concept to show the user the "Claimable" amount for the rewards
![image](https://user-images.githubusercontent.com/22870059/164411824-f701480b-ed36-4117-9af9-6413676e7d07.png)


For the crypto staking apps:
1. PancakeSwap uses a simple table where they display all of users Farms, and each record has the "Harvest" button displayed after expanding the row. When you click on it, the funds are transfered to your balance.
![image](https://user-images.githubusercontent.com/22870059/164411932-ae67db90-1362-4d0e-82b9-faa8a344cf55.png)


2. UniSwap on the other hand, uses a very simple screen that is similar to what we have in our widget: they display a tile with basic information, and after clicking this tile, the user is taken to another very simple screen with "Your unclaimed XYZ token" amount displayed, and a simple "Claim" button inside the tile.
![image](https://user-images.githubusercontent.com/22870059/164411317-bfdc734a-7775-4df3-80a5-11b5c73d7d22.png)



Although I don't think we can re-use much from the sports betting apps (their UX is very... outdated let's say ;) ), they gave me a couple of small hints on how we can improve our views. I'll adjust those and show them to you soon!

All of the screenshots can be found here:
https://www.figma.com/file/c4TB1l0dcftQNlHtE3VDEl/Payouts?node-id=950%3A81389
