### ISSUE TITLE
Creator Rewards: Testing

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2364]
This phase can include activities such as conducting moderated/unmoderated usability tests on prototypes from the LoFi phase, doing surveys, or other types of user research.

The expected outcome is a brief summary of key findings, a list of recommendations, and a list of test participants to be paid out (if applicable). Learn more from [Approaching testing in Atlas](https://grizzled-corleggy-af8.notion.site/Approaching-testing-in-Atlas-115a1c0480144c8682dc9b63c99473c4) Notion article (WIP).

Depending on the results, the next step is either proceeding to the next phase of the design process or going back to the LoFi phase and repeating the tests if needed.

**Comment by TCzechowski** [comment]
# Testers to be paid out
5E9ZTTBh4p7vvrkJczqtYVMggimVhW3KJ83SdtBPy3TenANs
5EqVuvYEyzCa7xuEZYw9FM5Vkd7FaTcq5CKKN2LuSNqqv8FP
5CaDmoBUtV2ebxiFY3YVaK1k2k8bo9wcxGVTjKPhBSxXLuoH
5FdtkcMwGtPWH7bX7tLto39SxTG5zwyxBCXfXcmFHykCHp74
5CDCqEbzTiyxpaNGEK7M7wzEvwrjY6rQpM2Np5zm2nFPEVfj
5HMoR3CWHAtS52SjpTFNR5u7nJbYTKaGcBDeNJ431RYDzNAW

#Figma
https://www.figma.com/file/c4TB1l0dcftQNlHtE3VDEl/Payouts?node-id=831%3A77792

# Hypotheses

1. Users know how much they’ve received from the council, even if they couldn’t pay it out all at once. ❌ Failed
2. Users know that next payout date is just an estimate. ❌ Failed
3. Users know where to find past payout reports. ❌ Failed

# Key findings / TLDR (+ possible recommendations)

- **🔎 Users don’t recognize that Rewards are completely separate topic from the rest of the transactions**
	Possible solution: Splitting those 2 things into separate pages?
- **🔎 Users don’t understand the concept of working group being “out of budget” and current way of displaying total/claimable reward is confusing. They thought that greyed out amount is the maximum amount of reward that they can receive and it won’t exceed this number in future payouts.**
Possible solutions: Think of a different way to display that information (To be explored).

- **🔎 The current way of displaying ETA brings more confusion than value for the user and they don’t find it useful if it’s not an exact date.**
Possible solutions: We probably should get rid of that information from the screen, and maybe include a small info that “payouts usually happen once every week” instead of saying “>3 days” 
- **🔎 Current placement of entry point for rewards history is not intuitive at all (When asked to find reward reports, users went straight to transaction history)**
Possible solutions:  1. Change “Transaction History” to “History”, add a new tab in the table called “Rewards” 2. Split into two separate tabs?

- **🔎 Users don’t understand that they don’t have the reward in their account until they claim it**
 Possible solutions: Try different labels for that box (e.g. “Awaiting reward” instead of “Available reward”) 
- **🔎 Users don’t read the tooltips - we cannot rely on them to provide important information** 
Recommendation: Take the “Full reward” amount out of the tooltip, find another way to display it 

# Tasks
## 1️⃣  Task 1: Click “start mission” and take a look at the displayed page. Don’t click anything, just tell us - what do you see and what do you think each section is about?

**First person:**
- Thought that “Rewards” is actually revenue from NFT

**Second person:**
- “I don’t have clear understanding what is this [channel balance]”

**Third person:**
- Available rewards means how much tokens I can claim right now any moment and I can do anything with it: transfer from my account, exchange something 
- ETA: It means I have an opportunity to get tokens in every each quantity of time, like week, and the next will be in more than 3 days
- Channel Balance: It means quantity of tokens that stayed on special channel balance, but I don’t know what it exactly is.
- When asked what the Available Reward is for the second time (to clarify), user stated that it is their Account Balance. 

**Fourth person:**
- Mistook Rewards with revenue from NFTs, bounties 

**Fifth person:**
- Rewards: They were confused and wondered if it is always going to be like that because they thought Rewards are the only way to make money and it felt weird that someone [council] has to notice them in order to earn money 

**Sixth person:**

- Reads the tooltip of Available rewards
- Total earnings are confusing because they don’t add up [with other numbers]
- Tries to add everything from transaction history to check if it adds to total earnings
- Does not understand why the channel balance is that low when she has the available reward for much more [it is not clear that the reward is not yet on their account]

## 2️⃣ Task 2: Claim the reward from the council.

**First person:**
- Thought that 900k is max for them to be withdrawn (that rewards are capped at 900k and he can’t receive more in the future)

**Second person:**
- Missed the total reward completely at first try
- "I didn’t think it’s from the council, I thought it’s from smart contract or NFT sales"
- When “total reward” was explained, the user said that they would check the tooltip in a real-life scenario

**Third person:**
- Didn’t have any problems with going through the flow
- Didn’t notice the total reward
- Missed the tooltip because “it was very small [tooltip]”

**Fourth person:**
- Was really lost, didn’t know what to do
- You can claim 900K max, but someone gave you 771K
- Thought 900K is the cap and you won’t be able to get more than that

**Fifth person:**
- Didn’t have any problems to find the button
- Reads the tooltip, which made them confused because they thought 900K is the max cap
- Thinks the previous channel balance was withdrawn when we claimed the reward

**Sixth person:**

- Did notice the tooltip, but couldn’t tell how much the council gave them [thought the group gave her 770K instead of 900]
- They were insecure about being dependent on the working group (“Payment should not be delayed”, “because for someone who is working hard to be creator and if the working group has conflict with the council and they can’t find an agreement on the budget and because of that payments of the creators will be delayed”)

## 3️⃣ Task 3: Please tell me, do you know when exactly is the next reward going to take place? When?

**First person:**
- “I think the sign is wrong here because it means it would be over 3 days [of wait time]”
- I don’t think it’s a useful information in this case

**Second person:**
- Thinks it’s actually less than 3 days
- Thinks it’s an estimate because of the blockchain (blocks)
- Said it would be better for them to have a range (3-4 days) instead of “more than 3 days”, because it can happen in 3, 10, 20 days and it’s confusing
- "Can we put a small text here [explaining why it’s just an estimate and why it can happen at a random time]”

**Third person:**
- Doesn’t have any problems with finding that information, but clicked the list of reports first and thought it’s a schedule, not history
- “I think that information is better than not knowing at all, but it would be more useful if I knew the exact date”.

**Fourth person:**
- Finds the information about the estimate,
- Doesn’t find that information useful (because it can happen in 3 days, 10, 30, we don’t know) 

**Fifth person:**
- Thought that the next reward is going to be in 3 days (specifically)
- Doesn’t know what it depends on (didn’t read the tooltip)
- States that this information is useful as it releases the anxiety “Just even knowing that it takes at least 3 days for council to proceed”. I’m not sure if they fully understood and if it really releases the anxiety since it’s really RANDOM and >3 days brings even more confusion ~Tomek

**Sixth person:**

- Did find the information,
- “You should have a fixed date of the week maybe, it should be better because it’s only an estimate, so you know, people hate waiting especially when they don’t know the exact date”

## 4️⃣ Task 4: Could you please tell me how much did you get in your previous reward and what is the reason you got it?

**First person:**
- Couldn’t find the history of reports
- Advised to connect both tables (reward reports and transactions) to be in one place

**Second person:**
- Didn’t really understand the task, but goes straight to the “transaction history”
- “My earnings [mistook earnings for rewards] are transactions, and I was expecting this to be in transaction history”

**Third person:**
- Easily found the “reward reports”, but it can be because they accidentally went there in task 3 :D
- “I expected to find that information there [points to transaction history]”.

**Fourth person:**
- Goes straight to the Transaction History
- When asked “what would you expect to find under “see all” button in Next reward ETA?”, they told “maybe information about previous rewards” - so they guessed it correctly, but they didn’t think of clicking that button, but went to the history straight away

**Fifth person:**
- Goes straight to the transaction history
- Tries to click on a table row to expand it

**Sixth person:**

- Goes straight to the transaction history
- Didn’t find the button and information
- (After explanation) “I would look for it in the transaction history to be honest”
- “The box says ‘Next reward ETA’, so it should focus on the timing only”
- “Maybe it would be better if there will be a section dedicated only to rewards” - Points to the transaction history [they meant another tab for just the rewards]

**Comment by toiletgranny** [comment]
Hey Tomek, thanks for the great summary! 💪 Here are my 5 cents:
> **🔎 Users don’t recognize that Rewards are completely separate topic from the rest of the transactions**
Possible solution: Splitting those 2 things into separate pages?

> **🔎 Current placement of entry point for rewards history is not intuitive at all (When asked to find reward reports, users went straight to transaction history)**
Possible solutions: 1. Change “Transaction History” to “History”, add a new tab in the table called “Rewards” 2. Split into two separate tabs?

I remember your initial explorations with reports being listed in a separate tab in the transactions history table, which was also something that @dmtrjsg recommended, which could be a potential solution to this problem. However, in the light of other findings from your research, I agree that having council payouts as a separate view/page might be the best way of approaching this. After all, Creator Rewards are just one of many possible sources of income for your channel, right next to NFT sales revenues, or Creator Tokens.

> **🔎 The current way of displaying ETA brings more confusion than value for the user and they don’t find it useful if it’s not an exact date.**
Possible solutions: We probably should get rid of that information from the screen, and maybe include a small info that “payouts usually happen once every week” instead of saying “>3 days” 

I'd still vote for finding a way of displaying this information in a way it's not confusing. If there is indeed some anticipated frequency of council payouts on which we could safely rely on (cc @bedeho?), then perhaps we could display the date of the **last** payout along with that footnote you suggested about _payouts usually happening every X_?

> **🔎 Users don’t understand that they don’t have the reward in their account until they claim it**
 Possible solutions: Try different labels for that box (e.g. “Awaiting reward” instead of “Available reward”) 

For me, this is yet another argument for making Creator Rewards a standalone view/page. For example, with less info to be displayed in a single view, that's just dedicated to Creator Rewards, we can allow ourselves for larger and more prominent "Claim" CTA, making it (hopefully) more clear that this is what you do with your rewards. You claim them.

> **🔎 Users don’t read the tooltips - we cannot rely on them to provide important information** 
Recommendation: Take the “Full reward” amount out of the tooltip, find another way to display it 

Same as above. I understand we hid some information on Creator Rewards mechanics to save page real estate, as we need to share it with general info on the channel's finances. But if these are two separate pages, then I think the problem's gone.

**Comment by bedeho** [comment]
> more confusion than value for the user and they don’t find it useful if it’s not an exact date.

Confusion for some  I understand, but how are we determining that its on net negative value? This is just very intuitively hard to grasp. Also, `ETA 3 days` is highly precise for the purposes of this kind of deadline, who needs to know with greater precision than this for this kind of event? This does not sound reasonable to me.

**Comment by toiletgranny** [comment]
Action items for @TCzechowski from the _Atlas Tech <> Design Sync_ meeting with @dmtrjsg:

1. Let's do A/B testing:
   - A: transaction history and council payouts are on the same page, as separate table tabs,
     - Let's rename the tab "Rewards" -> "Council Payouts",
   - B: transactions and payouts are separate pages/views,
2. ETA to be replaced with the last known payout date + a footnote about the frequency of historic payouts.
3. Let's try to rely less on tooltips and find more opportunities to display more concise copy as footnotes/captions.
4. Let's review sporting bets apps and cryptocurrency exchanges.
