### ISSUE TITLE
Allow linking to a specific comment

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2391]
## Context

1. User clicks the notification or a hyper link from the comment timestamp
2. We redirect them to specific video page

## Scope:
3. We scroll to make sure the comment from notification is visible on the screen
4. We use highlighted state
- [ ] Both notifications redirect with screen focus to originating comment or reply (https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2411:216105)

**Comment by dmtrjsg** [comment]
We were not sure how to handle teh case when comments are still loading on the page.. so putting it to redy for design. Let's discuss this on Monday, perhaps we'd need to do some additional tech research.. tbc

**Comment by toiletgranny** [comment]
I'd assume that if we don't solve this problem, this is also going to prevent us from having users being able to copy unique links to comments ([as described here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2411%3A217091), "Timestamp" section)? cc @kdembler

**Comment by kdembler** [comment]
Ah yes, good call

**Comment by toiletgranny** [comment]
Damn. That's a pity. 

I'm sensing that it's the "dynamic loading" of comments being an obstacle, am I right? If that's correct, perhaps there's something we can try looking at how YouTube handles this. From what I can see, YouTube also loads comments dynamically, as you scroll. Yet, somehow it is possible to generate a link to a specific comment, [like this one](https://www.youtube.com/watch?v=eqvBaj8UYz4&lc=UgwpJVSLUDxzVcg6G8F4AaABAg). They don't seem to be having as much fun as we aim for with more prominent styling or scrolling into the linked comment, but it's very clear that somehow they can do that (the linked comment is displayed at the top of the comments section, with a "Highlighted comment" label).

![CleanShot 2022-03-31 at 18 30 15@2x](https://user-images.githubusercontent.com/35307309/161104996-e6ff37f8-b2c9-4f22-aa60-9275f5f42ce5.png)

[Here's a regular link to this video](https://www.youtube.com/watch?v=eqvBaj8UYz4&t=20s), for comparison.

**Comment by toiletgranny** [comment]
Alright, @dmtrjsg, @kdembler, I updated [designs, docs, and user stories for comments](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1426%3A86220) to address the above, and also to address the other issue we talked about: adding replies to other replies, in a way that it doesn't technically create another thread.

Details can be found in the changelog in Figma, which I'm pasting below, for your convenience:
> - Comments: Updated user stories concerning comments and accessing them via URLs, so that the comment in the URL is always displayed at the top of the comments section (and a few more nuances):
>    - [As a channel owner I want to get notified about new comments under my videos.](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/?node-id=2550%3A230287)
>    - [As a content viewer I want to get notified about replies to my comments.](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/?node-id=2544%3A228764)
> - Comments: Updated [As a content viewer I want to reply to other people's comments under a video I'm watching.](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/?node-id=2213%3A140576) user story so that replies added to other replies are kept within the same thread and are, by default, prepopulated with a member handle.

---

@dmtrjsg A reminder that this solves two out of three issues we've identified with the comments dev epic. We've discussed the third issue with Klaudiusz to review possible solutions, but since it requires a collective decision to proceed, I turned it into a separate GitHub issue so that we can review and discuss it in group later next week: [Reapproaching the challenge of multiple simultaneous blockchain transactions for comments and reactions #2541](https://github.com/Joystream/atlas/issues/2541).
