### ISSUE TITLE
Creator Tokens — Owner & Issuer: Research & Discovery

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2406]
This phase can include activities such as debriefing, desk research, competitor analysis, booking and conducting discovery in-depth interviews, or performing moderated usability tests on existing competitors' products.

The expected outcome is a brief report on key findings & conclusions, a link to Figma moodboards, screenshots from the competitor analysis, etc.

**Comment by KubaMikolajczyk** [comment]
# Context
During the research phase, I walked through the resources included in the brief. 

# Key findings
1️⃣ The creator token feature is used by a few products only and as a concept is not yet being used by the mainstream audiences
2️⃣ The creator token (which is called a social token in many places) is here to allow communities to have better alignment with the brand both emotional and financial.
3️⃣  There is a smart contract AMM which gives liquidity to those creator tokens and creator tokens have their own bonding curve which calculates their price based on the current total supply by using some kind of predefined function

🛑I was unable to reach the part of the experience where I would be able to create my own coin because they were either hidden behind some type of form which I have to submit and wait for acceptance or I have to own their tokens to apply for this feature.

🟢With that said the process continues and we design the best possible experiences based on our common knowledge of the topic & available resources. Below are some thoughts which I gathered after going through resources and doing some of desk research.

# Similar platforms

# 1️⃣  Rally
 https://rally.io/
![image](https://user-images.githubusercontent.com/31144205/163141201-7cfb13db-55ad-46a7-adb7-d0135bf18856.png)
https://twitter.com/rally_io
They call themselves a go-to platform for Creators & Communities for building social token economies & NFT's. They even surface different coins and economies on their website in discover coins tab: 
![image](https://user-images.githubusercontent.com/31144205/163188258-7ab9c38d-b9f8-4bb0-ab7c-fb43e8a5946c.png)
You can inspect each individual coin and see the utility that this particular creator provides. This is definitely worth revisiting when we will be working on viewers side of social tokens. The token creation is hidden behind a form and you have to be accepted to create your coin.
![image](https://user-images.githubusercontent.com/31144205/163195422-df3e0478-f8e1-4694-b815-466bb4d01f17.png)


# 2️⃣ Roll
  https://tryroll.com/
![image](https://user-images.githubusercontent.com/31144205/163141357-0cea2f1f-5931-49aa-a0cf-d71e0fd08d7c.png)
They call themselves : social token infrastructure for the internet. Unfortunatelly token creating experience is hidden behind a typeform - so you have to submit your community first and then they will consider your application and either let you in ore reject your application - which makes it impossible to test.



# 3️⃣ Deso

  https://www.deso.org/
![image](https://user-images.githubusercontent.com/31144205/163142123-f5fffcb0-418a-4b76-a17d-9e8238890e17.png)
They call it the decentralized social network they allow apps to create social feature which are scallable - I managed to reach their documentation where their social tokens feature is described. 
The creation of social token on their platform is automated and not managed by submitting the form - user has to buy $DESO and then buy an asset called "creator coin"
![image](https://user-images.githubusercontent.com/31144205/163210653-b9e38309-18d0-47de-bb4f-8a1b78ce9938.png)

They state that everyone can buy their tokens - it looks like there is no coin whitelisting pattern used here.
There is a list of all coins and users can buy any token on the platform
![image](https://user-images.githubusercontent.com/31144205/163210994-bd5912c7-adb4-49ba-acd7-f583bd05b069.png)

### Utilities that can be connected with holding the coin brought by their social features: 
1. Creator can restrict that only holders of some amount of $CRT can comment on this creators posts
2. Private DMs restricted only for some amount $CRT holders or just prioritize the messages based on holding amount
3. You can send the creator a post that you want him/her to repost - and everyone can bid those posts with $CRT coin and if the creator repost it they can keep the money
4. Premium content for holders
5. Distribute scarce resources for holders with highest holding amount - eg. 1000 posters for 1000 highest $CRT holders
6. Likes that you can buy with coins

### Their bonding curve is also visible to all
It shows the relation between the amount of creator coins in circulation vs coin price. And how the price of creator coin changes when the supply changes.
![image](https://user-images.githubusercontent.com/31144205/163212939-fc9f30cb-dd69-48a6-b4a5-c59f40e88d93.png)
Below the function for the bonding curve}
![image](https://user-images.githubusercontent.com/31144205/163213268-e41ccb15-2a4d-49bc-99ba-36ea20b4159f.png)

### Founder rewards
Is a system similar to our revenue split - but it applies strictly to % of revenue from purchases of this particular $CRT coin. In our case the whole system is a bit larger and there are many possible revenue streams.

  
 # Inspiration
1️⃣  https://twitter.com/trends_vc/status/1401947070462763012 
![image](https://user-images.githubusercontent.com/31144205/163142360-2b215e6f-10f4-45cd-bab7-dedf08f6b026.png)

Creator tokens are called social tokens here - which allows the community to have more alignment with the brand both emotional and financial. 

It discusses the opportunities of providing utilities to those coins wit examples
![image](https://user-images.githubusercontent.com/31144205/163216636-e7d2ba34-86b6-4221-b8b7-b3c694d65255.png)

How it can be earned in different ways
![image](https://user-images.githubusercontent.com/31144205/163216747-debd2cdf-5adb-4446-ad57-0f64c6501ac3.png)




# Understanding bonding curves
1️⃣  https://www.youtube.com/watch?v=bBpa9395b4Q
What are Bonding curves?
![image](https://user-images.githubusercontent.com/31144205/163143354-0a8dd370-64f4-4bf4-924f-76781447b21b.png)
> Bonding Curves are a generalization of the pricing formula (a curve) and associated liquidity pool reserve design found in Automated market makers (AMMs). Implemented as smart contracts, they bring transparency in pricing and manage on-chain liquidity. 
> 
> AMMs swap two or more tokenized assets. In a bonding curve, the protocol increases the token supply or reduces it algorithmically based on market demand. These algorithmic agents automatically provide liquidity in Blockchain-based decentralized exchanges (DEX) and other electronic markets by replacing the concept of an order book with a deterministic pricing formula. 
> 
> The design keeps liquidity on-chain and offers transparent price mechanisms. Hence Bonding Curves and AMMs are a significant step toward building a more transparent and efficient financial market.


2️⃣  https://www.youtube.com/watch?v=14hH0dKktvc
![image](https://user-images.githubusercontent.com/31144205/163143645-4a511dbe-0ce6-4c4e-bc5e-b7ef6a933145.png)
Token Bonding curves (TBC)
- Token prices with changing token supply
- When supply changes the token prices changes
- So the more tokens there is in your ecosystem the more the price rises
- Value of your token grows because your network grows

3️⃣  https://www.youtube.com/watch?v=ZUJSslXdEz0
![image](https://user-images.githubusercontent.com/31144205/163182999-e52ec70e-fd17-40e3-9491-bf83feebd37f.png)
AMM - provide liquidity and allows for automatic exchanges. Prices are dynamic and it changes when supply changes.You can buy and sell at anytime.
