### ISSUE TITLE
Creator Tokens — Owner & Issuer: Exploration & Low Fidelity Mockups (LoFi)

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2407]
This phase can include activities such as sketching, prototyping, and discussing potential solutions internally, preparing for conducting usability tests (work tracked in a separate issue).

The expected outcome is a video walkthrough of happy paths for all user stories mentioned in the epic, along with links to Figma designs and prototypes.

**Comment by dmtrjsg** [comment]
Comments from the latest review:

### Create Token
1. Step 1: Drop custom image, only channel avatar is supported. 
> Token video trailer served via metaprotocol
2. If no vesting, disable First Payout (renamed from Initial Tranche ☠️ )  (No vesting applies means- don't have to wait; if no cliff - you get it all).
First Payment: define as % from total issuance 
3. Step 2: . If total allocation is 0, disable other inputs
4. Step 2: Default vesting and cliff settings> Research ERC20 examples and define best values for pre-populating.
5. Step 3: no comments

### Dashboard
**Your allocation:**
1. Remove next token unlock as the process is more fluid and defined by multiple overlapping vesting schedules. (dm comment: I now think would be great to have them all presented on a chart, but we first need to iron out the basics in scope of this task)
2. Show: Total; locked to vesting; lock to revenue split; (data is only for your (member) account only for this one token).

**Dashboard widgets:**
Standardise: Blue cta to start vs view more as tertiary link on the active state widget
Info architecture from most relevant based on state of the process (active/ not active): Multiple rows are better than 5 data points in a single level.

**Sale Tab**
End dates need to be made more prominent -> turn up
Sale progress -> tune down the bar and make labels standout more.

## Sale
Price per token  as input, Total funds to be raised as prompt
Instead of token show total funds  to be raised(on the left hand side preview widget)
For locked sale display purchase limit per member

**AMM** 
AMM variation will have 2 steps in the process flow.
Step 2 on cliff and vesting, needs to be confirmed if ❓ First Payout also applies there. one for @bedeho to come back with  
First Payment: define as % from total issuance in both cases.

Token Holders: Locked due to vesting; locked due to split; transferable balances

**Revenue split:**
Remove token holders
Add widgets in accord with overall module design
Enhance current state vs history

**History of Transactions**
- Can accommodate all transactions from all other tabs

**Comment by KubaMikolajczyk** [comment]
Thank you for taking notes from the meeting ♥️
All of the above is turned into action points already and I'm working on them.

Additionally below you can find a link to a 3min video update about the last 2 screens that we didn't have time to talk about yesterday: https://www.loom.com/share/f050f7d58f1141d4a52bf2ee4fb85de5

If you guys will have some time to give me some feedback for them as well would be lovely 🙌

**Comment by bedeho** [comment]
# Note on tables

I think this looks very reasonable, but the semi arbitrary position of the `TO`  and `MEMBER`columns  made me wonder: are we totally wedded to have all tables have a a same universal width? This is what is causing the awkward blanks space and readbility across long rows issue. If we just allow different tables to have different widths, this all goes away.

**What is the problem with that approach?**

# Adding to whitelist

We should def. allow adding more than one person in a practical way.

# Edit token type

This should just have the explicit label `Remove whitelist`.

**Comment by dmtrjsg** [comment]
## Search for Member

I'd say we should not hide it inside filters, but bring next to filters triggering CTA. 

## Tables 
>What is the problem with that approach?
Not against putting a quick version to compare with full width.

__
➕ support comments on whitelist and token type

**Comment by KubaMikolajczyk** [comment]
# Overview
After our last round of feedback, I iterated on existing & added new screens presenting ideas for creator tokens owner experience. Below I attach a link to the design files along with a quick video walkthrough. 

@bedeho we did an internal walkthrough today and feedback from this session is already included here - If you can watch the update and leave any additional comments/questions in Figma file - then we will be able to quickly iterate on those and/or discuss them during the tomorrows meeting.

Video walkthrough (11mins) : https://www.loom.com/share/68b6d4738242461bb8855266b79e171a
Design files: https://www.figma.com/file/VzPBMpUnGjGOHMSW2ZHbGY/Creator-tokens-(Copy)?node-id=1023%3A36892

**Comment by KubaMikolajczyk** [comment]
As we are moving towards exploring the next part of creator tokens this issue can be closed.
The last round of exploration of Figma design files can be found here: https://www.figma.com/file/VzPBMpUnGjGOHMSW2ZHbGY/Creator-tokens-(Copy)?node-id=1023%3A36892

**Comment by toiletgranny** [comment]
Rough note re next steps for this week (mid-fi):
- Updating mockups with the AMM functionality and all its implications,
- Token editing flow updated with things such as token description, terms & conditions, "thank you" message, and more,
- Preparing usability testing prototypes.

**Comment by KubaMikolajczyk** [comment]
Mid-fi Mockups are done and all are described in the video below (29 min - watch in x1.5).
🎥 Loom: https://www.loom.com/share/fc0296f86db6477a96b4dbbd67a9865e
📄 Files: https://www.figma.com/file/VzPBMpUnGjGOHMSW2ZHbGY/Creator-tokens?node-id=1861%3A161242
🪙 Coin codepen: https://codepen.io/ontokuba/pen/wvyObmj

**Comment by bedeho** [comment]
# Feedback

- I love the rich preview, they look so attractive. Should we add some sort of one liner header or something inside the panel which says where this visual will be seen? Because remember, the first time people enter this flow they may not know the app well enough, or at all, to recognize what that is.
- Is it not a problem that we have divorced the publishing of the token page from the issuance step? I predict many people will try issuing, and never discover the token page, or feel an imperative to do it well, unless we really make it a non-optional part of the issuing flow. As I said before, in the beginning, there will be a lot of experimentation and low-commitment usage, so unless we really encourage people to do the right thing, we may end up with a negative spiral of poorly constructed creator tokens. I really think we should make the token page as part of the issuance, and really _require_ the person to set it up. It also avoids _forcing_ the creator to in fact have an empty token page involuntarily, even for a short period of time, when they are trying to make a issuing the token somewhat of an announcemnt or event (not a big deal though). What do you think?
- I would make the same point about launching a sale, and in particular an AMM, as the past point. Should this just be left idle? I think we should urge them to make confront this, and then just make a decision to skip. There is so much info on the creator page that I worry this will be overlooked.
- I think communication around the two forms of sale should focus on what problems they solve for the creator, not dwelling on the multitude of things that are _not going to happen_. If its not clear what the distinction is, perhaps we should have a call. The main point is that 
  - AMMs are meant to be a continuous and easy way for people to get exposure to your asset, and for you to get liquidity whenever sufficient maturity in the market develops, but you don't know when that would be, or how deep it would be. The natural point in time to launch this is when you first launch the token, or after a public sale, and just leave it running. I don't see a compelling reason for turning it off ever, except to do a one off sale, or if something goes wrong in your community.
  - Public sales are meant for you to raise some relatively specific amount of funds as a creator over a short period of time, and provide exposure to a pre-existing audience who you know are relatively interested and able to participate. Importantly, as this is an event over a limited period of time, you are going to have to likely do marketing and coordination around getting people to learn about and participating in the sale. It will likely be a big effort on your part, and its something you could really only do after having done substantial planning, communications and execution. You will have to develop some conviction that you can basically convert some portion of your audience, which likely knows nothing about Joystream, to go through a substantial number of steps within a given period of time, for it to be successful. I expect these events to occur one or more magnitude less frequently than AMMs.

  So as you can see, these are very very different types of activities, one being way way lower barrier to entry and success. I think our product probably should take this difference more seriosuly, and perhaps ask people what their next objective is: liquidity or raise funds, etc., and perhaps try to nudge them down the most plausible path.
- Vesting graphs:
  - It would be great to somehow directly show the different quantities defining the unlocking terms directly on the graph, so you more directly see how they map on. Perhaps color coding can make it more clear? 
  - Try using a more realistic schedule (rectified & linear), not this smooth one, to validate the visual representation. Check my prior graph to see what I mean.
  - You are using non-linear scale on the time axis (7D has same size as 1M), this does not really work, or it is misleading. I suggest adding a graph break or something.
- I think the emojipicker should be conditional on some default implementation existing which is good enough, rebuilding that all from scratch seems very expensive for this stage.
- Remember that patronage _can only be reduced_.
- Rotating coin: remember, this may look bad because icon may be small, it will look horrible.

**Comment by KubaMikolajczyk** [comment]
> I love the rich preview, they look so attractive. Should we add some sort of one liner header or something inside the panel which says where this visual will be seen? Because remember, the first time people enter this flow they may not know the app well enough, or at all, to recognize what that is.

We can add some more explanation when the workspace is open.

> Is it not a problem that we have divorced the publishing of the token page from the issuance step? I predict many people will try issuing, and never discover the token page, or feel an imperative to do it well, unless we really make it a non-optional part of the issuing flow. As I said before, in the beginning, there will be a lot of experimentation and low-commitment usage, so unless we really encourage people to do the right thing, we may end up with a negative spiral of poorly constructed creator tokens. I really think we should make the token page as part of the issuance, and really require the person to set it up. It also avoids forcing the creator to in fact have an empty token page involuntarily, even for a short period of time, when they are trying to make a issuing the token somewhat of an announcemnt or event (not a big deal though). What do you think?

The idea of making it a separate flow from the token creation is not accidental. First of all if we require users to specify all of those descriptions, and videos at the very beginning when they only start creating their token we risk a lower % of tokens being created at all - by making them separate we lower the complexity of starting your own CRT. To address the possible issue with the discoverability of your token page I added an additional onboarding experience (which we can still improve) and it's worth mentioning that an action to edit the token page is one of two main actions on this page. I feel that it should be enough to inform user about importance of this element - but I will include this in my tests for sure.

> I would make the same point about launching a sale, and in particular an AMM, as the past point. Should this just be left idle? I think we should urge them to make confront this, and then just make a decision to skip. There is so much info on the creator page that I worry this will be overlooked.

I wouldn't try to force user to do everything at once - create, marketing and sale at the same time - This will make the whole flow gigantic and really heavy to digest. Once again I propose to really focus on mastering the art of introducing user to the features of the creator token and giving a free will - if they want to think more about their token page intro, video, description they can take their time - and the same about the sale - they do not have to put it on sale immediately - they can do it at their own pace. Once again I would test that - how users understand possible actions after creating a CRT and what they would do next.

> I think communication around the two forms of sale should focus on what problems they solve for the creator, not dwelling on the multitude of things that are not going to happen. If its not clear what the distinction is, perhaps we should have a call. 

I understand the difference here - the challenge is to show people options but at the same time do not mislead them - if on other products that they were using before, the concept of AMM, allowed them to earn (not only build liquidity) and in our case the outcome is different I would opt for communicating those clearly. It would be nice if we could hop on a call one day to discuss it :) 

I agree with the rest of the comments :) Action points noted. 

One last question about channel avatars though - couldn't we require the minimum size of those to solve the issue of those being too small? 

Thank you for the feedback 🙇

**Comment by bedeho** [comment]
> One last question about channel avatars though - couldn't we require the minimum size of those to solve the issue of those being too small?

In Atlas we could, that would require some extra work, but it would not prevent other apps from circumventing this, but I am not sure how much we should care about this now.

**Comment by KubaMikolajczyk** [comment]
First Hifi exploration / After first tests is ready ✅ the biggest update so far 🤯 (56 min recommended x1.5 speed). Hidden questions at the end 🫣
🎥 Loom: https://www.loom.com/share/5cc594963b8c49f8b9d345ee01890298
📄 Figma file: https://www.figma.com/file/VzPBMpUnGjGOHMSW2ZHbGY/Creator-tokens?node-id=3056%3A267127

**Comment by dmtrjsg** [comment]
Nice work buddy! Excited to see the iteration feedback 🙌 

My first impression:

## Default dash:
1. Start token sale is in the top right area, I would opt in for the version which has a dedicated widget on the dashboard, with empty values and a big CTA > create your token so user sees that one first:
<img width="161" alt="Screenshot 2022-10-02 at 13 52 16" src="https://user-images.githubusercontent.com/93924525/193448264-6473edeb-414b-4660-bd66-9c4a9aab0007.png">

I would put only the title, Channel Token like we  [with Payouts?](https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments-page?node-id=1552%3A25987), 

Just move the create token button inside the widget, like we did with Sale. Verify Token and View Token Page can be also placed in the widget? Maybe I'm asking too much 😇  but worth exploring imho.

2. Top level widgets - good idea to show different balances, but prob we could 

#### Option 2

Love the addon 😍, let's not offer the option of closing it :)  Dopamine rush 😆 buddy, this is amazing!

I think they can be combined.. But an individual widget for the token name as mentioned in the beginning of this comment, would serve better imho compared to all actions we do with the token spread out in header and tab-level. 

## Creat token flow:

### Copy edits
1. Step 1 
- For revenue split: "your holders to earn-> your token holders to earn"
- For Patronage: "Recommended value is up to 10%."
2. Step 2 
- Your starting holders.. Copy change "Decide on the initial amount of tokens to be minted for your channel. Add vesting period and cliff to your token, as this restricts token price manipulation and makes it more attractive for your buyers." 
- First payout "This is the amount of tokens that become transferable and can be sold right after the cliff period ends."
- Cliff: Default is 3 months.

### After Token created 
1. There's an ava of the token in the conf modal, which we probably need to remove, as this isn't customisable.
2. Verify token and view token page -> I would honestly overall explore the option of adding a full widget with the Token to the dahboard and place these buttons inside the widget, like you did with Sale.

### Token Page Setup

1. nice work! Fully agreed, maybe "Preview" CTA can benefit from being a bit more prominent, but let's test and see if they will discover it easily..
2. We only allow for the video, maybe worth adding an option with just an image upload? So user could do both, a video or an image upload rendered in the same place on the viewer side?


## Sale

### Start Sale
1. Do we need 2 CTAs on the same page? One in the widget and one next to the tabs?  I feel like this place for CTAs is not very effective altogether for me personally. 

### Choose Sale Type

Table is more effective, we just need to think about more points of comparison. IMportant ⚠️ Creators DO NOT earn from AMM sale vs Creators earn from Creator Sale.

### Create flow 

1. Copy: Nice adaptations of copy, look forward to testing insights, but lgtm!
2. Is it worth adding this to the sale widget, as people may miss this important info. Thinking a "share" button may help as creators will be doing their own marketing on this..
<img width="236" alt="Screenshot 2022-10-02 at 16 25 59" src="https://user-images.githubusercontent.com/93924525/193453857-b4d6dc5d-e59f-4408-b310-c0fd0e35e533.png">

## Active sale

1. Not sure about the placement of the "end sale" button. Best to have sale status widget and start/ end in the same place, presumably from the widget itself.
2.  This table headers need to be updated imho.. Start date/ Sale type/ Purchasing account (⚠️ membership not always known) / Exchange Rate / Total Sold (in CRT currency)
<img width="376" alt="Screenshot 2022-10-02 at 16 30 27" src="https://user-images.githubusercontent.com/93924525/193454034-4ee45878-01fe-402f-ae97-e7123fccdc82.png">


## ❓ Questions

1. Q:Is first payout dependant on cliff?
- A: First payout is independent from cliff, it depends on vesting schedule. If vesting is 0 days, then first payout is always 100%. You can have 100% after cliff if you want.
2. Q: if during active AMM creator ends it, will the buyers will be "stuck" with tokens without ability to sell them untill AMM is enabled again only by creator?  
A: I think so, and this would depend on creator. Joystream as platform cannot reasonably control this, so I don' think limitations are required. 

 @bedeho is best to answer the last question.

**Comment by bedeho** [comment]
> if during active AMM creator ends it, will the buyers will be "stuck" with tokens without ability to sell them untill AMM is enabled again only by creator?

From what I recall, and I think this may still be tweaked, closing an AMM requires emptying it first, so it means the creator has to sell enough $CRT into it to deplete it of any $JOY locked up, but even doing so does not mean other people are not holding $CRT, in which case _yes_ would be the answer to your question.

**Comment by bedeho** [comment]
# Feedback

Phenomenal work, really great that you are doing this user testing - as this stuff is super complicated. I would encourage you to make your update smaller next time, say <20mins, hopefully it should be possible to work on smaller parts and get feedback earlier, as this also reduces time between reviews, so there is less lost context for us reviewers.

1. I don't understand why the first alternative version of the dashboard, without a token launched, was made into a gigantic empty state rather than just focusing on the single available action? From first-principles this seems universally worse than before: much more for us to do to build the product and highly disorienting to the user, so what was the reasoning?
2. I think the second variation with the overall progress is an interesting variation, it does solve the fundamental point that this whole area is quite complex, and you are easily lost in what you are "supposed" to do. Tutorial getting hooked in also seems like a great move . I think the same problem as before remains in the initial empty stage, but that is not a fundamental point. The biggest obstacle I see here is that specifically getting verified is an activity the DAO is involved in, not the app. This means we will need to add some sort of new blockchain level metadata for the DAO to signal things like
   - how long verification may take currently
   - who can get verified
   - what it will involve, what will you have to do?
It may just be that we need to add this stuff. As I review this I am wondering whether we actually even have such a thing as token verification as distinct from token verification, it does not make a great deal of sense to me to have both, or to have only token verification. If we decide we really just need channel verification, then perhaps this whole granular verification business I am describing needs to be lifted out of the CRT page specifically, and this `Your progress` stepper should just hide this step if you are already verified.
3. Seems like it would be a good idea to find a more compact way of hiding progress cards when they are done, rather than taking so much primary space like now. Perhaps just starting with the first incomplete card is sufficient?
4. Really nice revamping of composer experience for token page, this seems more direct and transparent.
5. Perhaps we need to find better names to distinguish these two, `Creator sale` and `AMM` are really obscure. The main distinction from the user point of view is that one is limited for a specific period of time, and one is ongoing with no defined end. Naming I think should clue into this.
6. I am skeptical of the sale type comparison table, it looks really neat, but I think it is premised on a mistake of presenting features rather than _benefits_. Right now, features are being described, and they largely are going to not be understood at all by anyone. What is an "automatic market maker", 0 people will know. Another tell-tale sign of a problem is that there is no overlap in the checkmarks - which there always are in this form of presentation, so we are not really trying to describe features here, because there are actually lots of overlapping features if we just to capture them. I think _benefits_ to the users+creator is the way to go, and these will largely not overlap. So I would say for  `Creator sale` that the benefits are (these are meant to be descriptions, copy can be fixed)
    - Urgency: you get everyone focused on getting into one big event, this helps possibly get greater participation and excitement.
    - Revenue: you actually make proceeds directly as a creator.
  and for  `AMM` I would say benefits are
   - easy & low risk: you don't need to figure out what how to price your token or how much to raise, how to market, you just set it and forget. you can come back mcuh later and improve marketing or information if you want.
   - liquidity: you, and everyone else, can buy and sell at any time (almost).


# Your two questions

 Already answered.

**Comment by KubaMikolajczyk** [comment]
Thank you for all your great feedback guys 🙇

@dmtrjsg I totally agree with copy changes, changing action in the snack bar to share, and the rest of your insights - I will implement them before the tests 👍 

However, I'm unsure about what are the issues this separated token widget might address.? - current placement of CTA buttons was confirmed multiple times as effective in tests & token verification action being probably taken away from this page as Bedeho mentioned in his feedback - this widget would likely only consist of token name & show token page action and some of the stats if we decide to cramp it there. Additionally, with this prominent onboarding section, it won't even be the first thing that the user sees when opening this dashboard and it's probably fine as it won't be the most crucial part that the user should focus on. I had to express my thoughts as I already explored the idea of having one token info widget and it didn't work.

@bedeho Yes, I will try to make it shorter next time 🙇
1. This was the experience that we agreed to explore after the last feedbacking session with Dmitry. To not impose the whole "dashboard" onto users without giving them a way to explore it earlier. But I see your point and I agree that we might not have achieved the goal here and just one action at the start would be enough.
2. I agree - we probably need a universal creator verification process which might not even be a part of the CRT experience. I will remove it from the dashboard but at the same time, I will create a ticket that will encapsulate this on the channel level :)
3. 👍
4. 🙇
5. I would argue that the biggest difference is the fact that one earns you money while the other don't - the time element seems to be not as important. 
6. So you wouldn't go with comparison here but rather present it as two separate elements with their own benefits?

**Comment by bedeho** [comment]
> I agree - we probably need a universal creator verification process which might not even be a part of the CRT experience. I will remove it from the dashboard but at the same time, I will create a ticket that will encapsulate this on the channel level :)

Ok, great!

I think we need to start by actually defining a human process: how should verification actually work in a way that serves the intended goal of verification as a concept, while thinking about real-world constraints around preventing abuse, manpower, etc. Then the product design becomes the second-order exercise. Do you want me to proposer this process, or can you do it yourself? Either way, I would want to ask the current content curators to weigh in, as they also will think of problems we may not have thought of, or what new tooling they need to develop to manage this whole process.

Btw. are we saying anyone who does youtube synch should be considered "verified" ? that seems like a mistake to me, because then someone can just create a channel on YT, synch in, get automatically verified, stop the synch, then change the branding of the channel as it is some other person/entity.

Now how do we deal with the timing of this? are we bundling this verification stuff with CRTs? Does it come earlier?

@dmtrjsg 

> So you wouldn't go with comparison here but rather present it as two separate elements with their own benefits?

A comparison in terms of features I think is not working very well, I'm saying the comparison should be really be in terms of what the unique _benefits_ are.

**Comment by dmtrjsg** [comment]
@bedeho 

The empty state and widgetising each step stems from the originally combined flow asking the user to specify everything at once. My original view was to have a visual layout similar to Payments Dashboard, with a clear starting points for the journey. 

You argument on the potentially overwhelming view of empty states is valid, and I now thinking of it again it does not look like a bad idea to serve the dashboard after the token is created. I guess we can combine this with showing the progress stepper on the page load, with a single entry point to create the token, and not show the rest of the dashboard before step 1 is completed.

Thanks for the rest of the comments, agreed. And specifically on the AMM vs Creator Sale, It is always good to focus on the final outcomes so thank you for articulating these, v helpful. In terms of presentation it would be nice to present it in the way where the differences and benefits are comparable so the choice between the two can be made. 

@KubaMikolajczyk cc

**Comment by dmtrjsg** [comment]
>Now how do we deal with the timing of this? are we bundling this verification stuff with CRTs? Does it come earlier?

I'll tee this up in terms of risks, process and considerations, added to backlog of tasks.
