### ISSUE TITLE
Creator Tokens — Owner & Issuer: Testing

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2408]
This phase can include activities such as conducting moderated/unmoderated usability tests on prototypes from the LoFi phase, doing surveys, or other types of user research.

The expected outcome is a brief summary of key findings, a list of recommendations, and a list of test participants to be paid out (if applicable). Learn more from [Approaching testing in Atlas](https://grizzled-corleggy-af8.notion.site/Approaching-testing-in-Atlas-115a1c0480144c8682dc9b63c99473c4) Notion article (WIP).

Depending on the results, the next step is either proceeding to the next phase of the design process or going back to the LoFi phase and repeating the tests if needed.

**Comment by KubaMikolajczyk** [comment]
# CRT Owner & Issuer usability tests
### Overview
We conducted 4 usability tests for the CRT Owner & Issuer experience. We hoped to gain a deeper understanding of potential user pain points and preferences.

![image](https://user-images.githubusercontent.com/31144205/189899770-26bc6b60-9121-46fa-9f99-757d75d45ada.png)

👥 4 participants
# Joystream members to be paid (Bitcoin Cash | BCH) 👈 @bwhm 
169m3YZbHxhVAdEyezKAJbCSJhkbqpSRoG
qps3vyk0c6yp6n89m8wgapfuzu69q4mf8y4anw8ccj
1AQfaHjLwsecN3h5BmVirgbmHAq4i9XL57
1LmCsxabAkYiHjJg1CQzmAjyP2ne8CSVCS

# What do we want to know?
1. Are there any potential issues with Creating CRT experience?
2. What is the next action that user wants to take right after creating their CRT?
3. Are the token dashboard widgets understandable?
4. Do they understand how to perform edit token page & sell actions?
5. Is "Edit token page" understandable? Is this layout working?
6. Do they understand the difference between Public sale & AMM?
7. Do they understand how to start a public sale? And all concepts here?
8. Do they understand how to start an AMM? And all concepts here?

# Research outcome 

#### 1️⃣ Are there any potential issues with Creating CRT experience?
![image](https://user-images.githubusercontent.com/31144205/189899846-6b794c04-9be4-4571-ba8e-f7cef21437f9.png)
- Token ticker - 3/4 users didn't know what ticker means but they guessed that its the name. I would add a description that it is token name / or change the label to token name to get rid of confusion
- Main description of first step is misleading needs to be rewriten
- Token type & revenue split were easy to understand for all users
- Patronage - 4/4 users didn't understand patronage concept - it needs to be rewritten and rethinked the way that we present it

![image](https://user-images.githubusercontent.com/31144205/189900711-1f9e0afb-f23b-4849-815c-a263ec3e582f.png)
- All of the users were confused with this page - none of them could properly guess if this applies to them or those apply to buyers, sometimes they guessed that part of the fields apply to them while the others apply to buyers
- Some users lacked option to have no vesting and cliff easily accessible to them
- Most of them 3/4 - would appreciate some kind of video explainer walking them through those concepts
- Graph is not easily understandable needs to be reworked
- Allocation (as a term) is not easily understandable & in connection with confusion about to whom those fields apply - 2/4 users didn't know are those tokens for them or are those all token that users can buy (a lot of confusion)

![image](https://user-images.githubusercontent.com/31144205/189901682-e2449e4f-1b5c-4e6e-adf7-02ef382aeb5a.png)
This page has the least issues and explained a lot of concepts that were misunderstood earlier
- Users expressed the need to have dollar conversions in summary

#### 2️⃣ What is the next action that user wants to take right after creating their CRT?
![image](https://user-images.githubusercontent.com/31144205/189899770-26bc6b60-9121-46fa-9f99-757d75d45ada.png)
- 2/4 users would start editing the token page first to prepare their token for the launch and 2/4 users would start a sale immediately with a small part of the tokens that they own.

#### 3️⃣ Are the token dashboard widgets understandable?
- Users were expressing happiness over the fact that they can control much more about their tokens but 1 user also expressed that he is a bit overwhelmed by the fact that there is still much to do 
- Users are scanning dashboard in a Z pattern starting from the sale widget
- Revenue split widget in its current form is confusing for all users, all of them expressed that they are not quite sure what it is about
- Rest of the widgets were pretty clear to them

#### 4️⃣ Do they understand how to perform edit token page & sell actions?
Yes✅ All of them understand how to perform both actions and properly describes what will happen after they interact with the buttons. Short onboarding introduces them nicely to those functions (even if 1/4 user suggested he would probably skip it)

#### 5️⃣ Is "Edit token page" understandable? Is this layout working?
![image](https://user-images.githubusercontent.com/31144205/189908558-492b4192-d3aa-4ff4-bae8-29be83865cdb.png)
No 🔴
- Its really confusing for users why page is splitted in half and 3/4 didn't recognize that the section on the left is a preview of the inputs on the right
- Most users thought that area on the left is explaining how to use this page and considered it a waste
- Users really liked the idea of intro video but there was a comment: "Oh, so now I would have to pause and record a proper video for it because I don't have an intro for sure"
This page has to be reworked - more about that later in suggestions.

#### 6️⃣ Do they understand the difference between Public sale & AMM?
![image](https://user-images.githubusercontent.com/31144205/189909798-412f95d2-da9e-4218-9503-7935f7b13c28.png)
No 🔴
- Even though there are points below each type some users didn't even read those and based their understanding on the title and pill
- Most users were still convinced even after reading them
- 1 user knew what AMM is so he didn't have any problems, 1 user identified it correctly but only after selecting it and reading more about it on its page, while 2 other users didn't understand the concept even after reading the page of AMM
- All users wanted to go with public sale because AMM looked advanced for them 
- Most users wanted more explanation at this stage and stated that it would be best in video format of someone explaining those concepts

#### 7️⃣ Do they understand how to start a public sale? And all concepts here?
![image](https://user-images.githubusercontent.com/31144205/189910649-c0e1409f-5e03-4e15-ae33-14c9166311e7.png)
- When users started public sale all of them knew how to complete the sale
- All of them understood "tokens for sale" and "price for single token" but had problems with understanding "value of this round" and "marketcap" instantly. It clicked for most of them after a while.
- Users wanted to choose either default or custom T&C and then edit if they choose custom

![image](https://user-images.githubusercontent.com/31144205/189911213-42d67f36-bdcd-44f1-acab-b77b384f1d42.png)
🔴 All of the users were confused about this screen
- One user thought he is editing something that he already set
- Some users still couldn't say who this applies (Cliff/vesting) this time around
- 1 user wanted to have an option to disable cliff and vesting

![image](https://user-images.githubusercontent.com/31144205/189911635-849f03a2-067d-41ec-ac5e-4baf3875f87d.png)
Summary was understood and provided some help for users.

![image](https://user-images.githubusercontent.com/31144205/189911790-b79da21a-5093-4336-92a9-8e348c4c01fa.png)
- All users recognised that their sale started 
- 1 user wanted this information to be more prominent
- All users expected the page to update in REAL TIME with their sales 

#### 8️⃣ Do they understand how to start an AMM? And all concepts here?
![image](https://user-images.githubusercontent.com/31144205/189912316-453beed1-1c09-4424-90e1-3460bceee202.png)
- When users started public sale all of them knew how to complete the sale
- Users wanted to choose either default or custom T&C and then edit if they choose custom
- Users wanted to have more explanation up top above the input and the link to be more prominent to learn more - ideally even an explainer video about it
- Almost all users 3/4 didn't understand or really struggled to understand the concept of AMM even being on this page

----- Rest of AMM flow was the same as in Public sale - same comments and findings :)

# Suggestions & ideas

1️⃣ A lot of the copy has to be rewritten to make it easier for users to get an idea of complex concepts (especially page descriptions, Patronage, AMM)

2️⃣  We need to make it super clear that first vesting & cliff apply to creator and the second one during the sale creation apply to the buyers as none of the users seems to understand that.

3️⃣ We need to add option to have no vesting & cliff easily to not make it look like we force them to do this and really think about what we recommend as default (maybe even make some presets)

4️⃣  The whole experience of editing the token page needs to be changed - its not working at all. It needs to be explored again and come up with a solution that will be easy to understand and which would not create a feeling that they are obliged to do a looot of work before launching their sale. (Maybe we could have a preview of their empty token page and a wsiwyg experience of editing / adding more content on it there - don't know for now but we have to approach it differently)

5️⃣ Video explainers were suggested to me repeatedly throughout multiple sessions - maybe it would be worth exploring a concept where we have some small video explainers walking our users through the whole experience. If not definitely at least one video showing the whole process being available for them to get help as they can get lost really easily in those complex concepts.

6️⃣ Some words were to complex for users - and it was proposed for me few times that we could change some wording to be more beginner friendly instead of being so tech savvy like: token ticker - could be token name, allocation could be "Amount of token you will receive" those are only examples and maybe not even good ones but its at least a suggestion I'm raising that we should be more careful here :) 

# Conclusion
I think it was the first session where I could spot so many important pain points in the designs and while we will have to take time to rework some things - I think it was super valuable to have those findings right now. Please tell me your thoughts below and thank you for reading 🙇

**Comment by dmtrjsg** [comment]
# Research Outcome Comments

## 1️⃣ Issues with Creating CRT exp

>- Token ticker - 3/4 users didn't know what ticker means but they guessed that its the name. I would add a description that it is token name / or change the label to token name to get rid of confusion 

 ✅go for it   

>- Main description of first step is misleading needs to be rewriten 

✅Yes, needs to be a small para about setting up the basic  attributes of token  

>- Token type & revenue split were easy to understand for all users 

❓  is it not because we did not have a tooltip?  

>- Patronage - 4/4 users didn't understand patronage concept - it needs to be rewritten and rethinked the way that we present it 

✅ yes perhaps we could just go with "Stable reward to the creator for managing the tokens supply. And then go with recommendations.

__

>- All of the users were confused with this page - none of them could properly guess if this applies to them or those apply to buyers, sometimes they guessed that part of the fields apply to them while the others apply to buyers 

❓ General header to explain that this page relates to the creator own part of tokens mgt, and settings for token purchasers will be configured in other part?  

>- Some users lacked option to have no vesting and cliff easily accessible to them 

 ✅ add this to the drop down? What do you mean by easily?

>- Most of them 3/4 - would appreciate some kind of video explainer walking them through those concepts 

❓  I think an overall one can be done on first page load, and the rest of the info can be packed to the tooltips?

>- Graph is not easily understandable needs to be reworked 

❓ with labels? Or smth more specific?

>Allocation (as a term) is not easily understandable & in connection with confusion about to whom those fields apply - 2/4 users didn't know are those tokens for them or are those all token that users can buy (a lot of confusion) 

✅ let's reword

___

>-  Users expressed the need to have dollar conversions in summary  

⚠️  not possible unless AMM is enabled, which happens later. So perhaps we can just add a note about it.. 
___________________

## 2️⃣ Next Action after creating 

>- 2/4 users would start editing the token page first to prepare their token for the launch and 2/4 users would start a sale immediately with a small part of the tokens that they own. 

⚠️  We probably want them to nudge to do Set Up Token page as this will impact sales in a positive way.. Icon on the cta or popup interstitial on sale process (are you sure you don't want to set up the page first?)
___________

## 3️⃣ Dashboard
 
>- that he is a bit overwhelmed by the fact that there is still much to do 

❓  Thinking of solution with "Optional" labels on things that are not strictly required to start selling coins. 

>- Revenue split widget in its current form is confusing for all users, all of them expressed that they are not quite sure what it is about 

❓  Perhaps a rename with "Share revenue with holders". Copy quite often makes biggest impact. 

## 4️⃣ Top Level Buttons (edit page/ start sale)

⚠️ agreed to add "Edit token" (basic params) as a button. This will perform even better if we create a widget to display token details and let user edit what is mutable from the widget edit control.s

## 5️⃣ Edit Token Page

> - Preview > 
❓ Big fat label Token page "Preview" would sort it out perhaps?

>- Video trailer 

⚠️ Optional fields need to be marked so and a small copy with smth like "We recommend to do it as this delivers better results.."

## 6️⃣ AMM

⚠️ NB: imo by far the most challenging aspect of this flow.. so we may need a few iterations to get this right..

I feel like Public Sale and AMM  terms are also confusing.. perhaps we can go with "Sell your pre-minted tokens", "Allow Token Minting by buyers. Also, in terms of page layout this perhaps could benefit from explaining two concepts in paragraphs and showing a table with Two CTAs in the bottom. So its less features for each way, but head to head comparison.. 


## 7️⃣ Starting Public Sale

All params here need to be worked on for clarity, but what I feel we are missing in general is a short 2 sentence explainer what aspect of the tokens the whole page is about, so users don't need to guess it from the name of the stage or similar.. In general rich tooltips should also help with this stuff imho. 

##  8️⃣ Starting AMM Sale

AMM concept is hard.. I personally had to watch Youtube vids to wrap my head around it.. I wonder if we could create a short  3-4 step interstitial with imagery explaining the core concept, but as an MVP version paragraph of text with tooltips may do the job?

________________

# Suggestions Comments

🆕  Start with Token Empty State Dashboard rather than "Create token" and have Set up Token as the first widget due to Z or F shape perception this would work * Optional 

🆕  Show Token Details Widget first in the top left corner after creating one

🆕 _Discussed with Kuba on a call:_ Add "Edit token" not as settings wheel but on a widget / dedicated button

🆕  _Discussed with Kuba on a call:_  Add Preview Token Page as a button / or create a dedicated widget showing the state / configured/ not confiugured. * Optional

🆕  For all input forms add a paragraph to the top of the page explaining what is the page about and what implication it has

____

1️⃣ Copy > ✅ agreed for Kuba to take a swing and Adam and myself to conduct a joint review.

>2️⃣ We need to make it super clear that first vesting & cliff apply to creator and the second one during the sale creation apply to the buyers as none of the users seems to understand that. 

-> ✅  Agreed to tackle with section paragraphs and headers explicitly calling this out and enhanced labels.

>3️⃣ We need to add option to have no vesting & cliff easily to not make it look like we force them to do this and really think about what we recommend as default (maybe even make some presets) 

-> ⚠️ The way I understand this point: It is advisable to have vesting period and cliff for buyers, as this is a safety net against aggressive speculation. When purchasing tokens for one-self as creator, having these set as non-zero sends a positive signal to wiser buyers wrt good intent and longer term strategy.  As such I would not suggest to have a separate radio button to "None" but this option could be included to the drop down. A good default may be 2 year vesting schedule with 3 months cliff. @bedeho to advise on this with final recommendations.

>4️⃣ The whole experience of editing the token page needs to be changed - its not working at all. It needs to be explored again and come up with a solution that will be easy to understand and which would not create a feeling that they are obliged to do a looot of work before launching their sale. (Maybe we could have a preview of their empty token page and a wsiwyg experience of editing / adding more content on it there - don't know for now but we have to approach it differently)

⚠️  Here we discussed that perhaps a full page editing first with separate "Preview" CTA may be a winning recipe and better than splitting the screen in half. Also the default preview screen of the left hand side would need to start with some sort of empty state/ placeholders for the next iteration.

>5️⃣ Video explainers were suggested to me repeatedly throughout multiple sessions - maybe it would be worth exploring a concept where we have some small video explainers walking our users through the whole experience. If not definitely at least one video showing the whole process being available for them to get help as they can get lost really easily in those complex concepts.

Imho one video explainer may help a lot to pitch the full experience as fairly straightforward and explain the more challenging concepts before user dives in to reading the tooltips. Every step may be excessive as quite a substantial part of users also prefer to skip the videos.  Open to everyone's view on this. cc @bedeho @toiletgranny 

>6️⃣ Some words were to complex for users - and it was proposed for me few times that we could change some wording to be more beginner friendly instead of being so tech savvy like: token ticker - could be token name, allocation could be "Amount of token you will receive" those are only examples and maybe not even good ones but its at least a suggestion I'm raising that we should be more careful here :)

- ✅ yes very simple wording, which we will work collectively on. I bet that just focussing more on the copy and tooltips will increase the ease of navigation / comprehension of concepts dramatically.

**Comment by bedeho** [comment]
> As such I would not suggest to have a separate radio button to "None" but this option could be included to the drop down. A good default may be 2 year vesting schedule with 3 months cliff. @bedeho to advise on this with final recommendations.

The DAO has a strong interest in maintaining the integrity of these markets, hence we are going to implement global constraints on lower bars for vesting, as well as many other properties of CRTS. See https://github.com/Joystream/joystream/issues/4151. This means we may as well design for a future where the chain will be coercing some lower bound, but what exactly that bound will be may change over time, and _in principle_ the DAO may choose to adopt no bound for certain porperties. The most flexible product design is this to allow this "None" like features, as it implausible that an Atlas operator will enforce stricter rules than needed. What we end up configuring as the lower bound for when CRTs are actually deployed remains to be seen, but as stated, product should work with whatever the bound is.

> Every step may be excessive as quite a substantial part of users also prefer to skip the videos. Open to everyone's view on this. cc @bedeho @toiletgranny

I think these concepts are so complex that it may be warranted, I just don't know if we will have time to make content that is high enough quality for when this goes into production. Why don't you make the design accomodating for a scenario where we do indeed have videos, and then we can decide to include or not depending on bandwidth we have on making that content. It may be that even some very simple low effort content can help a great deal.
