### ISSUE TITLE
Testing ops for Atlas

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2468]
1. Create a staging env pointing to Rhodes network
2. Show block details and link to polkadot js in console after each transaction is signed. Similar to Pioneer implementation: https://github.com/Joystream/pioneer/issues/2289

**Comment by kdembler** [comment]
1. Sounds pretty easy, np
2. Switching between networks is implemented already but not using `config.json` file since we had that feature long before those files were generated. We basically provide avaiable environments during build time. Whenever you have Atlas open, you can press Ctrl+Shift+D to open developer tools. With that, you can pick which network you want to connect to. If you need separate playground for testing, we can include it in our config and you will be able to use it. Does that work, or do you need to be able to move between different playground dynamically?
3. 👍

**Comment by kdembler** [comment]
Additionally move `atlas-staging` Vercel deployment to Rhodes
