### ISSUE TITLE
Atlas does not use the  closest / fastest provider available.

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#2553]
Currently providers are chosen randomly.

Add a mechanism to determine which DP has the lowest latency and use that. Fall back to the 2nd one and so on.

[Context](https://discord.com/channels/811216481340751934/963365664180027412/964976537277444096)

somehow related: https://github.com/Joystream/atlas/issues/2511
> This could also be done to lower latency on starting playback of new videos

**Comment by kdembler** [comment]
Sorry for getting back to this so late, was focusing on Rhodes. So before we get into solutions, I would want to define the problem well and what are some metrics to measure how good a given solution would be.

When bringing this up, is low latency for end users is your only concern, is that the end goal? That would be a good first metric.

Second thing I already brought up in Discord is cache availability, which will impact the end latency as well. Because a single asset can be served by multiple distributors, there can be _X_ URLs for accessing the same asset, where _X_ is the number of distributors serving a given storage bucket. Browsers will keep a separate cache entry for every unique URL, so we would to keep the URL used semi-stable so that the browser can use its cached version.

Third thing to consider would be number of requests fired - we need to restrict the number of request per asset (ideally that's 1) to not block too much of network resources.

Lastly, I think the solution should also ensure some kind of load balancing, at least in a given region. If there are 9 distributors with average latency 100ms and 1 distributor with average latency 90ms, the load should be spread semi-equally between all those distributors, so that the app doesn't overly burden a single provider.

---

Just FYI, this is how we pick distributors at the moment. We get full list of distributors serving a given asset (pre-sorted), then we do `assetId % distributors.length` and this gives us an index of the first distributor to try. Very simple, but it doesn't introduce any latency and the same URL will be picked at all times for a given asset, as long as the distributors list doesn't change. It also should spread the load evenly.

---

Keeping this in mind, do you have some ideas on what we could to improve this process?

**Comment by traumschule** [comment]
Great, looking forward to improvements! Doesn't matter so much for thumbnails but mainly for currently played video. As suggested [here](https://discord.com/channels/811216481340751934/963365664180027412/967134290024480898) each assigned provider should be queried with a HEAD request and the first that responds be selected for streaming. It is possible that storage providers are closest / faster so they can be included.

**Comment by kdembler** [comment]
> As suggested [here](https://discord.com/channels/811216481340751934/963365664180027412/967134290024480898) each assigned provider should be queried with a HEAD request and the first that responds be selected for streaming

So I think this may not be a full solution to this problem, I think we need to be more sophisticated. This doesn't score well in the metrics I've mentioned above - if I understood you correctly, a number of HEAD requests would be fired for every asset, resulting in a ton of network calls, potentially throttling the browser resources. Additionally it wouldn't work well in terms of cache stability, as there would be a fair chance that users end up having multiple copy of the same asset because the latency is inconsistent and multiple distributors are used for a single file.

Seems like it would be much simpler to just know the approx location of the user and prioritize distributors that are close geographically, mixed with the solution we already have. The problem is that I'm not yet sure what would be a good way to figure out that location but there are a couple of ideas. I know that Cloudflare Workers that we already use give you access to user location (https://blog.cloudflare.com/location-based-personalization-using-workers/), potentially we could use something like that to personalize, but I wouldn't want to depend on Cloudflare too much.

**Comment by traumschule** [comment]
>  if I understood you correctly, a number of HEAD requests would be fired for every asset

As i said `mainly for currently played video` - makes one request per assigned provider.
You want one number per provider and pick the best one.

As for other pages when starting atlas, just send one request to each provider to learn their performance, save it on state or even local store for future decisions.

> Seems like it would be much simpler to just know the approx location

Not necessary if you have real latency (= network distance) which due to network topology says more than approx physical location.

**Comment by dmtrjsg** [comment]
Duplicate of https://github.com/Joystream/atlas/issues/2748
