### ISSUE TITLE
Creator Tokens — Viewer: High Fidelity Mockups (HiFi), Documentation & Handover

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2643]
This phase includes activities such as:
- creating Figma mockups from scratch, this time ensuring a proper design work hygiene (through naming layers, setting up constraints, ditching all unnecessary local components, etc.),
- creating/updating global components and their documentation,
- creating designs, documentation, and prototypes for all user stories,
- creating designs for responsiveness,
- identifying and designing for empty states, error states, and edge cases,
- applying visual finishing touches,
- etc.

The expected outcome is:
- a final video walkthrough of the Figma file and a prototype for engineers,
- links to Figma designs and prototypes,
- separate GitHub issues created for changing or introducing new global components.

**Comment by KubaMikolajczyk** [comment]
High-fidelity work for CRT Viewer is done ✅
Channel page Fix, Pages, RWD, user stories & components - a lot of things to unpack - enjoy 👍
🎥 Loom video update: https://www.loom.com/share/287dbb9c3ec942159dc760b792f60564
📄 Figma changelog: https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1624%3A85414&t=zx8D2llJWX7MKer0-4

**Comment by bedeho** [comment]
1. This was _amazing work_, there is so much here, but you explain it well, and you have given a lot of care ot some super complex parts, like the buy widget. Really nice how you treated time with such granularity. I don't really feel like I have much valuable input here, and I only picked up on one specific question (the one about how to thank the purchaser), this is largely a testament to how well the work has been done, so cudos!
2. I'm still beating this drum: lets use a more direct and natural terms for people to claim their share of a revenue split than _stake_, its just confusing, because staking has other associations  (in particular that it is a perpetual activity), and it is specifically for providing security, not cashing out. I have said this before, but I don't remember seeing any rebuttal.
3. The "how to get whitelisted" seems like an overkill, and I'm not sure people will even read it tbh. The page being linked to can handle any explainer that is needed, and anywhere we can restrict scope is a win at this point.
4. I think we should go with the easiest "thank you" message, so just the animation thing, its just not worth it doubling down on a video right now.

**Comment by KubaMikolajczyk** [comment]
Thank you kindly 🙇 I'm glad you like the outcome

2. OK I understand that, I list some examples of microcopy for this action with a focus on the idea that staking allows users to claim their share of the revenue. Do you find any of those appropriate?
![image](https://user-images.githubusercontent.com/31144205/210511138-8d801180-b52a-4a1e-b1f5-3e57da52ae05.png)

3. I just want to clarify my understanding of this situation. Are you suggesting that we redirect users to an external link rather than displaying a dialog with information when they click this button? While I see the benefit of limiting the scope of the feature, removing the input on the Creator side and the dialog on the viewer side may not have a significant impact.

I have two concerns about this decision:

- For Creators, this would require them to use external tools to display any messages they want to show to users. If we assume that 90% of users just want to write a simple message like "Write to me on priv on discord my nick is @mynick," requiring them to use external tools to do so could be a potential pain point.

- Redirecting users to an unknown link from the site could potentially cause problems. Users may try to cheat other users with phishing websites, and this could also lead to a drop in trust when clicking the button.

Incorporating these elements could help us avoid these issues and make users more likely to click the button without feeling insecure about the action. Let me know your thoughts on this

4. OK I will go with this variant :)

**Comment by bedeho** [comment]
2. `Get your share`.
3. We are already primarily depending on sending someone to an external link? there is no way they can get on a whitelist by just looking at that screen, they will have to go _somewhere_, read something do something? I am not adding anything new, am I?

> If we assume that 90% of users just want to write a simple message like

Yeah this is a very good point, I just assumed it would be very involved, at least filling in a form. For the example you have in mind, why even require people to do that? If you genuinely are not even going to collect any information, just approve anyone who sends a message, then why even vbother. If you are going to collect any information or do some screening, then don't you really need some sort of form or something aynway? 

I don't know for sure, but isn't this the sort of thing we will figure out quickly in practice?

> Users may try to cheat other users with phishing websites, and this could also lead to a drop in trust when clicking the button.

I don't understand how phishing would be done here, perhaps you can unpack.

**Comment by KubaMikolajczyk** [comment]
>We are already primarily depending on sending someone to an external link? there is no way they can get on a whitelist by just looking at that screen, they will have to go somewhere, read something do something? I am not adding anything new, am I?

Yes, you are right nothing new added here. Except of scenarios when they don't require you to go anywhere then a message in a dialog might be enough.

> If you are going to collect any information or do some screening, then don't you really need some sort of form or something anyway?

Yup, if screening is involved then a user might want to create a form but not 100% necessarily - it can also be manual screening in form of a simple 1-1 conversation. One of the participants (Zach) of our tests who spoke highly of the concept of whitelisting said that they need to know every single holder before they sell to them. In this case, even a form wouldn't be needed, a simple message about where to find me, and what my nick is may be enough. 

> I don't understand how phishing would be done here, perhaps you can unpack.

Just quoting the definition: "Phishing is a type of online scam in which attackers send fake emails or texts, or create fake websites, in order to trick people into revealing sensitive information such as passwords, credit card numbers, and bank account details." - I think we would be prone to such practices either way so we might want to include a simple warning above the external link to not to provide any sensitive information.

In case when there would be a middle step though with a dialog we would give the Creators option to show a message and maybe a link won't be even needed then.

**Comment by bedeho** [comment]
>  I think we would be prone to such practices either way so we might want to include a simple warning above the external link to not to provide any sensitive information.

I don't think this is correct, the trusted authority is the creator, only they can provide the link, and if they choose to provide a link to some bad place that would not be phishing. A bad creator can already harm the person in many ways, hence a bad link here seems like quite an arbitrary emphasis. There is no independent risk of some malicious third party compromising the link itself, if you leave aside that you obviously have to trust the whole app itself also to begin with.

> One of the participants (Zach) of our tests who spoke highly of the concept of whitelisting said that they need to know every single holder before they sell to them.

Ok, its not a big deal, you seem very convinced about the merits of this, so lets do it.

**Comment by KubaMikolajczyk** [comment]
OK, I understand your POV. I won't add the additional info.

**Comment by dmtrjsg** [comment]
Amazing work @KubaMikolajczyk 

Seems like the only two points of discussion are whitelisting and success screen. 

### Whitelisting 

I actually believe **current designs work pretty well**. We can ofc just go with a simple message or just a redirect, but.. 

1. It is 100% always best to keep user in the app and minimise redirects to other sources so showing info on how to do it on Gleev is my strong preference. 
2. If only text box is considered - the link may get pretty lengthy with all of the UTM tags, so this may take up all too much space and look subpar.
3. Having a large distinct CTA triggering popup makes it  possible to analyse engagement (event for analytics emitted on click) and helps to contribute to user research and later to creator analytics dash. 
4. The message itself when customised by creators can get quite lengthy and we don't want to restrict them on space or overload the initial view of the page. 

### Success screen 

Simplest possible form is great - so third variant is best for me. Unlockable content would be added later as that requires more work on the app/ qn / and possibly runtime levels, so let's not worry about it just yet. 

Portfolio is better than "wallet" in the toaster confirmation screen 👍 

### Timer

I'd go for Red as early as 1 week.. as soon as it flips to ENDS IN variation.

**Comment by KubaMikolajczyk** [comment]
🟢 Update after feedback for CRT Creator & Viewer | Removing sections, Sale & Market, Revenue share
🎥 Loom video: https://www.loom.com/share/3a441d4c7bba4f0b99d8531da984ac8b
📄 Channel page changelog: https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1624%3A85414&t=9LSU5rQo1PxdSNma-4
📄 My token changelog:  https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=925%3A139042&t=Jen95QDQKLIYpAWi-4

**Comment by bedeho** [comment]
https://github.com/Joystream/atlas/issues/3445#issuecomment-1410738037
