### ISSUE TITLE
Creator Tokens — $CRT Holder: Research & Discovery

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2687]
This phase can include activities such as debriefing, desk research, competitor analysis, booking and conducting discovery in-depth interviews, or performing moderated usability tests on existing competitors' products.

The expected outcome is a brief report on key findings & conclusions, a link to Figma moodboards, screenshots from the competitor analysis, etc.

**Comment by KubaMikolajczyk** [comment]
# Overview

During this phase, my goal is to get more familiar with the last part of the creator token experience: holding the token, transferring it, & performing other tasks that the CRT holder would do.

# Key findings

1️⃣  Usually there is one place with a list of all coins where the user can check the balance of all of them and perform some actions this page is called wallet or portfolio (the latter feels more accurate but that's my opinion)
2️⃣  Apart from the creator coins being listed there, the main prominent place on this page takes the platform's main coin (RLY, DESO), and here users can purchase the coin to later exchange it for various creator coins
3️⃣  The important information given by both platforms is the value of the whole portfolio

🟢  After exploring those platforms I'm confident that apart from the list of owned creator coins a really important place should be reserved for the platform coin (JOY) as this will be used later to purchase other coins. Also, there is a big opportunity here to provide users with an easy way to start the journey with coins and guide them through the process as our competitors leave the user to explore it all on their own. 

### Below in-depth exploration is TLDR. Read-only to gain a deeper context of the findings.

# 1️⃣  Rally

On rally, it's really easy to access all your coins wallet. Once you are logged in you can see an additional navigation item called a portfolio. When clicked you will be presented with this screen:
![image](https://user-images.githubusercontent.com/31144205/168786768-513814ef-3ff3-47a5-b3b2-9998f3d085f8.png)
Here right after a prominent title, we can see a button to download the history and the total value of your whole portfolio. Right under that, we have a two-column layout with the main part being the table of you all your coins and in the right column, a CTA & you rewards summary.

When the user clicks on trade action on the coin row we can see those actions
![image](https://user-images.githubusercontent.com/31144205/168787449-e9d41c63-6ddc-4498-9e71-5d8894d0c42b.png)
As for now because I don't hold any tokens the only token I can see in the list is the platform token. The actions in the trade list are also related to this particular token. 

The platform itself makes a distinction between actions with platform token and with creator token which we can see here if we click on the trade button in the top right corner of the navigation
![image](https://user-images.githubusercontent.com/31144205/168787849-baceea84-e55f-4b2e-b3f3-bd8f91e6f716.png)

If we choose to buy a creator coin from here we will see this modal with a single select input which expands to a list of creator coins after clicking
![image](https://user-images.githubusercontent.com/31144205/168788131-1a92e543-09b1-44d4-ba58-8eae0ade9f94.png)
![image](https://user-images.githubusercontent.com/31144205/168788142-c6a3fd14-5af8-4857-8c30-094d21f0a515.png)

If the user chooses any coin and clicks continue the next visible step here would be the same purchase flow as if the user try to purchase it from this particular creator token page
![image](https://user-images.githubusercontent.com/31144205/168788412-2bb9d413-febf-43c6-bd1b-46f8fd88dbbd.png)

The user might also want to send, 
![image](https://user-images.githubusercontent.com/31144205/168789030-3a58be5f-63f5-4404-aaa1-a1622bca5150.png)
We can find the rest of the sending flow in their documentation
![image](https://user-images.githubusercontent.com/31144205/168790509-bdd095ff-853a-40df-89f0-30c910ffb598.png)
![image](https://user-images.githubusercontent.com/31144205/168790559-b69f47e7-1d65-4ce3-8fba-8f9eaa56e10d.png)
![image](https://user-images.githubusercontent.com/31144205/168790593-41c975ac-6857-4b07-ae53-b748752debad.png)

To swap user uses this kind of modal:
![image](https://user-images.githubusercontent.com/31144205/168789074-f5510fd5-b610-49b9-a8af-a996edaa1852.png)
![image](https://user-images.githubusercontent.com/31144205/168791003-ae97c373-9c73-4122-93e5-72d9d8dfa1bd.png)
![image](https://user-images.githubusercontent.com/31144205/168791018-ea0b475c-51a1-4734-a45f-c07cc8a17281.png)

The last part of the experience is to convert creator coins to rly coins and this is done in a modal.
![image](https://user-images.githubusercontent.com/31144205/168789153-eb8731a0-215f-4a88-8ea8-3588ac02bdfc.png)

As told before the user has a separate column of options to buy, convert bridge in and bridge out the platform tokens.
![image](https://user-images.githubusercontent.com/31144205/168789719-eb27bbcd-86ed-4817-a390-87d0712f8c1d.png)
![image](https://user-images.githubusercontent.com/31144205/168789752-ed42b088-97a1-4a8d-9891-e530c07c32de.png)

While two first actions are performed in already familiar modals - the two last are linking to an external bridging platform that allows transferring $RLY coins from mainnet to sidechain and back.
![image](https://user-images.githubusercontent.com/31144205/168790007-b4dbb036-bf33-4b3b-b8f6-8abb93955305.png)

# 2️⃣  Deso / Bitclout

It's extremely hard to find some clear information about actions on creator coins in deso documentation. But we can observe some of the actions implemented in bitclout. 

Here we have a wallet page with information like the total wallet value, the balance of the platform token deso & its current value, list of all owned tokens with a distinction between those you purchase and those you receive.

![image](https://user-images.githubusercontent.com/31144205/168791904-1f02edec-92e0-4450-9b74-4292df9c9088.png)

On the left navigation, we can see an action to send creator coins. But we cannot say how the flow would look like because we don't own any
![image](https://user-images.githubusercontent.com/31144205/168792559-dcd292bc-03b7-4614-ad0d-9dc5e7b2e9ad.png)

The next action is to send deso and here we can see some fields - the experience of sending creator coins would be probably similar
![image](https://user-images.githubusercontent.com/31144205/168792661-ab6fa811-1939-4051-ad56-a65252f81bb5.png)

There is also a separate option to buy DESO where you can choose the currency, amount and country,
![image](https://user-images.githubusercontent.com/31144205/168792791-b3329af8-53a9-4fdb-a339-4625146d6de2.png)

And an option to buy creator tokens
![image](https://user-images.githubusercontent.com/31144205/168792897-ca4490ce-efca-4cee-ad05-629c04400ffe.png)

Here if we choose to buy action we can also see sell & transfer actions which probably are later available for users from the wallet level if this coined is owned.
![image](https://user-images.githubusercontent.com/31144205/168792962-5d3add84-c333-4503-af6c-34368ac4cf0e.png)
![image](https://user-images.githubusercontent.com/31144205/168793001-239c605d-4fc4-4bb6-a03e-78c986fe07fe.png)
![image](https://user-images.githubusercontent.com/31144205/168793022-0b934d78-ca9b-4f17-9a5e-5035a0f9f150.png)

If you have read it all, thank you for your time 😅🔥
