### ISSUE TITLE
Creator Tokens — $CRT Holder: Exploration & Low Fidelity Mockups (LoFi)

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2688]
This phase can include activities such as sketching, prototyping, and discussing potential solutions internally, preparing for conducting usability tests (work tracked in a separate issue).

The expected outcome is a video walkthrough of happy paths for all user stories mentioned in the epic, along with links to Figma designs and prototypes.

**Comment by KubaMikolajczyk** [comment]
1st Exploration (Pen & Paper) Holders experience
🎥 Loom: https://www.loom.com/share/9f77a6d60fdc424795189fd4dea7e2ac
📄 Figma files: https://www.figma.com/file/VzPBMpUnGjGOHMSW2ZHbGY/Creator-tokens?node-id=2630%3A210854

**Comment by bedeho** [comment]
Thank you for preparing this, I can tell it's been a long while since we looked at this, but its great to get back into this.

1. While having a dedicated space which is easy to get to for creator tokens makes a great deal of sense I think, it's not clear to me why we would not need a similar space for managing NFTs we own? There are similar owner specific actions, as well as a total overview, that seems to be of similar significance across both. I am not saying we need to do both now, I am really asking about whether there is any difference. Remember there are other NFT features we have entirely skipped, like sending an NFT, or making an NFT offer conditional on payment, as well as accepting such offers, etc.
2. If we call this page "Portfolio", I also wonder whether NFTs also don't belong there. If they don't, eprhaps a different name? I am not sure.
3. Remember that for all of tehse designs, they have to also work if there is no USD price feed for $JOY.
4. I think the designs for the revnue splits here really need to reflect that they are likley rarely, extremely rarely will more than 1 be occuring at the same time in the same normal portfolio. When they happen, they are extremely time sensitive, because the person looses their piece of the pie if they dont. I think the single column design in general is more compatible with this, as the two column design ends up wasting space for something that rarely happens, and when it does happen, does not give that much prominence to it.
5. The dual table approach does seem a bit rough to me, not only because I think the top tabel will just have one row 95% of the time its visible (I assume its hidden when there are no splits), but also having two tables with disticnt column sets/numbers often looks disorganised, and just that the table overhead to content ratio seem wrong. I wonder if using cards, even horizontal one(s), with flexible internal composition, would work better, in particular when you have 1 or few displayed. Just a thought.
6. In general we should just avoid trying to unpack the details of what locks apply and what tehy are, its just too complicated, and utility is low. So a specialised page for this is not worth it, certainly a this stag. Also, what locks exist is irrelevant to the question of revenue splits, because all tokens you hold can participate, whether vesting or not.
7. Yes, I think we should just require the user to use all tokens when joining a revenue split. I do believe the blockchain allows you to set a lower number, but we should not encourage this.
8. Lets call it "Claim Revenue" & "End Claim", or something tangible to user goals "Stake" is not actually something user recognizes as a goal.
9. I think we need to indicate what tokens are permissioned vs permissionless (anyone can receive/buy).
10. Remember that each recipient in a multiway transfer can receive distinct amounts, at least on the chain level. Also note that, if you are the issuer, you can transfer and add vesting condition on those funds on the recipient. I am not sure if we should allow issuer to make such multiway transfers that include vesting from the portfolio, or if they have to go to their issuer/channel view to do this.

**Comment by KubaMikolajczyk** [comment]
Thank you for the feedback :)

Answers:
1. I think it makes a lot of sense to have them both in one "Portfolio" page - to look at all of the assets that one can own. I would be happy to explore such direction.
2. If we decide to commit the NFTs from here we can also call this page "wallet" 
3. Right! There will be two versions prepared
4. I agree!
5. I can explore that :) 
6. OK I will drop this
7. Agree
8. I'm a little worried as claiming the revenue is a result of an action of staking. And concept of staking (as locking your tokens to get revenue) is widely known across crypto space. I would gladly test this assumption but I think it can be misleading if we state "claim revenue" only without telling what they're about to do to claim it.
9. Will do!
10. Vesting would be nice to have here so I'm all in to include this in explorations. If it comes to distinct amounts we can explore it but I feel it's going to complicate the transfer flow a lot more than just saying all recipients will receive equal amounts - will explore that too.

**Comment by bedeho** [comment]
> If we decide to commit the NFTs from here we can also call this page "wallet"

I think portfolio is actually great, wallet is scary, makes you think of keys, secret phrases, addresses, sending (looosing!) funds, etc. I think main function of this screen is to manage what you own, so portfolio is great.

**Comment by KubaMikolajczyk** [comment]
2nd Exploration (Pen & Paper) Holders experience
🎥 Loom: https://www.loom.com/share/822ca3ea92e24f178ebd5031e02083e4
📄 Figma files: https://www.figma.com/file/VzPBMpUnGjGOHMSW2ZHbGY/Creator-tokens?node-id=2830%3A222027

Please let me know if we are on the right track and can proceed to higher fidelity with this :)

**Comment by bedeho** [comment]
Great job, this was really concise and small scope, easy to give feedback.

1. I think the variation with only two tabs was better, and a floating card whenever it rarely is needed above. Perhaps having a title like "Active revenue splits" or something seems like a nice addition.
2. I agree with having uniform amounts in one multiway transfer, overhead is small, and ux was getting quite involved.
3. I would recommend doing the same with vesting: so everyone in one multiway transfer has same vesting terms, for the same reason as in 2.

**Comment by dmtrjsg** [comment]
Looks solid for me, a few questions / comments:

1. "Discover more tokens" underneath your portfolio - where does it get the user to? Does this warrant some sort of a table view for tokens discovery on a dedicated page? (dont remember this was addressed as part of Viewers, worth creating an issue for this and adding to the pipe, probably ok for MVP to have it a table with search and filters underneath.. before doing a fully fledged marketplace for both NFTs and Tokens discovery 😇 )
2. I think sending creator tokens should be possible from both Holder view and Creator view. Also, q can token holder send tokens to someone else, or only sell on AMM? @bedeho 
5. Sending uniform amounts and revenue split as a card on top of the table lgtm :)

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg answers 👇 
1. I think i might have added that myself and with it being probably out of current scope I removed it in the current iteration
2. As far as I know any holder can transfer their tokens

1st Hi-fi exploration Holders experience is ready ✅
![image](https://user-images.githubusercontent.com/31144205/191319188-5c468a94-af0c-4e77-8a8b-ac47ec68da3a.png)
🎥 Loom: https://www.loom.com/share/ecef511d2f204ba796a119e0e5885389
📄 Figma files: https://www.figma.com/file/VzPBMpUnGjGOHMSW2ZHbGY/Creator-tokens?node-id=2902%3A239537

**Comment by bedeho** [comment]
Thanks for the great summary, got inspired to prioritize sharing these with the community again!

1. I think Total value of portfolio should be more prominent than it is now, it's drowining, and it should be doing the normal thing of being denominated in $JOY if there is no price feed, and $USD+$JOY otherwise. I also think we should not exclude NFTs, despite them being much less liquid, I think it should be a prominent reminder. It could make sense to distinguish the NFT and Creator Token values into two separate cards though.
2. There are tons of labels that need to be cleaned up and simplified here, here is just a sample, hope the idea is clear
  - `Owned NFTs` => `NFTs`
  - `Token Name` => `Name`
  - `SPLIT Starts` =>  `Starts`
  - `TOTAL TRANSFERRABLE` => `Transferrable`
  - (STATE label )`Active revenue split` => `Active` or `Ongoing`
  - (Section header )`Active revenue split` => `Revenue Splits`
  - `Future revenues split` => `Announced`
  ...
3. One weird edge case: new split started, for same token, but no unstaked for last.... how to show? 
4. I think we need a price and (24h) volume columns, and they should be early in the table. Price can be AMM price if active, if not it can be last token sale if there was one, otherwise it should be missing. Similar treatment possible for volume.
5. You are correct that the unit price changes per unit you purchase or sell. When you interact with an AMM, the price is impacted, but I am not sure the user really needs to think bout this, they just need to understand how many creator tokens they will receive in total for what they are choosing to spend.
6. Tes there is fee on interacting with AMMs.
7. To your questiona bout how amounts locked and transferrable change: correct
8. Normally I would have said "just hide" on buy/sell, but since everything is so new here, and people may not even be understanding that AMM may not run forever, its worth trying to add something that explains why its disabled. 
9. Remove sort & filter, not a priority, people won't have portfolios that large, and if they do, there will be standalone portfolio sites for that. At least for now Id rather not even distract engineers with this.

**Comment by dmtrjsg** [comment]
Apologies if some of the questions were answered before, but this is vast topic with lots of nuances, so thought its best to clarify once again. 

1️⃣ Portfolio
How about we go with Total / Coins / NFTs, as widgets re-using the widget components from Payments dashboard? They seem to be suitable for here and will nicely decorate top of the page when splits are not active. 


2️⃣  One weird edge case: new split started, for same token, but no unstaked for last.... how to show?

From my pov best is to go with _two separate cards_ with diff statuses would be good from user perspective if we can hold on to the timing of split starting/ ending blocks to segregate the two.  Once the revenue is claimed from the first split, it disappears. 

❓ lock recovery happens automatically or actively recovered?

I propose to have a simple status machine linked to CTAs:
1. `Split: Active; Tokens: Unstaked -> CTA: Earn Tokens`
2. `Split: Active; Tokens: Staked -> CTA: Stop Earning` 
3. `Split: Active; Tokens: Stopped -> CTA: Claim Earnings`  
4. `Split: Ended; Tokens: Staked -> CTA: Claim Earnings`

⚠️ I thought it is possible to stop it anytime before the split ends, or are we locking it for full duration of split?

This comment from earlier discussion made me think its possible to stop it and claim rev before split ends 
>"Lets call it "Claim Revenue" & "End Claim", or something tangible to user goals "Stake" is not actually something user recognises as a goal. 

@bedeho  

If not possible, 2 and 3 from above 2 are not applicable.

3️⃣ Copy of toaster

Small one but still noticed that confirmation toaster copy when staked was confusing for me using "Claimed" wording..  
Suggest the copy of : "You staked 1000 ABC, to claim 205 ABC in Earnings if kept till dd/mm/yy, when the revenue split  ends." 

4️⃣ Transfer

Token transfer -> can be done to just a wallet, does not have to be a member, so we can try and re-purpose same modals as with payouts/ withdrawals.

❓ Are `platform fees` taken when tokens are transferred? or just tx fees? @bedeho

**Comment by KubaMikolajczyk** [comment]
Thank you for your replies 🙇

@bedeho :
1. I agree that we can add even more prominence to this indicator. Just to make sure I remember it correctly - we can show value of those tokens only which have AMM enabled am I right? Do you have a way in mind to get the value of the NFTs that you own? 
2. 👍
3. I thought about this one - maybe we can introduce some kind of "new split" indicator to mark that there is a new split apart. I will explore this.
4 - 9 👍 👍

@dmtrjsg :
1. You mean to display the value in them right? 
2. As far as I know - when you claim your reward you get the reward immediately, but the tokens you use to stake will remain locked there for at least as long as the split ends. After the end of split user has to come back and manually unlock their tokens from the split and it cannot be done automatically :) please correct me @bedeho if I'm wrong
3 -4  👍

**Comment by bedeho** [comment]
> we can show value of those tokens only which have AMM enabled am I right? Do you have a way in mind to get the value of the NFTs that you own?
NFTs: last sale price, if available, 0 otherwise.
CRTs: if AMM is live, used that, if sale is live, used that, if neither is live, use the last one of the two which may have been live, use that, 0 otherwise.
