### ISSUE TITLE
Creator Tokens — $CRT Holder: High Fidelity Mockups (HiFi), Documentation & Handover

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2689]
This phase includes activities such as:
- creating Figma mockups from scratch, this time ensuring a proper design work hygiene (through naming layers, setting up constraints, ditching all unnecessary local components, etc.),
- creating/updating global components and their documentation,
- creating designs, documentation, and prototypes for all user stories,
- creating designs for responsiveness,
- identifying and designing for empty states, error states, and edge cases,
- applying visual finishing touches,
- etc.

The expected outcome is:
- a final video walkthrough of the Figma file and a prototype for engineers,
- links to Figma designs and prototypes,
- separate GitHub issues created for changing or introducing new global components.

**Comment by KubaMikolajczyk** [comment]
The hifi work is ready to be reviewed ✅
🎥 Loom video: https://www.loom.com/share/cf93a1d503934ed2a34d4f85b29c6f7a
📄 Figma changelog: https://www.figma.com/file/VvWuJfHYpOPFQrcDVAeHkT/My-portfolio?node-id=5%3A3259&t=6o0iqPNCLk1Y3tqT-4

**Comment by bedeho** [comment]
Great job sir, I hope some of my remarks are not too late for the stage we are at.


# My portfolio

- In the drop-down menu, why don't we just call it "profile" and "portfolio", dropping the "my" prefix?
- what about havin same tab selector as used in marketplace that Adam just made? seems to make sense? This would probably require putting hte revenue share widgets _inside_ the creator token tab, which I can't quite recall now why we did not do to begin with in low-fi stage. If the issue was making sure peopel don't misss it, perhaps this can be solved by just having some sort of alert counter or something deocrating the tab when there are active shares? Let me know what you think.
- I think the portfolio value widgets need to get pinned down asap, ebcause they are so important, yet subtle. I also thought we made some decision during lo-fi, did we not? I think placement of these indicators need to really reflect the priority people give to them, right now it feels a bit low prio. I also think that perhaps these indicators should live inside the relevant tabs, just as mentioned above. Off-the-cuff it seems to me like what people will want to track is
  - value of all liquid tokens
  - value of all tokens: including non-liquid tokens which have at least one last price, e.g. sale or closed market. 
  - value of all NFTs: this is basically just sum of what you have paid for all NFTs you have bought. This will be very stable, as there is no real liquid market for 1-1 NFTs, so this number only increases when you buy and decreases when you sell, even if you made a profit. Not sure its worth including. 

# Selling when on market

- "tokens to spend" => "tokens to sell"
- are we going to hide more advance controls which deal with slippage and such? I think that makes sense tbh.
- the breakdown at the bottom seemed too confusing. You are mixing total of what you are giving away and what you are receiving, which is confusing. I also think the "You will receieve" is actually extremely critical here, its is the main output value the user will be looking to look at as they adjust their sell amount, at least this is my guess. Not sure if these should all be combined together like this. Also you are not purchasing the $JBC, as you are getting rid of it, arguably you are purchasing $JOY by spending $JBC.

# Buy $JBC

- Why was the balance of the currency used to spend removed here, namel y$JOY balance, while you kept it when selling $JBC. I don't understand why these cases should be treated differently.
- Same question about assymetry of remainder of the buy screen here actually, I don't see the reason for this.

# Participate in Revenue share

- $JBC Tokens are not transferred back when share ends, you have to "unlock" them in order to actually start transferring them again. I believe $JOY is transferred to you the moment you click claim actually, but double check with @ignazio-bovo on this.

**Comment by dobertRowneySr** [comment]
> $JBC Tokens are not transferred back when share ends, you have to "unlock" them in order to actually start transferring them again. I believe $JOY is transferred to you the moment you click claim actually, but double check with @ignazio-bovo on this.

Correct: when a JBC holder participates in a split the $JOY dividend amount is transferred immediately to his account, after that his $JBCs are staked.
In order for him to unstake them he must wait for the revenue split to end (i.e. current block must be past the end of the `SPLIT_START` + `SPLIT_DURATION`)

**Comment by KubaMikolajczyk** [comment]
@bedeho not too late at all - thank you for the feedback 🙇 

> In the drop-down menu, why don't we just call it "profile" and "portfolio", dropping the "my" prefix?

The only problem with that is that we currently use "my" prefix for all pages that somehow relate to the user displaying this UI, so here it's used only to follow the pattern. Do you suggest we should drop this pattern in other places as well or we should break the pattern just for this one? (below some usecases of my prefix)
![image](https://user-images.githubusercontent.com/31144205/218068051-8c26782d-ef74-4c0e-862f-254b59dcecab.png)
![image](https://user-images.githubusercontent.com/31144205/218068156-8587f668-e0c0-4da7-be81-497b94d62aaf.png)

>what about havin same tab selector as used in marketplace that Adam just made? seems to make sense? This would probably require putting hte revenue share widgets inside the creator token tab, which I can't quite recall now why we did not do to begin with in low-fi stage. If the issue was making sure peopel don't misss it, perhaps this can be solved by just having some sort of alert counter or something deocrating the tab when there are active shares? Let me know what you think.

The tab selector that you mention here is the one below in the picture am I right? Is there something in particular about them that you like over the regular tabs which we use normally in the system? Is it the icons?
![image](https://user-images.githubusercontent.com/31144205/218069142-00d9cd6a-3a6f-45d7-ad80-0d640c7563b6.png)
I think there is no harm to putting revenue shares under the creator token tab as long as creator tokens will be the first thing to show when user enters the portfolio page as it is designed right now. Counter on the tab is a nice idea too to bring some more prominence to revenue shares.

>I think the portfolio value widgets need to get pinned down asap, ebcause they are so important, yet subtle. I also thought we made some decision during lo-fi, did we not? I think placement of these indicators need to really reflect the priority people give to them, right now it feels a bit low prio. I also think that perhaps these indicators should live inside the relevant tabs, just as mentioned above. Off-the-cuff it seems to me like what people will want to track is
value of all liquid tokens
value of all tokens: including non-liquid tokens which have at least one last price, e.g. sale or closed market.
value of all NFTs: this is basically just sum of what you have paid for all NFTs you have bought. This will be very stable, as there is no real liquid market for 1-1 NFTs, so this number only increases when you buy and decreases when you sell, even if you made a profit. Not sure its worth including.

We didn't agree on anything specific during low fi and with only one variable this was the solution I came to but with all those variable I think we can easily go for something more prominent such as widget tiles like the ones we use in other places in the app. Something like this - is this what you meant?
![image](https://user-images.githubusercontent.com/31144205/218071923-877d5a15-3911-4e49-88d7-b718a34cc840.png)

>"tokens to spend" => "tokens to sell"

✅ OK gonna change that

>are we going to hide more advance controls which deal with slippage and such? I think that makes sense tbh.

Yes that's something that we agreed on during low fi - to not show those controls at least for now.

> the breakdown at the bottom seemed too confusing. You are mixing total of what you are giving away and what you are receiving, which is confusing. I also think the "You will receieve" is actually extremely critical here, its is the main output value the user will be looking to look at as they adjust their sell amount, at least this is my guess. Not sure if these should all be combined together like this. Also you are not purchasing the $JBC, as you are getting rid of it, arguably you are purchasing $JOY by spending $JBC.

Noted! Yes I had a small issue with coming up with something that will work here - glad that you speak about it - so I will take a closer look and come up with something tidier.

>Why was the balance of the currency used to spend removed here, namel y$JOY balance, while you kept it when selling $JBC. I don't understand why these cases should be treated differently.

So what you're saying here is that we should show the balance of Joy tokens when buying $CRTs like we show $CRTs balance when selling them right? I agree we can do that

> Same question about assymetry of remainder of the buy screen here actually, I don't see the reason for this.

Great catch! I will make them unified.

> $JBC Tokens are not transferred back when share ends, you have to "unlock" them in order to actually start transferring them again. I believe $JOY is transferred to you the moment you click claim actually, but double check with @ignazio-bovo on this.

Yes I'm fully aware of that there is even a state for the revenue share widget where users can unlock their tokens:
![image](https://user-images.githubusercontent.com/31144205/218073704-eb7673f7-e1ab-4afb-a73c-5fcabe41b70e.png)
and I tried to find where I made a mistake in communicating that - is it this modal that you're writing about: 
![image](https://user-images.githubusercontent.com/31144205/218073446-3b97a9a7-9143-4ce6-8491-e765452757b9.png)
I will change the copy here as this is totally my mistake here. If there is any other place where you found that mistake please do tell so I can repair :)

**Comment by bedeho** [comment]
> Do you suggest we should drop this pattern in other places as well or we should break the pattern just for this one? (below some usecases of my prefix)

Def. I had not seen all like that before, much cleaner without it.

> The tab selector that you mention here is the one below in the picture am I right? Is there something in particular about them that you like over the regular tabs which we use normally in the system? Is it the icons?

When the screen basically has two major options for what to see under one topic, as opposed to having some smaller area or container that can be toggled, then having big prmary indicators are great, as you get to have some space to add badges, explainers, counters, and it also just clearly stands out as a primary choice for the user, rather than a small button drowing in a complex scene of many options at the same level of prominence. Lastly, I don't see us doing it differently across thee two cases (portfolio vs. marketplace), its the exact structure to the screen, and the user is doing something very similar, so just seems inconsistent as well.


>  Something like this - is this what you meant?

Yep, but without the big `Portfolio` title though.

**Comment by KubaMikolajczyk** [comment]
@bedeho @dmtrjsg @attemka @WRadoslaw the updated version with implemented feedback from above of CRT holders portfolio is done and ready for review ✅

🎥 Video update: https://www.loom.com/share/b73da507a5a24ed78791de75427f0a8c?sid=1636a34e-dad6-48f4-9625-442832e4f855

📄 Portfolio changelog: https://www.figma.com/file/VvWuJfHYpOPFQrcDVAeHkT/Portfolio?type=design&node-id=1355-78829&mode=design&t=S2JIdARTjP0TXAUI-4

📄 Side navigation changelog: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=9779-174960&mode=design&t=YvtglDwdPLRTByao-4

📄 Account dropdowns changelog: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=9258-167766&mode=design&t=YvtglDwdPLRTByao-4
