### ISSUE TITLE
Take a look at Orion crashes

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2705]
It seems that there is some memory leak in Orion. After the container is started, its memory usage keeps increasing, up to a point when it hits the default Node.js memory limit and the app crashes with this error code: `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`. The default limit is 2096 MB, we could increase it, but that just postpones the crash so we need to figure out where this is coming from.

I _think_ (cannot tell for sure) that this didn't happen before so potentially this is caused by some recent Orion change, worth analyzing. Ping me for any more details/help or the prod DB dump

**Comment by traumschule** [comment]
The only recent commit (Apr 12) increases a query limit https://github.com/Joystream/orion/commit/0e9a6cf7fec5c23a756698c55a6ecce2c3de827b
Unlikely the result is too big but possibly mongodb/mongoose struggle somehow.
If not a recent change could be previously introduced silent bug that went unnoticed before NFT because no app used it.

Also could be because of stale connections (to QN or from somewhere else). https://github.com/expressjs/express/issues/3552#issuecomment-363226856

Did you upgrade Node or anything else recently? https://github.com/expressjs/express/issues/3871

**Comment by kdembler** [comment]
Yeah I looked at past commits as well and nothing obvious as to what is the cause. I really doubt it's the different limit on the query, shouldn't really have an impact, we also don't save the result to the DB. We haven't done any updates recently as well, so really clueless. Spent a better part of yesterday debugging but no results so far
