### ISSUE TITLE
AMM User Research for Creator Tokens

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2728]
@bedeho commented on [Wed May 18 2022](https://github.com/Joystream/joystream/issues/3765)

# Background

Our ongoing creator token work involves building in a possible _Automated Market Maker (AMM)_ to assist in liquidity for very long tail assets. This is a complex feature, which causes complex product implications, and its not going to be easy to change course once live. For this reason, we are well served checking how well such AMMs are working for other systems. We are in particular interested in _DeSo_, which has a very similar _Initial bonding curve offering (IBCO)_ type AMM for its creator tokens, as this is the closest analogue to what we are imagining. The power of this AMM is that it does not require third party _Liquidity Providers (LPs)_.

# Proposal

Try to understand how well the IBCO construct is serving the liquidity and price discovery objectives of creator tokens on DeSo. Primary sources to review are their

- Github
- Reddit
- Discord
- Forums
- Community calls
- YouTube reviews
- Users: 1-1 interviews

Example topics we are interested in are
- How happy purchasers are with the price dynamics that emerge from the AMMs: volatility, fairness, rationality (do they make sense), dilution (under pricing), access (over pricing)
- How happy creators are with the price dynamics that emerge from AMMs: volatility, fairness, rationality (do they make sense), dilution (under pricing), access (over pricing)
- How happy are purchasers with the ease at which they can get exposure to creator assets at a decent price.
- How happy are early purchasers vs. late purchasers, is there any tension being caused by how the AMM operates in that market.
- How happy are creators with the fact that they cannot customize or control any part of their AMM? the bonding curve shape is universal and static.

**Comment by KubaMikolajczyk** [comment]
# Overview
Before approaching 1-1 interviews it was crucial to gather a deeper understanding of the AMM feature by reviewing available resources touching on this topic and in particular one implemented on the Deso blockchain.

# Key findings

🟢 Overall no major issue was found. There is little to no conversations touching the topic of AMM online (and creator coins in general) which can mean that the way it works do not cause any essential problems for the users. With that in mind below I mention few issues that I managed to find:

1️⃣  No option to whitelist the coin - one creator thought bots are driving the price of their coin - ended up selling everything
2️⃣  Price confusion - some creators seem to be unhappy that they loose money when the platform coin (DESO, RLY) looses value 
3️⃣  Easy to pull of scams - creator can buy into the coin and drive the price up and when others buy in the creator can sell it all and get profit.

➡️  Next steps: 1-1 interviews with both creators & holders.

## Content below is TLDR 🤌

# AMM
First of all, I needed to understand better the AMM itself. It's almost always mentioned together with the liquidity pool term which is different in our case as the way that the AMM is implemented on Deso does not require liquidity providers. An algorithm allows users to buy tokens with DESO and lock it in the token - each next token bought from this AMM is more and more expensive - which means that at some point minting even one token can cost millions of $. Its really well shown here:
![image](https://user-images.githubusercontent.com/31144205/169708398-9596d4e9-cc10-4f23-9f80-f533d86f135f.png)
![image](https://user-images.githubusercontent.com/31144205/169708404-461f3f24-2acd-4fed-93b1-e290bb82b6b6.png)
Some other well-known platforms that also implemented such protocol for exchanging two or more tokens are Uniswap, Bancor, Balancer, Kyberswap - but the liquidity on all of those are handled by liquidity providers who fill the liquidity pools with their own tokens and get % each time someone makes transactions using their pool.
As previously mentioned this is pretty different from the way AMM works on Deso and Rally. By buying the coin with the platform coin (DESO, RLY) user mints new coins and the price of new ones rises, when the user sells the coin the price will fall as demand shrinks no liquidity pools are needed.
Also if you are interested below are two bonding curves of tokens on rally - first is V1 and second is V2:
![image](https://user-images.githubusercontent.com/31144205/169708997-dcc24c3e-e28a-410a-8150-573f6a2fffa7.png)
![image](https://user-images.githubusercontent.com/31144205/169709021-bc07138c-5016-4dce-b85a-28e14a0031ce.png)

####
Sources:
https://www.youtube.com/watch?v=1PbZMudPP5E
https://www.youtube.com/watch?v=NwtyFM61K_k
https://docs.deso.org/about-deso-chain/readme
https://wiki.rally.io/rally-io/101/tbc

# Users thoughts on AMM

To gather user insights I decided to review a number of different sources such as reddit, github, twitter, user video reviews and others. On the first glance it looks like no one is talking about the AMM, while scanning the sources I found little to no conversations or even mentions of AMM - this can be a good sign that users do not share any issues and therefore do not encounter any issues connected with this topic.

With that said I found few issues that communities reported. One user reported that "bots" (or as we can assume - people unknown to this person) drove the price of his coin up. He expresses the discontent with this fact that he couldn't stop it and  had to set the revenue split in a way that 100% of income comes to him. 
![image](https://user-images.githubusercontent.com/31144205/169758267-6ff652dd-663a-44ae-91a0-2474f6f15acf.png)

Another one mentioned the discomfort that comes with the price of the creator coins being connected with the price of the platform coin (DESO) - because when one loses value the other loses as well.
![image](https://user-images.githubusercontent.com/31144205/169758709-0f80685e-7b41-4df5-ac37-00fd418d6627.png)

Different user thought that someone stole their money - from the conversation it looks like some other user bought into the creator coin of this person effectively rising the value of the coin and then they sold it. The user which is an owner of the coin probably thought that the 10$ valuation of the coin is the amount that was earned.
![image](https://user-images.githubusercontent.com/31144205/169759597-95634e34-ed0b-4bb3-85b6-98f84d312e96.png)

Beacuse there was almost no issues (nor praises) posted online I had to try myself and post some questions about user feelings on creator coins and AMM. 

On reddit one person responded saying that there was no issue with buying creator coins. This person also mentioned that the 3-4 first months were the most active and now CCs are not so hyped anymore.
![image](https://user-images.githubusercontent.com/31144205/169760403-f260d599-3c1a-4140-953b-76d1b7614af9.png)

On discord one person described as "status quo" that a creator should first buy in their own coin and after that the community will buy in as well and from here the market regulates itself.
![image](https://user-images.githubusercontent.com/31144205/169761332-58238be3-0d87-4680-a744-793899d48cff.png)

Other person tried to explain that the bonding curve is the thing behind the AMM and some users like it and others don't. They also mentioned that the new feature which is being implemented (DAODAO) will have a possibility to set a price manually without bonding curve.
![image](https://user-images.githubusercontent.com/31144205/169761984-a684de58-739d-47aa-bf45-b2281ad70916.png)
When asked about their feelings on this type of AMM the response was all positive
![image](https://user-images.githubusercontent.com/31144205/169762470-a73e38c5-5d70-47eb-b0a2-70c5025cd0ea.png)
The same user also mentioned their concern about the fact that the way this AMM is implemented makes it easy to cheat people. In short there is no vesting for the creator so one can pump some money into the coins and when other users buy in the creator sells it all for a profit.
![image](https://user-images.githubusercontent.com/31144205/169762671-fc045d2b-2c44-4357-8b06-fa32b84726ce.png)

**Comment by bedeho** [comment]
First off, really great work, love it!

> Also if you are interested below are two bonding curves of tokens on rally - first is V1 and second is V2:

- Are you saying that Rally uses a similar AMM style to Deso and what we are planning?
- Are you further saying that Rally supports multiple different kinds of curves which users can select among?
- What was reason for change from V1 to V2.

> On the first glance it looks like no one is talking about the AMM, while scanning the sources I found little to no conversations or even mentions of AMM

If you just searched for AMM, that may appear to be the case, but people may not even realise what this concept is. What we want to look for is discussion relating to the coin prices and how they change for various reasons.

> "Got immediately bum rushed by bots and opportuntists"

This is interesting. So we won't have this problem, because the way the creator obtains their own coin is by setting the initial issuance to themselves directly, but on DeSo you actually have to start buying up your own coins by paying with $DeSo, and even then you are competing with these bots.

> Another one mentioned the discomfort that comes with the price of the creator coins being connected with the price of the platform coin (DESO) - because when one loses value the other loses as well.

That is very interesting! In a sense, this seems like it should not happen in a rational market.

Lets say that the fundamental value of some $CRT is `p` in USD, this would be based on some forecast of the prospects for future revenue payments. Now, if the channel has a large holding of $JOY in the channel account, then I agree that this effect could take place, but even then, one woudl assume that most of the revenue lies in the future. This revenue is denominated in $JOY, but if $JOY itself drops, then one would assume that the value of that revenue in say $USD would still be the same, hence the price `p` would be the same. Now it is correct that the USD price of the $CRT in the AMM would now be reduced, but this should create an arbitrage opportunity for someone to come in and buy up underpriced $CRT until the AMM price matches the real price `p`.

Anyway, this is very interesting none the less.

I don't think we can do anything about this until we allow stablecoin integrations, and switch to having them as part of the channel balance.

> The same user also mentioned their concern about the fact that the way this AMM is implemented makes it easy to cheat people. In short there is no vesting for the creator so one can pump some money into the coins and when other users buy in the creator sells it all for a profit.
image

This is very intersting indeed.

Again we can sidestep part of this problem by allowing the creator to self-impose a schedule on the initial issuance, but of course we cannot _block_ the creator from buying from the AMM which does not have a schedule.

**Comment by KubaMikolajczyk** [comment]
> Are you saying that Rally uses a similar AMM style to Deso and what we are planning?
Are you further saying that Rally supports multiple different kinds of curves which users can select among?
What was reason for change from V1 to V2.

Yes. Rally implemented two different curves with V1 being this one
![image](https://user-images.githubusercontent.com/31144205/169821987-496109c0-e4cc-48cf-a892-a3a8bc682067.png)
it was designed for mid-size communities and allowed Coin prices to increase with lower Coin purchase volume required. More can be read here: https://wiki.rally.io/rally-io/101/tbc/v1
Then they changed it for this V2
![image](https://user-images.githubusercontent.com/31144205/169822253-c004d0b6-addb-4d29-a058-8b95e365b1c1.png)
a linear curve, was designed to support larger Coin holders communities, larger single-transaction purchases, and fractional liquidity pools. More can be read here: https://wiki.rally.io/rally-io/101/tbc/v2
Also it's worth knowing that: 
![image](https://user-images.githubusercontent.com/31144205/169822604-584393e9-c18a-4929-8101-af520b420067.png)

> If you just searched for AMM, that may appear to be the case, but people may not even realise what this concept is. What we want to look for is discussion relating to the coin prices and how they change for various reasons.

That is why I searched for AMM, bonding curves and creator coin topics in general because the word AMM is not widely used - creator coin is used a lot more frequently in conversations

> This is interesting. So we won't have this problem, because the way the creator obtains their own coin is by setting the initial issuance to themselves directly, but on DeSo you actually have to start buying up your own coins by paying with $DeSo, and even then you are competing with these bots.

I don't know if those were really bots - the user states that it might be bots - but the main problem here was that he didn't have a way to control who owns his tokens + no way to turn off the AMM

> Now it is correct that the USD price of the $CRT in the AMM would now be reduced, but this should create an arbitrage opportunity for someone to come in and buy up underpriced $CRT until the AMM price matches the real price

Yes there are upsides to this as well, but I can imagine from the creator POV when they see that the value of their token dropped instantaneously it might be disrupting

> Again we can sidestep part of this problem by allowing the creator to self-impose a schedule on the initial issuance, but of course we cannot block the creator from buying from the AMM which does not have a schedule.

And by schedule do you mean some kind of vesting for AMM? is that doable?

**Comment by bedeho** [comment]
From some of these charts, the bonding curve is in USD, not the native asset RLY or ETH or osmething? Is that correct?

**Comment by KubaMikolajczyk** [comment]
# User interviews

To gather deeper knowledge about users' thoughts on AMM and the bonding curve which is used on DESO I conducted 5 in-depth user interviews. Participants were recruited on DESO discords and on the DESO platform itself. Candidates were pre-selected by questionnaire.

-  Ideal candidate profile: user that not only actively buys other users' creator tokens but also has their own token which is bought by other users on a regular basis. 

 With that in mind, it's worth noting that 2/5 of users had little knowledge about AMM, the Bonding curve which didn't prevent them from successfully using it to buy and sell tokens, while 3/5 of users had extensive knowledge about it.
 
 # Wallets to pay
 We promised to pay $40 in bitcoin cash to those 5 wallets:
 qplwhdvxmqgrd376a2cv2ptdqpdd0g2y7cn4yq9lyp
 qqa3qymwtyj2t55y3aq8udww064tzj7tuc3htdf0m0
 qqtyutsnd4wsvjy5x9x5tnqa4fxzkrtceyx2wegypg
 qpaqss6dtelkq9x35gks6r54g3xktareauz4dnasel
 qqr0ppwcupd9nmqvvv5yqwsnfz9a9009jq0q0g9usv
 

# Key findings
🟢  Both buyers and sellers are really happy with the way that AMM works, set prices, and handles the sale for them. 
➡️. AMM is considered an easy way to start selling your coins
➡️  Rug pulls are the biggest threat in investing, locking/vesting mechanisms are required
➡️  Big aspect of investing is a social aspect of looking at who already invested in the coin
➡️  Creators don't want traders to buy their coin they want long term holders
➡️. Coins need more utility provided by the platform otherwise the only reason to hold them is to later sell them for profit.

If you want to know below I'm listing 16 more in-depth findings of AMM, bonding curve, and creator coins:

### AMM, Bonding curve & Creator coins
* Listed below are not sorted in order of importance.

1️⃣  5/5 users say that buying coins directly in AMM is smooth, flawless, and fast. Both experiences of buying into other people's coins and other people buying their coins were rated really high 8/10 on average. 

2️⃣  5/5 users think the price set by the AMM is fair and reasonable. 

3️⃣   Most of the users consider interacting with AMM as an easy task and while a few advanced users mentioned that it would be nice to set some things manually, the vast majority said that the fact that everything is automatic and they don't have to worry about anything lets them focus on more important things. Setting things manually is considered to be more difficult.

4️⃣   None of the users can recollect any disappointing experience connected with either buying or selling their coins through AMM.

5️⃣   All users say that using AMM is really easy and don't have to think about it too much. They like that all they have to do is to choose the amount of DESO coins they want to spend and the amount of Creator coins is calculated for them. It's also useful to see the DESO price in us dollars.

6️⃣   Few advanced users mentioned that while they understand the bonding curve and they overall like it - they think that it might be a bit too steep as people in the community complain that it's not good for the long-term projects. For example, after the price reaches a certain level, no one wants to invest in it anymore, because the graph becomes stagnant.

7️⃣   One of the factors for choosing the good token to invest in is the founders' reward (revenue split value) as something they would look at when investing in a coin, the less creator takes the better as this allows other users to earn. 10,20% is acceptable for most, some users say that 50% is the max they would invest in. One user said that when he wanted other people to sell his coin he set it to 100% to make them sell it.

8️⃣   Another thing that is important for users is who is the person/project they want to invest in and what it is all about. Those users who value the project itself do not care much about the price if they believe in the project they believe the price will only go up.

9️⃣   More experienced users pointed social factor of the coin as the most important thing that influences their decision whether to buy it or not. Even if they like the project and the person they have to check who owns the coin and see if those are the long-term holders or are those traders who just wait for the price to rise and sell their shares as soon as that happens. It's important to show people who invested in the coin on the coin page.

1️⃣ 0️⃣ Most users feel tension caused by the fact that if you don't invest early enough in the project it might be too late. If you invest early enough you will see the biggest return when the coin grows so the FOMO here is huge and the pressure is noticeable. Investing in late expensive projects is mainly considered a nice way to store the value but you probably won't make large profits.

1️⃣ 1️⃣ 5/5 users consider rug pulls as the biggest threat and disappointment of investing in a new coin. The way it's done is when the creator owns a lot of their own tokens and when other people buy into the token and the price of it is naturally higher than at the beginning (due to the bonding curve), the creator sells all tokens they own and makes money out of it. Then the value of the token drops and other holders lose a lot of money. 
- The problem here is that there is no other point in holding your own token than to sell it one day. 
- "Selling your own coins is like destroying your reputation."
- The way that traders try to avoid it is by not investing in coins where anyone has a big part of the coins.


1️⃣ 2️⃣ Locking/Vesting mechanism as a form of protection against rug pulls was brought into the discussion several times. Few users mentioned that this is a hot topic in the community and that investors want it so it would be safer to invest and creators want it less as they want to have more freedom with their coins.

1️⃣ 3️⃣ Some users mentioned both whitelisting & blacklisting as tools that they would want (as creators) to be implemented to allow them to choose who can and who cannot invest in their token. It would be also smart to allow creators to whitelist their coins for users who on average hold their coins instead of aggressive traders who are not considered good holders and those are the ones that creators don't want to invest in their coins.

1️⃣ 4️⃣  Discovery of coins and projects is a big problem. All of the users agree with the statement that there should be more ways to find interesting creators than only going to their profiles.

1️⃣ 5️⃣  Few users raised the concern that the only reason for buying the creator coin now is to sell them later. There is no other way users can spend those creator coins provided by the platform - this lack of additional utility leads ultimately to holders selling the coins they have when the token price rises - which in result causes the price of the token to drop.

1️⃣ 6️⃣  From the creator's perspective users lack ways to give additional utility to the holders and new buyers. Few mentioned are worth considering: personalized welcome message from the creator after purchasing the coin welcoming to the community, unlockable content after token purchase (or in Joystream's case unlockable videos visible only to token holders).

**Comment by mochet** [comment]
Nothing to add just yet, but just wanted to say to @KubaMikolajczyk that that is some extremely high quality research and insight.

There are multiple things highlighted here that are significantly valuable to know and help a great deal in understanding these users--not just for the AMM aspect of the DAO but many other aspects that are actually somewhat removed from that.

I try my hand at researching certain new users that join our community but I will now aspire to the fantastic standard that you've shown above. It's tremendously well done.

**Comment by bedeho** [comment]
# Feedback

This was _epic_, probably the best research I have seen yet, just amazing. I feel like we should do more of this when we can. I feel like I learned a lot here, lots of questions still, and not totally obvious what we should do or change, but at least we have a baseline to start from now.

# Remarks

> Both buyers and sellers are really happy with the way that AMM works, set prices, and handles the sale for them.

This was super encouraging to read, it def. confirms we should go for it.

> Rug pulls are the biggest threat in investing, locking/vesting mechanisms are required

So we have a remedy for this as well: self-imposed vesting schedules.

However, I wonder, should these be mandatory? Should the platform be able to _require_ a specific worst case schedule at any given time, which then can be updated over time as a matter of policy? This updating would of course mean that prospective buyers woul have to actually look at the schedule and figure out what the status is for each individual creator.

The alternative would be to just leave it as an option, and allow creators to self-select into the scheme they prefer, taking into account how their prospective buyers will evaluate the prospect of buying. Theoretically, this should be more optimal, as different creators have distinct liquidity requirements and also levels of credibility in their community.

**One question comes to mind: if there is rug pulls, does that mean that we are talking about fake accounts? what is happening here?**

> Big aspect of investing is a social aspect of looking at who already invested in the coin

Ok, so what does this imply for us?

>  Creators don't want traders to buy their coin they want long term holders

- Partially we solve this through having vesting on tokens in a sale, and also whitelists.
- **We could also introduce vesting on $CRT purchased from the AMM?**

>  Coins need more utility provided by the platform otherwise the only reason to hold them is to later sell them for profit.

I feel like we have some of this out of the gate: the revenue splits.
But we certainly can do more later, like 

- adding tools so people can gate their Discord using coin holdings.
- add a token holder only on-chain forum.
- add a token holder only content gating.
- change presentation of users in comment section, like a flaire or something: perhaps we can alreayd do that now?

_Added later: what about NFT revenue splits?_

> they think that it might be a bit too steep as people in the community complain that it's not good for the long-term projects. For example, after the price reaches a certain level, no one wants to invest in it anymore, because the graph becomes stagnant.

Important insight for us. Deso has a quadratic curve I think, so perhaps linear would be better in these terms.

@ignazio-bovo

> One of the factors for choosing the good token to invest in is the founders' reward (revenue split value)

I'm confused here, I don't think Deso has a revenue model for creator coins, does it? I don't see it here

https://docs.deso.org/about-deso-chain/readme#what-are-creator-coins-useful-for

_moments later..._

Ah found this

https://docs.deso.org/about-deso-chain/readme#nft-cashflows-to-coin-holders

So is this actually live?

> Even if they like the project and the person they have to check who owns the coin and see if those are the long-term holders or are those traders who just wait for the price to rise and sell their shares as soon as that happens.

This is very interesting, so how does this work, because surely most people would only know a very small subset of all other participants on the platform, and I can only imagine there are very very few funds or branded investors that people recognise? 

How is long-term holding recognized if there is no vesting (I assume there is no vesting?).

> Most users feel tension caused by the fact that if you don't invest early enough in the project it might be too late. If you invest early enough you will see the biggest return when the coin grows so the FOMO here is huge and the pressure is noticeable.

Is this again because the curve initially is very flat, and then explodes? If so, that would be a second reason to consider a more slow and gradual curve.

> Discovery of coins and projects is a big problem. All of the users agree with the statement that there should be more ways to find interesting creators than only going to their profiles.

This goes back to one of the earlier questions really: how are people picking these coins? I would have assumed that people only buy coins for people they already know and recognize as reputable for some reason, but this does not seem to be the case from what you are describing?

> Few users raised the concern that the only reason for buying the creator coin now is to sell them later.

But I thought there were cashflows, like stated above?

> The problem here is that there is no other point in holding your own token than to sell it one day.

Again, I thought there was cashflows?

> users consider rug pulls as the biggest threat and disappointment of investing in a new coin. The way it's done is when the creator owns a lot of their own tokens and when other people buy into the token and the price of it is naturally higher than at the beginning (due to the bonding curve), the creator sells all tokens they own and makes money out of it. 

Perhaps this means we should not focus on allowing the user to just issue a token with a gigantic crator token allocation, at least if not subject to vesting? instead what we want is to allow them to launch straight into a sale with newly minted $CRT, and any $CRT not sold would just be burned? That way the creator can use the event ro raise funds, but they would not be this huge liability for the community. Any other $CRT created during launch would be subject to a vesting schedule.

From one of the bonding curves shown for Rally, it seems like they had such a model with a sale that could sort of happen in the beginning.

**Comment by KubaMikolajczyk** [comment]
Thank you @bedeho & @mochet for your kind words - I'm glad that you liked my work 🙇

# Answering remarks
> So we have a remedy for this as well: self-imposed vesting schedules.
However, I wonder, should these be mandatory? Should the platform be able to require a specific worst case schedule at any given time, which then can be updated over time as a matter of policy?

I would 100% opt for it being optional thing. According to what users informed us during interviews - it would be nice to have it but it shouldn't be mandatory to use it.

> One question comes to mind: if there is rug pulls, does that mean that we are talking about fake accounts? what is happening here?

Rug pull does not have to be done by someone who is fake. It can be even a real person - it's the fake intentions that this person presents. If we would unpack the meaning of rug pull https://academy.binance.com/en/glossary/rug-pull - it can be a real project that just wants to cash out and decide to abandon it. So to answer the question - the account don't have to be fake.

>Big aspect of investing is a social aspect of looking at who already invested in the coin ; Ok, so what does this imply for us?

I will suggest focusing more on holders on a coin page and even creating some kind of statistic for each of them that would show how long on average they hold the tokens. This will allow both Creators to identify and even reward their long holders & for potential buyers it will be easy to decide whether the community is stable or are there only short term traders.

> I'm confused here, I don't think Deso has a revenue model for creator coins, does it? I don't see it here

Founders reward (FR) is the % that the creator gets from the purchases of their token - so if someone visit their profile on the platform and buys 10$ worth of their tokens if the FR is 50% the founder will receive 5$ as a reward.

> This is very interesting, so how does this work, because surely most people would only know a very small subset of all other participants on the platform, and I can only imagine there are very very few funds or branded investors that people recognise?
How is long-term holding recognized if there is no vesting (I assume there is no vesting?).

It doesn't work to be exact. Thats why its really easy to get cheated even if its not the intention of the creator, lets consider this scenario: Price of token is 5$, some short holder comes in and buys enough to raise token price to 100$, then other people buy in, and when the price reaches level high enough this holder sells everything.

To avoid that more experienced users use external tools to see those users trading history and they learn, learn, learn - memorise each user and their trading patterns. Even though there is some amount of users its not millions at the moment so they know each other. If someone doesn't know who trades how, or how to recognize short term traders they just loose money in a way I explained above.

> Is this again because the curve initially is very flat, and then explodes? If so, that would be a second reason to consider a more slow and gradual curve.

Yes I would say that overall users think its a bit steep and some more experienced ones described it as: unforgiving. Even the ones with little experience recognise that it's hard to earn a lot money by not investing early.

> This goes back to one of the earlier questions really: how are people picking these coins? I would have assumed that people only buy coins for people they already know and recognize as reputable for some reason, but this does not seem to be the case from what you are describing?

On DESO each person has its own patterns of choosing coins but it's rare that someone invests only in people who they know or knew prior to approaching their coin. They look at many things as the mission, the project, the benefits, FR(so in our case rev split), and who is holding this token. The most experienced participate we had possibility to interview told us he inspects holders of particular tokens and then if among those holders there is someone interesting he might consider buying from the newly discovered one as well. 

But! We have to acknowledge the fact that the discovery on deso is practically non existent and people have a really hard time of finding valuable coins & project while the whole platform is flooded with a lot of bots & scammers. 

Users who mentioned discoverability as a problem also mentioned that they wish there would be a section where DESO would display promising coins so it would be easier to find them.

>Few users raised the concern that the only reason for buying the creator coin now is to sell them later.
But I thought there were cashflows, like stated above?
The problem here is that there is no other point in holding your own token than to sell it one day.
Again, I thought there was cashflows?

You can get money as a holder when other people buy into the coin, but it's not a lot - or its not revenue big enough that users will not consider selling the tokens when the token price grows as this way they can make the most. 

If it comes to the creator it's even worse - most of our participant mentioned that 10% which is somewhere a standard for the share of the revenue for the creators is not enough to have a steady flow of income. And again it more profitable to sell your tokens when the price is high then to wait and accumulate money with "cashflows"

> Perhaps this means we should not focus on allowing the user to just issue a token with a gigantic crator token allocation, at least if not subject to vesting? instead what we want is to allow them to launch straight into a sale with newly minted $CRT, and any $CRT not sold would just be burned? That way the creator can use the event ro raise funds, but they would not be this huge liability for the community. Any other $CRT created during launch would be subject to a vesting schedule.

The allocation for sure has to be thought through very carefully. I worry that I did not understand fully your proposition here - it's worth to talk more about it.

> From one of the bonding curves shown for Rally, it seems like they had such a model with a sale that could sort of happen in the beginning.

Which curve you thought about? V1 or V2?

**Comment by traumschule** [comment]
Great research indeed. Above insights gave the idea to change the fundamental concept for CRT.

Would it help to switch from the "buy in" logic to "staking $JOY" for a particular $CRT?
That way no one would be able to just sell all and drop the price. What retail investors fear as rug-pull is actually inherent market logic: buy low, sell high. Now the question for us is if Joystream intends to be a trading platform.

If not what is it exactly that "we" want to reward participants for?
My first thought:
- invest in a creator / channel to express confidence in future high value publications and gain nominal $CRT balance
- become channel shareholder: staking significant amount of my $JOY to gain bigger fraction of future channel rewards
- daily unvested automatic cashout as passive income
- the more "market cap" a channel has, the higher is total daily minting
- anybody can unstake all their $JOY all the time which gives everyone else a higher fraction of daily cashouts
- this way no rug-pull is possible and $CRT holders are actually rewarded with slightly higher cashouts for others pulling out
- the actual $ value of my staked $JOY does not fluctuate much apart from $JOY market value = low risk to stake $CRT

Conclusion: no buying of $CRT just staking. Still participants would need to hold / buy $JOY to stake $CRT which will increase $JOY price long-term if platform manages to attract high-value creators.

**Comment by dmtrjsg** [comment]
@traumschule thank you for your contribution. I'm packaging your suggestion to a separate standalone issue to be triaged slightly later. The implications of considering this shift in implementation would inevitably impact Runtime and all downstream apps dramatically and we do not have the allowance to get working on it right away. Thank you for taking time and laying out your suggestion here, very valuable indeed! 💪 ⭐ 

Issue: 
- https://github.com/Joystream/atlas/issues/2941
