### ISSUE TITLE
Channel accounts 

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2873]
**AC:**

- [ ] Change the publisher variant of member dropdown to display the channel (and its balance)
- [ ] Create the withdraw modal
- [ ] Create the send fund modal 

**Out of scope:**

- [ ] Extrinsic integration
- [ ] Fee amount in the Dialog

---

# Background

In `Carthage` and beyond, all funds for a channel, that is from NFT sales, payouts, etc. will not land in a personal account hte user has in their wallet, but in a _channel account_. Currently we don't show this in Atlas, also, we do not allow the user to withdraw funds from this account to a personal account. The latter is a planned feature for the full `My PAyments` screen, but that will not land for a long time.

In response to a question about this from @toiletgranny I say

> I agree, its actually kind of surprising we did not think of showing the reward account for a channel in the UI more prominently before in the NFT release, there the account which people will consistently see is the membership account, and I would have expected them to be confused about it not increasing when they get NFT revenue. This is actually quite a big problem to not have. Introducing this could actually also create the space to solve the problem that Klaudiusz recently pointed out that there is no way to “claim” NFT revenue which in Carthage and beyond will no longer land in a personal account, but in a channel account.

# Proposal

Introduce a super cheap light weight way to show the channel balance, and allow user to withdraw from this into the user account, which we can ship from `Carthage`, and use until full `My Payments` lands.

**NOTE: It is pivotal to make this a _cheap_ intervention, as the lifetime for this will be a few weeks/months, and Carthage timeline is tight.**

**Comment by toiletgranny** [comment]
Alright, @kdembler, this is ready to be picked up. Here's a summary of what we need to do in order to address the above-mentioned problem.

1. Update the **Member dropdown component**, based on designs, docs, and changelog which [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=8357%3A162093) ![image](https://user-images.githubusercontent.com/35307309/175483925-35a68c10-2f16-43a8-a54b-76d1e7bc7851.png)
   - In a nutshell, we're making a change to display channel information in the "Header" section of the Member dropdown, when in the Publisher experience. This way we can display the channel's current balance, as well as a button link to open up the Withdraw dialog. The Member dropdown component in the Viewer experience remains mostly unchanged, except for the "Header" section, which now comes with the "Send" link button. 

2. Implement **the Withdraw dialog**, which is originally part of the My payments page (and the entire Channel payouts epic done by @TCzechowski), but needs to be implemented separately. Designs and docs for this dialog [can be found here](https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments?node-id=1547%3A19347). 
![image](https://user-images.githubusercontent.com/35307309/175486448-9ecbfb8a-514b-4b80-a960-12c3408bac40.png)

3. Implement **the Transfer dialog**, which we decided to include in the scope of this for the sake of keeping the entire user journey complete. This is to allow members to transfer JOY tokens the same way they can do that in Pioneer. Designs and docs for this dialog [can be found here](https://www.figma.com/file/uHzbhNX9dP4QtZbIapvZI6/Transfer-dialog?node-id=0%3A1). 
![image](https://user-images.githubusercontent.com/35307309/175486557-de46b0a0-7e90-4b0d-8408-a9716047d743.png)

cc @dmtrjsg

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2873?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow

**Comment by bedeho** [comment]
Keep in mind that you can withdraw to any random account, not just a member account, so you can't really display a member handle on the withdraw screen.

**Comment by dmtrjsg** [comment]
Yep, discussed exactly that just now, so this would only show for recognised members. Thank you for the comment @bedeho!

**Comment by toiletgranny** [comment]
@bedeho If you're referring to the Withdraw dialog, then the current design is based on the assumption that tokens on the channel account can be only withdrawn to the owner's member account, which is known, and therefore we can display a member handle and an avatar.

However, if your comment was about the Transfer dialog, then @dmtrjsg already clarified that the member avatar will only be displayed if the wallet address is associated with an existing Joystream membership. :)
