### ISSUE TITLE
Mobile user agent onboarding flow

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2903]
## Context
Mobile wallets are not supported in Polkadot

## Scope
* [ ] Adjust copy update for onboarding flow if user agent is mobile 
>(e.g. Before Polkadot JS signers support mobile, you can look but to do smth use desktop)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202496816781150) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
Alright, @bedeho, @dmtrjsg, @kdembler, my thoughts, ideas, and recommendations for this are ready to be reviewed! Find out all about it from:

- [This Loom video update](https://www.loom.com/share/e7c366c23fb5469592212062abda643c) (9 min at 1.5x speed)
- [This Figma prototype](https://www.figma.com/proto/zuDTBn9X87fUT8geRkCjIm/Mobile-user-agent-onboarding-flow?page-id=802%3A5523&node-id=1301%3A14097&viewport=-1058%2C166%2C0.75&scaling=scale-down&starting-point-node-id=1301%3A14097).

I'd be happy to iterate further on copy and visuals once we have a decision the direction we'll take with allowing or discouraging users from using Atlas on mobile.

![CleanShot 2022-09-29 at 18 09 24](https://user-images.githubusercontent.com/35307309/193082958-382e8b0f-8791-48cf-9db4-4b3f8817793e.png)

**Comment by dmtrjsg** [comment]
@toiletgranny I think we should inform users that better experience is achieved on desktop and offer share link as the first option. But also allow to install this wallet, for cases where bidding on NFTs / CRT revenue staking may be time-critical users may choose to go for it. Since this does not require us to do anything on the integration side, we should offer this option. It has benefits from marketing pov. Also big part of population in the developing countries are accessing the web primarily form mobile, while its unlikely we will be marketing there first, there may be benefits of supporting it (bar studio experience due to browser mismatch). 

so smth like:

Best experienced is on desktop.

Share to myself>

If mobile signer is required, here's the first few that support it:
-

**Comment by toiletgranny** [comment]
@dmtrjsg I'm afraid I don't know what you mean by:
- "bar studio experience due to browser mismatch",
- and "If mobile signer is required, here's the first few that support it". 

Anyway, unless I'm missing something from your comment, I think that's pretty much what I recommended there. But just to recap and say it back to you:
1. Upon clicking "Connect wallet" on mobile, instead of the regular sing in flow, you first get the _Best experienced is on desktop_ dialog, which encourages you to switch to desktop, while still offering a less prominent option to connect the wallet anyway.
2. The main CTA of the dialog is the "Share to myself" button that brings up the iOS/Android native share sheet, hoping to make it at least that much easier for you to switch from mobile to desktop.
3. Upon hitting that "Connect manually" button, the regular sing in flow is triggered, but instead of displaying the list of supported browser extension wallets that we get from Talisman, we display a hand-curated list of mobile apps that we know can be used to access your membership on Atlas.

I put together this refined prototype to be 110% sure we understand each other — [try it out here.](https://www.figma.com/proto/zuDTBn9X87fUT8geRkCjIm/Mobile-user-agent-onboarding-flow?page-id=1314%3A22951&node-id=1314%3A22993&scaling=scale-down&starting-point-node-id=1314%3A22952)

---

Assuming we all agree to move forward with this change, I have 2 follow-up questions:
1. @kdembler It makes perfect sense to display a list of mobile wallet apps you can install, when you open up Atlas in a standard mobile browser, such as Safari or Chrome. But once I actually am on, let's say, this Polkawallet, is this step really necessary, you reckon? I mean, if we can detect the user's entering Atlas from a wallet-encapsulated browser, couldn't we go straight into the account selection step in our Sign in flow? 
2. @dmtrjsg I haven't gotten any response irt the idea of doing a quick and possibly low-effort video walkthrough on how to export an account from a browser extension wallet and import it into the mobile app wallet (and in reverse). I would imagine having such a video linked in the Sign in dialog, making it a tiny bit easier to use Atlas on both devices simultaneously for less-technical folks, in case that's their first time using crypto wallets. What's your angle on this, worth the effort now?

**Comment by dmtrjsg** [comment]
@toiletgranny 

Prototypes are perfect, thanks that's exactly what I had in mind better executed 👍 

Re video, I'm not sure if it would be handy to import a json via mobile anyways unless you are next to your laptop, so my angle is majority would use a seed phrase to import.. it is not ideal, but I'd just watch them struggle before we add any enhancements. For the time being I think what you have cooked is perfecto 👌

**Comment by kdembler** [comment]
> if we can detect the user's entering Atlas from a wallet-encapsulated browser, couldn't we go straight into the account selection step in our Sign in flow?

I think we should still offer wallet select, as the user may still somehow have multiple extensions. We also handle wallet connect and loading in this step.

I would put little less emphasis on "Share to myself" in this "Best viewed on desktop dialog". I think with the current designs it's actually a bit too hard to proceed. I would give users a warning that this experience will not be ideal but let them connect smoothly anyways

**Comment by toiletgranny** [comment]
@dmtrjsg Ok, awesome! Re video: sure, got it!

@kdembler While making it harder for you to proceed on mobile was kind of the point, I get it I might have gone a bit too far with this direction. 😅 Hopefully, tweaking the copy and swapping buttons order should do the job. Since the copy got a bit lengthy, I came up with this new custom illustration to make the dialog a bit easier to scan visually and figure out what it's about.

[Here's the end result](https://www.figma.com/proto/zuDTBn9X87fUT8geRkCjIm/Mobile-user-agent-onboarding-flow?page-id=1324%3A23298&node-id=1324%3A23299&viewport=623%2C195%2C0.47&scaling=scale-down&starting-point-node-id=1324%3A23299), and — hoping you're satisfied with it — I'll now proceed with finalising it.

![CleanShot 2022-10-03 at 14 23 28](https://user-images.githubusercontent.com/35307309/193575698-48ae57f3-5bc0-4a88-9e8c-5ccc43129aaa.png)

**Comment by kdembler** [comment]
Looks nice!

**Comment by toiletgranny** [comment]
Ok, cool! It's all ready to be reviewed and implemented then. Here's what's changed:

- Designs, docs, and changelog for the Sign in dialog component [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6322%3A126310)
- Designs, docs, and changelog for the updated mobile Sign in flow [can be found here](https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-in-flows?node-id=1284%3A11692).

Please, make sure to go through all changelog lists, flow descriptions and new component documentation bits.
