### ISSUE TITLE
Replay button unnecessary centered on mobile

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2916]
![Screenshot 2022-06-27 at 12 41 36](https://user-images.githubusercontent.com/12646744/175923647-1cd9de58-bd2f-4f86-8adb-cbb8229c2d92.jpg)

Look at the button in the control bar at the bottom. This only applies on mobile and I'm sure is related to this piece of code: https://github.com/Joystream/atlas/blob/3bcc79f53837414dcf27b6ee5c84fb32572b82f1/packages/atlas/src/components/_video/VideoPlayer/VideoPlayer.styles.ts#L144-L151

**Comment by drillprop** [comment]
Hmm, Im not sure if I remember correctly, but I think this was intentional. 
In the design, there was no button here at all, but in the end, we decided to add that.  Once a video is done and a channel has at least two videos, the user will see an overlay where he could go to the next video: 
![image](https://user-images.githubusercontent.com/51168865/175932341-e3a9f06a-eb81-46e2-bbdb-feeef8af69e5.png)
If we remove this button, the user won't have the possibility to watch the video again. That's why we placed the replay button here. 
cc @toiletgranny 

Also, I think you're wrong about the code - `@media (hover: hover)` is applied only to devices where it's possible to hover, i.e. desktops.

**Comment by kdembler** [comment]
Yeah but shouldn't the button be on the left as it is on desktop?

**Comment by drillprop** [comment]
We would need to move the timestamp to the right once the video is done. The controls are centered on mobile: 
![image](https://user-images.githubusercontent.com/51168865/175934529-ea53c213-4cf9-48eb-82dc-4338d3c3d61e.png)
That would result in a layout shift.

**Comment by kdembler** [comment]
ah okay, I'll close then, thanks
