### ISSUE TITLE
High CPU load when starting auction

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#2956]
I tried the recently updated atlas and wanted to start an auction for one of the NFT i own. When i click to see tooltips and change options the app seemed to freeze and did not recover for minutes. Had to close the tab.

![atlas-cpu](https://user-images.githubusercontent.com/31551045/177007837-755748c5-8b4e-4dfe-a971-39b0e73439d4.png)

CPU: Intel(R) Celeron(R) N4020 CPU @ 1.10GHz (2 cores)

**Comment by drillprop** [comment]
Hey, @traumschule, thanks for creating the issue. Could you share more information? 
How frequently does it happen?  Could you provide exact steps on how to reproduce this?
Works fine for me, I didn't experience a drop in performance on this step.

**Comment by dmtrjsg** [comment]
We triaged it with the broader team and arrived to the conclusion that this issue is not actionable for the time being, and in the light of the road to mainnet priorities there is no bandwidth to unpack it. 

Closing on this basis, and if the issue / similar issues re-occur please raise it and I will connect with this issue to address these cases holistically. 

Closing for now.
