### ISSUE TITLE
Channel Balance for public view

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2981]
channel balance for public view

Is super important. It should be very prominent.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202570962318926) by [Unito](https://www.unito.io)

**Comment by KubaMikolajczyk** [comment]
Exploration for channel balance 👇
🎥 Loom video (Channel balance starts at 19:15): https://www.loom.com/share/5595fb504d334ad99ac9478b2cf22810
📄 Figma files: https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1412%3A83542

**Comment by bedeho** [comment]
Thank you for this iteration @KubaMikolajczyk , a pleasure to review as always <3. Also let me commend you on all the variations you have tried and all the effort and evaluation that went into that, it really shows.

1. I really _love_ the clean menu free view, lets keep that.
2. Many of the header shots were really beautiful and compelling, but I think the last one indeed brought home the message as well. The one thing I would be concerned about would be whether people would discover that this center-line is adjustable, and whether everyone will understand what it means. I think this is not a blocker at this point, lets go with the last one you proposed.
3. Combining the examples with the focus of the section really made most sense, so other verified creators with the header, and recently paid with the rewards.
4. Steps section was really great, not sure you even need the detailed visuals, just focusing on the steps and a short title can bring the message home clearly.
5. On the channel balance subject: I think that it probably does deserve more attention than the final location you advised, its arguably more important than the set of NFT collectors for the channel. I also think that it may need a bit more space than you have chosen, because I suspect it may need a label. Simply showing a balance leaves a little bit too much unsaid for the large number of users who are going to be new to the whole idea of a channel having a balance, and what that even means.

**Comment by dmtrjsg** [comment]
@bedeho just a few points of consideration on point 5, perhaps that may win you over to starting with a version that Kuba has suggested. Perhaps increase the size/ and have a slightly offset positioning from its exact one, in the last variation but overall I think this may actually work well 🤞 

> more attention than the final location you advised.. more important than NFTs

I think this location is beneficial from the pov of replicating it in the Channel Info section on every video posted by this channel. If we agree that it is beneficial to include it there, here are my two suggestions where that would look not out of place and easily discoverable: 

<img width="827" alt="Screenshot 2022-08-01 at 17 14 09" src="https://user-images.githubusercontent.com/93924525/182194829-c4ffbeea-acc6-4842-a96b-c8d80504bd54.png">

> leaves a little bit too much unsaid for the large number of users who are going to be new to the whole idea of a channel having a balance

With an on-hover or more explicit tooltip we could try and do it without the label, and a quick test will reveal if that's not discoverable.. Tooltip allows to benefit from adding some explanation to the context behind it, and even mentioned "Revenue share" and "Creator Tokens" Features, which are exciting for the viewers.

**Comment by KubaMikolajczyk** [comment]
Following the feedback above I created another iteration for the channel balance. I decided to go with the suggestion to showcase it both on the channel page and the video page next to the channel & tried to show it with label & without - all of those exploration can be seen in the file here: https://www.figma.com/file/A1JMVHIbL3gBUtyDv4XFwx/Channel-balance?node-id=1101%3A103866
Or in the screenshot below:
![image](https://user-images.githubusercontent.com/31144205/187173836-7f6b8cda-6cb7-46dd-8a6d-af28685d9245.png)

But in the end after discussing it with Adam we came to the conclusion that having no label can create a feeling of confusion so my final proposition would include the label as well 👇 
![image](https://user-images.githubusercontent.com/31144205/187174099-c58f5072-a003-47f1-83fb-be6fc817bd50.png)

Please let me know what you think.

**Comment by dmtrjsg** [comment]
Thanks guys, iteration 3 works well 👍

**Comment by kdembler** [comment]
@KubaMikolajczyk let's finalize those designs and also prepare a mobile version 🙏

**Comment by KubaMikolajczyk** [comment]
✅ Done - while finalizing I proposed a to shorten the label and show only word balance there as we are already viewing it on a channel page - really short update 
🎥 Final walkthrough : https://www.loom.com/share/e9790e83f04642eabdf8fa6bd904af0c
📄 Figma changelog: https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1624%3A85414&t=O0awrzDiEdpc6AoP-4

**Comment by bedeho** [comment]
Short and sweet! Looks good to me 🖖
