### ISSUE TITLE
Carthage testing

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2998]
We need to test all the major flows in the app after Carthage to notice any possible issues:
1. Creating membership
2. Creating/editing channel (with and without assets)
3. Create/editing video (with and without changing assets)
4. Minting and putting NFT on sale (with different params, try out whitelisting, end dates, etc)
5. Buying NFT (buy now), participating in NFT auction
6. Settling NFT auctions
7. Comments and reactions (all the associated actions)

**Comment by drillprop** [comment]
1. Creating and editing membership - works fine with Polkadot and Talisman extension - ✅ 
2. Creating/editing channel
   1. ~Creating a channel with and without setting assets not working correctly at the moment. You can create a channel but the channel id was not set properly in local storage. The user needs to change channels manually in the member dropdown. I created a PR that will fix this #3014 ➖~ Creating channel works with and without setting assets ✅  
   2. Editing channel works just fine without updating assets ✅ 
   3. Setting new assets - cover, and avatar not working - there is a bug with mappings. And as far as I know, Zeeshan is preparing a fix. ➖ issue: https://github.com/Joystream/atlas/issues/3010
3. Creating/editing video 
   1. Creating video works, without mint NFT checkbox checked and with different parameters. **One important note** - selecting video categories are disabled for now because we don't have categories available in Carthage testing QN. I'm not sure how we will fetch categories in the future. ✅ 
   2. Creating video works with mint NFT checkbox checked ✅ 
   3. Editing video work without changing the thumbnail ✅ 
   4. Editing video thumbnail is not working. Same issue as `2.3`. Zeeshan is preparing a fix ➖ issue: https://github.com/Joystream/atlas/issues/3010

**Comment by rafalpawlow** [comment]
4. Minting and putting NFT on sale (with different params, try out whitelisting, end dates, etc)
    * Minting is working ✅ 
    * Starting sale is fully working for all combinations. However there is a bug when you type too hight number in input #3018   ✅
5. Buying NFT (buy now), participating in NFT auction
    * Buying NFT is working ✅ 
    * Participating in NFT auction is working ✅  
    * Changing price is working ✅
    * Selecting bid is working ✅
6. Settling NFT auctions
    * settling NFT is working ✅
7. Comments and reactions (all the associated actions)
    * reacting to video is working ✅ 
    * reacting to comment is working ✅
    * commenting is working ✅ 
    * editing comment is working ✅
