### ISSUE TITLE
Update Atlas Branding

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3021]
## Context
* #2959 

## Scope
- Exploring and discussing together that capital "A" alternative version
- Updating components & flows:
   - [Adding Atlas logo as a component here](https://www.figma.com/file/Cc3VDoK6qglJ617ChA2EMr/Foundation?node-id=716%3A70391),
   - [Updating the top navigation component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=3173%3A135755),
   - [Updating the Side navigation component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=4322%3A173750),
   - [Updating the Sign in flow](https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-in?node-id=0%3A1),
   - [Updating the logo in the embedded variant of the Video player component](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2090%3A120662).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202652214192092) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
@kdembler Here we go!

1. The new logo can be found and exported from the [Foundation figma file](https://www.figma.com/file/Cc3VDoK6qglJ617ChA2EMr/Foundation?node-id=716%3A70391), where you can also find favicon examples. 
2. Components to be updated, based on the scope outlined in changelogs (to which I'm pasting links below) are:
   - [Side navigation](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=9151%3A168502),
   - [Top navigation](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=9151%3A168457),
   - [Member dropdown](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=8357%3A162093),
   - [Video player](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2583%3A230865) — no changelog here, as we haven't updated this component's documentation to the new standard, but the only change here is logo in the controls bar, in the embedded variant.
3. I believe it makes sense for me and whoever will be the lucky engineer to get assigned to this to jump on a quick call on Slack and discuss the following:
   - finding all instances of the name "Joystream" in text, in code, and deciding whether it needs to be replaced with the "Atlas" name,
   - how should we tackle updating logo assets in the [Figma API -> Storybook](https://www.figma.com/file/1uxugLps6oooI38PGmdrn9/Figma-API--%3E-Storybook?node-id=1007%3A310) Figma file, so that we don't hurt no one or break anything?
