### ISSUE TITLE
Additional messaging to new accounts creation (faucet)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3038]
**Scope:**

- [ ] Introduce Snackbar informing user about received JOYs after they create a membership: https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-in?node-id=1277%3A30169

---

Context:
- https://github.com/Joystream/atlas/issues/2969

Scope:
Add messaging and placement of captcha to the new accounts flow

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202676405083232) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
Ok, @dmtrjsg, @kdembler, a few questions to help me get started:

1. I did some digging into other GH issues around this subject, and please let me know if I'm correct to assume we'll be indeed moving forward using [hCaptcha](https://www.hcaptcha.com/)? 
2. In the UI, do we intend to somehow distinguish the balance of tokens received from the faucet, upon JS membership creation, from the balance of tokens that can be used without limits? Since faucet tokens can not be spent the same way as regular ones, I'm assuming we won't be adding them to the user's account balance we display in the Membership dropdown in Atlas, right? 
    - This will certainly introduce some complexity to UX/UI, so I think this should be considered carefully.
    - If the amount of faucet tokens is very small and insignificant, would it make sense to omit the faucet tokens balance entirely in the Atlas UI?
    - I remember you @dmtrjsg asked me to explore a similar-sounding concept a while ago, but we decided to pause this for reasons I can't remember. Could it be related? [We had quite a lot of iterations, I remember.](https://www.figma.com/file/YKEUOEIVcSnzzny3KlhXym/Web-Components-Playground?node-id=401%3A136981)
![image](https://user-images.githubusercontent.com/35307309/182879385-ef115070-d10b-49b7-b34e-1775a28815bf.png)
3. In his proposal in #2969 @bedeho suggests adding "some very clear big visual that sort of says 'you will get some tiny amount of free coins, but you can only use them for fees, not transfer or selling, that wont work'". I just wanted to confirm whether the purpose of this message is mainly to give potential abusers a heads up that their shameful intentions won't really work. Or is there some other purpose for that?
   - I'm asking about this because I'm afraid that if we get too hung up on making this warning too prominent, it might appear suspicious to other people. As in sending a message that sort of goes like "hey, watch out! not only you're about to enter a web3 space (which is already known for being full of scammers) but you're also about to get treated like one".

**Comment by bedeho** [comment]
> do we intend to somehow distinguish the balance of tokens received from the faucet, upon JS membership creation, from the balance of tokens that can be used without limits?

Sounds wise.

> If the amount of faucet tokens is very small and insignificant, would it make sense to omit the faucet tokens balance entirely in the Atlas UI?

I focusing on one total balance is simplest and best. I think it is important to make sure someone sees an accurate total balance, because when they cross-reference with other applications/sites they would otherwise get confused. Then showing a much smaller and less prominent indicator of locked balance could be fine. If the total balance == locked balance, then perhaps you want to show something a bit more prominent about all funds being subject to a lock, but not even sure its worth the complexity. Ultimately I think the primary occasion to remind the user about the lack of free funds for some purpose is when they are attempting to do this specific action (e.g. bidding), and running into this limit.

> I just wanted to confirm whether the purpose of this message is mainly to give potential abusers a heads up that their shameful intentions won't really work. Or is there some other purpose for that? 

Correct.

> but you're also about to get treated like one

:D

**Comment by kdembler** [comment]
> if I'm correct to assume we'll be indeed moving forward using [hCaptcha](https://www.hcaptcha.com/)?

Yes. You can see the POC here: https://atlas-git-dev-joystream.vercel.app/playground/captcha

> I'm asking about this because I'm afraid that if we get too hung up on making this warning too prominent

While I agree it should be visible, I wouldn't make it too prominent, just a part of UI. Captcha will be our main defense against abusers anyway

**Comment by toiletgranny** [comment]
@dmtrjsg @kdembler @bedeho Alright, thanks a lot, guys, for all the answers. That's really helpful. As we don't have much time we could spend on this, as I can imagine, here's a quick 10 min video update with my recommendations. Looking forward to hearing your thoughts on this. https://www.loom.com/share/beacdf8c7d0f4ffcaf737aea84636e2c

Figma prototype link is here — https://www.figma.com/proto/2Snx8rlijd8iD6btfbtY6j/Additional-messaging-to-new-accounts-creation-(faucet)?page-id=802%3A5357&node-id=1103%3A21603&viewport=87%2C459%2C0.15&scaling=scale-down&starting-point-node-id=1102%3A8864

**Comment by kdembler** [comment]
Thanks for the update Adam, there's a couple of things to unpack here:

**Captcha**
I agree that the no-captcha solution is the best - less friction, less styling etc, **but** to access no-captcha version we need to pay 100$/mo for a plan, the regular version is free. Maybe it's worth to start off with the basic "captcha-captcha" and potentially invest in the paid plan in the future if the solution works fine overall?

**Messaging**
I like the "gift message" snackbar, I would go with that 👍 

**Locked tokens**
One issue that may not be instantly obvious is that locked funds actually don't get spent first to cover transaction fees. If you have both free and locked tokens, seems free tokens are spent first.

I think we may need some other improvements to display of token balance (member and channel), I think exploring showing both member and channel balance could be beneficial. Maybe it makes sense to make this ticket only about captcha&messaging in member creation flow and tackle locked funds separately, taking more holistic view?

**Comment by toiletgranny** [comment]
Thanks for your feedback, @kdembler!

**Captcha**
Oh, noes. Sorry I totally missed it's a paid feature. Of course, I'll proceed with the captcha widget.

**Messaging**
Oh, great! 👍 

**Locked tokens**
Oh wow, somehow I just assumed it has to be the balance of the locked tokens that is spent first, and not the other way around. The way you explained now... Yeah, I think it makes a lot of sense to tackle it all together with that other issue we want to discuss around displaying balances. cc @dmtrjsg

**Comment by toiletgranny** [comment]
Ok, @kdembler, designs and changelog for the updated Sign in flow [can be found here](https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-in?node-id=1284%3A11692).

![image](https://user-images.githubusercontent.com/35307309/183678423-bf6b3ac1-0eae-48cd-9198-cce82c953938.png)

cc @dmtrjsg, [based on this Slack discussion](https://joystreamworkspace.slack.com/archives/C03A9SE8197/p1660049763433739), I took the opportunity to make a few updates addressing potential Joystream/Atlas branding confusion. The exact list of changes can be found in the changelog linked above.

![image](https://user-images.githubusercontent.com/35307309/183679303-fe18dcc1-1c4a-4b7d-b16b-39d37a09875f.png)
