### ISSUE TITLE
Improve "Welcome to Studio" screen

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3092]
On [signin screen](https://play.joystream.org/studio/signin), which now will be destination from main screen, we use old illustrations which I think are far inferior to what we now have on the landing page. Can we replace?

![Screenshot 2022-08-08 at 13 06 52](https://user-images.githubusercontent.com/437292/183404421-b1c25978-9ac8-4e73-b9c6-a4d01ae98a1a.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203003530215165) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Also,  " How it works" sort of does not do anything useful here now, it just sends you back to the main site. 

![Screenshot 2022-08-12 at 08 52 17](https://user-images.githubusercontent.com/437292/184300363-aba2487c-290c-4ed5-8bff-342eefa90563.png)

**It sort of begs the question: if what we want people to do here is to "connect wallet", and most people probably wont even have a wallet, is this the right page for them to land on?** Seems like this page needs to be refocused on getting a person wide variety of people to "claim their channel", most of which will be outsiders with no wallet, and perhaps not even understanding what that means? Next thing I see as a newcomers is this, which may be just too cryptic, more handholding is needed

![Screenshot 2022-08-12 at 08 55 40](https://user-images.githubusercontent.com/437292/184300853-3fb77862-d464-4d72-883a-53e664b41e3b.png)

**Comment by kdembler** [comment]
Fully agreed. We didn't foresee this screen as a landing from a marketing website so definitely needs a refresh. We probably should focus on this flow:
1. Web2 creator heard about Joystream
2. They go to joystream.org
3. They like what they see
4. The click "Claim channel"
5. They go to this page, currently probably quite confused as to what is even going on

**Comment by bedeho** [comment]
Is the only way you get here "claim channel"? Say I first land on the YPP page, perhaps referred by a friend or something, and I am starting the flow to create a channel, do I cruise by this page then also?

**Comment by kdembler** [comment]
Regarding YPP, that's actually a good question, I don't think our designs include a flow for when the user doesn't have a membership yet, they only include a case for creating a channel.

You can also get to this page if you create a membership in Atlas viewer and go to Studio but you don't have a channel yet. Then you see this screen with "Create first channel" instead of "Connect wallet"

**Comment by toiletgranny** [comment]
@kdembler I'm currently in the process of going through @KubaMikolajczyk's final designs for YPP, and I can see there is a user story for handling not signed-in users. You can see it here: handling

In a nutshell:
1. Clicking on "Authorize with YouTube" will first prompt you to connect wallet and create membership (if you don't have one already). A reminder tall of that takes place in a dialog, so you're not redirected outside of the YPP LP,
2. Having your membership created you're supposed to be redirected to the channel creation flow instantly,
3. Having created your first channel, you're prompted to authorize with YouTube again with a "Heard about YouTube?" dialog  (this heading is most likely to be changed). This will initialize the flow of YT channel authentication (?).

**Comment by toiletgranny** [comment]
Alright, @bedeho, @dmtrjsg, @kdembler, my recommendations for the new "Welcome to Studio" screen, as well as a few more tweaks around the flow of setting up a membership and creating a channel, are ready to be reviewed! Find out all about it from:

- [This Loom video update](https://www.loom.com/share/f3e6a37be9cb4f45a35ef55784cceebd) (~8 min at 1.5x speed)
- [This Figma prototype](https://www.figma.com/proto/XTEw20c32ssifL0cShd3yG/Improve-%E2%80%9CWelcome-to-Studio%E2%80%9D-screen?page-id=1234%3A68800&node-id=1234%3A68811&viewport=-3922%2C83%2C0.38&scaling=min-zoom&starting-point-node-id=1234%3A68811).

**Comment by dmtrjsg** [comment]
Excellent work ⭐ 

All made sense to me including the YPP. Loved it how you looked at the end to end journey with pre and post screen considerations, very well done 🎩

**Comment by kdembler** [comment]
Looks sweet! The only feedback I have is about redirecting users directly to channel creation after they create their membership. What I like about the current flow (Click "Connect wallet" -> Create membership -> Back to "Welcome to Atlas Studio" -> Click "Create first channel") is that you deliberately click "Create first channel" so you understand what is happening and where in the flow you currently are. I'm afraid that taking users to this create channel view right after they create a membership, they may be a bit lost as to what is this form supposed to do. WDYT?

**Comment by dmtrjsg** [comment]
Actually its a fair point, Klaudiusz, the transition is sharp! ..but in terms of solution perhaps we could explore adding some sort of a prompt to the user for the empty channel view? Thinking from the pov of in general dropping every extra non-mandatory step impacts conversion rate positively.

**Comment by toiletgranny** [comment]
Thanks, @dmtrjsg, @kdembler! I see what you mean guys, and I agree that this could be a problem. Maybe not a huge one, but let's see what we could potentially do instead. I recorded a video update to show it to you: https://www.loom.com/share/27cdb0eb49a94f0c8be630f14bdd1e9e

Which option would you like me to finalize? A, B, or C (my recommendation)?

**Comment by kdembler** [comment]
I'm fine with any of those, maybe @dmtrjsg has some preference, otherwise let's go with your recommendation

**Comment by dmtrjsg** [comment]
My recommendation was to just skip the whole coming back to the same page and go straight to default channel edit (screen in the end of this comment) view with some messaging to entice and complete the journey since I was looking at it from the creator journey perspective. 

Now I get that not everyone would like to do so and a big portion of audience would want a membership to purchase NFTs / CRTs but not content production. 

For that reason I think **it's safe to go with scenario A** animation here doesn't add much from my _personal perspective._ Change of copy does the trick :ok: My second choice would be B, so CTA in the modal. Blinkingi animation didn't work for me personally and I think user will hardly get confused on the screen with a single CTA.

On a slightly tangential note, how does user go to Viewer side if they don't want to complete this journey, only browser back button, right? Was this deliberate to minimise drop off on this step?

<img width="1486" alt="Screenshot 2022-09-23 at 15 11 21" src="https://user-images.githubusercontent.com/93924525/191957711-6ad050e2-1785-4d5d-bf6d-79783e6068ef.png">

**Comment by toiletgranny** [comment]
> Now I get that not everyone would like to do so and a big portion of audience would want a membership to purchase NFTs / CRTs but not content production.

@dmtrjsg  Not necessarily in this particular context. Let's keep in mind you're having your membership created only because it's required for you to have a channel, which will most likely be the initial and ultimate goal of the majority of users clicking on the "Get started" button (see the screenshot below). 

> For that reason I think it's safe to go with scenario A [...]

✅ Will proceed with finalizing option A then.

> On a slightly tangential note, how does user go to Viewer side if they don't want to complete this journey, only browser back button, right? Was this deliberate to minimise drop off on this step?

Yeah, I noticed this problem, too. As of now, with the current design and implementation, if you are redirected here from the Joystream.org website, clicking the back button would take you there, not the Viewer experience. That's why, in the new designs I've been showing to you here, I added the "Go to Atlas" button. Please, let me know if this was unclear to you when you looked at the new designs.

![CleanShot 2022-09-26 at 08 25 44](https://user-images.githubusercontent.com/35307309/192207375-f868ce88-bd2f-4bb8-9ad2-756f4986b14f.png)

**Comment by toiletgranny** [comment]
Alright, @kdembler: 
- The updated CTA for the YPP LP for a signed-in viewer with no channel created [can be found here](https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=2544%3A76203).
- Designs, docs, and changelog for the new Welcome studio screen [can be found here](https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-in-flows?node-id=1284%3A11692). 
   - ⚠️ To whoever is the engineer implementing this, please, reach out to me to discuss implementation of onload entrance animations for the copy and app screen illustrations, thanks!


![image](https://user-images.githubusercontent.com/35307309/192811729-6d145377-2e02-4ff8-b46b-55a83fc1e1d9.png)
