### ISSUE TITLE
Poor handling of failed uploads

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3130]
### Problem
If you publish a video and some of its assets fail to upload, you will see this in `My uploads`:

![](https://user-images.githubusercontent.com/12646744/185357259-da79a855-9e92-429d-9cad-f388b0b3ad76.png)

Then, user can reconnect the file and try to upload again. However, if they don't have the file available or some other problem occured, they may see the following modal:

![](https://user-images.githubusercontent.com/12646744/185356932-cc4ca148-4aaf-469b-a140-0e72955055d3.png)

There are some issues with the above:

1. We don't offer an option to just close the modal and don't take any action. You are forced to either edit the video or try selecting the file again. This can be frustrating to the user. Because of the current implementation, if you click Esc, it its equal to clicking the secondary button in the dialog and results in opening the video workspace.
1. The "Edit video" option actually doesn't work - it just opens an empty video workspace and you cannot edit the video in question - implementation issue
1. I'm unsure if the "Edit video" option makes sense if we are talking about media files. Even if it worked, we currently don't allow editing the media file inside Atlas, only the thumbnail. So you still wouldn't be able to fix the issue

### Proposal
I think we need to refine this flow as uploading assets will be one of the most fundamental actions creators will take on the platform and we need to make sure that everything works smoothly. Fixing first point is probably quite easy with some basic design treatment and improving the implementation. Second point is purely technical. When it comes to the third one, I suggest we allow editing the media file if its upload has failed. Maybe it's also worth taking a more holistic look at the issue, maybe there are some other improvements we could do.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202882567635505) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
@dmtrjsg I think you meant to move this to design sprint backlog, not dev sprint backlog?

**Comment by dmtrjsg** [comment]
yes absolutely, thanks  for the pointer ;) @kdembler

**Comment by toiletgranny** [comment]
@kdembler A few noob questions:
1. Actually, why can't I select another video file? 
2. What file is considered the same one as the original? Is it the name that must mutch (but the video can be of a different format, or length), or is it something else?

**Comment by kdembler** [comment]
1. You mean, like in general? I think it was a product decision to not allow changing the video once you initially publish it. My suggestion from the original issue was to change that so if the upload failed, we allow that. Are you suggesting we allow editing the video file in general?
2. It has to be exactly the same file, as in, all the contents are exactly the same. File name doesn't matter, to compare we read bytes contents of the file and calculate its checksum to validate it's the same thing.

**Comment by dmtrjsg** [comment]
+ Thumbnail handling error does not have Edit CTA,  if doesn't get uploaded but video does.
+ worth enabling editing video from video detail view

**Comment by dmtrjsg** [comment]
Here;'s the screen of the error for Thumbnail:

<img width="524" alt="Screenshot 2022-09-22 at 14 02 29" src="https://user-images.githubusercontent.com/93924525/191730340-8fb357a6-69e6-4704-8278-f7816bd68f17.png">

**Comment by toiletgranny** [comment]
Alright, @dmtrjsg, @kdembler, my recommendation for tweaking the flow of reselcting the uploaded file, as well as a few other UX/UI design tweaksd, are ready to be reviewed! Find out all about it from:

- [This Loom video update](https://www.loom.com/share/fbf74c36f1054d52bb2ce6c7d7a5d2a8) (~7.5 min at 1.5x speed)
- [This Figma prototype](https://www.figma.com/proto/Pe1Y0nrl4mpHWs7AkuQOk5/My-uploads-page?page-id=321%3A203&node-id=1102%3A4452&viewport=391%2C119%2C0.11&scaling=scale-down&starting-point-node-id=1102%3A4274&show-proto-sidebar=1).

**Comment by kdembler** [comment]
Thanks for the update @toiletgranny! I like the new flows, but have few thoughts:
1. I think we should be more explicit about what happens when you try to upload a different file. Current designs just say "You will need to sign a blockchain transaction" and from the user POV this looks like they need to pay to upload the file (also `Upload file` button), when in reality, you actually pay for editing the video instead. I would tune the messaging to give the user a better understanding
2. One additional case we need to account for is videos that have NFTs minted. Remember that those cannot be edited currently (that includes changing any of the assets), so unless the user provides the exact same file, they will be blocked from proceeding. While unfortunate, that's the current system limitation and we need to work around it.
3. The flow when you select a new image is a bit misleading. In the video flow, you have yellow "Upload file" button that initiates the signing (I think the copy should be different as mentioned in point 1 above), but in this image flow you have the same button that instead goes to the crop modal that has a primary "Upload file" button. It seems like we're a bit inconsistent and don't give the user a good understanding of what happens next. (Sorry if those are just prototype inconsistencies)

**Comment by toiletgranny** [comment]
Thanks for your input, @kdembler. Thoughtful as always, I really appreciate it! ❤️

1. Right, I see what you mean. At the same time, I don't think we want to flood the user with technical info, potentially making them think the new file selection process is more than it really is, would you agree? I cooked up a few alternatives; let me know if you see a candidate that's both user-friendly and provides accurate technical details.
    - **Original:** This file (the_joystreamers_amy_wa...dio.mov) is different from the one you selected before. To upload it, you’ll need to sign another blockchain transaction. Are you sure you want to continue?
    - **Option 1:** Since this file (the_joystreamers_amy_wa...dio.mov) is different from the one you selected previously, you’ll need to sign a transaction adding a new record to the blockchain. Are you sure you want to continue?
    - **:star: Option 2:** This file (the_joystreamers_amy_wa...dio.mov) is different from the one you selected before. To upload it, you’ll need to sign a blockchain transaction to confirm editing your video. Are you sure you want to continue?
    - **Option 3:** This file (the_joystreamers_amy_wa...dio.mov) is different from the one you selected before. To upload it, you need to confirm your edit by signing a blockchain transaction. Are you sure you want to continue?
2. Oh, of course. Is there really nothing we can do about that, you reckon? Perhaps we could experiment with making the user sign the transaction only after the video file is uploaded, if it was set o be an NFT during video creation? Or something else along those lines? My fear is that if something happens with my video file during the upload process, it's a dead end for me as a video creator. I end up with a video I can not upload or remove from my channel.
   - In case there's nothing we can do about it now, let me know if this dialog would work: 
![image](https://user-images.githubusercontent.com/35307309/192500571-9bbc1ce9-1840-450e-9fc0-30a650e868ce.png)
3. Well, the fact that a new blockchain transaction will be initialized was not enough for me to use the yellow button in this case. I use the yellow button in the video flow not only because there is a new blockchain transaction involved but, more importantly, to bring your attention to the fact that a different file was selected (as it can also be just a missclick).
   - Now, coming back to this specific flow, my thinking is that if you select _the exact same image_, but using a different browser, then it's just a transaction you need to deal with, and therefore there's no need to make things overly complicated. I mean, things are already quite complicated the way they are, compared to traditional web2 experiences, plus: what other option do I have in this case? :D **But**, if you select a different image file, then, and I hope this was clear based on my video update, my recommendation was to still throw in this yellow warning confirmation dialog and make sure the user is aware of the fact. And only once the user confirms, only then the crop dialog would be displayed.
   - If you still don't buy my thinking around it, then here: [check out this alternative flow](https://www.figma.com/proto/Pe1Y0nrl4mpHWs7AkuQOk5/My-uploads-page?page-id=321%3A203&node-id=1126%3A18716&viewport=-627%2C-1421%2C0.33&scaling=scale-down&starting-point-node-id=1126%3A18716&show-proto-sidebar=1) and let me know if it properly captures and addresses your concerns and if you like it better.

**Comment by kdembler** [comment]
1. Option 2 sounds great! Although I would recommend also updating the primary button copy to "Edit video" or "Edit and upload"
2. Yeah, I know it sucks :( For the future we have this idea of "freezing" an NFT which would allow the owner to enable editing it (for example to change the asset, add subtitles, etc), but for now that's not available. While the experiment you mentioned could work, it would be quite disruptive to our general publishing flow and I think for now we just have to bite the bullet and continue with the dialog you've suggested for that case.
3. So my main concern is around the fact that it's not clear what the primary button does. In your original prototype, if I selected a wrong image I would click "Upload file" twice - first it would be a warning variant then the primary one. User should always understand what's the consequence of clicking a button and if we offer a button with the same copy twice and the result is different, the user will be confused. I checked the alternative flow and I think I like it better

**Comment by toiletgranny** [comment]
@dmtrjsg We discussed the copy details with @kdembler over the slack call, and the final outcome of our discussion is ready to be reviewed and implemented. Just so you know, the handover part took a bit longer than usual this time, as the designs for this screen were not updated for about a year and a half, so I had to recreate and update a lot of stuff in Figma.

**Anyway, designs, docs, and changelog [can be found here](https://www.figma.com/file/Pe1Y0nrl4mpHWs7AkuQOk5/My-uploads-page?node-id=703%3A5382).**

![image](https://user-images.githubusercontent.com/35307309/192560875-963e2fda-8b44-40b3-8cdf-3a30cb77f77f.png)
