### ISSUE TITLE
Provide better error messages for failed faucet requests

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3172]
## Scope

- [ ] implement custom messages in the popup notiffs as per [this comment ](https://github.com/Joystream/atlas/issues/3172#issuecomment-1268525367)
- [ ] keep generic error message for all cases not defined in point 1

## Context

**Describe the bug**

Membership creation with Talisman failing.

**To Reproduce**

1. Go to https://play.joystream.org/studio/
1. Click on `Connect wallet`
1. Select Talisman wallet
1. Select account
1. Accept terms of service
1. Type in member handle ‘talisman’
1. Click create membership
1. Wait ~25 seconds on creating membership screen
1. See error “Something went wrong. There was a problem with creating your membership. Please try again later.”

**Screenshots**

![2022-08-25 10 45 27](https://user-images.githubusercontent.com/437292/186619175-568ff772-9460-4873-8059-5ade38557abc.jpg)

**Device (please complete the following information):**

OS: MacOS Monterey 12.2.1
Browser: Chrome

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202882495509820) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
It's not a bug per se - this failed because of faucet rate limiting. The user created a membership and then tried creating another one, while our faucet only allows one membership/48h/IP address if I'm not mistaken. If we want, we can repurpose this ticket to display better error message to the user

**Comment by dmtrjsg** [comment]
Agreed, let's display a better message, nice one 👍

**Comment by toiletgranny** [comment]
@kdembler Do you reckon it's safe to openly communicate the `one membership/48h/IP address` limit in the copy, or is there a reason we should consider something more like "You've reached membership creation limit. Try again _later_."

**Comment by kdembler** [comment]
I think I would go with the generic message since the specific limits can be updated independently in the faucet and wouldn't want those to get out of sync. FYI, there is also a "global throttle" concept, meaning that it's possible that you actually haven't created the membership at all, but the faucet is throttled at the moment anyway. In reality, I wouldn't expect us to hit this case too often, so not sure if worth changing the message to include this.

Now that I look at this issue, I've noticed that while we haven't included this in the initial scope, it would be beneficial to handle an additional error case that users hit up quite often: if you use an account that is not _fresh_, faucet will reject your request. Account is considered _fresh_ if it hasn't sent any transactions yet and also doesn't have any funds. Let's handle that as well 🙏

**Comment by toiletgranny** [comment]
@kdembler Oh man, now that you shed some light on all the things that could go wrong when you create a membership, it really makes you appreciate when it actually succeeds. So much, in fact, that perhaps we should consider changing the success snackbar copy to something more like, "This must be your lucky day! That's right, your membership has been created! Against all the odds! It's a miracle!" 

On a serious note 😅, though, I created custom copy for each case and would appreciate your review to ensure messages are correct from the technical standpoint:
1. **Membership/48h/IP limit**
   ![image](https://user-images.githubusercontent.com/35307309/194086672-3c0b825b-2898-47ee-a252-e9e4b9f224c9.png)

2. **Fresh account**
   ![image](https://user-images.githubusercontent.com/35307309/194086504-36568d8e-752f-435f-bd92-4b603927a25d.png)

3. **"Global throttle"**
   Now this one was a bit tricky. I wanted to convey the idea of the system being too busy without using words that could be more challenging with the general audience, such as the "faucet" or "throttle". I feel like I might have gone a bit too dramatic, however. "System overload" sounds a bit like Matrix...
  ![image](https://user-images.githubusercontent.com/35307309/194087073-71d80174-7411-4436-a9e0-0f1ec68fb650.png)

4. **Other problem**
    If it doesn't cost us anything and we're open to the idea that there might be other issues in the future, I would still vote for keeping the generic error snackbar.
    ![image](https://user-images.githubusercontent.com/35307309/194086235-d42a0e24-9387-447c-9a54-358ad70af01c.png)

---

If this is all okay with you guys, then, as always, **designs, docs, and changelog [can be found here](https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-in-flows?node-id=1284%3A11692)**.

cc @dmtrjsg
