### ISSUE TITLE
Test That Vesting Locks do not cover tx fees, storage and bloat bond fees Atlas

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3179]
@dmtrjsg commented on [Fri Aug 26 2022](https://github.com/Joystream/pioneer/issues/3580)

## Context
2nd round of QA, Env details are in the Epic pls see pioneer/3577>
- https://github.com/Joystream/pioneer/issues/3577

Testing Vesting Lock Fees Coverage

⚠️ this issue must be tested together with:
- https://github.com/Joystream/pioneer/issues/3452

## Scope

1️⃣ Ensure that Vesting lock in Atlas cannot cover any of the transactions:

### ⛔ Not Supported
- **Standard transaction fees**
- **Transfers** (`balances::transfer`, `balances::transfer_keep_alive()`, `balances::transfer_all()`)
- **Nft auction bids** (`content::make_english_auction_bid`, `content::make_open_auction_bid`)
- **Nft payments** (`content::buy_nft`, `content::accept_incoming_offer`)
- **Channel swap payment** (`content::accept_channel_transfer`)
- ☝️ **Bloat bonds** 
    - Channel bloat bond (`content::create_channel`)
    - Video bloat bond (`content::create_video`)
    - Storage data objects bloat bond (`content::create_channel`, `content::update_chanel`, `content::create_video`, `content::update_video`)
- ☝️**Storage data size fee** (`content::create_channel`, `content::update_chanel`, `content::create_video`, `content::update_video`) 

## Env

⚠️ 🆕 

1️⃣ Playground to use: https://3.92.226.32.nip.io/network/config.json
2️⃣  Atlas instance:  https://atlas-staging.vercel.app/.

ctrl+shift+d to change playground to "Atlas Dev Testnet"

**Comment by polikosi** [comment]
⛔ Not Supported

**- Standard transaction fees**
Like/Comment
Successful transaction: Withdraw, MemberRemarked, ExtrinsicSuccess
on network: wss://atlas-next.joystream.org/ws-rpc
in block: 0x1e5b75f2683bceb01810fe94043b2e957bd4930ed8d62ec55c0848349e442a30
extrinsic hash: 0x595c113025b31c358082a6b997de203d789c02f14eb71fb53a6ff378d5f5ae10
more details at: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x1e5b75f2683bceb01810fe94043b2e957bd4930ed8d62ec55c0848349e442a30
![image](https://user-images.githubusercontent.com/80429191/189101270-fbbf3781-228a-4ee3-ba7c-6cd81fbe81c4.png)
Successful transaction: Withdraw, MemberRemarked, ExtrinsicSuccess
on network: wss://atlas-next.joystream.org/ws-rpc
in block: 0x8f935d3a46e52e4da810580130b73459253879e58fe6d3cef253f37c939ce5b0
extrinsic hash: 0xab6a677d8e86b3e08bca30a4fc7aa204b94671c5f6727c8715ad18d1d2eb9ff4
more details at: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x8f935d3a46e52e4da810580130b73459253879e58fe6d3cef253f37c939ce5b0

**- Transfers (balances::transfer, balances::transfer_keep_alive(), balances::transfer_all())**
![image](https://user-images.githubusercontent.com/80429191/188622973-1c84367e-f68f-4cfe-b66e-3dcaf474f2e6.png)
**balances::transfer**
![image](https://user-images.githubusercontent.com/80429191/188626896-c3c08876-6070-4e94-8047-35298413fe1d.png)
**balances::transfer_keep_alive()**
![image](https://user-images.githubusercontent.com/80429191/188627071-ea8fbd2a-d661-4efa-b07f-036ce63e6e11.png)
⚠️**balances::transfer_all()** 
looks like a successful transaction
[TX](https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x9d335abcebf53d1b3425d0d6fadb489ce5cef56e21ecf7a0439c12939574ac49)
![image](https://user-images.githubusercontent.com/80429191/188627346-e5481782-bcba-460e-8468-52d5ea61675b.png)

**- Nft auction bids (content::make_english_auction_bid, content::make_open_auction_bid)**
![image](https://user-images.githubusercontent.com/80429191/188625959-6a413a5d-3bb9-42cc-9a5d-cb33ac4c48a9.png)
**content::make_english_auction_bid**
![image](https://user-images.githubusercontent.com/80429191/188629328-35478ffb-8c9a-45a2-8026-bc0fcec00cc1.png)

**content::make_open_auction_bid**
![image](https://user-images.githubusercontent.com/80429191/188629622-2ad4c71f-6283-4c32-9789-cc63a2213de3.png)


**- Nft payments (content::buy_nft, content::accept_incoming_offer)**
**content::buy_nft**
![image](https://user-images.githubusercontent.com/80429191/188629940-88aa3480-0d2a-43fb-afd3-0fa5104db400.png)
**content::accept_incoming_offer**
![image](https://user-images.githubusercontent.com/80429191/188630116-53620d06-e96d-498f-b032-6b5fcc450d95.png)

**- Channel swap payment (content::accept_channel_transfer)**
![image](https://user-images.githubusercontent.com/80429191/189101510-a0214b04-c35c-4ad9-9076-4226da3c4ed5.png)

**⚠️- Channel bloat bond (content::create_channel)**
I can create channel
![image](https://user-images.githubusercontent.com/80429191/188634610-f92814a7-988e-4dbb-8fb4-60900b21a9ec.png)

https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xb9d427ccecf036bec315f5511b12e06107222da47b1ad6405a24ba348e2975ad

**⚠️- Video bloat bond (content::create_video)**
Succesfull upload video
![image](https://user-images.githubusercontent.com/80429191/189102179-cce753ec-6a59-4700-957a-d3fff8d67b86.png)
https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x88cf068f0f99401364a98fba14f9666cc68b5e21ec6dced417fee57971301efd

**⚠️- Storage data objects bloat bond (content::create_channel, content::update_chanel, content::create_video, content::update_video)**
Create channel
Successful transaction: Withdraw, Withdraw, Deposit, Withdraw, VoucherChanged, VoucherChanged, DynamicBagCreated, Withdraw, Deposit, NewAccount, Endowed, ChannelCreated, ExtrinsicSuccess
on network: wss://atlas-next.joystream.org/ws-rpc
in block: 0xd2382681ccd8be131e4991dd89b9486192724e60f5cdba73ebc836b086fbc388
extrinsic hash: 0xd2d7d743c554472967e2a1069af1d4401472851d557253db748cf103960f239d
more details at: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xd2382681ccd8be131e4991dd89b9486192724e60f5cdba73ebc836b086fbc388

Update channel
Successful transaction: Withdraw, VoucherChanged, VoucherChanged, DataObjectsUpdated, ChannelUpdated, ExtrinsicSuccess
on network: wss://atlas-next.joystream.org/ws-rpc
in block: 0xd942e149f63ac14affa9702f5417e30e90dd783f07cd875d0b14c9271b1871ad
extrinsic hash: 0xf3d7256635075ea73565c478bb3942658bdf16382f3f96920761ca93b61d2b67
more details at: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xd942e149f63ac14affa9702f5417e30e90dd783f07cd875d0b14c9271b1871ad

Create video
Successful transaction: Withdraw, Withdraw, Deposit, Withdraw, VoucherChanged, VoucherChanged, DataObjectsUploaded, Withdraw, Deposit, VideoCreated, ExtrinsicSuccess
on network: wss://atlas-next.joystream.org/ws-rpc
in block: 0x4aa57b8da547dd9ad7b2572cc1f3cab3bee8a0464fd1ca16090436aadd1b0205
extrinsic hash: 0xbf10fdd6958c232d0b6f58c22e2c6048e5046e47e0398af6b5ece937d997e802
more details at: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x4aa57b8da547dd9ad7b2572cc1f3cab3bee8a0464fd1ca16090436aadd1b0205

Update video
Successful transaction: Withdraw, VoucherChanged, VoucherChanged, DataObjectsUpdated, VideoUpdated, ExtrinsicSuccess
on network: wss://atlas-next.joystream.org/ws-rpc
in block: 0xe7490ffc097ad4c6337d5dcfceef0eda772adf356edc122bb592e72d3ea81dae
extrinsic hash: 0x0f6f06dd3767cb96582d9d9317ea6a3f745202e7cc55e742c7f888f2b3349cc9
more details at: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xe7490ffc097ad4c6337d5dcfceef0eda772adf356edc122bb592e72d3ea81dae

**Comment by dmtrjsg** [comment]
Hey @polikosi thanks for running though the scenarios, I am afraid this one needs to be retested.. 

After looking into all transaction links (thanks for providing those btw!!) we figured that most likely the account used in testing was used to create membership with help of Faucet which led to 'Invitation lock' applied and sponsoring the use cases.

Suggestion is to get an account which has ONLY the Vesting lock applied to it (locked and unlocked funds, but not claimed/ converted to transferable balance).   Basically you'd need to either claim some vested funds to be transferable and purchase membership / or transfer some free funds to this account from another account and purchase membership using account's own funds, and not the Faucet funds. After the membership is created transfer all free funds to another account and try to test the above cases with 0 in transferable balance.

Try with Alice, Bob, Charlie, Dave.. but if all of them are unsuitable we can spin up the new network for you. 

Additionally, please pay attention to the error messages as two of the scenarios with Purchasing NFTs, Settling auction and purchasing buy now were unsuccessful due to mismatch in the type/ state of the respectice auctions.

If you have any questions, pls do not hesitate to ask me or @ kdembler. 

cc @singulart

**Comment by polikosi** [comment]
⛔ Not Supported

**- Standard transaction fees**
![image](https://user-images.githubusercontent.com/80429191/189954531-fddff65f-22eb-486d-96ee-88ad5a21f3ad.png)

**- Transfers (balances::transfer, balances::transfer_keep_alive(), balances::transfer_all())**
_balances::transfer_
![image](https://user-images.githubusercontent.com/80429191/189954621-48710e3b-1579-4cdd-a946-7dbcf9e06272.png)

_balances::transfer_keep_alive()_
![image](https://user-images.githubusercontent.com/80429191/189954761-70dbd631-26fc-4339-84e8-fead9e66f7a6.png)

_balances::transfer_all()_
![image](https://user-images.githubusercontent.com/80429191/189954828-3f2afb52-4b43-48f5-9972-f35fb0e3b6d9.png)

**- Nft auction bids (content::make_english_auction_bid, content::make_open_auction_bid)**
_content::make_english_auction_bid_
![image](https://user-images.githubusercontent.com/80429191/189954902-df50f224-2c11-40d7-bb83-f3b1e47e7731.png)

_content::make_open_auction_bid_
![image](https://user-images.githubusercontent.com/80429191/189955013-9a96d966-3694-475e-bb15-80838a022e86.png)

**- Nft payments (content::buy_nft, content::accept_incoming_offer)**
_content::buy_nft_
![image](https://user-images.githubusercontent.com/80429191/189955079-d2fd657d-f260-4de5-8e9a-37974ce682fa.png)

_content::accept_incoming_offer_
I can't upload videos and make NFTs, so I don't have any incoming offer

**- Channel swap payment (content::accept_channel_transfer)**


**Bloat bonds**
**- Channel bloat bond (content::create_channel)**
![image](https://user-images.githubusercontent.com/80429191/189951659-0543975c-60c6-447d-b4cd-59509bfd80e2.png)

**- Video bloat bond (content::create_video)**
I can't create video without a channel.

**- Storage data objects bloat bond (content::create_channel, content::update_chanel, content::create_video, content::update_video)**
I can't do anything from this list because I can't create a channel.

**- Storage data size fee (content::create_channel, content::update_chanel, content::create_video, content::update_video)**
The same situation (I can't do anything from this list because I can't create a channel.)

**Comment by kdembler** [comment]
### Testing vesting lock for state bloat bonds

Let's assume Bob has a big vesting lock and no other funds to start with. Let's also assume Alice has a bunch of transferable tokens. Let's also use Polkadot apps for testing

1. Transfer a bunch of funds from Alice to Bob
2. As Bob, buy yourself a membership
3. As Bob, prepare create channel extrinsic and check its basic transaction fee:
![CleanShot 2022-09-15 at 14 34 25@2x](https://user-images.githubusercontent.com/12646744/190404839-a32abbef-1699-4af4-9060-1beb58f36d68.png)
4. Don't send the extrinsic just yet - first transfer all the free funds from Bob back to Alice, leaving only enough free funds for the basic fee in Bob's account
5. Try to create a channel - because there's enough funds for basic fee, the transaction should be included in the blockchain but just fail because of business logic rejecting vested funds as a source for bloat bond fee.

This test can be easier if you set the channel bloat bond value to something really high - this way you can make it easier to make sure that your free funds won't be used for the bloat bond.

**Comment by polikosi** [comment]
everything seems to work as expected

![image](https://user-images.githubusercontent.com/80429191/190870515-22575823-84e4-4bb0-b376-150fb5a008d2.png)
https://polkadot.js.org/apps/?rpc=wss://3.92.226.32.nip.io/ws-rpc#/explorer/query/0x03436e5f45f95214e69653e3ea92b432d707cf35cbffff4910d7b0263ed7451e

**Comment by kdembler** [comment]
You provided big values for both state bloat bonds but those are incorrect - in this extrinsic you only provide the **expected** state bloat bond value - it needs to be exactly the same as the value on chain. Since the value on chain is different that what you expected, the extrinsic failed, but that's not related to the vesting locks. If you want the bloat bonds to be higher, you would need to call extrinsics to change them (for example `content.updateChannelStateBloatBond` that needs to be run by the content curator)

**Comment by dmtrjsg** [comment]
@polikosi  

ℹ️ How to get the precise values:

1. Go to https://polkadot.js.org/apps/#/chainstate (I assume it's already connected to the current playground)
2. Select storage => dataObjectStateBloatBondValue and click the "+" icon: This value should be set in expectedDataObjectStateBloatBond
3. Select content => channelStateBloatBondValue  and click the "+" icon: This value should be set in expectedChannelStateBloatBond
4.  Select storage => dataObjectPerMegabyteFee and click the "+" icon: This value should be set in assets.expectedDataSizeFee (if provided)
