### ISSUE TITLE
Creator Tokens — Owner & Issuer: Testing (round 2)

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#3312]
This issue is encapsulating all discussions regarding round 2 of tests for Owner & Issuer CRT experience.
The tests will contain all previous flows such as:
- Issuing CRT
- Editing token page
- Selling CRT
And will check if all findings from the previous round of tests were addressed in the designs.

🎥 Loom test walkthrough: https://www.loom.com/share/4fb4309850304ed1a9bf831315f32825
📄 Test figma prototype: https://www.figma.com/proto/VzPBMpUnGjGOHMSW2ZHbGY/Creator-tokens?page-id=3784%3A278656&node-id=3784%3A278805&viewport=1170%2C820%2C0.14&scaling=min-zoom&starting-point-node-id=3784%3A278805

**Comment by dmtrjsg** [comment]
Looks solid :muscle: Ready to be tested. 

Small comments:
Yes loving the idea of highlighting the chart components on hover.
Can the image is a good idea, but the design of the token could be improved if we are going this direction, at least show the token short name, three chars?
Share link should be somewhere on the token public page but also available from dashboard, perhaps from the sale widget is the best place to do it.
Completed steps I’d prob opt to the more “accomplished” rather than “crossed-off” designs from the emotive pov, but that can certainly be fine tuned after the test.
Informing the users on the Select Sale type has to be more explicit. Assumption is some will not hover but click on active.
I personally  do believe that placing start/ end process inside the widgets would be more effective. But let’s see what the tests bring us.

Overall looking good mate, well done :rocket:

**Comment by bedeho** [comment]
Fantastic work, really liked how you connected the fields and the vesting schedule hovering ;)

**Comment by KubaMikolajczyk** [comment]
# Reply to small comments @dmtrjsg above 👆

> Can the image is a good idea, but the design of the token could be improved if we are going this direction, at least show the token short name, three chars?

Can you elaborate more on that - I don't know if I understand it right

> Share link should be somewhere on the token public page but also available from dashboard, perhaps from the sale widget is the best place to do it.

I agree it has to be included, in sale page, widget or in both places.

> Completed steps I’d prob opt to the more “accomplished” rather than “crossed-off” designs from the emotive pov, but that can certainly be fine tuned after the test.

We tried to iterate with the design of completed steps and the effect of completed step being not too important anymore was critical to not distract users from the goal which is completing the next step. 

> Informing the users on the Select Sale type has to be more explicit. Assumption is some will not hover but click on active.

That was a good call which was proven in tests - so more about that below 👇

> I personally do believe that placing start/ end process inside the widgets would be more effective. But let’s see what the tests bring us.

Start / End sale process is also now in the widget along with it being prominently exposed in the cta's next to the tabs - and according to tests it works really well :) more about that below.



#
# CRT Creator & Issuer Test results
#### Overview
We conducted 4 usability tests for the CRT Creator experience. We hoped to see if the understanding of core CRT principles increased after implementing the changes to experience.

# 👥 4 participants to be paid 👈 @bwhm 

Joystream participants $30 worth of BCH
qrrz283ay4m7nq4l78fsuhl8czkt4hyx25cdjsnqz9
qphaa35c0rszdx4xml958k38yfw0t9u5jccw68usrg
qzv9yhjnawqrmpgdcufca40nw90e3zhckuswsdu0xc

External expert $40 worth of BCH
qqtyutsnd4wsvjy5x9x5tnqa4fxzkrtceyx2wegypg

# What do we want to know?
1. Does the users understand all of the concepts during the CRT issuing process?
2. Is dashboard clear and understandable & what is the next step that the user will take after creating CRT?
3. Does the user understand how to edit the token page?
4. Does the user understand what is the difference between two sale types?
5. Is the process of setting AMM clear, are all concepts clear?
6. After setting the AMM can the user tell what changed and what they can do now?

# Research outcome 

#### 1️⃣ Does the users understand all of the concepts during the CRT issuing process?
![image](https://user-images.githubusercontent.com/31144205/195375739-c0964366-58fb-4c29-ac3c-8bac85db7ee2.png)
a. Surely its a huge plus that we start from this simple CTA - it was a lot less confusing for users to start the process and 2 users said that they would start it even by watching an additional explainer video hidden under learn more btn
![image](https://user-images.githubusercontent.com/31144205/195376214-2818bfe1-b52d-4db3-939b-bd095467720a.png)

b. Almost all fields are now understandable - the only one that cretes confusion is Patronage which confuses not only those users who understand it but also those who guessed correctly that its a reward for them. The benefits of this tool is unclear as well as how it is calculated - we need to think about another way of presenting it to make it more clear ( one user suggested to show some calculations here) [Zach 41:50](https://drive.google.com/file/d/1CS-m99k9HijlF9PDUHf4_FXo4OgiNPJD/view?usp=sharing) [James 7:30](https://drive.google.com/file/d/1gCeVXNBXupWbORtOvRmsVSp5X3-DU9tu/view?usp=sharing) [Alex 8:40](https://drive.google.com/file/d/13I246G2cpUQoJPXkbHLBL1gmKsetN27u/view?usp=sharing)
![image](https://user-images.githubusercontent.com/31144205/195376890-5cb003e3-435c-4960-a44d-a317b824e630.png)

c. The good news is that it getting more and more clear :) 2 users guessed correctly but only 1 had no doubts about it  - the rest didn't understand at all that this applies to them and that they will receive those tokens [James 13:50](https://drive.google.com/file/d/1gCeVXNBXupWbORtOvRmsVSp5X3-DU9tu/view?usp=sharing) 

d. One user mistaken your tokens that you will receive with a concept of total circulation which is understandable as the pattern of just giving users free tokens is rare on the market [James 12:50](https://drive.google.com/file/d/1gCeVXNBXupWbORtOvRmsVSp5X3-DU9tu/view?usp=sharing)

e. It looks like we could benefit from moving your starting tokens variable to the previous screen separating it from cliff & vesting & bringing it closer to patronage - this way we could show more details about patronage related to the tokens that you will receive 

f. It would be extremely beneficial if at the time of token creation we could educate a little the creators about ways that they will make money later in the process - this way we can explain why they need those starting tokens, also that they don't have to worry and they can have a cliff and vesting because there is always amm to get rid of confusion that is happening when they open sale selection page

g. Making cliff and vesting for creator as an optional and super clear step is super important as decisions made here can lock you for many months or years in a purgatory state when you have no access to your funds - it should be marked as an advanced optional option with a tutorial next to it - imposing a default state with big cliff and big vesting on creators when there was no similar pattern on other platforms so far can be more harmful than beneficial because they may just click through it and lock themselves for good
h.Graph readability improved a lot! users can now see value in the graph and its really helping - but the dots on it give away the wrong suggestion so we should get rid of them 

i The suggestion that I write about above is about how often tokens will be released to the creator during the vesting period - from the lack of the information about it on the page and from the dots on the graph users were guessing that the tokens are released every three months but in reality those will be released every block - so we have to share that information with creators
![image](https://user-images.githubusercontent.com/31144205/195382538-e6e6f8b8-61ee-4b6e-a95e-633ab4b7eef1.png)
![image](https://user-images.githubusercontent.com/31144205/195383094-344dc9b1-b289-42e1-8e5d-6c34c7f998fc.png)

j. On the modal we should change the action from OK to go to dashboard and the main page title on the token dashboard should say "[token name] Dashboard" as there were users who thought that dashboard is the token page so there was this confusion around naming

#### 2️⃣ Is dashboard clear and understandable & what is the next step that the user will take after creating CRT?
![image](https://user-images.githubusercontent.com/31144205/195383315-21616ae5-6468-4609-ac66-6fae546400ec.png)
a. Yes it is much more clear! Now with the progress indicator users feel much less lost on it.

b. Except of that almost all concepts are understandable except of the patronage.

c. Next action was always edit token page - users tend to stick to the progress path and are even expressing thoughts such as: Now I want to be a token master :) 

#### 3️⃣ Does the user understand how to edit the token page?
![image](https://user-images.githubusercontent.com/31144205/195383960-e50d6978-a74a-4a00-bdd1-ebec3b59abd4.png)
a. Yes they do - after the last iteration the experience became much more clear. Users understand how to add intro, benefits and description 

b. Not a single user found preview button which was wrongly placed in the top right corner of the page- it has to be moved down to the action bar so users will have much easier way of discovering it.

#### 4️⃣ Does the user understand what is the difference between two sale types?
![image](https://user-images.githubusercontent.com/31144205/195384723-e617ab06-6044-4560-96a3-f648fe347b94.png)
a. There is an improvement in the level of understanding the difference between two of those - users can clearly read the table and get some insights from it 

b. **🔴There is a huge problem with the fact that users do not earn from AMM as they do on other platforms🔴** - users mention things as "Then who earn my money?", or "As I know how AMM works I'm curious why I don't earn from it" - they are used to services on other platforms such as DESO where they do earn a % called founder reward from AMM Minting [James 35:50](https://drive.google.com/file/d/1gCeVXNBXupWbORtOvRmsVSp5X3-DU9tu/view?usp=sharing) [Zach 28:05](https://drive.google.com/file/d/1CS-m99k9HijlF9PDUHf4_FXo4OgiNPJD/view?usp=sharing) - this is something we have to discuss about.

c. On other platforms such as Uniswap the concept of AMM has liquidity pools - we don't have this concept here and it also need to be explained that its different [Alex 42:20](https://drive.google.com/file/d/13I246G2cpUQoJPXkbHLBL1gmKsetN27u/view?usp=sharing)

#### 5️⃣ Is the process of setting AMM clear, are all concepts clear?
![image](https://user-images.githubusercontent.com/31144205/195387789-996e5d4f-3786-4c7b-ac24-87455882bad8.png)
a. The concept of AMM is more clear than before but still there is confusion about how the AMM works and why they do not earn from it directly & why someone else can sell to AMM 

b. There is a problem with the fact that we allow users to set their own price for the AMM - firstly its harder for them to set it themselves as they have to come up with the price and value of their token - from user I heard that they would much rather have this parameter set for them / and then there is a second problem - if creator can set any value as a starting price then if its the second AMM (first one was ended by creator) then if the starting price would be set really high the second time around all of those purchased coins would rise in value really fast which can be potentially harmful 

c. One users was really confused about the word "minting" and was asking what it means - "are they going to mint and buy at the same time?" - it happened only with this user but its worth noting at least to be explained in explainer video 
![image](https://user-images.githubusercontent.com/31144205/195389366-e86a28a4-a372-4fd1-b0ed-52a44adb5c9e.png)

d. The concept of vesting and cliff on this page was received much more clearly than the one which applies to the Creator - there is an overall improvement in level of understanding from the last iteration

#### 6️⃣ After setting the AMM can the user tell what changed and what they can do now?
![image](https://user-images.githubusercontent.com/31144205/195390267-e88bb963-a1e8-455f-a175-26232609a171.png)
a. All of the users knew what changed, all pointed to the right widget and all knew how to move to sale tab
b. All users knew how to end the sale either with btn in widget or one in the CTAs buttons next to tabs

**Comment by bedeho** [comment]
Great work doing this research, and the breakdown was really clear.

> The benefits of this tool is unclear as well as how it is calculated

That is interesting. So I think having a steady income is a supe attractive proposition for most creators, and this gives them that. So I think we need to make sure that people are only ever setting this to 0% if they really know what they are doing and have a clear reason.

I think the copy there is not good, I mean its litreally wrong - its not for "managing the supply", which doesent even have a meaning. But I also think it can be restated as a benefit to be clearer, e.g. "Inflation you receive in creator token as recurring income"

**Given how bad this copy was, I suggest reviewing all of it TBH.**

I also think perhaps you are getting influenced by the technical names for things, and not what users need. So like "Permission type", I don't think thats the best name for the user. A more direct name is "Access", and then you call the variants "Anyone" and "Invite Only", this is more plain english. This is just one suggestion, but the issue seems to be real across all the CRT stuff.

> Surely its a huge plus that we start from this simple CTA

Want to quickly as, is this visual actually all that good? What is the J for in the mind of someone who is trying out Gleev or app xyz? Seems like we are just reusing an asset we already have, rather then optimising for user comprehension. Even no visual may be better than this.

> There is a huge problem with the fact that users do not earn from AMM as they do on other platforms

First off, we actually can easily change this still, because AMM stuff has not even been implemented on the runtime. However,
a) my intepretation of that segment of the video was not that he was all that upset about it, perhaps I am missing something?
b) the fact that this is the standard on Deso is not that significant per say, that constitutes a very small share of even just the video creators we are targeting, let alone all the more general creators found on Deso.

I think we should introduce this on the premise that it is impmortant for the creator, and that is not clear to me. They already have PAtronade as a steady income which even does not depend on transactional volume on AMM, and to get $JOY liquidity for theri $CRT they would need to sell into the AMM, so they have a very strong interest in having a functional AMM just for that simple reason. There are also just the simple reasons of increasing liquidity of the token among users. So I am just not seeing the case for why this is _important_ as separate revenue stream from first principles. If we add this, it also raises the question of _how much_ should the crator get as an AMM fee. They will need to extract ths on top of the platform fee, and it must be communicated properly to both sides of the transactions (buyers and creator during AMM launch), so its not for free.

> On other platforms such as Uniswap the concept of AMM has liquidity pools - we don't have this concept here and it also need to be explained that its different 

Right, so thiss is another argument for not calling it an AMM, because the most popular AMMs work differently than ours. We have also considered going to the step of doing our AMMs like uniswap directly, but that makes it hard to bootstrap liquidity, because then the creator will need to have significant amount of $JOY, which most will not have ot begin with.

> The concept of AMM is more clear than before but still there is confusion

Again here the copy is not good tbh. Its emphasisng one random fact, out of a sea of facts (price goes up when you buy), as the main tagline. Also the name is just a disaster for normal creators, even some crypto creators will not know.

**Comment by KubaMikolajczyk** [comment]
Thank you for great feedback @bedeho 🙇

> That is interesting. So I think having a steady income is a supe attractive proposition for most creators, and this gives them that. So I think we need to make sure that people are only ever setting this to 0% if they really know what they are doing and have a clear reason.

My idea for solving this is to create a separate step for tokens claimed by the creator & patronage where we will be able to give more careful explanation about it and some calculations maybe - I will be posting a short video update with that soon.

>I also think perhaps you are getting influenced by the technical names for things, and not what users need. So like "Permission type", I don't think thats the best name for the user. A more direct name is "Access", and then you call the variants "Anyone" and "Invite Only", this is more plain english. This is just one suggestion, but the issue seems to be real across all the CRT stuff.

Frankly, it was one of the few fields that was clear as day to the participants. But I understand the premise and the copy overall need to be reworked. We can try going with Access though :) 

>They already have PAtronade as a steady income which even does not depend on transactional volume on AMM, and to get $JOY liquidity for theri $CRT they would need to sell into the AMM, so they have a very strong interest in having a functional AMM just for that simple reason.

I think those reasons are exactly what we have to tell users as we don't communicate it clearly so far.

> So I am just not seeing the case for why this is important as separate revenue stream from first principles.

The reason I heard a few times was that selling their own tokens on AMM is stigmatised and frowned upon - so if you as a creator don't want to look bad in the eyes of your followers (because if you sell then the AMM drops and the value of their token drops) then you have to base your earning on that "Founder reward" element.

>They will need to extract ths on top of the platform fee, and it must be communicated properly to both sides of the transactions (buyers and creator during AMM launch), so its not for free.

Yes - on deso its one of the most important parameters - visible right next to token name.

> Right, so thiss is another argument for not calling it an AMM, because the most popular AMMs work differently than ours. We have also considered going to the step of doing our AMMs like uniswap directly, but that makes it hard to bootstrap liquidity, because then the creator will need to have significant amount of $JOY, which most will not have ot begin with.

Right it's tricky - because in our case its also an AMM right? We have a bonding curve and it works just as AMM - the only difference is that we don't have liquidity pools. I m not sure if I would call it differently because of that fact only - but it would be nice to make it clear how it works for creators.

**Comment by KubaMikolajczyk** [comment]
@bedeho there is one more thing that was not highlighted in the report but probably needs a highlight on its own 

### Video tutorials / walkthrough
All participants very clearly suggested that the first thing they would do is to click the button "learn more" at the first intro screen - and they would expect a broader video telling them about CRTs and a walkthrough through the process of creating CRTs (more experienced user said to us that if there would be documentation he would also read it)- then during each next step the "learn more" buttons were noticed and when asked users told us that they would surely click them before doing any action. (same in dashboard, same in sale types, same in setting sale)

It is clear that with a such complicated topic video guidance would be a huge help to a large number of users - and without it, we will have to try to explain a vast number of topics in the UI - the example of such a situation could be AMM where for now we only tell about rising/falling of the price when it's merely a tiny piece of information about AMM - if we would want to explain more in UI it can quickly turn into a wall of text.

So from my POV those videos seem to be a crucial part of the experience and I would highly recommend including them - it would be even nicer if we would agree that we will have them as a part of the process and therefore we could design UIs in such way that watching a short video would be a first suggested step when entering each flow - and then the rest of UIs could assume that user already gained some knowledge from this video.

In a world where we would resign from having them as a part of this experience, or even in the current scenario when we design for having them or not, if we would want to explain some concepts more carefully to the users, we would have to consider how to squeeze a large amount of explanation in a different part of UIs.  

Let me know what you think about it and what is @dmtrjsg , @toiletgranny views as well.

**Comment by dmtrjsg** [comment]
**Starting screen**

We discussed to have a progress steps/ widgets on landing, together with a simple CTA in the bottom. Curious to hear if that was a go from your and Adam's end after a quick sketch. Imho will be better than "J" visuals. 

**Video helper**
I think we should assume / rely on the video guides when building interfaces. We 100% need to add tooltips to every parameter and I'll try to draft them up with Bedehos reviews this could move the needle. Video is a nice to have, which we can hopefully deliver, but we should not build our interfaces around the idea that users familiarise themselves with the videos before diving straight in. Tooltips are more robust as deliver contextual bite-size info.

**Copy**
Copy-wise once you prepare the final version I'll try to go and have a second review, I think we may benefit from a content-trio including @toiletgranny for another review, once I am done, as we had some good results working on other parts of the app in the group before. 

**Re AMM concept** 
It's difficult for me to spot the nuances since I was in and out of this topic, so let's go with what Bedeho suggests here. In general I feel like we need to dive into it again, and have a clear list of benefits (reasons why to go with it) that creator has going with AMM and how this interplays with Creator sale. @bedeho is that too much to ask and write smth up focussing on that part specifically, like a full comprehensive list? 

**Creator Vesting and Cliff**
The trick is the default values, is going with 0 actually beneficial for the community? 

Cliff: I had doubts on non-zero cliff for one-self last time, as this does not make economic sense, other than sending some sort of a nuanced signal, which only experienced and attentive buyers would notice. So going with a 0 days cliff sounds good tome as a default value. Also, that's what I would go with.

Vesting: Here starting with 0 seem to be less straightforward.. as attentive buyers would spot a risk of the coin been dumped with AMM enabled. So perhaps starting with a 6 months default is a more plausible option. Also worth mentioning ofc that tokens get unlocked on every block.

**Patronage**

It was discussed in the interview that the frequency of payouts can be changed, which I am not sure it can be based on what we discussed. @bedeho can you confirm if that can be changed towards more frequent payouts, or maybe its even user-configurable?

**Comment by bedeho** [comment]
> it would be even nicer if we would agree that we will have them as a part of the process and therefore we could design UIs in such way that watching a short video would be a first suggested step when entering each flow - and then the rest of UIs could assume that user already gained some knowledge from this video.

I'm happy to have us do this, worst case we have to do something pretty low effort, then polish later.

> Right it's tricky - because in our case its also an AMM right? We have a bonding curve and it works just as AMM - the only difference is that we don't have liquidity pools. I m not sure if I would call it differently because of that fact only - but it would be nice to make it clear how it works for creators.

It's not even so important what _it is_ per se, we just need to pick the right language to convey the important understanding for our target audience, and I am not sure AMM is that. Uniswap is not for creators, so even if they explain 
parts of their product as AMM (not even sure they actually do that even), its less of a problem. 

> It was discussed in the interview that the frequency of payouts can be changed

Payouts are pull based, like normal creator payouts, so there is no inherent frequency. In principle you could claim patronage rewards every block, it would just be a very very small amount of tokens. What is important for people to understand is how much they would get over some reference duration, like a year, regardless of frequency of actual cashouts.

**Comment by KubaMikolajczyk** [comment]
Hey @bedeho @dmtrjsg as we are heading to bring this CRT Creator experience to hi-fi stage and start finalizing it I have a quick 14min/1.5x video update with the direction that I propose after the test (keep in mind not much of copy changes yet but lets focus on the flow & experience:
🎥 Loom: https://loom.com/share/4243f1ed1f5641358228b86f7a8ee107
📄 Figma files: https://www.figma.com/file/VzPBMpUnGjGOHMSW2ZHbGY/Creator-tokens?node-id=3951%3A303056

**Comment by bedeho** [comment]
I did have a great time watching, as always, thank you <3

1. Def. the second intro screen variant is better, much more inviting, and much simpler, I get excited to get started on that journey!
2. I am not sure that you are fully understanding how patronage works, from some of the things you are saying, so let me reiterate to be sure. Patronage is an annual inflation rate, so its in %/year. This means the user cannot expect to specify some X number of tokens they will receive on some fixed basis, because it is not fixed. As the supply of the token changes, for any reason, the number of tokens the person will receive for some given period of time will change, and we cannot give them expectations to the contrary. Also you described it as "% of tokens not claimed" as well as the payout graph you showed, which really does not work, makes me unclear if the fundementals are clear here. Happy to jump on a call. I am actually not sure what the complexity is here for the user, we are just saying what annual reward of your own token do you want as a % of its value? We do not need to simultanously try to convey how and when they can access it, because it is not actually fundamental to the concept.
2. I think the fact that your own cliff constrains timeline for your own sale is a very astute point which we have to raise earlier. One way to deal with them is to just explicitly ask them "Do you know if you want to sell your own token in the near future: I don't know, def yes, def no.", and then we just set the initial cliff based on this. Also, if they set cliff to 100%,then we show inline warning unless they chose "def. no.". In fact, more of this assistant like approach could help part of this flow easier. you coul ask like "is it important to you to show your community you cannot sell your tokens in the short term", and then based on this one can also suggest rest of schedule. Obviously more work, but worth keeping in mind if we find real trouble spots later where people struggle.
3. I think having non featue compairson is good, but copy still needs work, ping me when to schedule this.
4. How many videos are we currently planning? I think a super simple format is just someone doing a sort of Loom like recording, as you are, in the product, talking about the fields and the concepts.
5. The new "learn more vaiation" was very salient and inviting, the only drawback I can think of is if there are multiple things in one scener where people may ant to learn more about each one, but that probably means the scene is too complex, or that the video should try to cover everything in the scene holistically.

**Comment by KubaMikolajczyk** [comment]
Thank you for the feedback Bedeho :) 

1. Which one of the screens is second for you? A or B
![image](https://user-images.githubusercontent.com/31144205/196108520-3115eb5e-6d32-4733-a31f-d7d2c878bea0.png)
2. Yes I understand that it is calculated based on how many tokens user has in that specific moment ( so the calculation will vary each time user sells / or buys) - my idea here was to show some calculations based on the amount of tokens that they would claim and show the perfect scenario as in what would happen if they would hold all of the tokens. We might have to rethink it then to explain it better for the user
3. I like the idea of asking user a question and then suggesting the experience - we could add it at the beginning of the cliff & vesting screen and suggest both of them based on the answer 👍
4. Will do 👍
5. Yes I was thinking something like this and at least 1 separate short video for each flow ( 1. issuing, 2. Editing token page, 3. Selling AMM, 4. Selling public sale, 5. Revenue split)
6. I think the video should cover everything holistically but can also dive deeper into some complex concepts I see no wrong with that. "The new learn more variation" - is the one with big play button in the bottom middle?

**Comment by bedeho** [comment]
> Which one of the screens is second for you? A or B

A 

> We might have to rethink it then to explain it better for the user

But I think if the user is asked to input X tokens, you cannot later come and give them Y, which is what will happen. No amount of explaining can really overcome this I think. But I think I am fundamentally  a bit lost on why exactly people would have a hard time understanding what this % means, conceptually this is dead simple.

**Comment by dmtrjsg** [comment]
1. Crossed off  - nice looks perfect
2. Quite like the low key steps and combined with the imagery looks very nice 👌 
3. I think moving patronage closer to token supply is good as they are logically a bit closer, as inflation is still prob a function of the total supply..  we just need to update the copy and the tooltips (which I will have a go at tomorrow so will be done before eod!)
4. For the types of sale we need some vertical delimiter or a way to draw attention that focus/ benefits / particular outcomes in two columns relate only to the sale above. Imho there's a chance to miss this crucial point. 
5. One big play button is prob a bit of an overkill imho.. let's perhaps revert back to the blue invitation as a link which can also summon a video in the same way. As this would make less emphasis on the video tutorial and have it in the place as a supporting act. Also sorry pls dont use it against me but this really reminded me Windows Media Player layout which Im not sure we want to tickle on the emotive level 👀 🤐 😅 

Plus ofc we also need to address the points on patronage (copy + tooltip) and try to rewrite the description in a way that Bedeho proposes... Do you want more this? Then select smth like that in the copy itself, not in the tooltip. Try to go with it and I will join your efforts. Let's aim to send this for final review to Bedeho by Wednesday mid-end of day 🚀

**Comment by bedeho** [comment]
> One big play button is prob a bit of an overkill imho

I don't think it is overkill, but this ultimately boils down to an assumption about how successful we believe the average person will be going through these flows. I think people really will need all the support they can get, the confusion will abound, and bad initial decisions can leave people locked into bad downstream effects. I see these videos as a first-order thing that pretty much everyone should consume, not an afterthought. On that premise, I think the suggested prominent presentation is excellent. Please offer your thouhgts.
