### ISSUE TITLE
Multiple Gateways for project homepage

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3321]
@dmtrjsg commented on [Fri Sep 23 2022](https://github.com/Joystream/marketing/issues/289)

## Context
Multi-gateway set up for the OB journey, covered here:

* https://github.com/Joystream/atlas/issues/3273

Implications on website covered in this issue

Website: Right now, the website has a few key CTAs saying Claim your channel, talking directly to creators, primarily because the whole site speaks very directly to creators, not because we were expecting that creators were going to land on the main project website as part of the natural signup flow, they were not. 

It may however be more prudent now to clarify things by either replacing this CTA, or having it send you to a section or new page which shows an overview of apps/gateways which you can get onto. This should also explain how these are different apps built on one platform. The Jsgenesis app would merely be one of these.

## Scope
* [ ] Update the project homepage copy wrt to multiple Gateways / Apps supported by joystream blockchain and dao.
* [ ] Update CTAs from "Claim channel" to smth like "View Apps"
* [ ] Create intermediate page which would feature all Apps connected to joystream blockchain. 

Suggestions for the latter: Apps are most likely to occupy a certain content vertical. Two first apps to be featured on the page will be supported by JSG. Gleev (Web3 focus, run by JSgenesis) and ~Vinteo (Broad category span, to accommodate all video content that falls outside of Gleev)~. The page must be designed in a way where 1 Apps looks, but can be extended up to 10+ without having to redesign the page. Add a CTA to invite users to set up their own gateway via Link to GH page dedicated to it.

🆕  Issue that can help with getting the presentation of the gateways right wrt available metadata:
- https://github.com/Joystream/joystream/issues/4307

NB: After design work is done, this issue will be transferred to monorepo for implementation.

- - -
@toiletgranny commented on [Wed Sep 28 2022](https://github.com/Joystream/marketing/issues/289#issuecomment-1260704841)

Note to self: start with low-if sketches

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203133453263218) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
@bedeho @dmtrjsg My recommendations on how can the Joystream.org website be updated to surface multiple gateways can be found in:
- [This Loom video update](https://www.loom.com/share/47dca42e11a04431b7a1d317f6b36edd) (~11 min at 1.5x speed)
- [This Figma prototype](https://www.figma.com/proto/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?page-id=6733%3A291586&node-id=6734%3A304240&viewport=-719%2C-3953%2C0.48&scaling=scale-down&starting-point-node-id=6733%3A344238) (on the prototype, click on the "Claim your channel" button to quickly go to the _Apps built on Joystream_ section, and then use left/right arrows to move between consecutive iterations).

**Comment by bedeho** [comment]
1. Thank you for this presentation, and the new Gleev assets look really fresh, was worth it indeed!
2. I regret us not giving you more support earlier, this was a really difficult problem, with legacy objectives and lots of tradeoffs. From now on, don't presume your problem is well specified just because we ask for something, you are probably often right to come back and demand more clarity.
3. I actually think that, since we have been on testnet for _so long_, drawing the viewer's attention that this having changed makes more sense than the current design does. Feel free to give this message more focus, and to make it clear one can read more about what this milestone means by some CTA.
4. I think the way we "resolve" the current increase in complexity that results in trying to communicate a broader set of things is to remind ourselves of three things. a) the primary landing page for creators will not be this page, it will be the YPP landing page for each app, or just the app page itself. Each app will have an operator who is in the business of promoting the app, not Joystream itself, and this also applies to Gleev. b) the reason we shifted focus to the creator lens for the page was that it was a very easy way to convey what the system actually does to a very broad range of stakeholders, everyone gets it, not only the creators. so it's not so harmful to broaden the messaging a bit, just like we already were doing with the DAO roles, to relay other ideas. c) we will likely need to actively iterate on how this page works as we learn more about what people need to learn in various places, we don't really know enough to make the perfect page right now.
5. Perhaps we should just totally abandon the idea of trying to take a new creator and send them into some specific suitable application. Instead, we just try to explain what the system does in general in terms of generating benefits for creators, and then this becomes the vehicle by which other stakeholders understand the platform in general. **I know this is radical, so let me explain the reasoning behind this hypothetical.** Showing the portfolio of active apps will have a very low chance of working as a way for a new creator to pick what app they should use to publish their work. If you just show generic information for >=3 apps, I think a creator would just get overwhelmed by all the details and even possible overlap in scope between the different apps. Likewise, viewers are not likely to just explore their way to an interesting app based on this sort of breakdown to find interesting content. In both cases, apps need to be doing their own direct acquisition. Moreover, by us aspiring to very specifically funnel people into Gleev specifically, if treated in any kind of special way in terms of CTAs, then it may confuse some people to believe that the whole point of Joystream is to serve Web3-related video content specifically, and one has to probably do a much better job of making it clear that this is not the case. Lastly, it does not step on the toes of the community or crowd out any initiative due to "unfair" treatment on the leading site. So instead, we go for the direct opposite, just as Deso and other project sites do, we try to convey what the project is about, and neutrally present all apps in a uniform way, while those apps do their own work.
6. In all cases, I believe we need a presentation of apps that works very well for our initial state of having very few, so I agree with your point here.
7. If we go with my take in 5, then I think the idea of there being multiple apps, and the benefits this brings, deserves either its own section or being listed as part of the overall set of benefits. Simply listing apps without much context on their significance may be a lost opportunity. I think the main benefit to creators is that they can publish once, and then sit back and have the creativity of all the worlds developer experiment with new ways of connecting their content to new audiences, without being a slave to one opaque mega algorithm, one term of use policy or one product experience, and the creator gets to earn a reward whenever creative developers find new ways to connect them with new fans.
8. I think it's brilliant to have a big separate section towards the bottom that t ries to highlight the opportunity of starting your own app. This deserves ample space. I think the framing should however not be that you are invited to _build your own app_, as this makes it seem like you have to start from scratch, but also our developer experience for third parties is still quite immature because we don't have excellent documentation and tooling. I think instead we should present it as _launch your own video community_,  sort of like starting your own subreddit for your niche, sort of along this spirit: https://github.com/Joystream/atlas/issues/3338. Trying to highlight just how easy this is, like you were doing with the command prompt, is a great idea, emphasizing how it literally takes you less than x mins. We may want to make it clear what the benefits are as well, as app operators can capture part of the value creators and content they onboard generate. So perhaps all of this is meaty enough that we need a new page for anyone intrigued by the prospect of making their own community. Happy to prepare some ideas if you think this is a good path.
9. In the app list we may want to signal what apps are on web vs mobil vs smart tv or whatever platforms we support.

**Comment by toiletgranny** [comment]
> 2. I regret us not giving you more support earlier, this was a really difficult problem, with legacy objectives and lots of tradeoffs. From now on, don't presume your problem is well specified just because we ask for something, you are probably often right to come back and demand more clarity.

Absolutely, will do whenever possible. Look, sometimes, when I see the timing is of the utmost priority, I would simply resist asking additional questions and choose to believe that the information I was given has been considered enough for me to complete the task. It never feels good to be cutting corners and not be doing your job to the standards you've been taught to aim for, but I do it hoping that I'm a team player and that I'm acting in the name of the greater good. Sometimes there's also the aspect of me not knowing what else I could be asking about. Like that time I've been working on displaying different kinds of locks, your tokens might be subject to. In that context, hoping for me or Kuba to come back with questions might be risky. Perhaps, next time we know more context is needed, but we're running short on time to put it all down _on paper_, we could just try scheduling a quick call and talking this through in voice instead? I'm always open to that, just so you guys know.

> 3. I actually think that, since we have been on testnet for so long, drawing the viewer's attention that this having changed makes more sense than the current design does. Feel free to give this message more focus, and to make it clear one can read more about what this milestone means by some CTA.

Of course, putting more emphasis on the mainnet launch banner makes sense when we assume a large (and/or strategically important) portion of the visitors have already heard about the project before. But in any other case, I believe we are better off using the space for talking about other things that get us closer to achieving the site's objective. Speaking of which... (continued in the next point)

> 4. I think the way we "resolve" the current increase in complexity that results in trying to communicate a broader set of things is to remind ourselves of three things. a) the primary landing page for creators will not be this page, it will be the YPP landing page for each app, or just the app page itself. 

I see what you mean, but, at the same time, I also remember we said that it's the creators being the most important target group upon entering the mainnet, as we need their content to start attracting other stakeholders. Unless I somewhat misunderstood things back then, I just want to see if you're not worried we might be now shifting more toward forsaking channel owners too much now. Especially in light of the recent decision to launch YPP sometime _after_ hitting the mainnet. I mean, if this page doesn't attract video creators, then what will?

> 5. [...] Showing the portfolio of active apps will have a very low chance of working as a way for a new creator to pick what app they should use to publish their work. If you just show generic information for >=3 apps, I think a creator would just get overwhelmed by all the details and even possible overlap in scope between the different apps.

Of course, there's no arguing about that. It's just where I'm coming from (and perhaps that's my mistake) is that _this_ is the problem we work towards having. But, for now, all we have is Gleev. And until new apps start showing up, we would have probably gone through another N round iterations of the homepage anyway. So, in other words, it does make sense to put more focus on the only app we have today. That's my thinking there.

> 5. [...] Instead, we just try to explain what the system does in general in terms of generating benefits for creators, and then this becomes the vehicle by which other stakeholders understand the platform in general.

From the sound of it all, it does seem like I might have perhaps overestimated the significance of speaking directly to creators on the homepage. In my defense, I still believe this makes a lot of sense if we believe acquiring quality content will help accelerate the growth of the project the most at this stage. Nevertheless, what other types of visitors do we want to attract the most today? Gateway operators? DAO workers? Who?

> 5. [...] Moreover, by us aspiring to very specifically funnel people into Gleev specifically, if treated in any kind of special way in terms of CTAs, then it may confuse some people to believe that the whole point of Joystream is to serve Web3-related video content specifically, and one has to probably do a much better job of making it clear that this is not the case.

That's a fair point. Are you saying that reverting product screenshots back to Atlas, with "The Joystreamers" being the sample content, will be putting us on the safer side in terms of this? Because if so, then I'm fully on board with this.

> 7. If we go with my take in 5, then I think the idea of there being multiple apps, and the benefits this brings, deserves either its own section or being listed as part of the overall set of benefits. 

I like this idea lot!

> 8. [...] We may want to make it clear what the benefits are as well, as app operators can capture part of the value creators and content they onboard generate. So perhaps all of this is meaty enough that we need a new page for anyone intrigued by the prospect of making their own community. Happy to prepare some ideas if you think this is a good path.

This sounds interesting, but I think I need some time to let that sink to see if I think it's a good path. But knowing what benefits you were thinking of would be very helpful for me now.

**Comment by dmtrjsg** [comment]
I think we need to step back a little and remind ourselves that joystream.org landing page is the entire project page and it needs to explain this fact as a primary message. There a few things we need to convey, and I suggest to present them in this order:

1. Joystream is network for video streaming service and we are now on mainnet. 
2. Joystream is built with having multiple gateways at its core.
3. Joystream is a DAO, and there is a genesis company JSGensis that helps to take it off the ground.
2. JSGensis developed the Gleev App that showcases the features of the network and we chose to focus this app on Web3 vertical.
3. Gleev will be coming soon with all the great features for creators are already available > Go check it out
4. YPP Programme is coming soon to help creators get started, but uploading with Gleev will have benefits with other apps. 
5. Pioneer is the DAO App, check it out if you are after this type of contribution.. 

I don't think featuring all apps on the joystream landing page is a good idea, as there's too much, but having a dedicated page discoverable from the top menu and a secondary CTA from Gleev App Section (view All Apps >) would be better. 

ALT:

We are speaking to three groups of customers: 
Creators / Operators/ Contributors (DAO folks) 

We may want to look at routing them to specific sections of the homepage based on that. Routing can be placed to the We are Joystream, we are on Mainnet now section, which would prob need to take over from App specific screenshot featuring Gleev at the first sight.

Keen to hear your thoughts on this and happy to schedule a call to get us aligned before the next iteration. 

Its a tough one, but we just need to get the flow of the narrative right, which I think is possible as long as we really understand who we are talking to and in what relative order of importance..

**Comment by bedeho** [comment]
Ok, this got very complex very quickly :D. Let us jump on a call and try to reach some shared understanding.

> I suggest to present them in this order:

This specific proposal did not make that much sense to me, but happy to take a full view of the entire page on this call.

**Comment by bedeho** [comment]
# Meeting Summary

We decided that we will 
- primarily focus on explaining Joystream as a platform for applications
- show variety of applications that exist on top at any given time: which in teh beginning will be a low number: 1
- use Atlas in-app visuals to communicate feature-set that exists in general
- entice prospective app-builders to learn more.

In order to support Adam in his pursuit to find some new prominent visual to communicate Joystream as a platform, I have tried to quicky summarise what happens at the platform, vs. what happens in applications. At the top level of this list I am ordering things in terms of :

NB: don't take this as well written copy, just trying to convey a summary quickly. Oh, and def. don't try to convey all information in this breakdown :D Its not all equally important by a mile, just wanted to do a braindump.

- Blockchain: This is the shared and public backend which holds the most important state
  - Content & Socials: all the channels, videos, likes, comments, reactions.
  - NFTs: each video can have a 1-1 ownerhsip NFT, with built in auction and sale marketplace features, and royalties for creators
  - Creator Tokens: each channel can have a 
  - Operations: All operations, inlcuding content moderation, development, infrastructure, marketing, etc. , is done by workers paid to contribute directly to the DAO.
  - Governance: Users can direct the policy and finances of the system through an open governance mechanism, with built in discussion forums and proposal system.
- Storage System: all the video, images and assets in the system are stored on community run, and incentives, infrastructure. 
- Content delivery: all the video, images and asset in the system are delivered through a community run, and incentivised, low latency content delivery network.
- Applications: 
  - each application brings its own discovery algorithms, terms of use policy, form factor and possible vertical focus.
  - creators can publish in one app, and reach audiences in another. Earn rewards bothf rom the DAO directly (payouts), but also through digital assets.
  - consumers have a portable persona across all apps, and bring their assets and data from one to the other without friction.
  - can be built from scratch, or most easily just by forking Atlas, our whitelabel community video platform application. Apps

**Comment by bedeho** [comment]
Let me add one more curveball 😅 

In order for there to be a sort of programmatic listing of gateways, as we imagine, there needs to be some changes on the backend, specifically this https://github.com/Joystream/joystream/issues/4307. We cannot expect that to be done by the time we launch on mainnet, hence this means we are left with two choices w.r.t. listing specific gateways

a) we need a variation that works without listing any explicit gateways at all, which we use until the issue above has been implemented and we are happy with there being at least a few of them, including Gleev, that make it look reasonable.
b) we need a variation which _just features gleev_ as the first and only listable gateway, but still retains the idea that this is not the only one forever, or even a special one.

Ok, I will shut up now :D

**Comment by toiletgranny** [comment]
Alright, @bedeho, @dmtrjsg, a new iteration is ready to be reviewed. Find out all about it from:
- [This Loom video update](https://www.loom.com/share/cecf28b9e49b439183fb8b0b2910977f) (~9 min at 1.5x speed),
- [This Figma prototype](https://www.figma.com/proto/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?page-id=6733%3A291586&node-id=6778%3A312078&viewport=-6312%2C-462%2C0.7&scaling=min-zoom&starting-point-node-id=6778%3A312078).

**Comment by bedeho** [comment]
- Thank you very much for this partial iteration, it's actually great to do it often and early ;)
- The way you showed the same content on different apps was **brilliant**. I am not sure its worth going into all of these nuances, but remember that comments, channels, reactions, profiles, ownership information about NFTs, that is all portable across apps, so you could take this one more level deeper by also having that information blend into the apps, but it may be a nuance which is not going to be perceived by a newcomer anyway. It also just may be way to complicated.
- I think variation B is best.
- I think its perfectly fine to skip the section on apps entirely in the initial stage, as you said.
- I will let Dmitry review the copy!
- YPP: To me, YPP is always associated with a specific app, where a given app may or may not chose to display it, and if I am part of the YPP program in one app, I will not have the same status information about that in another, hence I think really we should not have a section like this. I think the only way to include YPP as part of the general website would be as part of the features that Atlas offers would-be app operators, so they understand its easy for them to get new creators to get onboarded into their apps. But arguably this is so specific to the app operators taht its best to include in a deeper section or page which doubles down on trying to convert such operators, which currently seems a bit out of scope.
- In terms of benefits for for app-builders, I think its more than sufficient to just have a short blurb like you have now, just so people understand its a thing, and some extra interested people can organically discover it. Later we can treat this more deeply. Later there will also just be more informatino to present, like amounts being paid out to operators.

**Comment by bedeho** [comment]
Slept on this, and a few additional remarks came to mind
- https://www.figma.com/proto/3uoobZkRhFF4yibFjCWa2D?node-id=6778:312078#293488346
- https://www.figma.com/proto/3uoobZkRhFF4yibFjCWa2D?node-id=6778:312078#293491764
- https://www.figma.com/proto/3uoobZkRhFF4yibFjCWa2D?node-id=6778:312078#293500201

**Comment by dmtrjsg** [comment]
Great stuff Adam! 

Just to re-iterate some points from the figma which I also tend to agree with:
1. On section 2 of the multiple apps showing same content, the way how they look could be of bigger contrast in terms of look and feel. 
2. I feel like we would benefit from having a more explicit message saying that the features present here are included to Atlas codebase to pick and mix, and that all of the apps built on top of it can benefit from, or may chose to not include to their app. As the lack of Gleev logo is a little too subtle so we need a bit of emphasis before diving in to all the individual features. 
3. If we are to keep the carousel with recently paid out channels and minted NFTs, we need to reinforce the message that these are across all apps.. Update the title a little for each section, find a better place on the page perhaps and add the App name to the card.. Although a small detail, prob worth not getting lost.

Will review copy tomorrow, perhaps even better to do so if you decide to move forward with the alt approach that Bedeho suggested in Figma for the build your own app section 👍

**Comment by toiletgranny** [comment]
Alright, @bedeho, @dmtrjsg, a new iteration is ready to be reviewed. Find out all about it from:
- [This Loom video update](https://www.loom.com/share/4580dbbe5dcb4872a3b32bf534282801) (~8 min at 1.5x speed),
- [This Figma prototype](https://www.figma.com/proto/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?page-id=6733%3A291586&node-id=6855%3A360276&viewport=-1189%2C342%2C0.12&scaling=min-zoom&starting-point-node-id=6855%3A360276).

**Comment by bedeho** [comment]
- So first off thank you for this next iteration, I know the inquiries I made were not so easy to pursue within the limited time,but you have been phenomenally productive 😅 .
- I think my point on the mulitple apps section came across a bit too narrow. I really was not talking about supporting mulitple devices per say, Atlas already works fine on multiple devices, though not a smart tv. I was really thinking of just totally distinct applications experiences. This is obviously a very open ended design challenge, and not easy to really flesh out in a short period of time, but just wanted to make that clear. In the end I actually think your new B & C were very complex visually, as you also pointed out being a risk. I think A was best, due to its simplicity, but I actually think the original variation worked better in communicating the original point, again because it was just simpler, but I am not 100% sure on this. I suggest we just skip with your original one, and then we have this variation A to play with in some way in the future.
- You remarked that you still were working on finding different screen to showcase the different apps. My point here was not actually to find a different screen per say, but to just narrowly present content in som eway, and totally forget the app,because all _apps_ will be identical in whatever screen we pick in substantial ways, only the content will be different. Now, I actually think that, unless you have spent any meaningful time on this already, lets just skip it, its a minor point, not worth harping on now, it looks great as is, and we don't know when the next app will show up that we will be comfortable featuring in a deliberate way.
- I think the steps look really clear and enticiing, and we get to hint at there being a business model for folks, so lets stick with this. Copy can be tweaked later.

**Comment by dmtrjsg** [comment]
Great work, super fast turnaround and we are looking at a straight to finish line version already, loving the page composition and flow, with the hero visual it will be simply perfect for launch👌 

Comments: 
1. Re colour scheme I am aware that we will only offer dark mode at launch, but would it be pushing it too far if we created a mock light version for the first section illustrating that the same content will be on different apps altogether? For like very clear visual distinction to get the point across.. Diff coloured CTAs and logo does the job for the attentive viewer, so you may find this point debatable and I'm not pushing for this 👀  Having this done for the original version may bring us to the absolute winning recipe even at a small delay of < 1d to the dev start date, so worth taking a swing on it imho 😇 
2. Since the carousel features channel names, and these will be specific to the app they are created on, I suggest to add a small logo to the carousel cards, for both NFTs and Channels rewarded. 
3. Really liked how features are now compactly fitted to single section with the opening title, I think it makes it very clear that its a platform for launching your own app, and that's exactly how we wanted it 🚀 
4. Hero section landing variation perhaps could start with a diff target audience and go in this order> "Powering... Apps Operators, Creators and Viewers.."

**Comment by toiletgranny** [comment]
Thanks for reviewing this so quickly, as always! I appreciate it!

@bedeho 

Just so that we're aligned on the next steps, I'll finalise the page for Edvin with the following decisions:
- I'll go with the initial option from the 2nd iteration for the "One platform. Multiple apps." section visual.
- I'll skip updating the Gleev visual and skip introducing any other changes to the "Check out apps built on Joystream" section.

@dmtrjsg:
> 1. Re colour scheme I am aware that we will only offer dark mode at launch, but would it be pushing it too far if we created a mock light version for the first section illustrating that the same content will be on different apps altogether?

Given that the entire homepage and Gleev/Atlas visuals are dark, creating a mockup in light mode would make it really stand out, like _a lot_, and I'm not sure if that's what we would want. Here, let me show you: 
![image](https://user-images.githubusercontent.com/35307309/198531447-fa94fd5e-b335-4c65-aa5d-662f02a83bc6.png)


> 2. Since the carousel features channel names, and these will be specific to the app they are created on, I suggest to add a small logo to the carousel cards, for both NFTs and Channels rewarded.

If channels and NFTs will indeed be specific to the app they were created on, then I think it's a very nice idea! But I'm afraid my understanding is different, namely: while channels and NFTs _might_ be created/minted using a specific app, they are not tied to that app in any way later on. And with this understanding, I think putting a logo of an app next to an NFT or a channel would conflict with the high-level point of the landing page, which is that nothing you create on Josytream is bound to a specific app, and that's the point of it. Let me know if my understanding of the system or your suggestion is incorrect. 🙏 

> 4. Hero section landing variation perhaps could start with a diff target audience and go in this order> "Powering... Apps Operators, Creators and Viewers.."

I'm afraid I can't understand what you mean... How about a quick Slack huddle to clarify this? Let me know when you're available.

**Comment by bedeho** [comment]
> Since the carousel features channel names, and these will be specific to the app they are created on

- A channel may be created outside all existing apps.
- A channel may have been created in one app but both managed and consumed most frequeyntly in aother.

So I suggest we do not do this sort of binding.

> Just so that we're aligned on the next steps

Agreed.

> Given that the entire homepage and Gleev/Atlas visuals are dark, creating a mockup in light mode would make it really stand out, like a lot, and I'm not sure if that's what we would want. Here, let me show you:

This actually looked fine to me, and it does convey the variety better. Perhaps I am just not doing a goog enough job of anticipating how this will look on the page? Would it be a lot of work to just try the page with one, then switch out hte asset later if it looks bad?

**Did you feel this was a clear no-go?**

> Apps Operators

I don't think anyone knows what this means, builders or developers is more clear.

**Comment by dmtrjsg** [comment]
Channel payouts: Sorry my bad, I thought channel was app-specific while membership is not.. I rest my case for this point ofc and let's not 🙏 
 Re light variation.. I'd opt in for clarity of the independent apps at the expect of visual congruence. You've prob tried this already but would a 3rd colour in the back closer to white-white be worse then going black again? 😇 
 Apps operators > I guess you are right, its just we used it internally so often so I may become affected now..  After a second thought on considering to swap to  Builders > Creators > Viewers, I think starting with Creators is still better as that is exactly at the core of our mission.. convenience for builders is a byproduct of how we are set out :)

**Comment by toiletgranny** [comment]
> @bedeho: This actually looked fine to me, and it does convey the variety better.
> @dmtrjsg: Re light variation.. I'd opt in for clarity of the independent apps at the expect of visual congruence.

haha, I did not see that coming, ok! 😅  Of course, since I'm in the minority, I'll polish it out and cook up a complete alternative version of this illustration for us to review again and possibly include in the final design. I'll do it over the weekend or first thing next week once I'm back.

@bedeho to answer your question: no, it would not be a lot of work to experiment with this visual along the implementation work, as long as we keep the experimentation _inside_ of each mockup (so, for example: changing colors inside is fine, but changing the shape and positioning of the mockup will be slightly more time consuming once the current version is implemented).

--- 

Meanwhile... @DzhideX, all changes on the homepage are now cleaned-up, finalised, documented, and ready for you to implement. 🚀

- Just like the last time, all you need is gathered in this one Figma page — https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=5719%3A219138
- Also, just like the last time, I recorded a quick video introduction for you, trying to walk you through all of the key changes that we made and show you the things to keep an eye on when inspecting the designs or exporting assets. I recorded it in a rush, and it's a bit chaotic, for which I apologise, but I believe it contains everything you need to know: https://www.loom.com/share/55e3e31166d84436a04ccf596ccc6550
- **As discussed above, please note that the "One platform. Multiple apps." section illustration might be still subject to change, so perhaps you can start with other stuff first.**

**Comment by toiletgranny** [comment]
Ok, @bedeho, @dmtrjsg, let's take a look at this last missing, and prob the most exciting, piece of the new homepage: the new hero section illustration. As agreed on a call two weeks ago, I created low-fi mockups of three possible directions we can take with this, differentiating them by the level of complexity and, thus, the time required to create. Let me know which option you like the most, if there's anything you'd like to tweak in it, or if perhaps there's something completely different that you'd like to try out.

You can find out all about it from:
- [This Loom video update](https://www.loom.com/share/fbd6e707364a43e8aac4efc287e535d5) (~9 min at 1.5x speed),
- [This Figma prototype](https://www.figma.com/proto/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?page-id=6760%3A311699&node-id=7014%3A440124&viewport=-5846%2C-233%2C0.3&scaling=scale-down&starting-point-node-id=7014%3A440124&show-proto-sidebar=1)

**Comment by bedeho** [comment]
I think I agree, option C sounds really exciting, but given how risky it would be in terms of both time, cost and outcome, perhaps we go for a safer but still really ambitious option B, then we can revisit C later.

**Comment by toiletgranny** [comment]
Ok, @DzhideX, it's ready! 🚀 

https://user-images.githubusercontent.com/35307309/200615611-7a6e8ae5-9f6f-4673-9499-5be43bbe45d6.mp4

Everything you need is here:
- Figma file: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=5719%3A219138
- Exported assets: https://github.com/Joystream/design/tree/master/joystream-org/hero-illustration/_export/_Dev
- Handover Loom video: https://www.loom.com/share/c2db94e3ea494241a73655bce768143b
- JS fiddle with a POC: https://jsfiddle.net/toiletgranny/dzmqerx8/122/

**Comment by toiletgranny** [comment]
Moving back to `In Design` in light of recent comments and suggestions.

**Comment by toiletgranny** [comment]
Ok, @DzhideX, the hero illustration is ready to go now. There are two variations now (A & B), but option A is the one that should be implemented first. cc @dmtrjsg 

| Option A :star: | Option B |
| --- | --- |
| https://user-images.githubusercontent.com/35307309/200615611-7a6e8ae5-9f6f-4673-9499-5be43bbe45d6.mp4 | https://images.zenhubusercontent.com/315632044/65202245-f6c1-448e-8442-860bc36e549f/desktop_viewport_preview_b.mp4 |

Everything you need to know is here:
- Figma file: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=5719%3A219138
- Exported assets: https://github.com/Joystream/design/tree/master/joystream-org/hero-illustration/_export/_Dev
- Handover Loom video: https://www.loom.com/share/c2db94e3ea494241a73655bce768143b
- JS fiddle with a POC: https://jsfiddle.net/toiletgranny/dzmqerx8/122/

**Comment by dmtrjsg** [comment]
@toiletgranny Pls update the copy for the Blockchain layer to: 

"Public Blockchain Layer. 

Shared index of content, people and interactions. Content uploaded by creators in any app as well as channel's transactions and engagement are portable to any other app on the network."

**Comment by toiletgranny** [comment]
@dmtrjsg Updated in Figma ✅ @DzhideX Please refer to Figma for the most up-to-date copy on the hero illustration.

**Comment by traumschule** [comment]
probably too late to the discussion

imo "Create your own video platform and set the rules" is the bigger pull than "Upload your first video" but it can be both.

Following dmtr's 7 points i'd risk to show a few paragraphs of text before sending users somewhere else. As said before joystream.org is very strong on visuals but newcomers usually struggle to know specific details to get started or lack context how active this project actually and leave. ("Still on testnet?")

The onboarding to discord approach worked well to catch those with questions, although it may be unknown how many failed or were put off by discord or gave up struggling with membership creation. For example developers (contributors / DAO folks) can be expected to firstly be interested in working code, issues activity and see if there are PR being worked on.

> the idea of there being multiple apps, and the benefits this brings, deserves either its own section or being listed as part of the overall set of benefits. Simply listing apps without much context on their significance may be a lost opportunity.

No or maybe you meant similar: I see joystream.org also as a central ecosystem index with a (has to be) complete and uptodate (community maintained) list of "projects" as in code or instances run by the community or anyone. The reason is there is no other page with that kind of authority to claim to be complete or most "official". To your point it's only a lost chance with lack of context or explanation.

In this sense the structure could look like

(use your own words of course, just outlining topics)

# Joystream 

We build a decentralized video platfom since .. with backing of [link to investors below]. Checkout our GH project to get involved.

Joystream is a web3 project  founded by [jsgenesis] with dozens long-term community members and its customized substrate-based block chain to store video metadata, [governance](link to pioneer) and manage worker payouts. <- i see no risk in technical details being present as long as everyone can just scroll over

## Upload your first video

It's working!

You can start uploading your videos and channels from yt today. [Let's go]

## Start your own video platform

Did you get tired of centralized video hosting with arbitrarily changing Terms of Service and reward schemes? Make a new start with your own video platforms for your friends! We walk you through the process step by step. [Start]

## How it works

here all the fancy stuff

## Start building

List of (JSG / community maintained) code projects with summary (and incentives!)

**Comment by dmtrjsg** [comment]
@traumschule thank you for contributing the ideas, as project website homepage is catering for the variety of personas technical and not, it is important to keep a broad focus for the hero landing, and not just cater for technical audience. Irrelevant content risks of people dropping out. 

Generic section is followed by the sections that are relevant for each group individually. That's what we tried to accommodate for in the first version now designed. Once built and launched it is through the user journey observation and interviewing we can find the best way to iterate if forward based on strategic focus. 

Re full repo of Gateways, this will be accessible from a dedicated page once the number of gateways grow to substantial.

**Comment by dmtrjsg** [comment]
Issue moved to [Joystream/marketing #313](https://github.com/Joystream/marketing/issues/313) via [**Zenhub**](https://www.zenhub.com/)
