### ISSUE TITLE
Update categories icons in line with Gleev content vertical

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3339]
Categories:
Investing
Podcasts
Conferences
Reviews
Tutorials
News
Memes
Interviews
Analysis
Predictions
Trading

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203155930539987) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
and propose new KV images and color values, just like we have them now for the existing set of categories: https://www.figma.com/file/UdBMxrLspjcf6IVYYJS8YP/Discover-page?node-id=1%3A121

**Comment by toiletgranny** [comment]
This is ready to be reviewed and implemented! Designs, docs, and changelog [can be found in Figma](https://www.figma.com/file/UdBMxrLspjcf6IVYYJS8YP/Discover-page?node-id=1825%3A29298&t=Zi64VKH3e45RO3bf-4).

A few remarks:
- @drillprop, just like with Atlas video categories last year, I uploaded images for Gleev video categories to the `atlas-resources` GitHub repository [(link)](https://github.com/Joystream/atlas-resources/tree/main/video-categories/gleev) as uncompressed PNG files, where they can be converted further down to WebP (if I remember correctly, it was you @kdembler, who converted them the last time, [here](https://github.com/Joystream/atlas-resources/tree/main/video-categories/atlas)).
- @dmtrjsg Since now we know that "display" video categories can be defined by gateway operators (which we didn't account for when implementing the Discover page for the firs time), I added designs and docs for handling video categories with unspecified colors, icons and images. I created a fallback icon and included recommendations for colors to be used in such a case.

**Comment by eclipsingbinary** [comment]
Gleev Crypto Art category thumbnail
![gleev crypto art category thumbnail](https://user-images.githubusercontent.com/91294388/213791981-4c25d3bf-faef-4073-9f76-cd188094df1b.jpg)

**Comment by toiletgranny** [comment]
Thanks, @eclipsingbinary! I'm afraid we don't have a category like that at the moment, though.

**Comment by eclipsingbinary** [comment]
> Thanks, @eclipsingbinary! I'm afraid we don't have a category like that at the moment, though.

Hey @toiletgranny, thank you for replying.

I posted it based on this conversation, maybe I misunderstood
https://discord.com/channels/811216481340751934/1035131444080680971/1066013334341693540
