### ISSUE TITLE
Use absolute upload timestamp in VideoView

### ISSUE THREAD

**Issue by Songoku1691** [Joystream/atlas#3340]
**Is your feature request related to a problem? Please describe.**

Yes I think. Please correct me if I just don't see it. When I watch old videos in Atlas, I couldn't determine the exact date when the video was uploaded. It only shows how old are the videos like 4 months, 5 months, 6 months...

**Describe the solution you'd like**

I suggest to show upload date of Atlas Videos in their description or maybe below the video title.

**Additional context**

Just open any old videos in Atlas as evidence.

**Comment by drillprop** [comment]
That is a good idea but I would opt for adding a tooltip - when you hover on for example `1 day ago` in the video view we could display the exact upload date of the video.
![image](https://user-images.githubusercontent.com/51168865/196361172-6fe2fea2-62cc-4f83-a96e-7730250c4c01.png)

@toiletgranny wdyt?

**Comment by toiletgranny** [comment]
Actually, @drillprop, [designs for the Video page](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=5886%3A300811) have the absolute timestamp for the video upload date, and it's been this way since I can remember. I'm not sure how we ended up using the relative timestamp in the implementation and how it went unnoticed for so long 😅, but if anything, I'd recommend adjusting the implementation to match the designs.

**Comment by drillprop** [comment]
> Actually, @drillprop, [designs for the Video page](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=5886%3A300811) have the absolute timestamp for the video upload date, and it's been this way since I can remember. I'm not sure how we ended up using the relative timestamp in the implementation and how it went unnoticed for so long 😅, but if anything, I'd recommend adjusting the implementation to match the designs.

![200w](https://user-images.githubusercontent.com/51168865/196365047-3f843847-8ff2-4a0a-b294-e1227e575ea7.gif)

Whaaat? Okay, we'll fix this then! 😅

**Comment by Songoku1691** [comment]
Thank you guys!
