### ISSUE TITLE
Create Own Privacy Policy Page for Atlas codebase/ Gleev + Update Terms of Service

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3470]
## Context

1️⃣ 
Currently Privacy policy is linked to joystream.org master policy (link from attached img). This was okay when Atlas was hosted on the sub-domain but with launch of Gleev the GDPR requirements ask for each APP to have its own clearly accessible Privacy policy. Moreover external App operators may choose to modify/ have their own privacy policy. 

<img width="437" alt="Screenshot 2022-12-01 at 14 57 53" src="https://user-images.githubusercontent.com/93924525/205036518-8a9202c2-9024-4d74-b4eb-97a201badf71.png">

Suggested explicit link to be added to the bottom of the extended top nav menu:

<img width="379" alt="Screenshot 2022-12-01 at 15 05 00" src="https://user-images.githubusercontent.com/93924525/205037124-755d0901-de68-46a0-859b-dadd67a3fcdd.png">

2️⃣  Update respective parts of Terms of Service for Gleev to focus on Gleev (replace Atlas mentions with dynamic values)

<img width="700" alt="Screenshot 2022-12-01 at 15 06 45" src="https://user-images.githubusercontent.com/93924525/205037968-9e9e4a55-24d1-4d55-8440-995e06d549ec.png">

## Scope
1️⃣  Privacy Policy
- [ ] Create Privacy policy page for Gleev gleev.xyz/privacy-policy
- [ ] Add link to Privacy Policy to the bottom of the menu
- [ ] Copy content from joystream.org/privacy-policy/
- [ ] ⚠️ Make Privacy policy easily customisable for External App operators

2️⃣  Terms of Service
- [ ] Update "Atlas" to [app name] "Gleev" for JSG run instance
- [ ] Update hosted at "atlas.joystream.org" to  [app dmain] and "gleev.xyz" for JSG run instance
- [ ] ⚠️  hese have to be easily configurable for External App Operators

**Comment by toiletgranny** [comment]
Ready to be reviewed and implemented. Here's the scope of design changes:

1. **Side navigation component**
   
   ![image](https://user-images.githubusercontent.com/35307309/205062928-ee4e6592-6498-44d8-af64-f9e96aa49381.png)
   
   Designs, docs, and changelog [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=9779%3A174960&t=YLvrV6YGVjEA06JS-4).

2. **Content page**

   ![image](https://user-images.githubusercontent.com/35307309/205062833-0e4bb8e2-6a69-43bf-a5f6-39934282c732.png)

   Since we haven't had a dedicated Terms of Service or Copyright Policy page before, and [the ones we have now on production](https://gleev.xyz/legal/copyright) certainly haven't gone through our "design department" (😅), I created a really simple and quick design for how a "content page" might look like. It's more of a layout, rather than a design for any specific page. **Designs, docs, and changelog for this [can be found here](https://www.figma.com/file/wYFxObrO3NxQBOBBw2XdKn/Content-page?node-id=0%3A1&t=CaLuDe5WmBlEYav9-1).**
3. **Markdown** (Optional) (but please)

   ![image](https://user-images.githubusercontent.com/35307309/205068707-1edb42b1-cd3c-4c53-b22b-e7c18a0a05ea.png)

   Another hiccup with our current Terms of Service or Copyright Policy pages is that the actual content inside is just a wall of solid text, with no special treatment for things like headings, lists, or paragraphs. Giving it a tiny bit of design love might send a positive message that things like privacy or copyright infringement issues are not an afterthought.

   Now, since Atlas/Gleev already has a rather comprehensive styleguide, why don't we just use it to render a parsed markdown text? In fact, since this exercise is on our roadmap anyway (we're using markdown in Creator Tokens), together with @KubaMikolajczyk we've already defined the look of basic markdown blocks a while ago. Since Figma, being a design tool, doesn't support things like parsing text or even defining how much margin should be left before/after a heading, we captured our design decisions as design _components_ that are nicely documented and ready to be implemented. **[You can find them all here.](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=10059%3A175251&t=YLvrV6YGVjEA06JS-1)**

   Again, we did all that as part of finalizing creator tokens, but since the opportunity is there, we might as well consider implementing markdown rendering now. If the time allows it. @dmtrjsg

**Comment by dmtrjsg** [comment]
Thank you @toiletgranny for treating this so well 🙏 

I wonder if the way it is going to be built for easy configuration will allow for this implementation.. In fairness we were looking for something quick and practical, but @WRadoslaw please feel free to take a view on this during the implemenation. 

Key focus on having a dedicated page and link in the footer of the top nav + easily configurable in the same way other assets for Gleev are defined as custom parts of Atlas codebase. 

cc @drillprop

**Comment by kdembler** [comment]
I think we should skip all formatting and for the sake of customizabiliy just do the same as we did with copyright policy and terms of service and just use plain text
