### ISSUE TITLE
Creator Tokens: Creator sale & AMM

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#3496]
## Context 

Issue to encapsulate design work on Creator sales & AMM
- https://github.com/Joystream/joystream/issues/4406#issuecomment-1331978319 (Token Sale)
- https://github.com/Joystream/joystream/issues/4406#issuecomment-1334894184 (AMM)

## Scope
- [ ] Creator Journey for both

**Comment by dmtrjsg** [comment]
<img width="764" alt="Screenshot 2022-12-07 at 14 58 38" src="https://user-images.githubusercontent.com/93924525/206166605-fb8b9465-aaae-46b3-b2bb-2259d8d2342b.png">
<img width="788" alt="Screenshot 2022-12-07 at 14 58 47" src="https://user-images.githubusercontent.com/93924525/206166621-78439c3d-2c35-4e0c-9959-549525c0a545.png">
<img width="808" alt="Screenshot 2022-12-07 at 14 58 53" src="https://user-images.githubusercontent.com/93924525/206166629-862ad426-45da-4384-8369-30e80246c4eb.png">

**Comment by KubaMikolajczyk** [comment]
High-fidelity work for CRT Creator: Creator sale & AMM is done ✅
Pages, RWD, user stories & components - a lot of things to unpack - but if you are not a developer you don't need to watch the last part about components (but if you want you definitely can ;) ) - enjoy 👍
🎥 Loom video update: https://www.loom.com/share/0d4a9c7289c24088956f39945da3919d
📄 Figma changelog: https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=670%3A98986&t=0EjJTlcmUzpwhSJO-4

**Comment by dmtrjsg** [comment]
Excellent work 🌟 with the project of this complexity you've done such an excellent approach of carefully keeping the changelog. The best and only way possible to avoid a total brain explosion of the dev team 🤯, so a special thanks for that! 


Inactive sale
1. Is it not worth putting "no ongoing sale" above the table? Just mimicking the same layout as would be with the active sale?

AMM sale Page:
1. For whitelisted token we decided not to put label to the tab. Suggest to do the same here and drop it?
2. For current sale widget, I'd say we would benefit from showing more than 5 rows on a single page as at this point we don't need to allocate much space on the page for Sales history so current sale can take all of the space to the bottom of page fold. 

AMM flow: 
1. Did we decide to fix this param and not show in the FE:
>: "an optional (desired_price, tolerance_percentage). This prevents the order to be executed if the amount of JOY to be exchanged is greater than desired_price * (1 + tolerance_percentage). This also is in order to mitigate slippage risk" was reflected somehow?

2. also this: 
>"an optional deadline timestamp in such a way that if the order (the actual TX for the extrinsic) cannot be executed after the provided timestamp. This is in order to avoid slippage"

Sales history:
1. Why did we go for splitting the tables into AMM and Creator? Quite likely to have 1 and 2 or a few of both kinds that would nicely fit into the same list. On the similarity of data to display isn't the most important info is CRT sold and JOY earned an applies to both?

Closing AMM: 
1. ~Seems like the threshold to close the AMM will work in a different direction. So to close the AMM someone would need to BUY the CRTs for the required amount (so that AMM treasury becomes low)~. @ignazio-bovo can you pls confirm or did I mix it up based on your statement below.. Also what is `provided_supply` again? dm: Resolved ✅ 
(in the video its 34:23) Original condition:
"provided_supply/total_supply <= THRESHOLD and THRESHOLD is a governance set percentage number. This is meant to allow CC to close the Amm only when the provided_supply is low wrt to the token total supply (i.e. AMM treasury amount is basically empty)."

**Comment by dobertRowneySr** [comment]
Suppose I am a CC and I start the AMM sale. My outstanding total supply for CRT is say 1000 CRTs.
You come and buy 100 CRT from the AMM in exchange for some JOYs which will end up in the AMM treasury.
Now the total supply is 1100 CRTs = 1000 CRTs origin supply and 100 CRTs minted through the AMM (this is what I have called **provided supply**, because the variable in the code is named `provided_supply`, but you can call it AMM-provided supply, if that helps).
Analogously if you change your mind and sell back the 100 CRTs to the AMM the total supply will be decreased by 100 CRTs (becoming 1000 CRTs again) and so the provided supply (becoming 0).
Now suppose that the `THRESHOLD` for closing the AMM is 5%, the total supply is 1100 CRTs and the provided supply is 100 CRTs.
This means that I (the CC) can close the AMM only when the provided supply is less than (or equal) 5% of the total supply (in this case 55 CRTs = 1100 * 5%/100%). So I need someone to sell back at least 100 - 55 = 45 CRTs in order to close the AMM.

**Extreme Case**: if the `THRESHOULD` is 0% that means that every token that users have bought from the AMM must be sold back to it before the CC can close the AMM

**Comment by KubaMikolajczyk** [comment]
Thank you for the feedback @dmtrjsg <3

>Is it not worth putting "no ongoing sale" above the table? Just mimicking the same layout as would be with the active sale?

I would vote against it because we don't have any other data that we can display next to it - we cant even display empty widget tiles as the data is different between AMM and Creator sale - so it would look bad - but I visualised it below so you can see how it would look.
![image](https://user-images.githubusercontent.com/31144205/207039483-9468c5c0-982c-4688-a4b9-ce44273cc774.png)

> For whitelisted token we decided not to put label to the tab. Suggest to do the same here and drop it?

The whitelisted and sale is a different case in my opinion - here with a label we can easily present the state of the sale even without going inside the tab or looking in the widget on the dashboard. So user can quickly tell if there is a sale or not.

> For current sale widget, I'd say we would benefit from showing more than 5 rows on a single page as at this point we don't need to allocate much space on the page for Sales history so current sale can take all of the space to the bottom of page fold.

Current sale widget displayed up to 10 rows by default as all other tables and can be expanded by the user to up to 50 rows per page by using table pagination component :) 

>Did we decide to fix this param and not show in the FE:
: "an optional (desired_price, tolerance_percentage). This prevents the order to be executed if the amount of JOY to be exchanged is greater than desired_price * (1 + tolerance_percentage). This also is in order to mitigate slippage risk" was reflected somehow? also this:
"an optional deadline timestamp in such a way that if the order (the actual TX for the extrinsic) cannot be executed after the provided timestamp. This is in order to avoid slippage"

Yes we resigned from having those advanced options included early on the exploration phases due to making the scope smaller - do you want us to explore it? 

> Why did we go for splitting the tables into AMM and Creator? Quite likely to have 1 and 2 or a few of both kinds that would nicely fit into the same list. On the similarity of data to display isn't the most important info is CRT sold and JOY earned an applies to both?

Its due to the different nature of both of those sales - on one users can buy and sell and the price per token will rise and fall (AMM) and on the other users can only buy and the price stays the same all the time - after few tries to make it one table we decided to go with two separate as this would create a lot of confusion if we try to connect them

@ignazio-bovo wow man <3 this explanation was really clear - thank you

**Comment by bedeho** [comment]
- **Sale History:** My assumption is that most channels will do either 0, 1 or 2 sales, where the last is always an AMM. I think its very unlikely that someone does many creator sales in a row, because once they do one, they will want to launch the AMM, and unless liquidity dries up they will want to keep that running, also because community will want it. If they do more, it will be either because something went bad with the first AMM, or they every so often want to sell again. All of this is speculation though. I think the suggested complexity in displaying and controlling the display of sales history is overkill for these patterns of use, and its too complex. It would really be better to have no history view than all of this, because I just don't think its that important.
- **The notion of a Sale:** I think we have gotten stuck in a bad use of terminology which is making the product confusing, by referring to the AMM as a sale. The "public sale" is a real sale, in that the issuer is giving away $CRT to get $JOY, where the latter is a sort of unit of account/cash for the creator asset market in Joystream. The "AMM sale" is not a sale, its a market maker, and both $JOY and $CRT is being sold, in principle. These two activities are only related in that you can only do one or the other at any given time, other than that, they are just two distinct features, and calling it an "AMM sale"  and "creator sale" is not great. Even the term AMM is not great. Firstly, too complex - just a technical name which does not help the user, also AMMs mostly refer to a different kind of asset exchange mechanism to what we are using. I don't know what we should do here exactly, I don't know of some other concrete alternative which is better, I also don't know how much of the current design breaks for you to change this now, which is worth keeping in mind, because this problem is not of infinite significance, that is for sure. I guess I can only raise this issue and ask you to consider whether we are doing as well as we can for the user here.
- On a related note, and regardless of what we do about this sale concept, I believe I already suggested that overloading the tab "Sale" label like we are currently doing is not great.

**Comment by KubaMikolajczyk** [comment]
# Sales History 
> My assumption is that most channels will do either 0, 1 or 2 sales
That's a fair assumption given the fact that AMM might be considered as a potentially best option for a token to grow. But I wouldn't easily assume that it will be the case most of the times so easily 
1. We are giving an option to start and end infinite numbers of sales - even that possibility alone creates a really high chance that there will be more than 2 sales on most of the tokens during their total lifespan
2. During the tests creators were speaking really fondly of creator sale - this feature seemed new to them as on other platform they could mostly play with AMM - based on that we can easily say there will be more sales 
3. If user likes the AMM and creator sale there is a high chance they will keep opening and closing amm just to make a couple of creator sales in between 

With all of the possible scenarios also the one you mentioned (one two sales and them AMM forever) is really possible but I wouldn't focus only on this one particular scenario as there are a lot of different user types who might interact with this feature in completely different way.

That's why I would consider keeping the history of sales in the scope. What do you think?

# The notion of Sale
I understand that there is a significant difference between Creator sale and AMM + that the AMM is not a sale (at least not the real one). I might be referring to AMM as a sale because we agreed to simplify it for user and enclose it together with creator sale in one action called "start sale". Lets look at it from the eyes of the CRT Creator as it is designed now. Below a screen where we can start a "sale", sales type screen and an AMM screen:
![image](https://user-images.githubusercontent.com/31144205/210539561-40a26a36-f0dd-414e-b464-73a97109ac17.png)

### Are those both sales?

This approach is following the idea that, in a sense, both public sales (also known as initial coin offerings or initial exchange offerings) and automated market makers (AMMs) could be considered types of sales.

Here comes the quote comparing two of those:

>A public sale is a fundraising event in which a new cryptocurrency or blockchain-based project sells a portion of its tokens to the public. Public sales are often used to raise capital for the development of a new project, and they typically involve the sale of a fixed number of tokens at a predetermined price.

>An AMM, on the other hand, is a type of algorithm or system that is designed to facilitate the buying and selling of assets on a decentralized platform, such as a decentralized exchange (DEX). AMMs use various techniques, such as price curves or liquidity pools, to automatically set the prices of assets and match buyers and sellers.

>Both public sales and AMMs involve the exchange of assets (tokens or cryptocurrencies in the case of public sales, and various types of assets in the case of AMMs) between buyers and sellers. The main difference is that public sales are typically one-time events, while AMMs are designed to facilitate ongoing trading of assets. 

### What instead of AMM?

What could we use instead of AMM:
- Automated price setter
- Smart market maker
- AI market maker
- Smart liquidity provider
- AI trading assistant

Lets keep in mind that these alternatives might not be as widely recognized or understood as the term "AMM," so we might want to consider using them in conjunction with a more detailed explanation of the concept. And while term AMM is technical - it has also a concrete meaning which if we try to substitute with another word can be lost. I think I lean more towards using AMM with explanation than using some other term with explanation and additional note that this is also an AMM.

### What can we do?

So far we moved with this through all exploration phases and all testing phases. And though AMM was more difficult to learn by some newbie users - all users from the crypto space recognized the pattern and knew instantly what it is. 

With that said to address this concern, we have two options:

#### Change only copy
We can operate on copy without changing the information architecture - meaning we leave both of those "sales" under one action, there from the screen containing two options we choose one and then we proceed with either creator sale or equivalent of AMM how we would call it
Pros: Less time needed to implement, both actions held together on one page can effectively bring the message that only one can be active at a time

#### Change copy and structure
We change both copy and the structure of entry points for both actions to clearly define that there is a huge difference between both them. This will need more time for exploration and revisiting those patterns - also potentially if we split them we will have to explain why only one can be active.

### What I would recommend

First of all sticking to naming it "AMM" this is a pattern already known and will most probably become more known over the next years. And while "AI trading assistant" can sound better I feel like the alternatives could bring us even further from the true meaning than simply putting AMM and explaining what it is.

I would also focus on adjusting the copy in such way that it can address the issue and educate user better instead of changing the whole structure at this point in the process. 

In no way I am a copywriter so this approach would for sure need adjustments but below you can see a possible solution which won't require a lot of time input:
![image](https://user-images.githubusercontent.com/31144205/210568113-0b043ec4-e166-405f-872b-9fed818dd709.png)

# Sale tab

I won't fight really hard for it. The pill next to the tab "Sale" was supposed to ease the user recognition of currently running sale. But I can remove it if you feel its too much ✅

**Comment by bedeho** [comment]
> That's why I would consider keeping the history of sales in the scope. What do you think?

Even if you are right, I don't know at what number it becomes an important thing to separately have very easy visibility over. So then I would say, no now, and then it can be introduced later. Also, if we later go for a general history/event page, as I mentioned in the other review comment, then that may also partially address the need.

> The notion of Sale

What if we just name them
1) Sale (no need to say creator)
2) Market

These are two independent tabs, and you only show the relevant tab if that feature is active, the way you launch the feature is with the button "Start sale or AMM". This also simplies the current "Sale" screen, because it avoids having to multiiplex two different things in one area, which is leading us to have meta ocncepts  like "type", or sale history type selectors (which I am not for anyway, but its just a symptom of the broader issue).

**Comment by KubaMikolajczyk** [comment]
OK 
To sum up 
1. I will remove the sale history which may be later added in the future on this general states page
2. I will rename the creator sale and AMM to "sale" and "market"
3. I will fix the flows so now we have two separate tabs for sale and market

**Comment by dmtrjsg** [comment]
Adding my 5cents: 

1. @KubaMikolajczyk Summary and actions - sounds like a good way to simplify it based on all the comments and opinions exchanged, please feel free to go ahead 👍 

2. Re `desired_price`, `tolerance_percentage` which mitigates slippage risk; and  an optional `deadline timestamp` to avoid slippage, seems quite important to me so could be added under "advanced" settings.. but I'd also like @bedeho to chime in on this 🤔  

So suggest adding them to this screen:

https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=839%3A147378&t=ItPRDZUPV0Jw7SEX-1

<img width="715" alt="Screenshot 2023-01-12 at 12 33 13" src="https://user-images.githubusercontent.com/93924525/212067632-24f13c8e-4ad2-40d7-967a-f38a7485399b.png">

**Comment by bedeho** [comment]
> Adding my 5cents:

We agreed to not do any of this.

**Comment by KubaMikolajczyk** [comment]
🟢 Update after feedback for CRT Creator & Viewer | Removing sections, Sale & Market, Revenue share
🎥 Loom video: https://www.loom.com/share/3a441d4c7bba4f0b99d8531da984ac8b
📄 Channel page changelog: https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1624%3A85414&t=9LSU5rQo1PxdSNma-4
📄 My token changelog:  https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=925%3A139042&t=Jen95QDQKLIYpAWi-4

**Comment by bedeho** [comment]
https://github.com/Joystream/atlas/issues/3445#issuecomment-1410738037
