### ISSUE TITLE
Flash of YPP LP when going to dashboard

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3499]
https://user-images.githubusercontent.com/12646744/206176646-d97bbd77-bc21-4aa0-8a21-d850be0734dc.mp4

See the attached video, after I click "Go to dashboard" from the landing page, I get redirected to Studio but the YPP LP appears for a second again and only after that the dashboard shows up. We should go to dashboard directly without this flashing

**Comment by drillprop** [comment]
I think we would need to add some loader on `studio/ypp`. Let's say someone goes to the `studio` directly and click ypp on the sidebar. He will see ypp landing for a few seconds until we get all the information about verified user channels and then he'll be redirected to the dashboard. That's not a good experience. Maybe we should show some loader until we get all the needed data?

**Comment by toiletgranny** [comment]
@drillprop How about this one? https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=216%3A74181&t=WIuWaIrPCyBFfIBK-4

We could center it out (both vertically and horizontally) and display it for the time of loading. Since I can see it only takes a second, I don't think we need anything more than this.
