### ISSUE TITLE
Aut0-sync status display

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3555]
## Context

- https://github.com/Joystream/atlas/issues/3449

Design 

[LINK TO BE UPD]

## Scope
- [ ] Fetch info from backend if autosync is enbaled. if yes - show banner
- [ ] Banner can be closed, this status is saved in local storage

**Comment by dmtrjsg** [comment]
@toiletgranny can you pls add the link to the banner to this issue ty 🙏

**Comment by dmtrjsg** [comment]
[Link to figma> ](https://www.figma.com/proto/DiQrntuI4KlEdudZdlsH3f/How-to-inform-users-that-auto-sync-is-activated?page-id=1519%3A26568&node-id=1519%3A26800&viewport=281%2C192%2C0.08&scaling=scale-down&starting-point-node-id=1519%3A26816&show-proto-sidebar=1)

<img width="1020" alt="Screenshot 2022-12-22 at 14 31 33" src="https://user-images.githubusercontent.com/93924525/209115176-22955e92-c673-4128-bef8-cfa043b9ec1c.png">

**Comment by toiletgranny** [comment]
Alright, @dmtrjsg, @WRadoslaw, this is now ready to be implemented. Please note that I took the liberty of incorporating a few minor 1% UI improvements on the "since we're already here" basis. **Designs, docs, and a full changelog [can be found here](https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=784%3A26965&t=LFkIi79cpy2FRdKF-4).** 

I'm sorry this took a while to finalize. When I opened up the Figma file for the My videos page, I noticed it had been a while since we last visited it, and it needed some more thorough updating and cleaning up.
