### ISSUE TITLE
Post request to /users is not returning email anymore

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3566]
@drillprop commented on [Fri Dec 09 2022](https://github.com/Joystream/youtube-synch/issues/84)

it looks like `tokenInfo` doesn't have a field email.
![image](https://user-images.githubusercontent.com/51168865/206738528-9755b6ec-41fa-475a-9a31-7858bf5a2edc.png)
![image](https://user-images.githubusercontent.com/51168865/206738551-66bdfbbf-b93d-4f3a-90e2-317e6b8b097e.png)
We used email to populate the details form in ypp flow: 
![image](https://user-images.githubusercontent.com/51168865/206738893-fa3aa8e4-f90b-4c8b-b7ea-145623354082.png)

Could be caused by changes to the `GOOGLE_AUTH_PARAMS` in atlas(changing `scope`, or `acces_type`)

---

@dmtrjsg commented on [Wed Dec 21 2022](https://github.com/Joystream/youtube-synch/issues/84#issuecomment-1361149399)

Needs to be fixed on the Atlas side. We just need to add the scope with fetching email connected to YT channel.

**Comment by drillprop** [comment]
it turned out we could fix this only partially. Users can sign up for YPP with their Google and youtube channel accounts. If they choose a channel to sign up for, we will get from the scope an email, that's not the correct Gmail account for example `test-channel-5-4553@pages.plusgoogle.com`. Unfortunately, in this case, it's impossible to read the correct email. We decided to leave blank input when google responds with an email where the suffix is not `@gmail.com`.
