### ISSUE TITLE
Integration for leaving the program and turning off Ypp syncing

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3589]
- [ ] turn off syncing from the settings tab
- [ ] leave the program

**Comment by dmtrjsg** [comment]
That's how it worked for me: 

1. 🔴 Duplicate windows for the signer

<img width="1188" alt="Screenshot 2023-01-19 at 17 53 36" src="https://user-images.githubusercontent.com/93924525/213523010-efadfffd-afe4-4098-a26e-6af104033c8a.png">

2.  🟡 1/3 instead of 2/4:

 <img width="1214" alt="Screenshot 2023-01-19 at 17 53 56" src="https://user-images.githubusercontent.com/93924525/213522931-569e7a54-f415-481d-a32b-6c27bf656399.png">
 
3. 🟡  Would be nice to show some sort of explanation what the person is actually signing on each step of that flow (OR) before signing set expectations that multiple transactions required to be signed. 
 
 
<img width="1174" alt="Screenshot 2023-01-19 at 17 54 06" src="https://user-images.githubusercontent.com/93924525/213523300-0ab465f5-af92-420a-93d7-b98a80063a5d.png">

4. Step 4:

<img width="1166" alt="Screenshot 2023-01-19 at 17 54 15" src="https://user-images.githubusercontent.com/93924525/213523346-6abe9f7d-df71-4079-9296-93ab86f31af9.png">

5. Step 5: 

<img width="913" alt="Screenshot 2023-01-19 at 17 54 32" src="https://user-images.githubusercontent.com/93924525/213523628-619f94c9-a6ca-4613-be65-d135adae6f05.png">

**Comment by dmtrjsg** [comment]
🟢 On a second try (with the same account) it only took two steps, but the signer windows were still duplicated. 

🔴 In which case I think we only need to just make sure the signer windows are not duplicated

## More details

<img width="655" alt="Screenshot 2023-01-19 at 18 15 01" src="https://user-images.githubusercontent.com/93924525/213527188-d5ed8be6-5083-45b1-9c52-56ab1b2bf644.png">

<img width="642" alt="Screenshot 2023-01-19 at 18 15 13" src="https://user-images.githubusercontent.com/93924525/213527111-f105c3a0-9ec1-48f2-9b8f-87ac17769323.png">

**Comment by drillprop** [comment]
I can't reproduce what you show here https://github.com/Joystream/atlas/issues/3589#issuecomment-1397411654. 
What are you doing on these screenshots? Are you opting out or turning off/on syncing? Are you seeing two popups side by side, with 4 steps? What browser did you use? 


In this comment https://github.com/Joystream/atlas/issues/3589#issuecomment-1397412297 (your second try) - two steps are intentional, you need to `sign message` first(this is not a transaction) to authorize the user. This is required to send an authorized request to the ypp backend. In the second step, you must sign the transaction to remove the collaborator from your channel.  https://discord.com/channels/811216481340751934/1035125759687266364/1055109970905006101

**Comment by dmtrjsg** [comment]
Dudplicate windows confirmed, let's only fix that the rest looks good 👌
