### ISSUE TITLE
hide hero video if undefined

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3603]
## Context

Hero video keeps loading state if undefined. 

![Screenshot 2023-01-09 at 19.01.33.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/a75b881e-8cad-4762-a9fe-0ba7b35f7c69)

Would make it easier also for external operators in the early days of launching if this section was optional. 

## Scope

- [ ] Hide hero video section if not set up.

## Additional info

How to manage hero video: 
https://github.com/Joystream/atlas/blob/master/docs/community/featured-content.md

**Comment by toiletgranny** [comment]
@dmtrjsg You asked me to weigh in here, so here it comes. I believe that seeing a prominent hero section empty might act as a strong incentive for a gateway operator to actually specify featured content. Removing it when undefined is an easier, way more convenient way out. Therefore, my concern is that it might lead to seeing more Atlas instances without the hero section, ultimately making apps based on Joystream look less interesting for viewers and making it more difficult for everyone to attract a new audience.

That's why I don't think that's such an easy decision.

If you wish to go with it, though, this would require updating the [Video category hero component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=489%3A88557&t=pMSqDG4Tfifcn8w8-4), so that there's a variant that still displays the category title despite not showing any video. Let me know if you'd like me to come up with a design and documentation for this. Shouldn't take more than an hour.

**Comment by dmtrjsg** [comment]
@toiletgranny yes please that'd be helpful. At launch for the brand new portal where no content is pre-prepared we do not have a way to define this content, so need a fallback scenario.

**Comment by toiletgranny** [comment]
@drillprop Both Video hero and Video category hero components are ready to be reviewed and updated.
- Designs, docs, and changelog for the Video hero component [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=10809%3A189552&t=pMSqDG4Tfifcn8w8-4).
- Designs, docs, and changelog for the Video hero component [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=10809%3A191071&t=pMSqDG4Tfifcn8w8-4).
