### ISSUE TITLE
Gleev Testing

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3613]
## Context

Testing Gleev on Staging Env before release

## Scope

Fix Identified issues:

1️⃣ 

I have created new account and profile: [Link to profile>](https://gleev-git-dev-joystream.vercel.app/member/physicaltunnel?tab=NFTs+owned)

Transferred 100k Joy from Alice (j4W7rVcUCxi2crhhjRq46fNDRbVHTjJrz6bKxZwehEMQxZeSf)  to this member's wallet: j4WrEtcXgYgTxknV4GQXGzpXtqwPTnK3sYEcbb7SsghfBkuRq

Expected result: funds are transferable and can be spent on purchasing NFT
Actual Results: Funds shown under invitation lock: 

<img width="456" alt="Screenshot 2023-01-11 at 17 22 50" src="https://user-images.githubusercontent.com/93924525/211874733-479c570b-befe-475e-bceb-f35d3d386559.png">

2️⃣ 

- [ ] Gleev Content Adaptation Messages not showing:

Specifically:

Welcome message (Cookies banner)
Studio landing page message

- https://github.com/Joystream/atlas/issues/3319

3️⃣
- [ ]  Discover new channels section is empty

![Screenshot 2023-01-11 at 16.57.36.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/7f13e33a-d8b0-4395-bed9-645cb8149a65)

 4️⃣

Expected result: Only invitation lock is shown under invitation lock label
Actual result: Locked funds label shows (tbd) funds balances

Refers to this comment: https://github.com/Joystream/atlas/issues/3604#issuecomment-1376993672

5️⃣ 

- [ ] Published before date

Published before date when field entered, gives error:![Screenshot 2023-01-11 at 17.04.10.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/688f7f82-6de9-4be9-9db2-8f3b0d397ef0)

**Comment by drillprop** [comment]
1. Can't reproduce, works for me. I created a membership and received `100 000` locked funds from the faucet. Then I sent 100 joy from Alice and received a 100 joy transferable balance. Everything looks fine to me. Proof: 
![image](https://user-images.githubusercontent.com/51168865/211882519-fcd9eadd-c470-4c46-a2ab-d527d701fccc.png)
Are you sure you used the correct endpoint in https://polkadot.js.org/apps/ ?

2. I forgot to mention. The cookies banner only shows up if the environment is set to production. It should work on the production.  I can enable it on the dev environment if you'd like. We disabled it because it was annoying during development.  
Regarding, the studio welcome page - yeah, we forgot to change the copy, we'll fix it 


3. I'm not sure what should I do here.  Should I hide this section?  I think this was always like that and no one objected how this section looks. 

4. I don't think I understand. I think the member dropdown shows the correct transferable balance and the correct locked funds. What's wrong with it? Could you paste the screenshot of the label, that you're referring to? 

5. Nice catch, we will fix it 👍🏻

**Comment by drillprop** [comment]
AD. 2, actually I've noticed gleev logo doesn't work well with changes from the atlas repo. It's oversized - I fix this and enable cookies banner/modals also in development. 👍🏻

**Comment by dmtrjsg** [comment]
1. Invitation Lock display. Will retest, I was using Pioneer to do the transfer, so may have used a diff network in the settings. What set me off here as I transferred 100k as well and invitation lock on this playground was also 100k which I was not aware of :D  
2. Studio welcome message - Thank you 👍 
3. Discover new channels - what's the logic for this section? If there is none, are we able to show new channels created over the last week limited to 10 most recent sorted by date of creation with newest first? @toiletgranny is that how it is supposed to work? Pls advise. 
4. Here we still need to change the label to Invitation lock pls and _only show invitation lock_. We don't want to mix up vesting locks with invitation as their use cases are different.
5. 👍

**Comment by toiletgranny** [comment]
> Discover new channels - what's the logic for this section? If there is none, are we able to show new channels created over the last week limited to 10 most recent sorted by date of creation with newest first? @toiletgranny is that how it is supposed to work? Pls advise.

I don't really know how was that supposed to work, as this has been created before I joined the project and I haven't really worked on a home age at any point. What you described is also what I feel this logic could be, but I'm pretty sure that @drillprop can find the details in the implementation and help us understand it.

**Comment by drillprop** [comment]
@toiletgranny @dmtrjsg  this what we show in discover channels: 
```
  # Get list of 15 most followed channels out of 100 newest channels in random order
```
