### ISSUE TITLE
Fix designs for Market/Sale not being stopped by Revenue share

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#3633]
**Overview**
The designs for Market/Sale of CRT were prepared with a belief that active Revenue share will pause the Market or sale and make it impossible for anyone to buy or sale at that time. Current discovery brought by Ignazio & Bedeho revealed that it is not true and the designs need to be adjusted

**What need to be done**
1. I need to re-think the way that revenue share is introduced to the users on the channel page/ token. 
2. Fix the token widget component which currently presents an active revenue share state which replaces the active sale/market
3. Possibly create new revenue share small widget which will be separate from the token sale/market widget and which will inform users about future and ongoing revenue shares.
4. Put it in final designs, make required user stories for it
5. Fix all old user stories which mention old approach

**Estimates**
It will take around 2 workdays

**Comment by KubaMikolajczyk** [comment]
🟢 Update after feedback for CRT Creator & Viewer | Removing sections, Sale & Market, Revenue share
🎥 Loom video: https://www.loom.com/share/3a441d4c7bba4f0b99d8531da984ac8b
📄 Channel page changelog: https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1624%3A85414&t=9LSU5rQo1PxdSNma-4
📄 My token changelog:  https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=925%3A139042&t=Jen95QDQKLIYpAWi-4

**Comment by dmtrjsg** [comment]
Great stuff, a few comments from my end for the revenue share flow:  

### Rev share widget on token page
1. Suggest to put more emphasis on revenue share widget when its due to start in <48hrs.  I think it is easy to miss at a glance as the page is loaded with other details. I believe you had a variation of this timer component in red for <24hrs, worth extending the horison imho.
2. I see no harm in showing "Claim your share" as a primary cta. Equally important not to miss the opportunity. 
3. Is it worth displaying how much was locked in this widget, or add a link to the rev share details from here?
<img width="200" alt="Screenshot 2023-01-31 at 15 37 27" src="https://user-images.githubusercontent.com/93924525/215805634-b7d7f97d-41e6-49f7-9462-244772945d75.png">

### Transaction confirmation toaster
1.  The toaster confirmation message currently focuses on the Locked JBC tokens. I feel like the key here is that 205 JOY tokens have been transferred to the wallet as the rest was already explained in more detail on the preceding stage in the modal. 
<img width="259" alt="Screenshot 2023-01-31 at 15 43 40" src="https://user-images.githubusercontent.com/93924525/215807264-23fa37d6-240e-4cc4-ad4f-dab8158c2f23.png">

**Comment by bedeho** [comment]
Sounds good to me also.

**Comment by dmtrjsg** [comment]
Discussed again the comments on the meeting, and concluded that for staking/ revenue claim it is more likely for the holder to claim share from the portfolio view; and not from token details so moving ahead with a secondary CTA.

**Comment by KubaMikolajczyk** [comment]
All of the final feedback is translated into designs ✅
📄 Figma changelog link: https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=2386%3A171791&t=uxSTUMAuww7Cnfy1-4
