### ISSUE TITLE
Design&Impl: Payouts Table Update

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3635]
## Scope

Update the structure of the table to work with all of the cases below.  

- [ ] Add payout sender (who may be council, some random JS member account or own channel account)
- [ ] Add payout rationale field
- [ ] Add different icons for different payment types

### 1.Council Incentives Rewards 

Channels were initially designed to be paid with Payout Proposal. This involves minting tokens aka "claiming" within the allowance agreed by council and defined in a payload file (binary) added to storage system. Even though the rational field was populated in the human readable file, it was not possible to display the rationale at the time of payment.  It was not a problem since in the MVP version we agreed to have an external tool displaying the payouts channels qualified for and executed, with rationale added there. Based on the recent update it became apparent that we are going to rely on the payouts tab entirely to inform channels. **Wrt technical feasibility, it is possible to reveal the rationale field at the point of payouts being claimed.**

Details on technical implementation are in this ticket: 
- https://github.com/Joystream/pioneer/issues/3073

**What that means:** we want to add rationale field to the table and accommodate rationale from the proposal payout payload. Rationale will only be revealed and populated after rewards are claimed (transaction of claiming rewards executed). 

### 2. Private Transfers via Member remark used by App Operators (YPP programme)

We decided to allow direct payments from App operators to the channels, circumventing the payout proposal used for the DAO-driven incentives programme. It makes more sense for the YPP programme to go this way to increase reliability of payouts and since the channels are paid out from the Operator's funds reliance on council is unnecessary. It was implemented as member remark, where any member can execute payment to channel account with rationale, attribution to channel/ specific video. Now combined with the fact that Apps will be operating like channels from technical pov (on the runtime), the payouts to channels will be executed from the private accounts, that would be used to host proceedings from revenue splits. 

Implementation was done here: 
- https://github.com/Joystream/joystream/pull/4517

More context on this point is here:
- https://discord.com/channels/811216481340751934/1035123033196732427/1064615767846432932

**What that means:** We can show rationale for specific payments to channels done by operators.  

### 3. Proceedings from NFTs:

English auction -  when settled 
Open auction - when finished (time elapsed)
Buy now - when purchased

### 4. CRT payouts

4.1 Revenue splits  - Rev splits from the channel  will be shown in this table once built as part of CRTs
4.2 Patronage - can be also shown here 
4.3 Token direct sales - proceeds will show in this table once implemented. 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203752822160199) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk is there any screens/ components ready to be worked on? @WRadoslaw is out of tasks so we thought he could start on the payouts table if possible.. 

Maybe worth starting from preparing the queries/ exploring the related payout issues.. 

cc @attemka

**Comment by KubaMikolajczyk** [comment]
✅ Hey the whole thing is done - there is a bit more than just few new columns though as the whole file got an update and we have updated screens, stories, rwd - everything is fixed and there are a few minor improvements.
🎥 Loom final video walkthrough: https://www.loom.com/share/5fda16b5d17b4d48b8fb538d1edf109d
📄 Figma changelog: https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments?node-id=2629%3A30363&t=SbOEr9EJwnPqMqP7-4

**Comment by bedeho** [comment]
Thank you for this!

I hope I am not bringing up much new stuff here, but one thing I think we need to be in agreement about here is that this page is serving the purpose of managing payment flows pertaining to the account of a _channel_, either increasing or decreasing $JOY in it, nothing else.

1. Why membership wallet balance on my payments tab of studio for a channel? seems entirely irrelevant?
2. For council payments - which you here call "withdrawal claim", the should really be something like "council reward" and sender should "council". There is no such thing as a "rewards pool", and at any rate its not an actor that can send even if it existed. Also, it should not be possible to customize this icon as you say, because the sender here is not the app owner, it is the DAO itself, as represented by the council.
3. Please never refer to Creator tokens as CRTs anywhere in the product. This is not actually a valid abbreviation, and even if it was, its not one anyone will be familiar with.
4. `PAYMENT INFO `=> `DETAILS` or `DESCRIPTION`
5. Why bother with revenue share? this won't get shipped until many months into the future with CRTs, not now.
6. "Annual reward": this does not go into your channel account, should not be here, this goes personally to you as an owner, same applies to all fees from AMM trading or revenue from doing a sale. The purpose of the my payments page is not to manage funds of a member, but to manage funds of a _channel_. For this reason, $JOY should be the only currency here, not a variety of different creator tokens, or even a possible creator token of the channel.

**Comment by KubaMikolajczyk** [comment]
@bedeho Thank you for the feedback!

1. 
>Why membership wallet balance on my payments tab of the studio for a channel? seems entirely irrelevant?

I wasn't a part of the early discussions when it was decided to include membership wallet balance to my payments tab, but maybe @dmtrjsg can chime in here as (correct me if I'm wrong) Tomasz was working in coop with Dima on this. From my own POV I don't feel its entirely irrelevant as you can inspect your wallet from the same space where you withdraw funds so you have one fluent experience without the need to open any external tools for it. But please let me know Dima what you think about it too 

2.
> For council payments - which you here call "withdrawal claim", the should really be something like "council reward" and sender should "council". There is no such thing as a "rewards pool", and at any rate its not an actor that can send even if it existed. Also, it should not be possible to customize this icon as you say, because the sender here is not the app owner, it is the DAO itself, as represented by the council.

OK so there was a misunderstanding from my side so lets forget the avatar customization part - I will change the rewards pool to :Joystream council" and "rewards claim" to "council reward".

3.
>Please never refer to Creator tokens as CRTs anywhere in the product. This is not actually a valid abbreviation, and even if it was, its not one anyone will be familiar with.

Understood! Regarding this view though - we will drop anything related to Creator tokens on it as it is requested in point num 6 - so no harm here after we remove it.

4. 
> PAYMENT INFO => DETAILS or DESCRIPTION

OK!

5.
> Why bother with revenue share? this won't get shipped until many months into the future with CRTs, not now.

You mean why to bother having it designed here or why to bother have it here at all? I included revenue share here as I'm working on finalizing CRTs (apart from this issue here) so it was a natural thing for me that when updating this whole file I will also add this for the future to implement when the work on the CRT will be planned.

6.
>"Annual reward": this does not go into your channel account, should not be here, this goes personally to you as an owner, same applies to all fees from AMM trading or revenue from doing a sale. The purpose of the my payments page is not to manage funds of a member, but to manage funds of a channel. For this reason, $JOY should be the only currency here, not a variety of different creator tokens, or even a possible creator token of the channel.

OK! The work here was done based on brief above that's why I could make a mistake here. So to be clear: Annual reward (aka. Patronage) shouldn't be shown here, and CRT sales as well. Because those go straight to the member, not the channel? I will ofc remove them from the table.

**Comment by dmtrjsg** [comment]
@bedeho as discussed today it was my oversight re payout destinations, as I forgot that good part of them are paid to member's account and not the channel account.  However thinking about it now, I cannot see how this will be harmful for the payments to membership controller account to get included to this view as well.. 

👉 Let's ship this version focussing on channel accounts only but come back to discussing adding payouts to member accounts when CRTs are going to implementation?

Re **Displaying member account balance in the Payouts as widget** seemed reasonable as the ultimate destination for the channel rewards is the member account, that cannot be changed so worth showing where the withdrawals are actually going to.

cc @KubaMikolajczyk

**Comment by bedeho** [comment]
I disagree with this point of view. I believe it breaks the logic of the information hierarchy. If we want _members_ to be able to manage their own payments flows, then there should be a separate consumer side payments table just for this, integrating CRTs, NFTs, dividend payments, cashing out from cahnnels you own, selling channels and other things. I don't think this is very urgent at all, but putting it in here harms the product.

**Comment by dmtrjsg** [comment]
Acknowledged, let's move forward with strictly channel payment focus 👍 Re widget for the members controller account balance are you strongly positioned for removing it from the dashboard as well in this version?

**Comment by bedeho** [comment]
Yes.

**Comment by KubaMikolajczyk** [comment]
All of the feedback implemented ✅
📄 Figma changelog: https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments?node-id=2629%3A30363&t=ytMPU9OoSA2jdq79-4
