### ISSUE TITLE
Video player UI is huge in fullscreen

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3708]
When the player is in fullscreen the overlay UI scale is too big and bit hard to use. You have to move your cursor almost entire screen height to select an option.

Gleev (this is my 16" Mac fullscreen):
![CleanShot 2023-01-31 at 18 59 13@2x](https://user-images.githubusercontent.com/12646744/215844840-2ad96fdd-b7b8-432e-a1c4-d37432fef60f.png)

YouTube:
![CleanShot 2023-01-31 at 19 02 31@2x](https://user-images.githubusercontent.com/12646744/215845127-a4a70f45-ad5f-4420-8154-841397c153e6.png)

@toiletgranny @drillprop Not sure if it's the design or implementation, what do you guys think?

**Comment by dmtrjsg** [comment]
@toiletgranny @KubaMikolajczyk  can you guys chip in pls..

**Comment by KubaMikolajczyk** [comment]
Hey the design for the fix is done - we replicated the Youtube way of scaling the UI of expanded video player which is 1.125 ratio of font size comparing to default player view.

In our case the change will look as following:
![image](https://user-images.githubusercontent.com/31144205/216581087-e7e990e4-5945-41d5-a248-6043a74b4f6c.png)

This is also documented here in video player docs:
📄 Figma video player docs: https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2090%3A142096&t=1pxOVt51m4KyYXf1-4
