### ISSUE TITLE
Creator: Revenue Share history widget

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3848]
## Context
- #3384 

## Scope
- [ ] Revenue share history widget

Not showing during very first sale
Shows for all other ones

## Design
[LInk to Figma>](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=787%3A107013&t=9ogR3tZzrka32tXb-1)

<img width="834" alt="Screenshot 2023-02-17 at 14 50 46" src="https://user-images.githubusercontent.com/93924525/219626053-2baebf60-90a5-488e-b01a-b349aabf7bcc.png">

**Comment by polikosi** [comment]
All holders - 3
participant in first - 1 holders (it's me - owner tokens)
participant in second - 0 holders
I don't see the percentage and number of all owners
![image](https://github.com/Joystream/atlas/assets/80429191/a0e7bb8a-dd9c-4097-b0e5-b72984b10af2)

**Comment by WRadoslaw** [comment]
> All holders - 3 participant in first - 1 holders (it's me - owner tokens) participant in second - 0 holders I don't see the percentage and number of all owners ![image](https://private-user-images.githubusercontent.com/80429191/288459381-a0e7bb8a-dd9c-4097-b0e5-b72984b10af2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTI0NzIsIm5iZiI6MTcwMTk1MjE3MiwicGF0aCI6Ii84MDQyOTE5MS8yODg0NTkzODEtYTBlN2JiOGEtZGQ5Yy00MDk3LWIwZTUtYjcyOTg0YjEwYWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDEyMjkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OGY1YTUwMjA2YTk1MjQwODlhZDNhOWMxZTU4YzY1Yjc2YTI5ZTI5MDAzZWE2MDAxYzNiZTg5ZDFlOWIwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f-pnwgtly1KrJbueyfXBaUq0TKC38TT8IbUGcGBD3t4)

This is Orion issue, we don't know the number of token holders at a specific time in the past, so we will need to introduce some logic to add this number to the revenue share entity, but the problem will be scheduling this, since ppl can join till the end of the revenue share and there is no runtime event that would trigger it, so we either can introduce some scheduling (more work) or check holders number at the time of finalizing the share by the owner (it will include an error of ppl that got the token after end time, but before finalizing).  cc @bedeho @ignazio-bovo

**Comment by polikosi** [comment]
a somewhat strange calculation of the total number of tokens and the number of tokens that have been claimed by holders.
Holders have been claimed onlu 178 tokens.
![image](https://github.com/Joystream/atlas/assets/80429191/ae84cfff-74f8-48fc-813c-f04014bb784c)
