### ISSUE TITLE
Categories update for Gleev

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4040]
1. Remove `Predictions` category (Remap any existing videos and channels to `Analysis` category). 
2. Remove `Interviews` category, Rename `Podcasts` to `Podcasts & Interviews`. Remap all existing videos from Interviews to `Podcats and Interviews`.
3. Remove `Trading` category, Rename `Investing` to `Investing & Trading`. Remap all existing videos form Trading to `Investing & Trading`

**Comment by bedeho** [comment]
ACK.

**Comment by dmtrjsg** [comment]
@Lezek123 when you are back on Monday pls advise how this would be better executed. This is NOT urgent, pls don't reply while you are on vacation.

**Comment by Lezek123** [comment]
The solution I already shared while discussing this issue w/ @attemka would be to introduce new metaprotocol actions, allowing the Content Working Group Lead to remove categories and assign videos to different ones. This should be possible without any changes in the runtime, because:
- Video categories are purely a metaprotocol concept and don't have any runtime representation
- We have a generic extrinsic called `lead_remark` in the runtime which was introduced specifically to support new metaprotocol actions like this

How we can do this:
- Add new messages in `@joystream/metadata-protobuf` like `UpdateCateogryOfVideos` and `RemoveVideoCategory`. Those messages should be the new `oneof` variants of `RemarkMetadataAction`.
- Add a new CLI command to make it easier for the lead to submit a `lead_remark` extrinsic with the new metaprotocol actions.
- Add mappings in Orion to process those new actions.

It may also be advised to add respective mappings to QN as well, unless we decide to drop the content mappings completely from QN earlier.

**Comment by bedeho** [comment]
I think I initially interpreted this issue totally different to the direction it has taken. What I believed was being contemplated was to work for an improved organization of content _in Gleev_. I don't actually know what categories exist on-chain vs. in Gleev, which I will from now on call on-chain categories and Gleev categories , respectively, perhaps the two spaces have identical categorization so far. 

Either way, I don't see why there is a need to introduce a new notion of the DAO having editorial power over what categories exist and what content lives in what category, in order to solve this problem. My understanding is that in Gleev, the operator is totally free to aggregate public categories into gleev categories for presentation purposes. If it is important for us, as Gleev owners, to specifically include only a subset of videos in a public category in one of our presentation categories, then the least invasive engineering change is just to allow expressing more complex rules in Orion about what to include or not.  This requires less engineering, likely may be needed anyway, and sidesteps having to deal with difficult conceptual problems around whether it's even acceptable for the DAO to manage metadata owned by the creator in this way. It will also be entirely infeasible for the curators to, as matter of ongoing business, be involved in managing and moving the categorization of eventually hundreds of thousands and millions of videos. This would on  recurring basis involve monumental migrations running on QNs as a result of very complex bureaucratic process which has to make sure to not break expectations of all the apps running on top.

**Too be honest, and in retrospect, I'm not even sure its worth doing any acrobatics to make sure we don't loose existing videos when display categories are changed**. Realistically, there is just not enough content for this to really be an important matter compared to all the things that would get delayed, even if we did the fix the way I am describing, which takes radically less time.

**Comment by dmtrjsg** [comment]
Ok so let's just kill: 
- predictions
- trading

Interviews: 
- leave it out of scope, as after we reviewed the content Interviews has DAO strict content and not really falling under podcasts category. 

Rename Investing to Investing & Trading
