### ISSUE TITLE
Collapsible NFTs component

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4124]
Part of #nft rework

![Screenshot 2023-04-26 at 14.06.31.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/4a316c30-6e52-46b9-9f60-f329514d0764)

**Comment by drillprop** [comment]
I opened PR #4140 but I don't think we should merge it. The design work is not finished yet. 
In [figma](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video?type=design&node-id=7348-321558&t=scHhEjwBDrXSE2JJ-4)  Kuba provided only some propositions how this could look like. 
In my WIP implementation, I already spotted some issues on the smaller and medium screens: 
![image](https://user-images.githubusercontent.com/51168865/236778533-c6156c8b-39d6-45d2-a852-60c2cf4f2f5b.png)
The NFT widget header feels squished with the "On auction" pill. Also, should we show the "on auction" text when NFT is "buy now" only?  
Besides that, the NFT widget component is not updated.  https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video?node-id=2077-112136&t=52piT6lRXTew5yXV-4
I'll wait for @KubaMikolajczyk to finalize the design and will update my PR accordingly.

**Comment by KubaMikolajczyk** [comment]
I explored all possible options for addressing this issue and consulted the results with @drillprop 🙇 In the video overview I showcase my exploration process and the recommended solution which both me and Bartosz support. @dmtrjsg @bedeho  please review when you have a moment:
🎥 Video update: https://www.loom.com/share/f5643b4fe89c416d911e8118eea8ea4f

**Comment by dmtrjsg** [comment]
Excellent work there, nicely triangulated across all cases so from my side I can only agree with you guys 🤝 nothing to add other than well done!

One question on the expanded vs collapsed state by default. You said when users are browsing Videos vs NFTs.. are you saying we need to distinguish this for the previous page, from where the video was opened. I guess doable, @drillprop are you also aware of this part in the designs?

Collapsed:
Homepage > Videos
Channel > Videos
Discovery > Videos


Expanded: 
Marketplace > NFTs
Profile > NFTs
Channel > NFTs tab
Studio > My channel NFTs

**Comment by drillprop** [comment]
> Excellent work there, nicely triangulated across all cases so from my side I can only agree with you guys 🤝 nothing to add other than well done!
> 
> One question on the expanded vs collapsed state by default. You said when users are browsing Videos vs NFTs.. are you saying we need to distinguish this for the previous page, from where the video was opened. I guess doable, @drillprop are you also aware of this part in the designs?
> 
> Collapsed: Homepage > Videos Channel > Videos Discovery > Videos
> 
> Expanded: Marketplace > NFTs Profile > NFTs Channel > NFTs tab Studio > My channel NFTs

yes, I'm aware and it's of course doable with not a lot of effort, we talked about this with Kuba during our meeting.

**Comment by bedeho** [comment]
# Feedback: Collapsible NFT Widget

Thank you for this exhaustive review, that is really great, here are some thoughts

1. I agree that the final variation was better than the others.
2. I very much agree that avoiding the small down arrow is very valuable, instead having a large clickable area witha hover effect is much better.
3. I think it is an excellent idea to open the player in a different state depending on where they are coming from.
4. It is unclear to me what preview state indicator is really required here at the top level. The role of the NFT card on the players screen is _primarily_ to share that there is an NFT issued, and who the owner is. The reason for this is to give the owner the social proximity to the content and the creator. 
   - Its not totally clear that its important to signal that an NFT has been issued while it is in the hands of the channel owner and has never been owned by anyone else.
   - Its not clear why detailed considerations about the nature of a possibly ongoing activity should be included, like auction vs buy now vs nothing - and how much time is left, etc. These are relevant only for someone with an extremely hightened background interest in executing a purchase, and doing so without coming through some explicit call to action on another page, or marketing message, where the full NFT state view is automatically shown. This combined set of assumptions seems very slim. At the very least, it should be sufficient to indicate something like `purchasable`, which just is status indicator that you can indeed buy this now, without going into all of the nuances.
5. I feels like we hvae covered this before, but it is further made relevant by what you just showed: Why are we having a distinct visual representation simply to restate, only less clearly, that there is indeed an NFT using `NFT` as a label. If there was no NFT, the whole thing would not be there. Certainly having this static immutable indicator in the same place as other dynamic information seems wrong. If this is meant to simply state more explicitly that this whole card is about this being an NFT, then this should be communicated in a way differnt to the state indictors for an NFT.

**Comment by KubaMikolajczyk** [comment]
Thank you @bedeho 🙇‍♂️ as always great feedback!

> It is unclear to me what preview state indicator is really required here at the top level.

I assume you meant why it is required - from my POV when we took the decision to collapse the whole "NFT" part of the video we were considering primarily the "well-being" of a user who is purely consuming content, when we say that ownership information is important we consider the needs of an owner of that NFT. We considered the needs of those two personas but it is really rare that one user will fall under only one type of persona when engaging with the platform.

The information about the state of the ongoing auction is needed for:
- Viewer who is also a potential spontaneous (impulse) buyer
- Creator who loses potential sales to "just viewers"
- Buyers who use video browsing for "buying" purposes

# Suggestions
1. We can consider remembering the state of the widget (something I talked about with @drillprop) - so when a user opens an NFT widget in one video, do not collapse it, and then opens another video with NFT the widget will be open by default as well
- This can mitigate the issue where users who want to buy NFTs while browsing videos (not NFT tiles) will have to open the widget over and over again each time when they open a new video
- It can also let the user decide if they want to have it open all the time, or not (we could even measure it later in the app to see what is the overall trend)
2. We can exchange the pills we have in the final solution for something saying "purchasable" but:
- We still have to keep it in a separate line due to the fact that scaling of this component gets bad really quickly and when we consider that we would have to use the very similar amount of space to show only that information why won't we show at least some basic details of the state of that NFT? wdyt here? 
![image](https://github.com/Joystream/atlas/assets/31144205/d604218b-61c5-4641-94ba-bff0684ddf14)

> Why are we having a distinct visual representation simply to restate, only less clearly, that there is indeed an NFT using NFT as a label.

I agree - my bad. In the examples above I removed it 👌

**Comment by bedeho** [comment]
> We can consider remembering the state of the widget (something I talked about with @drillprop) - so when a user opens an NFT widget in one video, do not collapse it, and then opens another video with NFT the widget will be open by default as well

Ok, we can try that. I'm not sure its important, but its a very cheap change.


> We can exchange the pills we have in the final solution for something saying "purchasable" but:

Makes sense, lets go with the green dot then ;)

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg @bedeho - Collapsible NFT widget component is done - new components are added, new logic is described and all user stories are updated - everything is here in the video update ✅

🎥 Loom update: https://www.loom.com/share/0979ffb0359c41dd92a97eb1eae11ba2?sid=20b7101c-ba90-4a8d-807b-8c2350d99290
📄 Figma changelog: https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video?type=design&node-id=6396-297910&t=nMLAGOUgLnJ2zCuC-4

**Comment by drillprop** [comment]
The NFT history could be pretty long in the future(there could be a lot of bids in an auction for example), so if a user clicks `Show more` the component can be very high and occupy a lot of vertical space. Should we tackle this somehow? Currently, the NFT history is a section that can be scrolled, maybe we should use the same approach, once a user clicks the show more button? 

Besides this small issue, everything looks fine to me

**Comment by KubaMikolajczyk** [comment]
@drillprop thank you for the feedback - yeah it was tricky part for me too if it comes to NFT history. I think your suggestion is valid to make it scrollable - I will rework this part and implement your feedback.

**Comment by KubaMikolajczyk** [comment]
Feedback is implemented into designs ✅
🎥 Loom video: https://www.loom.com/share/927563f73c1c481bb0f9725465cb501e?sid=2b337c26-3ccf-4b69-b2cd-0474830cddd5
📄 Figma changelog: https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video?type=design&node-id=2077-123384&t=PeZIeauCRo5GHnpJ-4
