### ISSUE TITLE
User Accounts Dev Epic

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4132]
## Context
- https://github.com/Joystream/atlas/issues/1820

## Design

[Link to Figma > ](https://www.figma.com/file/C3hvYPVkZ7TcjAsXfqizSD/User-accounts?node-id=2076%3A106193&t=pr1CoPkxLNk9Fp7d-1)

## Scope

- [x] #4138 
- [x] #4133 
- [x] #4134 
- [x] #4135
- [x] #4136
- [x] #4156
- [x] #4233
- [x] #4235
- [x] #4238
- [x] #4242
- [x] #4243
- [x] #4244
- [x] #4283
- [x] #4284
- [x] #4287
- [x] #4286

### Out of scope
- [x] #4152
- [ ] Enhance security of assets (move to external signer)

**Comment by attemka** [comment]
Questions to discuss:

1.  Storing seed on client side
  1.1.  Possibility of seed encryption to prevent XSS vulnerability
  1.2. Showing the seed in the membership settings - should it be done? Why would we have 2 different account recovery possibilities (seed\password)
2.  Accounts  
  2.1.  Possibility to have the support of membership settings being stored on orion side along with avatar, handle etc.
  2.2.  Should multiple external wallets be bound to one orion account?
  2.3.  Should orion account as an entity has its own naming?
  2.4.  How will transition from credentials to external signer will look like?
  2.5.  One-to-many orion account -> memberships. One-to-many memberhip -> channel. Is it really needed?

**Comment by dmtrjsg** [comment]
MM:

**Seed**

1.1. -> Issue of storing unencripted seed in local storage: 
Cipher key is a more safe approach. Generate on client side and send to server. Stored for the duration of the session. 

1.2. -> should we show seed in membership settings?
seed vs password to get access to account assets. You don't need backend for seed, but need for password. What does it buy us in concrete sense to not have seed in the local storage? Extra step for someone who has data not deliberately but just got the data contained in local storage.Not having it in clear text seems not to be worth the effort and risk of introducing bugs doing it. If we have them in local storage then we might as well show them in the app. 

_To summarise:_
Storing in the app: best not to
Storing in the local storage: worth additional time spent on encryption is worth it. 
Requesting it from server to download: downloads file after prompting user to re-enter password. 

**User Accs**

2.1 Should we store membership assets on Orion? > settings stored on orion acc because of one to one relation outlined below
2.2 multiple external wallets to One orion acc?: No. 
2.3 No, naming same as membership
2.4 Transition from credentials to external wallet -> Security Upgrade is out of scope. Export seed and use it in extension to use other app (e.g. Pioneer). We give. What happens with credentials? 
2.5 One to one Orion Acc <-> One Chain Membership? : Let's go with One to One single bond. 

___ 

➕ Add the design when relationship between chain account and orion account is broken. Like controller account is changed. 
You can browse but cannot interact. 

@bedeho

**Comment by dmtrjsg** [comment]
When relationship between chain account and Orion account is broken:

Here all the cases which will be impacted are same as Anonymous interactions but because user may be logged in to Atlas with their Orion account it is only on the attempt to perform any of the operations the error must be shown in a dialogue or smth. Error stating "On-chain membership and Orion account relationship is broken. Speak to support team on Discord." 

Exceptions, data that is stored only in the Orion account: 
Follow channel
Notifications settings
Change membership details: password & avatar 
Export seed

**Comment by KubaMikolajczyk** [comment]
Hey team! (@dmtrjsg @attemka) 
I had an opportunity today to test the User Accounts implementation and it looks awesome 🙏👌 however I stumbled upon issues that didn't allow me to continue testing and I was not able to create a new account - more about that below.

# Sidenote
## Not able to check wallet sign in
I was not able to check if logging to an already existing membership with wallet works properly (I cannot test that) as I had no membership on dev.gleev.app in the past apparently. And I have to say I like the dialog you guys made for this scenario as it was not covered in designs.
<img width="580" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/afac7510-48b5-4027-a128-2a725f5a8a80">

## Not able to check full sign up
I was not able to move past create membership profile step in create account flow as it was not letting me do so on many different browsers (chrome & arc - restarted a lot of time + restarted mac) - look point 3

## YPP throws this error 
<img width="702" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/3bc26554-2c0f-4fa2-888a-483fc14444f9">


# Improvements
From what I was able to get access to:

### 1. No error on caqptcha validation when member name is entered
When I click continue without confirming the captcha after entering member name there is no error msg below it - should be smthn like this https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2924-50212&mode=design&t=vanLKobUtIYL9tWi-4
<img width="514" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/6f62e4f1-d986-4852-b22e-589f05ef3d20">

### 2. Member handle in constant loading state
When I enter member name and the loading starts it didn't finish on chrome and arc browsers.( the only 2 I use)

### 3. I cannot progress with creating a membership 
Video expalining below:
https://github.com/Joystream/atlas/assets/31144205/c4ee73a8-9d90-40c1-ad48-143f079aa1ab

### 4. No tooltip on password icon button (no show/hide)
When I hover the show icon button on password I should have a tooltip with the action name displayed on top of it - same for hide when its the oposite action I want to perform - it should look like this https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2924-50276&mode=design&t=vanLKobUtIYL9tWi-4
<img width="489" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/49760cf7-6679-417d-aafa-792efc6cbf51">

### 5. Cursor jumps to the beginning of the input when show/hide
When I show or hide the password the cursor jumps to the beginning which is not a desired behavior.
https://github.com/Joystream/atlas/assets/31144205/df742656-624e-4101-ab5e-572853ee792d

### 6. Form validation of change password
We should change the word mnemonic as its not used in the designs to "Enter wallet seed."
<img width="489" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/201ede48-545a-4d47-b840-7b90644cfa67">
<img width="455" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/bfaa07c7-ad60-4323-80dd-ff766d8bc22c">

### 7. YPP not met req dialog is not here
Right now in implementation after we dont meet the requirements for the YPP we are brought back to first dialog in the flow while we have a special dialog for this scenario in the designs - in the designs it looks like that https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=1638-99413&mode=design&t=UQYHHnbGpjTKQl37-4 
and in implementation like that
<img width="673" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/be964200-452a-4fef-8fe0-cd933e288db7">

**Comment by KubaMikolajczyk** [comment]
Hi team (@dmtrjsg @attemka) - I had an opportunity to test the implementation of user accounts more in depth and I found few more elements that we can improve:

# Member & channel dropdowns 
Currently the implementaton of both dropdowns is different from what we can see in the designs. In the member side of experience when we click on my channels
<img width="321" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/3a97f8fb-d7c2-4692-b07c-bb62a7c35e0b">
We can see that the switcher variant of member dropdown is missing the add channel option as the last list item - link to designs: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=3201-112016&mode=design&t=homVxNnb7e4nKZpf-4
<img width="337" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/c6e72176-e225-4d4c-b698-0ea098576798">

On the studio side we can see that the view channel list item option is usign the wrong icon and there is no switch channel option (which should be there also if there is only one channel) currently the implementation is not following the designs and adding add ne channel button instead - Link to designs: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=13465-364894&mode=design&t=homVxNnb7e4nKZpf-4
<img width="346" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/35b49f70-1451-4ca8-a2e1-9632b0cb9007">

When user does not have any channels yet the list item with an action to do that should be titled differently then what we have in implementation: link to desings: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=3201-114969&mode=design&t=homVxNnb7e4nKZpf-4
<img width="324" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/d33a4508-41b0-4f49-9dc6-b7d5e9aea6ce">


# Add new channel
In add new channel dialog the empty avatar field uses the placeholder background (which is semi transparent and it looks bad when on top of a divider) while it should use just a still empty state variant. - link to designs: https://www.figma.com/file/zi5siPUXme0Fivq2i40XBd/My-channel?type=design&node-id=1774-82691&mode=design&t=PK68zUbsRh0yuJPV-4
<img width="519" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/7c105846-47a9-4067-8224-38c9ad98f84a">

On mobile variants the top part of the dialog is not reaching the edges of the dialog but has some added paddings which should not be there
<img width="683" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/5acdf5af-23e9-4110-b9f4-d65b42f96d22">


# Membership settings
In membership settings the empty avatar also uses the wrong styling - link to designs : https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?type=design&node-id=3031-66688&mode=design&t=v5DJiHIP3gNZOcaf-4
<img width="497" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/09a01856-7d92-4e7a-9181-12787e17d484">

When displaying a settings page like member settings but also my channel page where the page tabs are visible on top it would be best to keep this navigational item stick to the top while scrolling to allow user to use navigation at anytime (and not hide it from them)
<img width="1072" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/ccdcfe59-5b01-48b5-b954-0025f9b2c0a4">

On smaller breakpoints on pages where we have a bottom action bar we should make sure thet the action bar is visible for users at all times. Currently when user scrolls up the bottom nav overlays the action bar
<img width="690" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/9a4267e8-27c1-474a-955e-f1c56513e9d3">
Which results in a very weird issue when user has to scroll down to hide the overlaying bottom nav to get access to the action bar
<img width="686" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/7943b3e4-3907-421d-8a72-e299ecaa2016">
Ideally we should aim to move the bottom bar up as the bottom nav appears on screen.

# Studio sign in page
Does not have the icons inside of "sign in" buttons and additionally the bottom footer overlays the buttons at the small screen height - we should prevent this and add content scrolling if the content on the left side is too long. https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=508-58893&mode=design&t=nEcMQRwh04SiKGYx-4
<img width="1060" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/2c44ebac-7f69-46c7-8728-a634b08b2ec1">

# Sign in dialog
The password field's show/hide icon button should display a tooltip with the name of the action while hovering over it - Link to designs: https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2924-50276&mode=design&t=nEcMQRwh04SiKGYx-4
<img width="493" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/b02bb9af-138a-4ac6-ac22-361a8124ba99">

When clicking on show / hide icon button the cursor jumps to the beginning of the input making it a possible pain point for the user using it as this behavior is not obvious. Ideally cursor should stay in one place after showing/hiding password.

# Wallet seed dialog
In this dialog the label on text area of the wallet seed should say "wallet seed" not password recovery seed, also the text area could wrap horizontally under the text to prevent creating this weird empty space below text, additionally please notice that gap between copy to cliboard text button and text area should be equal to 16px, lastly the checkbox label mentiones "mnemonic" which is not featured anywhere in designs: Link to designs https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=3234-77715&mode=design&t=nEcMQRwh04SiKGYx-4
<img width="482" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/835966d7-e56c-4525-bd2d-4b6b2433ab25">

# Sign up password
On password fields on show/hide icon buttons we should show the tooltips when hovering the icon button & also the hide show icon button resets cursor to the beginning of the input which is not a desired behavior ideally it should stay in the same place where user had it - link to designs https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2968-76108&mode=design&t=nEcMQRwh04SiKGYx-4
<img width="512" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/58d0bb43-7639-4c04-a08a-8633dc7ac872">

While entering the password the field does not recognize any of the following character as a special character - see img below
<img width="490" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/883052f6-ff76-4782-8e1c-eec6f0940248">

# My channel 
In my channel page we should also use the correct background for the empty states of the avatar and channel cover instead of placeholder background which is used now - Link to designs: https://www.figma.com/file/zi5siPUXme0Fivq2i40XBd/My-channel?type=design&node-id=1760-98726&mode=design&t=PK68zUbsRh0yuJPV-4
<img width="1365" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/a13a3f20-f18e-437c-95ea-a780967105db">

We should also have the top tab bar stick to the top of the top of screen when user is scrolling - so user will have always access to navigation.

Please notice that avatar component is used in wrong size - it has 136x136 in implementation while in designs we use 88x88 also there should be a different icon used - https://www.figma.com/file/zi5siPUXme0Fivq2i40XBd/My-channel?type=design&node-id=1760-98726&mode=design&t=PK68zUbsRh0yuJPV-4

Please notice that the last section on the page - channel settings in this scenario should not have the bottom divider - link to designs: https://www.figma.com/file/zi5siPUXme0Fivq2i40XBd/My-channel?type=design&node-id=1720-82104&mode=design&t=PK68zUbsRh0yuJPV-4
<img width="966" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/3706af16-4eb5-4edf-9a80-e654e54c4e51">

There is no dialog which prevent user to leave the my channel page after making any changes so I can add new assets for avatar, channel cover and click on view channel button in the top tab bar and all changes will be lost - we should display a warning dialog like this one in designs: https://www.figma.com/file/zi5siPUXme0Fivq2i40XBd/My-channel?type=design&node-id=1754-86898&mode=design&t=PK68zUbsRh0yuJPV-4
