### ISSUE TITLE
Forgot password flow 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4190]
From Orion's perspective, there are no passwords, there are only Gateway accounts and the associated Joystream accounts. If you want to log in to a Gateway account, you always need to provide a signature from one of the associated Joystream accounts.

On the Atlas side, you can either sign the message by retrieving a seed from user's email and password or ask the user to sign it themselves, using an external wallet.

You can also:
1. Ask user for the e-mail, seed and a new password, so that you can re-encrypt the seed and allow the user to continue using e-mail and password to log in, without the need to install an extension.
2. Allow the user to change password once they are already signed in (which would be also available for users that remember their password, but just want to change it), so that they can install an external wallet, import seed, sign in, change password and continue using e-mail + password to sign in, but this would require migrating everything to a new account. 
However it may be challenging on the Atlas side to figure out whether a user is using an external wallet because they already switched to this more secure approach or because they just imported their Atlas-generated seed (which has limited security) to an external wallet.

**Comment by dmtrjsg** [comment]
Going for this> Ask user for the e-mail, seed and a new password, so that you can re-encrypt the seed and allow the user to continue using e-mail and password to log in, without the need to install an extension.

meaning:
On login screen add forgot password> enter email + seed > new password twice > show new seed (THIS IS THE NEW ONE!).

**Comment by dmtrjsg** [comment]
@Lezek123  So we decided to go forward with the following flow:

On login screen add forgot password option > (user clicks), on new modal enter email + seed > next modal  enters new password twice >  (here the seed gets regenerated)> Atlas shows **new** seed to user to save. 

Question: is that already implemented on Orion?

**Comment by Lezek123** [comment]
@dmtrjsg I think the new seed generation is not strictly necessary, there are actually 2 possible approaches:

## Re-encrypting the old seed

1. User provides `email`, `seed` and `newPassword`
2. Atlas encrypts the seed using a `cipherKey` derived from `email` and `newPassword` and posts the encrypted seed to Orion (`POST /artifacts`)
3. User can now login using the `email` and `newPassword`, as Atlas will be able to retrieve the encrypted `seed` from `Orion` and decrypt it using the provided data. The same blockchain account is still used, as the seed doesn't change.

**Pros of this approach:**
- No migration required

**Cons of this approach:**
- Someone who knows the old password can still log in to the user's account, so there are now effectively 2 valid passwords for 1 account (this is another issue which comes from account/artifacts data serpartion, cc: @bedeho)

## Generating the new seed (the approach you mentioned)

1. User provides `email`, `seed` and `newPassword`
2. Atlas **generates `newSeed`** and encrypts it using a `cipherKey` derived from `email` and `newPassword` and posts the encrypted seed to Orion (`POST /artifacts`)
3. At the same time, Atlas needs to issue transaction(s) to migrate assets and membership from the old account (the account derived from `seed`) to the new account (the account derived from `newSeed`). Those transactions will include `members.update_accounts` and `balances.transferAll`. However, **any locked/staked assets will not be transferred**.
4. User can now login using the `email` and `newPassword`, as Atlas will be able to retrieve the encrypted `newSeed` from `Orion` and decrypt it using the provided data. Since the seed has changed, the blockchain account of the user will also change.

**Pros of this approach:**
- `newPassword` is the only valid password after recovery, so it's safer (1 account = 1 password rule is preserved)

**Cons of this approach:**
- Asset migration needs to be performed which requires more effort on the Atlas side
- There is no obvious solution w.r.t. how to solve the locked/staked assets issue, as they cannot be directly migrated to a new account.

**Comment by dmtrjsg** [comment]
@attemka how much of a difference in effort are we talking about? 

@Lezek123 re multiple passwords for same account.. does that mean that user who has access to his account and goes to change the password, in essense just adds another one to his account and the old password will still be working? OR is it only the case with the forgot password flow you are describing above?

**Comment by Lezek123** [comment]
@dmtrjsg It will be the case when both of those are true:
- the old `password` is forgotten/unknown AND
- the assets are not migrated to a new account

Because otherwise:
- If the old `password` is known we can easily add `DELETE /artifacts` endpoint to Orion to solve the multiple password issue,
- If assets are migrated to a new blockchain account, someone who knows the old password would still be able to access the old blockchain account (not Gateway account though, because it can be disconnected from the old blockchain account), but it will be empty at this point, so it doesn't really matter 

However, those are the options we have **unless** we stop trying to maintain data separation between encryption artifacts and user accounts, which is why I cc'd @bedeho, as I think the arguments for not separating this data start to pile up and the argument for keeping it separate was weak to begin with in my opinion (or actually we weren't even able to find any good argument, we decided to do that just because that was the approach taken by the Hedehog library)

**Comment by dmtrjsg** [comment]
Thank you for the explanation. Duly noted 👍  @bedeho awaiting for your steering before we proceed with the implementation.

**Comment by bedeho** [comment]
1. It is at this point unclear to me what the new scheme is, as we did discuss at least one substantial changes in how encryption would be simplified to avoid double encryption. Is there perhaps a canonical statement of how the scheme works you can share, when ready? e.g. as part of the Orion dev docs.?
2. I did not understand why there could be two valid passwords simultaneously, but I think understanding this probably requires 1 to be done first.
3. I do understand the need for migration of assets under the "Generate new seed" approach, but I did not understand the asset migration problem with locked assets con of. All content directory assets are tied to membership, not accounts, so no staking should be relevant there? Nothing obvious on the. Not sure if there is any other form of staking we are having in mind? It could of course be the case that the user some how has taken the raw account and started doing ltos other stuff with it, which Atlas could not migrate, but then presumably the user would have a copy of the seed for those purposes?

>  I think the arguments for not separating this data start to pile up and the argument for keeping it separate was weak to begin with in my opinion

In my understanding, there are three issues (correct me if I am wrong)
- more complexity
- problem with account based login throttling
- possible migration of locked assets problem above, if we indeed choose to go with 

I appreciate those, but I am very hesitant about throwing away this design component when we are not at least able to account for the hypothetical problem it solves, so we cannot even pick a different tradeoff in an enlightened way, we simply would be doing it because we don't know of a good reason for why its there. I give the Audius team the benefit of the doubt in that there is a real case, they are very good, and their design has almost certainly been audited, and they are making an explicit point of mentioning it. My assumption is also that doing a migration in production later will be very complex, so we really need to make the right choice now (correct me if I'm wrong on this).

**Can we make one last attempt at understanding the idea behind this design choice before we deviate?**

I will personally contact the right people, and I'm hopefully it would work. I was able to chase down an answer to these questions in the end on Discord https://github.com/AudiusProject/hedgehog/issues/54, so I am cautiously optimistic.

**Comment by dmtrjsg** [comment]
We have 2 cases:
1. One is change password from settings > here we just delete password and set a new one. 
Design implication: Change password > enter seed > enter new password twice  > ok.  @KubaMikolajczyk  fyi
Orion implication: `DELETE /artifacts` endpoint to be added.  @Lezek123  pls confirm

2. Second is forgot password from "forgot password" > here because we decided to remove the account / artifacts separation we can go with the re-encrypting old seed and changing password from forgotten does not require this. 
Design implication: User clicks forgot password > enters seed + email > sets new password. Old Seed remains active and valid. @KubaMikolajczyk fyi
Orion implication: (atlas uses `delete/artifacts` endpoint to delete the old password once the seed and email combo is verified).  @Lezek123 pls confirm

**Comment by Lezek123** [comment]
The Orion API has now undergone some big redesign due to several factors:
- We decided to introduce a relationship between encryption artifacts and gateway accounts
- We decided to have one-to-one relationship between blockchain accounts and gateway accounts (previously many-to-one)
- We decided to have one-to-one relationship between blockchain memberships and gateway accounts (previously non-existing)

Because of that a lot of the API endpoints could also be simplified, removed or merged.
I light of those changes I decided not to introduce `DELETE /artifacts` endpoint, but instead add a more clear `POST /change-account` endpoint which serves as a way to change blockchain account and optionally encryption artifacts related to a given gateway account.

It is described in more detail here: https://github.com/Lezek123/orion/blob/user-accounts/docs/developer-guide/tutorials/authentication-api.md#change-blockchain-account--encryptionartifacts-associated-with-the-gateway-account

Going back to your questions then:
1. In order to change a password of a **logged-in** user, you don't need to ask them to provide the seed. The tl;dr of what happens here is:
    1. User provides `newPassword` (although Atlas can require other information from the user as confirmation, it's not strictly needed by Orion) 
    2. Atlas already knows the seed (if the user authenticated using a password when logging in)
    3. Atlas re-encrypts the seed using `newPassword`
    4. Atlas signs and sends a request to `POST /change-account` containing the new artifacts and the current blockchain account address (ie. the blockchain account doesn't need to be changed, only the artifacts)

2. This is mostly right (except the `DELETE /artifacts` which won't exist), but to provide similar explaination as I did for `1.`:
    1. User provides `seed`, `email` and `newPassword`
    2. Knowing `seed` Atlas can log the user in (`POST /login`) in Orion.
    3. Once logged in, the flow basically continues the same way as in `1.` (steps `3.` and `4.`), the seed / blockchain account remains unchanged.

**Comment by KubaMikolajczyk** [comment]
Forgot password & change password features are here ✅
Logged in user (change password) : https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?type=design&node-id=3025-79832&t=RWMmx86XTOq9EJbX-4
Not logged in user (forgot password) : https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=3098-78238&t=vwj07DuRIBjZobr3-4

Forgot password needed a log in dialog update which is now using dividers regardless of its size to space possible user actions better. All is described here in changelog : https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2013-33819&t=vwj07DuRIBjZobr3-4
