### ISSUE TITLE
Gallery Error Handler disappears for a brief moment

### ISSUE THREAD

**Issue by fcescob** [Joystream/atlas#47]
Currently, a gallery error handler will go back into a loading state for a brief moment before going back to the correct state.

**Comment by ZK3DEV** [comment]
Could you guys explain how to reproduce this a bit more ? or a screenshot where it's happening would work as well. So I could work on it. thanks :)

**Comment by kdembler** [comment]
@ZK3DEV sure thing!

This happens when the error handler for the gallery is triggered. If there's some error when fetching the data for one of the carousels (Featured videos for example), an error handler is used that will display something like "Error occurred, use that button to try and reload".

So the flow should be: Gallery loading -> Gallery displaying error message

The bug is that the flow is actually Gallery loading -> Gallery displaying error message -> Loading -> Error message

For some reason the error message display will flash for a fraction of a second before the gallery goes back to the loading state.

To try and reproduce, you will need to introduce some kind of error. The way I've been doing it, I've returned empty data from our mocked server. You can do that by changing return to `null` for one of the functions in `src/mocking/server/resolvers.ts`, for example `featuredVideosResolver`. That should trigger GraphQL error because we're returning null for non-nullable value.

Let me know if you need any more details or if you have trouble reproducing :)

**Comment by kdembler** [comment]
We don't use that handler anymore
