### ISSUE TITLE
Rewards: `withdraw` should support withdawing to external accounts in a single flow

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#4795]
# Problem
Currently, the UI for creator rewards uses the word `withdraw` which I think is a bit confusing--some users seem to think that this has sent the tokens to some account that they didn't specify (https://discord.com/channels/811216481340751934/1147348817692340284/1147348817692340284)
![image](https://github.com/Joystream/atlas/assets/50830161/4fde7be0-24ad-4d3a-aa16-8fdeac4e2508)

# Solution
Change `withdraw` to `claim`. This is because `withdraw` is commonly used to signify that a transfer between accounts has happened (typical language used on exchanges) and while this is technically true, from a UX standpoint the user is actually `claiming` rewards that go to a preset account.
Once this is done, then the user would `withdraw`.

**Comment by bedeho** [comment]
I agree this is complex, but I think the real solution here is to allow users to withdraw funds directly to an external account if they want to, this is what most people want to do, like move it to ane xchange or something. So ideally, when they click this, they get a choice between "external accoun" and "my membership account". This will under the hood require a batch transaction because its not possible, on-chain, to withdraw to an arbitrary account.

**Comment by dmtrjsg** [comment]
Just linking up quick solution to the ux issue I have drafted before which is in the design bl: 
- https://github.com/Joystream/atlas/issues/4803

If batching txs is possible, then we'd rather go with that ofc (I recall there was some sort of a limitation that prevented us form doing so before).

**Comment by dmtrjsg** [comment]
Scope:
- [ ] Keep the CTA as `Withdraw` and allow to withdraw to external acc in the same modal
- [ ] Use the same modal that is used for Transfer
- [ ] Change the copy in the destination account from "Polkadot wallet account" to "Joystream account address"
- [ ] do point 3 for the transfer modal when transferring from the membership account
