### ISSUE TITLE
Referrals page

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4931]
## Context
Simplify referrals for new members 

## Scope
- [ ] Create separate referrals landing page
- [ ] Page accessible from side nav for studio and viewers
- [ ] Referrals page contents
- Clear indication how much you get for each referred tier
- They can be of any category or content
- Static  section with top 5 referring channels and how much JOY earned in total from YPP (can use same cards as for recently paid out channels)
- Visual with referrals dashboard
- Visual explaining how to generate referral link from accounts + link that takes you to Dashboard (depending on state starts journey to sign in/ create channel/ go to dashboard
- link to this page from YPP dashboard

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg created low fidelity explorations for the Referrals page and recorded a video update about it to further explain the design thinking there ✅

🎥 Video update: https://www.loom.com/share/c13278b2070541549725ffd5ca71a814?sid=57213e47-ee72-43f1-9976-7a182807d23f

📄 Exploration file: https://www.figma.com/file/ZBZI3Od7qHddy1USVYtRaB/Referrals?type=design&node-id=1%3A3&mode=design&t=GclhAOqnwL0ChFum-1

**Comment by dmtrjsg** [comment]
v2 looks better imho, and added a few comments to Figma

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg I have the high fidelity first iteration of the Referrals page - its ready to be reviewed ✅

🎥 Video update: https://www.loom.com/share/eea81d810cfd41bc94c9216727e0a100?sid=b69f2cdd-16db-4b80-b21a-c571f75e5dad

📄 Referrals file: https://www.figma.com/file/AHeOPBgaJxmZb0zamEHhq8/Referrals?type=design&node-id=1002-7657&mode=design&t=PM0YRDDN6N5zvEBj-4

🖥️ Prototype: https://www.figma.com/proto/AHeOPBgaJxmZb0zamEHhq8/Referrals?page-id=1%3A15535&type=design&node-id=1069-4670&viewport=-715%2C-479%2C0.26&t=rdfjZxt73y2GVrfn-1&scaling=scale-down&starting-point-node-id=1069%3A4670&mode=design

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk thank you for putting it together, absolutely love it in high fidelity! ❤️ 

Comments: 
- H2 under Earn by referrals - "Referrals rewards is the biggest source of earnings for Gleev creators." 
- Are the channels showing in the animation made up or some real channels? I think we should use made up ones
-I like showing the idea of showing channel avatar as it makes it more personal. Do we want to use a different placeholder (not just default) for cases when channel is not set up or user not signed in?
- How to start - loving it. Second step: "Create Gleev Channel" (not Create Free Channel). 
- Top referrers - will be channels and not members. 
- Bottom section - swap to channel avatar, and tailor the CTA based on the "state" of that member/ channel. So if they have channel already, the CTA would be "Copy referral link".  or create channel during step 1 etc. Also I think like rotating avatars are adding visual overload and will not work that well on mobile, so I'd make it simple and remove this animation from the bottom section.

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg 
The final designs for the referrals are here, together with user stories, RWD, and custom animation files ✅ Please make sure to check the prototype! 

🟠 If you are a developer please watch the whole RWD section walkthrough!

🎥 Video update: https://www.loom.com/share/dcfbecf579ef43b9a63e14cade12e42d?sid=98fc78c3-9d3e-4afa-a48d-b5ec8c02e8c1

🖥️ Prototype: https://www.figma.com/proto/AHeOPBgaJxmZb0zamEHhq8/Referrals?page-id=1115%3A12275&type=design&node-id=1115-12279&viewport=849%2C853%2C0.46&t=2vCmAVLE3UyUVBvF-1&scaling=min-zoom&starting-point-node-id=1115%3A12279&mode=design

📄 Referrals changelog: https://www.figma.com/file/AHeOPBgaJxmZb0zamEHhq8/Referrals?type=design&node-id=1-14419&mode=design&t=VP8fSqL3tuuDIpvD-4

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk off the back of the marketing sync meeting we have a few things to add to it
1. Toaster banner showing 30 seconds into the session when user is on Homepage or studio, pulling users to the referrals page
2. Update referral rewards to 2 dollars for Bronze (add bronze to second section)
3. Additional tier for Top Referrer component (bronze)
4. Add link from Dashboard referrals to the referrals page (tbc?)

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg 
Every requested change is done and can be reviewed below ✅

📄 Referrals changelog (New tier in tier section + new tier counter in top referrers): https://www.figma.com/file/AHeOPBgaJxmZb0zamEHhq8/Referrals?type=design&node-id=1-14419&mode=design&t=AWBppHxWq3VZRoKo-4

📄 YPP Dashboard changelog (new learn more link): https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=3338-84773&mode=design&t=Dg543KQxARuCqFhL-4

📄 Web components announcements (top banner): https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=14281-33200&mode=design&t=eoB7wkLxHNzi1Dh8-4

📄 Referrals changelog (referrals banner user story): https://www.figma.com/file/AHeOPBgaJxmZb0zamEHhq8/Referrals?type=design&node-id=1381-20005&mode=design&t=AWBppHxWq3VZRoKo-4

https://github.com/Joystream/atlas/assets/31144205/57a02ff0-decc-4a2a-bb55-c88e94168fac
👆 *Note: Banner has animated elements inside.

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk can we do an upgrade of OpenGraph referral links preview (Without the 20%) but similar to how it was done in v2?

**Comment by KubaMikolajczyk** [comment]
> @KubaMikolajczyk can we do an upgrade of OpenGraph referral links preview (Without the 20%) but similar to how it was done in v2?

Its here: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=5911-40087&mode=design&t=2dBFN4ud05W5bpMS-4

**Comment by dmtrjsg** [comment]
Great stuff Artem!  Almost there..

## Banner
1️⃣ Did not trigger for me on the preview branch. Here's the [link to user story>](https://www.figma.com/file/AHeOPBgaJxmZb0zamEHhq8/Referrals?type=design&node-id=1381%3A20005&mode=design&t=Hb7fqphaOcKmB2JX-1)


## Referrals page
1️⃣ . Colour of hyperlink needs to be double checked
<img width="746" alt="Screenshot 2023-11-03 at 12 22 59" src="https://github.com/Joystream/atlas/assets/93924525/d16f4aed-f9c4-412a-9583-61e8f42db35c">

2️⃣ . Top section table animation: can we make animation on the top section to update the table faster (every 2 seconds)

3️⃣ . The "Earn even more section" needs to be commented out as we are not launching this just yet 😬 

4️⃣ . The avatar should lines connecting to the tiers: 
<img width="1033" alt="Screenshot 2023-11-03 at 12 27 46" src="https://github.com/Joystream/atlas/assets/93924525/0227ea79-452d-4d4d-b3d4-a77d4e97ee55">

5️⃣ . Dimensions of the core CTA needs to be revisited (needs to be bigger)
<img width="332" alt="Screenshot 2023-11-03 at 12 28 58" src="https://github.com/Joystream/atlas/assets/93924525/7c3604c6-2949-40a8-ba17-2d2c483516d3">

6️⃣ . The header of the section should be  `Top Referrers`
<img width="446" alt="Screenshot 2023-11-03 at 12 29 40" src="https://github.com/Joystream/atlas/assets/93924525/6c596c8a-2186-4dc8-a5e7-c6911627ba93">

7️⃣ . The central animation with steps needs to change to next step after the previous one is finished 
[See recording ](https://www.loom.com/share/dcfbecf579ef43b9a63e14cade12e42d?sid=98fc78c3-9d3e-4afa-a48d-b5ec8c02e8c1)(15:30 timestamp)

8️⃣ Referrals link from CTA should get to ypp/dashboard/referrals (now gets to /ypp/dashboard)

9️⃣ Referrals dashboard need to have primary CTA on top in all cases (even if it is empty, as this helps w referrals on mobile)

__
⚠️ Could not test
1. Top referrers endpoint as needs to be on dev before I can test
2. Showing avatar of channel on the referrals page (as assets upload always failed for avatar)

**Comment by attemka** [comment]
@dmtrjsg 
thank you for the review.
1. ✅
2. ✅ increased speed to 2x, let me know 
3. ✅
4. ✅
5. ✅
6. ✅
7. ✅
8. ✅
9. ✅

p.s. top referrals endpoint works on dev (but with less channels\data)

**Comment by KubaMikolajczyk** [comment]
Hey @attemka great job! Here are some elements that I spotted:

# Grid layout
1. From LG the layout looks different than on designs - we have 64px paddings on left and right while in designs we have a centered grid 
2. Please check the spacing between sections on different breakpoints - eg. on LG we should have 96px of space between sections not 64px but it depends on the breakpoint
3. Please double check the spaces inside of sections as those also change across different breakpoints - eg. XXS breakpoint should have small spaces inside of sections while now in How to start we have 72px

# Hero section
### Overall
1. Logo being displayed should be gleev not atlas

### XXS
![image](https://github.com/Joystream/atlas/assets/31144205/def0f31a-61ba-4600-b8e5-bb1a686ae84b)
1. The top navigation is different than in designs
2. Logo should be spaced from the top nav
3. Distance between logo and title header is to small
4. Distance between header title and desc is too large
^ all of the above holds true for all breakpoints

### MD
![image](https://github.com/Joystream/atlas/assets/31144205/47958753-8141-4f3f-a25a-c4e5e9dbd807)
1. It looks like everything here is not aligned to the center

# How much you can earn
### Overall
1. Too big of space between title and description
2. No lines connecting avatar and cards
3. Gap between the check icon and list items in tier cards should be 8px

### XXS
![image](https://github.com/Joystream/atlas/assets/31144205/e2eede32-2bb5-492c-9ea5-eb6f697195bc)
1. Additional space in vertical layout inside of the cards below the points is not needed here

### MD
![image](https://github.com/Joystream/atlas/assets/31144205/950ad4bd-1d56-4c43-8e52-bd11c0559238)
1.Earn for referring is centered instead of being left aligned

##LG
![image](https://github.com/Joystream/atlas/assets/31144205/29db4506-9d63-4965-bf3b-621ad252a341)
1. Cards should use 10 columns of space not whole width of the container + the grid is not like in designs here

# Earn even more
### Overall
1. The gap between title and description is too large

### XXS
![image](https://github.com/Joystream/atlas/assets/31144205/4838a158-32b4-4f9a-8b24-293a88359e42)
1. Description uses only 10 columns of space
![image](https://github.com/Joystream/atlas/assets/31144205/6b439072-ca94-4e85-b5d8-e76b411d9b4b)
2. The illustration is displayed in such way that its cut + it looks like the avatars numbers and the lines are not aligned

### SM 
![image](https://github.com/Joystream/atlas/assets/31144205/b2222dd5-a0a5-476d-8370-c728990faeca)
1. On this breakpoint this visual should be centered like in designs

## LG+
![image](https://github.com/Joystream/atlas/assets/31144205/6b52966a-0530-49e9-bcf8-9ba6f4a36ad8)
After LG the grid is centered and do not scale anymore and the elements in this section should take 10 columns of it

# How to start
### Overall
1. The steps should have an animated background and change automaticly

### XXS
1. The gap between steps should be 16px
2. The gap between the number and the title inside of the step should be smaller
3. The spacing between the elements inside the section is too large

### SM
1. The button should have a fixed width of 240px

### MD
![image](https://github.com/Joystream/atlas/assets/31144205/983f1f67-de78-421b-b58b-6a97243a145b)
1. The video uses  incorrect amount of columns and it is not using the correct height it should fill all columns horizontally + adjust vertically to keep the ratio - and now there are gaps on the left and right side
2. The steps should take 5 columns of width

### LG
![image](https://github.com/Joystream/atlas/assets/31144205/cead1e26-3a23-4c67-873f-caa1ffcba9b2)
1. From this breakpoint the whole sexction should use 10 central columns
2. The above problems from MD brakpoint still exists

# Top referrals
### Overall
1. Avatar does not load
2. The referred channels tiers have the wrong sizing - those are too big - please chek with the designs
3. If we resigned from border animation please remove the gradient left border on this card

### Breakpoints
1. There are no users except only 1 so I cannot review the full layout for any breakpoints

# Bottom CTA
### Overall
![image](https://github.com/Joystream/atlas/assets/31144205/d4b68fce-4749-4be7-b1cc-c221117189ee)
![image](https://github.com/Joystream/atlas/assets/31144205/2ab7f085-57e2-41ab-b96c-301ede3eabcc)
1. The gradient on implementation is too intense - its almost all blue while on the design we have a subtle hint of gradient
2. Space between the title and description is too big

### XXS
1. Padding is too large

### XS
1. Padding is too large

### LG
1. The banner should take 10 columns of space on a centered fixed layout
