### ISSUE TITLE
YPP 2.0 - QA2

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4965]
### Referrals

- [ ] Referrals are only showing for users signed up to YPP. Need to show to all, regardless of participation..
- [x]  Suspended channels using wrong icon in the referrals table

<img width="377" alt="Screenshot 2023-10-05 at 20 02 58" src="https://github.com/Joystream/atlas/assets/93924525/5db832db-9454-43a0-94aa-8df3b79421e1">

- [x]  Opted out channels do not show in the referrals tab

### Sign up flow
- [ ] "Continue" cta and not "create acc' for users who are already signed in
- [ ]  Duplicate entry in the category selection (probably not relevant for production)
<img width="466" alt="Screenshot 2023-10-05 at 20 12 24" src="https://github.com/Joystream/atlas/assets/93924525/124dbd23-5e99-41a0-b45d-09e35e2bc406">

### Dashboard
- [x] If channel opts out and then signs in again (and gets verified) the dashboard status keeps showing as "unverified"
- [x]  Sync status does not show up right away, but only after the channel is verified (in the new implementation sync does not require verification)

### Landing page
- [x]  Let's remove the video section from the landing page (I will shoot it using prod instance)
- [x]  Payments widget on landing page needs to link to [Notion>](https://www.notion.so/joystream/YouTube-Creator-Payouts-02f7cf50972145bfb64c8543914ae4bb?pvs=4)

### Backend
- [ ] Joystream/youtube-synch#268
- [x]  Video Category ID  update by operator issues
- [x] Issue with opting out, [Link](https://discord.com/channels/811216481340751934/1159435741282172958/1159538889850105887)

**Comment by WRadoslaw** [comment]
1. ` Suspended channels using the wrong icon in the referrals table` result of the update of suspended reasons (it defaulted to bronze icon.
2. Opted out shows in table - confirmed by QA
3. `Sync status does not show up right away, but only after the channel is verified (in the new implementation sync does not require verification)` fixed 
4. `Let's remove the video section from the landing page (I will shoot it using prod instance)` commented out
5. `Payments widget on landing page needs to link to` - replaced in config

All above fixed by #4968
