### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by mnaamani** [Joystream/atlas#593]
Just a few UI issues while testing on https://atlas-reckless.netlify.app

1.  In Atlas Studio I always see the dialog "No network connection" even though everything seems to be working fine

![Screen Shot 2021-05-10 at 9 41 38 PM](https://user-images.githubusercontent.com/1621012/117706329-38478780-b1de-11eb-947d-bccaf9731525.png)

2. A channel doesn't cost anything to create, but we see in the background 0.2 JOY transaction request, perhaps it was just a place holder? Because at bottom it correctly showed 0 Joy for cost

![Screen Shot 2021-05-10 at 9 46 42 PM](https://user-images.githubusercontent.com/1621012/117706474-63ca7200-b1de-11eb-99d0-c495b06b99d2.png)

3. In the studio/edit-video view the drop down menu doesn't seem to appear (probably hidden behind

![Screen Shot 2021-05-10 at 9 52 06 PM](https://user-images.githubusercontent.com/1621012/117706517-7644ab80-b1de-11eb-9d64-51f162c464b6.png)

4. If I start with a short height then minimize the video then expand the height of the window I see the edit form at the bottom but I can't really scroll so it doesn't really make sense to show it?

![Screen Shot 2021-05-10 at 9 58 35 PM](https://user-images.githubusercontent.com/1621012/117706623-97a59780-b1de-11eb-9c5d-a1f1bd951a22.png)

5. I created a channel (`11`) but it is not appearing in the atlas channels: https://atlas-reckless.netlify.app/channel/11
I double checked that it is public. It only has an avatar but no cover photo.
![Screen Shot 2021-05-10 at 10 26 02 PM](https://user-images.githubusercontent.com/1621012/117706754-be63ce00-b1de-11eb-9ccc-cdd6b3eab6b6.png)
It appeared after I added a cover photo only.

**Comment by kdembler** [comment]
Thanks for that!

Some thoughts back:

1. That's a weird one, seems it's working fine for all of the development team. We check the connection by pinging `google.com`, maybe some of your extensions are blocking the request? Could you take a look into Network tab?

2. Yeah that's just an illustration from the design, it's fixed like this. I think it's mostly a background thing so I'd say as long as we indicate in other places that transactions are free, this is fine to leave out. lmk wyt

3. Yeah, the video sheet covers it. The design had the backdrop extend over the top navigation, I think we should do that as well. Created https://github.com/Joystream/atlas/issues/597 for that
<img width="478" alt="Screenshot 2021-05-11 at 14 10 11" src="https://user-images.githubusercontent.com/12646744/117812863-a03fb180-b262-11eb-8e5d-ef181b0839b8.png">

4. ~We generally decided to not worry about the height of the window changing during the app usage. Our goal was for it to work properly on all screen sizes, not necessarily when the screen size changes. Do you think that's a usecase worth covering? The only thing that comes to my mind is changing the orientation of a mobile device.~ 
On a second thought, we should handle that, I've created #599

5. Yes, that was a bug and it should be fixed by https://github.com/Joystream/atlas/issues/553. The version that was redeployed today should already have this change, can you check again?

**Comment by mnaamani** [comment]
1. Yes the privacy plugin was blocking the ping to google.com because it considered it a "tracker"
2. Its just confusing thats all, I did hesitate and questioned myself more than one before submitting. I hope it doesn't prevent other from trying it out if they think they need to fund account. Its more a UI/UX issue here so I'll leave it you guys. If someone else raises the same point maybe you can re-consider.
3. Doesn't seem that fix https://github.com/Joystream/atlas/pull/601 was deployed yet?
4. The fix Does not seem to be deployed yet?
5. Confirmed - channel now shows up even if no cover photo is provided

**Comment by kdembler** [comment]
1. :+1: We'll probably ping something else in the future
2. Yes, I see your point. Let's do what you suggested and wait to see if someone else raises this as well.
3. Will be deployed in 10 min
4. Same as 3
5. :+1:

**Comment by mnaamani** [comment]
All issues were resolved :+1:
