### ISSUE TITLE
Initial AMM parameters

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#5947]
One of the things I've pointed out in my CRT QA (https://github.com/Joystream/atlas/issues/5636#issuecomment-1941713947) is that the curve initialization is not deterministic - going through the Atlas flow on 2 separate occasions with the default parameters in the UI produces 2 different AMM curves - which I found quite confusing.

Another issue is that the input in the UI tells you that you can set the initial price for your tokens expressed in JOY, but that also seems to not produce expected results.

We discussed briefly during Nara call today and it was mentioned that the curve parameters are somehow influenced by the current JOY/USD price. I don't understand why that's the case, let's discuss so we can get a shared understanding.

**Comment by dobertRowneySr** [comment]
Since we don't know any actual plausible values a priori for the various CRT I suggested to default to those particular value such that the curve will keep the same property as the DeSo curve.
**I am aware that their pricing function is quadratic and our is linear** but for lack of better alternatives I suggested to use default parameter values such that the **pricing function in terms of USD value of the CRT market cap** will look like theirs when the user leaves everything to the default Atlas settings.
See the calculation on how we are using the various parameters to set up a similar pricing as DeSo [here](https://github.com/Joystream/joystream/issues/4488#issuecomment-1768635722)

**Comment by dobertRowneySr** [comment]
As an alternative if you think that the above method is to difficult is to put by default:
- `slope = 2 * 10^10`
- `intercept = 0`

This will give you that when you buy 1 CRT at the beginning of the AMM activation you get 1 JOY = 10^10 HAPI
That is very simple to understand for the user. Same reasoning can be done with `slope, intercept = 1,0` for which the first CRT is worth half a JOY. And so on
Doing this we implicitly are forgetting the CRT market cap USD value relation, as basically the pricing now only depends on JOY

**Comment by bedeho** [comment]
# Goals

An issuer of a creator token has the following objectives when launching the AMM:

1. **Accessibility:** Allow investor with small portfolios to get exposure to the asset when priced below fair market value (FMV) of future revenues. This will not be possible if the token price is too large for the optimal amount of exposure in a small portfolio, despite being below FMV price. A concrete example is if FMV is 10K USD cap for channel revenue share, but the the first token is priced at 4K USD mcap and the next is 6K USD mcap. In this case, a portfolio which is sufficiently small cannot even buy the first token, despite the cost being 4K and the value being 10K/2 = $5 in equilibrium.
2. **Control Dilution:** If there already is some set of token holders , whether the creator is a holder or not, the creator may want to constrain how much dilution is likely to occur of these holders as a result of the bonding curve minting new tokens up to FMV price.
3. **Constrain Profits to early buyers:** The bonding curve will charge an increasing unit price per token minted. Buyers will keep minting until value of of next token is equal to price, this means earlier tokens are profits transferred from issuer to buyers, in exchange for building liquidity. However, the issuer may want to bound or constrain how much to give away.

Depending on the size of the existing supply, it may be impossible to reconcile 1 and 2 simultaneously. If you wish to target a given amount of dilution, then this may limit how many units will be minted at below FMV prices, leading to unit prices which are very high, which blocks out smaller portfolios. Even if we assume we can guide initial selection of supply, these are not guarantees, as tokens may be burned or lost before bonding curve is launched.

Lastly, constraining profits may be possible by lifting initial price of curve, but this should be revisited later, there is not enough time now.

## Approach

### Setup

- $Q_s \ge 0$: amount of CRT already mint.
- $a > 0$: slope of curve
- $b > 0$: intercept of curve
- $1 \ge \alpha \ge 0$: Share of revenue going to token holders.
- Bonding curve has shape $p(q) = aq$, where $q$ is current minted supply of CRT from the curve.

### Problem

Provide policy for generating value for $a$ such that goals are satisfied.

### Assumptions

- $F > 0$: USD dollar vale of future gross revenue into channel. We assume we cannot ask the creator to volunteer this, so we set to 10,000 USD worth of JOY tokens for all channels for now.
- $b = 0$: If we want to achieve goal 3 we would generate new equation for profit to traders in terms of $b$, and then calibrate $b$ to hit profit cap.

### Model

Traders will mint quantity of $q^*$ creator tokens such that price reaches a market cap that equals fair market value of revenue that creator token holders are entitled to, that is it must satisfy

$$p(q^*)(q^{*} + Q_s) = F\alpha$$

hence

$$aq^* (q^{*} + Q_s) = F\alpha$$

simplifying to quadratic form in $q^*$

$$a(q^{*})^2 + (aQ_s)q^{*} - F\alpha = 0$$

which yield final value (when discarding negative value)

$$q^* = \frac{-aQ_s + \sqrt{(aQ_s)^2  + 4Fa\alpha}}{2a} (I)$$

We want to ensure that $q^*$ both is above some minimal quantity that reflects the minimum number of distinct holders we want to be able to accommodate, but we also want to be mindful to not dilute current holders more than some acceptable amount. To be specific, we assume that 1000 holders is sufficient and we assume that we should try to not mint more than 1/3 of the initial supply $Q_s$. Hence we require

$$q^* = \max (1000, Q_s/3 ) (II)$$

We can combine equations (I) and (II) to derive final equation for $a$, so

$$\max (1000, Q_s/3 ) = \frac{-aQ_s + \sqrt{(aQ_s)^2  + 4Fa\alpha}}{2a}$$

equivalent to

$$2a\max (1000, Q_s/3 ) = -aQ_s + \sqrt{(aQ_s)^2  + 4Fa\alpha}$$

equivalent to

$$2a\max (1000, Q_s/3 ) +aQ_s = \sqrt{(aQ_s)^2  + 4Fa\alpha}$$

equivalent to

$$[a \left ( 2\max (1000, Q_s/3 ) + Q_s \right)]^2 = (aQ_s)^2  + 4Fa\alpha$$

equivalent to

$$a = \frac{4F\alpha}{[2\max (1000, Q_s/3 ) + Q_s]^2 - Q_s^2}$$

Notice that this formula works also when $Q_s=0$.

## Conclusion

- When $\alpha = 0$, just set it to some very low value for the sake of it, like $0.01$
- During minting, we should encourage $Q_s$ to be at least $3000$

## Examples

Can someone else do this? checking some cases

## Questions

- @mrbovo: Does the algebra check out?
- Does this produce reasonable numbers for $a$
- Should we pick different values for $F$ and $1/3$?

**Comment by ignazio-bovo** [comment]
Looks ok algebra-wise, I also have tried to come up with some values for the `slope` proposed

![Image](https://github.com/Joystream/atlas/assets/51839739/6a3da671-78e0-4d23-9d93-803a447f6413)

The `slope` parameter in the runtime is a `u128` whose units are [HAPI/CRT^2] and the minimum value allowed is 1 million, 

❗ DRAFT

**Comment by dobertRowneySr** [comment]
# Is the algebra Right

The maths looks good

# Does this produce reasonable numbers for `slope`

From your observation I infer that we should have about 10k USD market cap (FMV) at about 1000 CRT in circulation, so I came up with the following values for `slope`

<img width="626" alt="image" src="https://github.com/Joystream/atlas/assets/51839739/2cebbc0e-b0cc-4e91-a5c0-282e0f59cf5d">

To get this values Atlas would construct a `activate_amm` extrinsic with the following configuration:

- `slope = .45 * 10e10` (allowed by the runtime)
- `intercept = 0` same as your model. (However this can be adjusted so that it specifies the requested initial price by the user, provided that it's above a certain amount, namely `initial_price = slope /2 + intercept` which yields `intercept = initial_price - slope /2 >=0` so that this can be computed and adjusted in the correct units if we want to ask the user to provide an initial USD price for CRT).

Your methodology looks fine in the sense that yields similar values, provided that at about 1000 CRT issued we want to be in the ballpark of 10k USD market cap


![Image](https://github.com/Joystream/atlas/assets/51839739/afe3ec37-5218-42c4-848c-71e442a1c0c3)

# Should we pick different values for F and 1/3 of the pre-amm supply
I don't think there's an answer for this :) 
Picking the values for F is equivalent of somewhat setting the price dynamics. Your reasoning suggest that at about 1000 CRT we would like to be around 10k USD Market cap (FMV). 

This is the Circulation, Coin price USD dynamics that DeSo is aiming for

![Image](https://github.com/Joystream/atlas/assets/51839739/85a3fd86-d70e-4d5a-9218-8bb24e3117cb)

As you can see it's very high (at about 320 CRT minted you get a market cap greater than 1 million USD), it is their model under their assumption that
> Creator coins are naturally scarce, with generally fewer than 100 to 1,500 coins in existence for each profile.
> *Deso Doc.*

However DeSo dynamics it's very flat at the beginning and it grows very quickly, our curve also has this property but the DeSo one is way more remarked, so that's also a factor

If we look at the values then at about 1500 CRT minted the price for one is about 15 USD. Which might be too low, so possibly increase the vale of $F$ of one or two magnitude could be a good idea. So that aiming for Market cap at 100k or 1mil USD at about 1500 CRT issued.

**Comment by dobertRowneySr** [comment]
After the call on AMM parameters we have agreed that:
- computation is ok
- we just want to bound the Qs value in order to to trigger a runtime error due to the constraints for the slope parameters hardcoded in the runtime

If I input in wolfram alpha
> 4*alpha*F*5e11 / ((2max(1000,x/3) + x)^2 - x^2) >= 1 million, solve for x >= 0

Here the 5e11 is the price of 1 USD in HAPI given that we are assuming that the lowest possible price point USD / JOY is 0.02

As solution I get
$\alpha F>8, 0 \leq Q_s \leq 750 \sqrt{2} \sqrt{\alpha F}, 2< \alpha F \leq 8, 0 \leq Q_s \leq 500 (\alpha F - 2)$

and for $\alpha F = 10000$ I get 
$$0\leq Q_s \leq 106066$$

This means that according to the proposed algorithm for choosing $a$ we do not allow the user to open a AMM if the outstanding CRT supply is above $106006$

Is $0 \leq Q_s \leq 750 \sqrt{2} \sqrt{\alpha F}$ an acceptable formula, in the sense that the number of CRT allowed pre AMM reflects the magnitude of shares of a small cap company in the real world? 
I think so because if I think the CRT as shares and a Channel as small company then a quick search on google that
- average # of authorized shares of small cap company = 10 millions (= target magnitude for $Q_s$)
- average market cap of a small cap company = from 300 millions to 2 billions = $\alpha F$

the formula above gives a bound of 33 millions shares outstanding upper bound

**Comment by bedeho** [comment]
Be aware I am not assuming $\alpha F = 10000 \text{USD}$, this does not make sense because user controls $\alpha$ directly, I'm assuming $F=10000 \text{USD}$.

**Comment by dobertRowneySr** [comment]
Ok but I don’t have any ideas for alpha values so the only quantity that I can reason a out is alpha * F
And if the user picks values like .8,.9 then the formula makes sense

#### Discussion status
given then current status of the Conversation on discord, I suppose that a somewhat acceptable conclusion on this issue has been reached for the Nara release.
I propose to close the issue @bedeho
