### ISSUE TITLE
IDEA: Creator Engagement Ideas

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5975]
# Context

This document encapsulates a set of product and operational improvements aimed on boosting the creators growth and engagement. It collects the ideas expressed by multiple team members in a single place to provide context for the Gleev product updates and will serve as an umbrella issue for feature development and improvement. 

The objective is to attract more creators  to Gleev, make them use the product more often and grow avg session duration per user. Since the product is not marketed to the viewers here we assume that engaged creators will attract their audience to Gleev. The bet is on the unique value proposition that puts apart Gleev from the competition. 

⚠️ Important: the economics of this program needs to be carefully modelled, and before that all actual reward numbers are for illustrational purposes. Here's the reference ([LINK](https://docs.google.com/spreadsheets/d/1o81c_6vpvGgHMsVOjSCXhAEySfC2Mx2m1IooKSn6DpA/edit#gid=811996845)) on how YPP program budgets and rewards were approached in the past. 

# Scope

## Connecting with Gleev and Joystream

- Get Creators Discord Role
"Get a discord role within creator community. Join WEb3 video creators on Gleev and participate in rewarded activities and earn extra JOY." Every week 3 randomly selected creators are rewarded with 50$ each. Should roles be linked to creator tiers? 

- Follow Gleev X acc
"Follow Gleev Twitter acc. Be the first to know about product releases and project news."
Every week 3 creators are rewarded with 50$ each.

- Apply for Ambassador program
Become a marketing collaborator and earn tokens based on result. Limit this to Gold + channels.

- Apply for Community Moderator Role in your category
We create channels for each category and appoint a community lead. This will be salaried role paid at 250$ per week in vested Joy tokens. 

- Join Creators Advisory Panel 
Creators panel that is involved in early features beta testing (e.g. CRTs), votes on roadmap items. 

- Join Bi-Weekly Fireside Chats
Pretty much fireside chat invitation. Can be rewarded but probably better to foster pro-bono interest. We can give a branded Tangem wallet to 1 selected participant who asks the best question/ offers the best idea. Decided by Joystream team. 

## Promote Unique content uploaded to Gleev

- Mint NFT task to YPP dash
"Mint NFT, put it on sale, request to be featured"
Every week 5 creators are rewarded with 150, 100 and 50 usd based on other creators voting for them on discord dedicated channel, smth simple like an emoji. Would be good if they self-select winners and JS team does not have to judge. 

- Join Gleev Original Creators Club task to YPP dash
We distribute a branded video snippet "Originally Published to Gleev" with sound branding (same as Netflix has for their shows) and ask creators to use it in their videos, and first upload to Gleev. They can still upload to YT but at least X days later. They get Original Gleev Creator Role on Discord. We reward each of these creators with a x3 multiple compared to YPP rewards for each video based on their Tier assigned. There will be manual spot checks. 

## Promote Gleev content on Social Media

- Bring Viewers to Gleev
Share your Gleev video on SM and for every unique 1000 sessions from this link we reward with 10$.  And for every 10 new memberships created reward with 10$. If user who they invited bought an NFT, they get 5% reward from the purchase price. 

⚠️ That would require some improvements to how shared videos are displayed on SM. We would need to update the metadata of SM posts. Ensure that each video link has a preview thumbnail, has metadata which encapsulates #Gleev #Web3Creator #Joystream hashtags and a call to action to view their NFT on Gleev. KEY change: The SM post would need to have a utm link which is attributed to individual creators, so that would be appending the URL for signed in users. We can then track the attribution of users. 

- Share your creator token on SM
⚠️ Requires token SM preview design and implementation

- Unblocking of Gleev links on FB would be beneficial

**Comment by leetjoy** [comment]
> Follow Gleev X acc
> "Follow Gleev Twitter acc. Be the first to know about product releases and project news."
> Every week 3 creators are rewarded with 50$ each.

Is it typo? I believe we should direct creators to `@JoystreamDAO` handle.

**Comment by mochet** [comment]
> Get Creators Discord Role
"Get a discord role within creator community. Join WEb3 video creators on Gleev and participate in rewarded activities and earn extra JOY." Every week 3 randomly selected creators are rewarded with 50$ each. Should roles be linked to creator tiers?

* Yes this should be linked to creator tiers--we should create separate roles for each plus a more general `@creator` role that covers all of them (this may require a Discord bot but is achievable)
* It should only apply to approved YPP channels ideally, otherwise we will likely get sybil attacked heavily
* Are we thinking here of assigning non-YPP users to have YPP tiers? I think we should use the same tier system at some point for original creators.
* There is no way to tie Gleev <> Discord membership so we would have to just tag the winners and have them prove they own a Gleev channel


> Apply for Community Moderator Role in your category
* What categories are we thinking about doing? In terms of community building I would suggest we start with like ~5 at most. It is easier to build up activity in a smaller number of categories and easier to manage. Obviously crypto would be a category but it would be good to have a creative one. AI generated video etc may also be an interesting category to play around with but we would need to attract a certain kind of user for that.
* I also think we need to have related areas on Gleev for each category

> Join Creators Advisory Panel
Creators panel that is involved in early features beta testing (e.g. CRTs), votes on roadmap items.

* I really like this. I have seen other projects with "gamified" roadmaps like this and I think its a great way to get creators more invested in the platform.

> Mint NFT task to YPP dash
"Mint NFT, put it on sale, request to be featured"
Every week 5 creators are rewarded with 150, 100 and 50 usd based on other creators voting for them on discord dedicated channel, smth simple like an emoji. Would be good if they self-select winners and JS team does not have to judge.

* This is great. I believe there may be some off the shelf Discord tools that can accomplish this.


> Bring Viewers to Gleev
Share your Gleev video on SM and for every unique 1000 sessions from this link we reward with 10$. And for every 10 new memberships created reward with 10$. If user who they invited bought an NFT, they get 5% reward from the purchase price.

* I would suggest that maybe we don't make the activity requirements public to begin with, and maybe there is more value in targeting >silver tier creators for this as a starting point?


Overall, great stuff and I'm fully on board, I just think we will probably need some custom made Discord bots to achieve some of things more seamlessly--I am mindful of drawing up Discord bot requirements, but there are plenty of Discord bot devs around on the internet so maybe it is something we can just contract out?

**Comment by igrexac** [comment]
I especially like the idea of organizing among creators to insert a preview before the video - Original Joystream Content
