### ISSUE TITLE
Drop cookie modal for basic stuff

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#6023]
# Background

If someone links me to a specific video or the landing page, and I have never been on Gleev before, then I get this

<img width="1630" alt="Screenshot 2024-03-19 at 17 06 38" src="https://github.com/Joystream/atlas/assets/437292/4d6c8a61-675a-4081-9132-ccf1ed6feb60">

Meanwhile, if I do that on rumble, I just get this

<img width="1964" alt="Screenshot 2024-03-19 at 17 07 15" src="https://github.com/Joystream/atlas/assets/437292/84279488-5da7-419e-8ad8-05dd3975368e">

In fact, I can navigate around Rumble and not have to deal with the cookie question at all.

# Proposal

The cookie dialogue is there because we are using cookies from some purpose, but that purpose may very much not be worth it. It may be better to postpone any cookie question until later in the user life-cycle to improve the first experience for everyone. So lets start by mapping out exactly what is currently generating the need for cookie at all, and perhaps just dropping that is the easist place to start even.

**Comment by WRadoslaw** [comment]
@bedeho Currently cookies are used for:
- Segment analytics
- LiveSession (I don't think it is used anymore)
- Google Analytics (same as above)

**Comment by dmtrjsg** [comment]
All of them are needed for product analytics. To make more people opt in we need to change the "accept non-essential" to "Manage cookies". The issue was in the design backlog but never got to be worked on due to other prios.

Livesession is helpful with understanding the why behind the analytics high level stats. I am planning to use it for CRT onboarding analysis. 

⚠️  What is 100% required to get changed is the copy on this banner. 

`Gleev is a web3 & crypto content-focused video platform that's part of the Joystream ecosystem.` -> `Here creators can uniquely connect with the viewers and monetise content with the help of native Web3 features: Creator Tokens and NFTs .`

**Comment by bedeho** [comment]
Then we need to badly redesign it. I don't know how Rumble is getting away with  not having it, because they are also doing analytics for sure, and they are a public company, so they have to respect this stuff.

Here is how TikTok does it, which seems way better. They dont block the whole screen, they make it a small banner at the bottom the user may or may not ignore.

![Screenshot 2024-03-20 at 11 17 17](https://github.com/Joystream/atlas/assets/437292/76cec820-6620-4ccd-8a22-f78fe07a4de6)

**Comment by bedeho** [comment]
Added issue: https://github.com/Joystream/atlas/issues/6030

**Comment by dmtrjsg** [comment]
There was an issue created for it before, so will add it to 6030.
- https://github.com/Joystream/atlas/issues/4098
