### ISSUE TITLE
[USERSNAP] error sincronizar email

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6053]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: error sincronizar email
- Expected Result: error sincronizar email stupid
- Your Channel and Account Details: josevestina@gmail.com https://youtube.com/@MESRTREMAFUBA?si=2R6LrbxS9POJjxr5
- Email or Discord handle for feedback: josevestina@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #760 in Usersnap](https://app.usersnap.com/l/feedback/d21aba89-f020-4d33-b673-1d73ad6ed843?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
Also informed the creator that due to channel suspension, videos won't sync.
