### ISSUE TITLE
Atlas improvements ideas

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#617]
Ideas for short-term improvements for Atlas:
- better, modern build pipeline
- improved "dev mode" (dynamic mocking, staging , etc)
- introduction of some global data store?
- common persistence layer (maybe part of global data store?)
- style linting
- simple analytics (at least screen size, device, etc)
- reducing providers count (shared layers for overlays, storage, etc)

**Comment by eldiegod** [comment]
Mainly for me:
- Centralized state management
- e2e testing i.e. cypress
- https://malte-wessel.com/react-custom-scrollbars/ could be a good polish to get rid of the ugly and jumpy default scrollbar
- Probably way out of scope but since we mentioned SSR then Next would be the way to go imo

**Comment by kdembler** [comment]
@eldiegod I'm curious, what would you say would be the benefits of using Next.js for us?

**Comment by eldiegod** [comment]
Well they are quite a bit feature packed but as Atlas scales I think it's a matter of time until SSR is needed, mainly for the prerendering server side of the common routes like the homepage they would load almost instantly and then the app would be rehydrated with the js and then the things that are specific to each user, so load speeds in that aspect.

- Preview in social media as content is prerendered
- API endpoints to use as a backend
- They also have their Image components which add great optimizations on the get go.
- has language detection
- has analitics

**Comment by mikkio-j** [comment]
Some things that came to my mind

- accessibility testing (or we could use storybook add-on: [https://www.npmjs.com/package/@storybook/addon-a11y](https://www.npmjs.com/package/@storybook/addon-a11y))

- visual testing? That's something that could've help us during phase 1 of sumer release (e.g. https://www.chromatic.com/). Not needed so much currently. Just an idea.

- when we're talking about storybook, amount of new components grew significantly during sumer release (I believe new components were also introduced after we've finished phase 1). So I think we could use some cleaning there, updating stories with new components, making some order in category tree and making sure everything works

- I agree with introducing global data store. Redux was mentioned couple of times, but imho we should consider different alternatives and make sure to choose what would be the best for our needs - that will be a tough one since there's a lot to choose from

- Base for localisation, a lot of text was introduced in sumer release (dialogs, warnings, snackbars etc.), we could extract those to some json file and prepare it for future language localisations

**Comment by drillprop** [comment]
Generally, I don't have anything to add.  
I also agree with introducing a global data store, and I think we could using redux here. Alternatively, maybe we could use apollo's local state management? Just an idea, personally I never tried it, so don't have any opinions on it.

**Comment by kdembler** [comment]
Almost all done
