### ISSUE TITLE
Idea: Optimistic UI update for likes and comments

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#6342]
Lets try an experiment and just see how complicated this gets on the client side. We dont even bother with telling the user if the action failed, we just pretend it workd if th client side validation (you have enough money and everything to make tx).

**Comment by ikprk** [comment]
So... I've checked and this is not really that easy when it comes to updating these fields optimistically.

The problem is that in Apollo they are not standalone values under a video object as for example `title` field. Both reaction and comment live in the cache purely as a reference to the `VideoReaction` object which is linked to more fields inside it. 

I'm not sure how will the cache behave after we modify it and the correct data comes from the Orion, whether this will be overridden or will it live next to optimistic write which results in duplication.

**Comment by bedeho** [comment]
I'm afraid I dont know enough about how Apollo caching works to appreciate whether there is a workaround or a more complex fundamental solution, so will have to leave this with you until you have something more conclusive to say on what it takes to do this while keeping complexity tolerable, if not minimized.

**Comment by ikprk** [comment]
The problem I found is that when let's say I add a comment, it will have some mocked ID in the cache, but the user can still click edit on it, which is a problem since there isn't a point in making a tx with the mocked ID. 

The easiest solution would be to check the ID of the comment and when a user is trying to submit an edit, we would just display a snackbar that the comment is not yet confirmed by the server (it will get confirmed when on transaction sync, so about 30 seconds after creation)

The second approach would be to hide the triggers for action that cannot be done on an "unconfirmed" comment.

**Comment by ikprk** [comment]
> The problem I found is that when let's say I add a comment, it will have some mocked ID in the cache, but the user can 

@dmtrjsg any comment?

**Comment by bedeho** [comment]
> The second approach would be to hide the triggers for action that cannot be done on an "unconfirmed" comment.

I think this would be the most elegant solution, is it a lot more complex?

How do you distinguish between real vs mocked comments?

**Comment by dmtrjsg** [comment]
It would be great if comments were submitted in like a higher opacity font and then once blockchain processes them take the shape of regular font. Also for such comments replies would be disabled before they are fully registered on the server side. 

Even tho the chances of interacting with the element that is mocked are quite low, if the effort of implementing hiding elements that are leading to error would be better.

**Comment by dmtrjsg** [comment]
Tested the updated implementation on:  https://atlas-196yxaqcs-joystream.vercel.app/  and the transition is jumpy :) 

So if it is not possible to make it smooth let's keep the toaster approach
But change the copy to

Title: Retry later
Text:  The comment is not yet processed by the blockchain. Give it a few more seconds.

And also change the icon from red to Yellow
so it does not look like an error
