### ISSUE TITLE
Auto set title not subject to immediate validation

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#713]
The title picked up from the video file being selected in an upload is not automatically subjected to the title string validation. Instead, the possible error occurs when the user attempt to actually publish the video:

![Screenshot 2021-06-04 at 14 23 36](https://user-images.githubusercontent.com/437292/120801448-77e56300-c541-11eb-9636-14e236a01837.png)

**Comment by kdembler** [comment]
It's not really about the title being auto-filled, this is a general approach we use - we don't do validation until first attempt to submit. Only then the validation will be in real-time. If you think that's not the best way to proceed, we can change that to validate whenever user leaves a field. I think in general our approach makes sense however it may not be the best in our specific case because we don't let user know anything about the validation that will be applied. So they're not able to tell that the title cannot be longer than 40 characters. Wdyt?

**Comment by kdembler** [comment]
After most recent changes this is actually a bug
