### ISSUE TITLE
Misleading interaction

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#795]
When publishing I often find myself attempting to scroll while the cursor is in this area (green), this is particularly bad the wider your screen is, but the area frequently still appears with quite narrow window sizes. It is a significant problem.

![Screenshot 2021-06-17 at 00 31 49](https://user-images.githubusercontent.com/437292/122303408-cad8f600-cf03-11eb-96d6-681d622bb1bd.png)

**Comment by KubaMikolajczyk** [comment]
To avoid this misleading interaction I propose to introduce scrolling on the Video workspace content as a whole instead of scrolling just the form itself. Of course we would have to do it differently on desktop where we have two columns and tablet/mobile where we have one column.

You can test solutions below:

Prototype for two columns layout: [Desktop link](https://bit.ly/3xTdLVs)
Prototype for one column layout: [Tablet link](https://www.figma.com/proto/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?page-id=9818%3A262848&node-id=9818%3A263990&viewport=513%2C701%2C0.42195576429367065&scaling=scale-down)

Page in Figma with additional comments: [Figma page](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9818%3A263583)
