### ISSUE TITLE
Player's UI revamp/overhaul

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#821]
The scope of this task is:
- To make the currently available controls visually aligned with the JS design system (through the use of components from the JS component library or through introducing new components, based on previously established style guide).
- To ensure a working mobile experience for each functionality mentioned below.

And to adjust the logic behind showing/hiding player's UI:
- To hide the player's UI immediately after the cursor leaves the player area.
- To hide the player's UI after 3 seconds (? to be confirmed through research and testing) after the playing has been resumed.

---

_Based on: #785_

**Comment by toiletgranny** [comment]
Designs for this can be found here:
- [Interacting with player controls](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=10070%3A361806),
- [Toggling play/pause](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9977%3A269931),
- [Controlling volume](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9981%3A257165),
- [Toggling full screen](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9981%3A257254),
- [Toggling Picture-in-Picture Mode](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9981%3A257679),
- [Toggling Cinema / Default Mode](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9981%3A257177),
- [Toggling CC/ Subtitles](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9981%3A257266).

**Comment by bedeho** [comment]
# Feedback

Overall this looks great!

1) I think it would be great if the size of the controls in the player were augmented by the size of the player itself. Right now, the controls are fixed size. It would be better if they were scaled with the size of the player, in order to make more effortless to aim and interact.

2) In the spirit of making interactions more effortless, it wold be great if there was a hover interaction on every button or nob. So when you come close, the size of the button or nob grows a bit. This can occur outside the narrow boundry of the icon or figure. So this would apply for example to the play, pause, and also the nob on the volum control or progressbar.

3) Its not entirely clear to me what this design says about how the player itself shold adjust to the aspect ratio of the media. All media does not have the same aspect ratio, althrough we prefer a specific one. You could have a player which always has a fixed aspect ratio, and then just adjust the media dimensions, or you could have something more flexible, as YouTube does, where it will adjust to the media also.
This becomes particular important when one wants to go for full screen mode, as the screen aspect ratio varies for different screens.

4) For the final screen I think we can actually go for an auto suggested next video. Lets not allow the creator to specify the next video, as this would also require changes on the publishing side, and its not clear we want to really stay with a feature like that. We can easily auto suggest a next video by just picking another random video from the same channel, or, if this was the only video, pick another video in the same category. This works well enough, and does the minimal job of inducing people to stay on for longer.

5) For the loading state, would there still be some indication of progress towards playback actually beginning somewhere? because this animation does not do that.

**Comment by toiletgranny** [comment]
Hey @bedeho, thanks so much for your feedback!

1. Frankly, as I was testing the Figma prototype on my mobile phone, I didn't find the need to increase the size of player controls to accommodate for finger size. However, we agreed with @drillprop to remain flexible when it comes to small changes/adjustments to the player component on mobile/touch screens, in the implementation phase. I'll keep an eye on this, now that you brought it up.

2. We have a hover/active/focus state for every control within the Player component. I'm not sure if you've missed that while playing with the Figma prototype, or whether you're looking for something more pronounced (in which case, please let me know) but this is how it looks like right now:
![CleanShot 2021-07-05 at 12 34 52](https://user-images.githubusercontent.com/35307309/124458621-7e0f6f00-dd8d-11eb-906a-6cb0d40618fc.gif)

3. Since the current video content page supports only the "cinema mode", I don't think the current behavior needs to change. I run several experiments, before the design phase, to test how different aspect ratios are handled with the current JS player ([you can see it here](https://play.joystream.org/channel/143)) and we come into a conclusion that the current behavior is 100% fine. This is also how YouTube handles it while playing in the "cinema mode". Now, handling different aspect ratios in the "default player mode" is something I plan to tackle while thinking about the changes/adjustments to the video content page. :)

4. That actually makes a lot of sense! I've discussed this with @drillprop earlier today and we agreed to proceed with the suggested next video screen included as part of the MVP. We will, however, keep the simpler version (with just the channel name and the replay button) in case there are no other videos uploaded by the author.

5. I'm not 100% sure if this is what you meant, but the player's UI will remain available to you when the video is loading in the background. So: yes, as a user, you will be able to see the progress of the video when it's loading. 
![CleanShot 2021-07-05 at 12 32 35](https://user-images.githubusercontent.com/35307309/124458487-50c2c100-dd8d-11eb-9377-fc1b456a0c43.gif)

**Comment by bedeho** [comment]
1. When going to mobile, it would be a question of reducing, not increasing, but perhaps this is what you meant. What I am thinking more about is going to bigger sizes, where retaining small controls is a worse experience, at least for me. What comes to mind is the excellent experience I have with the Netflix player, they have invested much more in making sure full/cinema mode works well, because this is primary mode for their content. I often consume YT content in fullscreen mode also, and I think it would have worked better with similar treatment. Anyway, just have a look and see what you think.
2. Yes, and that is great, but do we have something for the scrubber button, and the button inside the volume control?
3. The current player also supports full screen mode, and full screen can be arbitrary aspect ratio effectively. No less important: we don't have it described in our designs how it is actually supposed to work, do we?
4. great.
5. great.

**Comment by toiletgranny** [comment]
Hey @bedeho,

1. Right, now I got you! Sorry, I assumed you were referring to the mobile experience. 🙈  Anyway, I think that's a very interesting point. While I'm not 100% convinced about scaling the player's UI all the time _by default_ just yet, I think it would make a lot of sense when going into full screen. I reached out to @drillprop to explore our options here, and we agreed to rewrite some of the CSS and use relative units (`em`), instead of absolute ones (`px`). By doing this we've built foundations for scaling player controls dynamically, based on the user's viewport size. We plan on using this later, once all the UI is in place and we're ready to tackle all the little adjustments related to responsiveness holistically, as the last step of the player's implementation process. For now, you can use [this link](https://deploy-preview-986--atlas-dev.netlify.app/video/1161) to preview the player in its current state of implementation and see how the UI scales up upon entering the full-screen mode. (Please note, that currently we scale it by 200%, but we know it's too radical. We'll adjust that later).

2. No, we don't, as both of them appear upon hovering _other_ elements, so I don't think an additional hover state is needed there. I'll experiment with adding subtle hover states anyway and let you know once we have something. :)

3. If I'm understanding this comment correctly, the most common approach for handling different aspect ratios on full-screen is scaling the video so that it fits the player area, keeping its original aspect ratio. Since this is what we already had with the previous Joystream player, I didn't want to change this, thus it's not described in our designs. Please, let me know if I'm still misinterpreting your comment; I'd love to discuss this with you in person, eg. during our Monday meeting. :)

**Comment by bedeho** [comment]
> If I'm understanding this comment correctly, the most common approach for handling different aspect ratios on full-screen is scaling the video so that it fits the player area, keeping its original aspect ratio. Since this is what we already had with the previous Joystream player, I didn't want to change this, thus it's not described in our designs. Please, let me know if I'm still misinterpreting your comment; I'd love to discuss this with you in person, eg. during our Monday meeting. :)

Ok, I guess if the policy is very obvious, then there is no need to document it. I dont think this policy is the best in all edge cases though, for example, try to make the window really short vertically, when in normal cinema mode, eventually the size becomes too small to really make sense. On YT, the policy is to stop this resizing at some breaking point where they deem it no longer sensible to make the video smaller. I don't think this kind of stuff is a big issue now, but I think a lot of these kinds of edge cases will become more important to think of when we go for the non-cinema standard player mode as part of the player screen redesign. Happy to leave this be for now.

**Comment by toiletgranny** [comment]
@bedeho Ok, now I see what you mean! Yes, this is exactly what I wanted to tackle when designing the video player _page_, not the video player _component_. You can rest assured that the case you've mentioned will be addressed in the designs for the video player page. :)

If you don't have any further comments for now, I'll close this issue so that we can move on with the whole milestone.
