### ISSUE TITLE
Search & Discover

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#874]
This page is a part of a discovering new content experience. 

### Links

Search & Discover on Figma: [Figma link](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9775%3A4614)
Figma prototype : [Prototype link](https://www.figma.com/proto/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?page-id=9147%3A79&node-id=9373%3A1506&viewport=-20337%2C905%2C1.3755624294281006&scaling=min-zoom)
Card animation prototype: [Card animations](https://www.figma.com/proto/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?page-id=9470%3A253095&node-id=9470%3A253104&viewport=787%2C232%2C0.08659876883029938&scaling=min-zoom)

**To get more in-depth knowledge about the page consider watching video update in the comment below 👇**

**Comment by KubaMikolajczyk** [comment]
### Video update from 25.06.2021
https://play.joystream.org/video/1542

**Comment by bedeho** [comment]
# Feedback

First off, thanks for the recording, it was extremely clear and effective, lets keep doing this unless there was significant overhead for you to do this.

## Questions

1. Is it the case that just going to the new search box will not display the full category screen? You have to click the `Search` item in the menu to get this? Or do both do this? If both do, then I don't see the need for having a `Search` item in the menu.
2. Did you intend to replace the [`Explore`](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9105%3A236997) screen with this search experience, or did you just forget to include it?
3. You did not describe what happens when you actually get the full search result? What does that screen look like?
4. You have segmented the cards into `Most popular` and `May interest you`, what is the basis for this? Is it the amount of content in each category? Is it human curated? (The latter seems best too me)
5. If I am inside a category, like `Film & Animation`, and then I go to another screen, and then I click `Search`again, does it remember that I was in  `Film & Animation`? 

## Comments

1. Overall I find the idea really promising.
2. `Trending searches` does not seem useful to me, and its in the most precious location. The diversity of searches is immense, its not like trending topics Twitter - where lots of people are by definition coordinated around the same thing, also we don't have any easy way to support this on the infrastructure side.
3. If we are assuming some categories are more important than the other, than the visual presentation of the more popular ones may deserve more salience, right now its all flat, only distinguished by vertical location.
4. The biggest problem I see is that very little attention is directed at what actually distinguishes the categories. Here is only the small thin text. The patterns and high contrast colors are not useful ways for people to distinguish, yet they are at least as attention grabbing, if not more. I think the original Spotify example also shows that they give the titles really prominent high contrast attention, even using custom imagery with meaning. I think since the space of categories will be very stable, and also because a subset of them will have most relevance, its worth investing in making them far more distinguishable.
5. While our directory is small, could it be useful to actually show a small counter in each card also, indicating how much content is there?
6. Lets drop `All` 
7. If we want to support both modes of displaying search previews, then we have to have a much clearer interaction for switching between them, I don't think I would have every discovered that extra click. But I think we should start easy and just go with only the simpler one you suggested.
8. I loved the featured in category version, really great. It would be cool if we had the ability to have more than a single video featured, so there could be a way to click next to see the next video.
9. Being able to search only in the given category could also make sense? basically in the same place as the filters in the category.

**Comment by toiletgranny** [comment]
Hello @bedeho, I will be taking the designs for the Discover page over from @KubaMikolajczyk. We met yesterday to discuss answers to your questions and comments.

## Questions
1. No. Clicking on the search bar will not automatically take you to the ~Explore~ Discover page. Please note, that everything concerning the experience around the search bar will be tackled in a "Search" sprint.
2. No. As mentioned above, search will be tackled in a "Search" sprint and **will not replace** the current ~Explore~ Discover page.
3. _To be tackled in a "Search" sprint._
4. There is no logic behind this in the current designs, as of now. Kuba's high-level intention was to diversify the page layout and not present the user with a grid of 16 the same looking tiles. I'll look into that more closely and try to come up some logic.
5. No, Kuba's intention was to always have the user landing on the initial view of the ~Explore~ Discover page. :)

## Comments
1. 👍
2. I see your point. We agreed with Kuba to remove this section altogether. 
3. I agree! I'll iterate on that for sure.
4. ☝️ 
5. That's an interesting idea. I can also see value in this, as long as the directory of videos is still small. But once Atlas becomes the world's leading video sharing platform (which I'm sure is a matter of time), then I'm afraid having eg. "56M videos uploaded under Film & Animation" would probably not be the most helpful information ever. Perhaps we could display the number of new videos uploaded daily, or weekly? I'll explore this for sure! 
6. Got it.
7. I was told you already had discussed this point with Kuba. Plus, this will be tackled in a "Search" sprint.
8. I remember Kuba iterating on this idea before, but perhaps we could revisit that. I'll definitely explore our options here.
9. _To be tackled in a "Search" sprint._

**Comment by kdembler** [comment]
Design for both search and discover features has been finished and is being implemented, closing this issue
