### ISSUE TITLE
Bad view of slow asset download

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#877]
The loading of visual assets is frequently quite slow, this is in part due to performance of storage providers - which will improve over time as the DAO operates more effectively, and possibly other factors about Atlas. More importantly, the way this is dealt with is not great at the moment, you see this sort of preview

![Screenshot 2021-06-25 at 18 37 07](https://user-images.githubusercontent.com/437292/123485566-a4edd880-d60a-11eb-8812-d19c18df5dcf.png)

A screen filled with a bunch of these is really not great, it looks like something went wrong.

Could we find a better loading state here? could we perhaps just use the existing loading state for longer?

**Comment by bedeho** [comment]
An additional problem is that, when rendering images, there is bad intermediate state when they are being fetched, which leads to large blocks of white which shrink all over the screen as images are filled in. This transition ideally should be hidden.

![Screenshot 2021-06-26 at 10 26 09](https://user-images.githubusercontent.com/437292/123507343-21170900-d669-11eb-9918-d56a47e2bfa8.png)

**Comment by kdembler** [comment]
Just checked, the browser gives us the following info:
- the image started downloading (there's _some_ progress)
- the image is fully loaded

So AFAICT, we should have a full flexibility in terms of what the technology allows us to do, let's design a good experience for this

**Comment by bedeho** [comment]
Correct me if I am wrong, but the currently deployed improvement to the situation above seems to work quite well already, is the policy just to show loader component until you know the URL of all assets on screen, and when you do, you allow each preview to load independently, and show its downloader component until the asset is fully downloaded?

**Comment by kdembler** [comment]
Yeah, this has changed slightly since we had the discussion, the current policy is:
1. show the full video tile placeholder until we have data from query node
2. show video metadata but use greyed out box for the thumbnail until the storage provider starts responding with the image
3. show the image loading/loaded image

**Comment by bedeho** [comment]
The behaviour has been changed here, and @toiletgranny should review it either accept or recommend changes.

**Comment by toiletgranny** [comment]
Overall, this for sure looks much better than the starting point of this discussion. There are, however, a couple of tweaks we could consider to step it up.

1. It seems we're still using old skeleton loaders. Remember the new ones that we discussed [back in May](https://www.figma.com/file/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?node-id=8732%3A0)? **These are ready to be implemented and — ideally — we could have _that_ instead of the current video tile placeholder** (displayed "until we have data from query node").

2. Alternatively, we agreed that until we find some time to fully implement new skeleton loaders, we could simply adjust the colors of the current one in the interim. And so, I would recommend replacing:
a. `rgb(82, 97, 107)` color with → `Neutral / 800` (`#181C20`)
b. `rgb(49, 58, 64)` color with → `Neutral / 900` (`#0B0C0F`)

3. The "_greyed out box for the thumbnail until the storage provider starts responding with the image_", with a wave gradient, is a bit off, to my taste. Another thing we can do to trick our perception into thinking the loading is faster is using [placeholder dominant color](https://manu.ninja/dominant-colors-for-lazy-loading-images/). @kdembler do you think we could actually use that over here? Would it be possible to have that implemented for both the video thumbnail placeholder as well as the channel avatar placeholder?
a. In case this is possible, I would recommend applying an additional 50% black overlay on the generated dominant color, so that it blends with the black background a little bit easier.
b. Also, I would recommend adding a subtle fade animation between the thumbnail/avatar placeholder and the real image. I'm thinking about `100ms` and `ease-out`.

I put up a quick comparison prototype of how a video tile is loaded now and how it can look if we go with the above suggestions. You can see it here — [FIGMA LINK](https://www.figma.com/proto/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?page-id=8456%3A0&node-id=12271%3A468018&viewport=458%2C77%2C0.28560787439346313&scaling=scale-down&starting-point-node-id=12271%3A467075&show-proto-sidebar=1).

| Before (currently)  | After |
| ------------- | ------------- |
| ![CleanShot 2021-08-03 at 15 13 17](https://user-images.githubusercontent.com/35307309/128021623-7de5c80b-e4a7-4fbc-81fe-315d61429cac.gif) | ![CleanShot 2021-08-03 at 15 13 57](https://user-images.githubusercontent.com/35307309/128021729-3967ab73-05e2-4ecf-8c49-be2a4d5e7f7d.gif)  |

**Comment by toiletgranny** [comment]
@bedeho, after discussing this with @kdembler yesterday, here's an updated proposal, in regards to my previous points:

1. ✅  This is already in the making by @eldiegod, so we can cross that off this list.
2. ✅  The same as above.
3. Klaudiusz explained to me why it would be problematic to have the placeholder dominant color implemented in Atlas, as a replacement for images that are still being loaded. So instead, my recommendation would be to simply keep the animated wave loader displayed in those places, for as long as it takes to load and display the image. See the preview below, [and here's a Figma prototype](https://www.figma.com/proto/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?page-id=8456%3A0&node-id=12369%3A377891&viewport=-1079%2C-883%2C0.2776763141155243&scaling=scale-down&starting-point-node-id=12369%3A377874&show-proto-sidebar=1).

| Before (currently)  | After (updated) |
| ------------- | ------------- |
| ![CleanShot 2021-08-03 at 15 13 17](https://user-images.githubusercontent.com/35307309/128021623-7de5c80b-e4a7-4fbc-81fe-315d61429cac.gif) | ![CleanShot 2021-08-05 at 10 58 57](https://user-images.githubusercontent.com/35307309/128322797-eb6ab97e-7a7d-4b1b-9d41-a2adc0bc69ee.gif)
 |

**Comment by bedeho** [comment]
This looks sharp, love it, but I wonder if you check how this looks when you see a full grid of these loading like this? There was more uniformity in the loading effect before, but now there is this diagonal effect, will that still work well? Just good if you can check that, otherwise looks sharp ;)

**Comment by toiletgranny** [comment]
@bedeho Yes, we did this together with @kdembler. You can see it in [this Figma prototype](https://www.figma.com/proto/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?page-id=8456%3A0&node-id=12369%3A378262&viewport=-1079%2C-883%2C0.2776763141155243&scaling=scale-down&starting-point-node-id=12369%3A378056&show-proto-sidebar=1).

(💡  Hit "R" to reset the prototype and play the animation again)

**Comment by kdembler** [comment]
I've created #1182 for implementation, I think we can close this as design work is done? @toiletgranny
