### ISSUE TITLE
New discovery mode product review

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#878]
# Background

The following set of designs were prepared for how we can improve discovery

https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/?node-id=6215%3A2622

Base on that design, @klaudiusz made the following comment about the fundamental technical requirements of being able to put this into production

https://github.com/Joystream/atlas/issues/132#issuecomment-863874230

He identified multiple limitations of our current system, and proposed two alternatives for moving forward with the design above.

# Overview

The following constraints guide my review of the design and the issues identified

1. Our current content directory is still small (200+ channels, 1400+ videos, 30-100+ videos per day), albeit growing, and the level of quality is very variable.
2. We are not going to use viewing history of the viewer, or certainly of other users, to surface content for in the short-term. This may be totally feasible later (most likely the gateway should do this, since they have the data & business model), but right now it is of limited value, given the prior point about the size of the directory, and also compared to other focus areas.
3. It is still not clear what model we should use long-term to retain and serve data like video counts, viewing events, follower counts and follow events. Most likely this should be held by the content directory lead in some easy verifiable and easy to replicate data store (like Dat), but we have not spent any time thinking about this. The value add of getting this right at the moment is limited, and picking a solution when we have limited information is not ideal.

For reasons above, relying on human curation for primary dynamic discovery, seems wisest . Human curation solves (1) the best, does not need (2) or (3), is cheap and flexible and provides additional meaningful tasks for the curators in the DAO. Indeed, in the early days of YouTube, the human curated front-page was a primary discovery mechanism, and that is closest to where we are at the moment.

Based on this conclusion, and my more detailed remarks below, I suggest we do another iteration on the designs for discovery and update.

# HOME

## General

We need two distinct variations of this screen:
one for when you are following == 0 and one for when you are following > 0. Where
we would have some way of surfacing content from people you follow in one case, but not
the other.

A note about the current way this is handled. Right now, if I follow someone, their videos are shown on my HOME screen - which is great, but if someone all of a sudden uploads lots of videos in a row - something which frequently happens, then my entire HOME screen is just content from one creator. So there may perhaps need to be some sophistication in displaying content from people you follow beyond the simplest possible approach.

I think this is the screen where it's most important to control, through curation, what people see, because it is the first impression, and repeated impression, people have when they open the app. For example having a set of feature videos & channels really makes sense in this experience.

## Continue watching

This feature does more harm than good at the moment. The majority of content
people, including myself engage in is either a video I uploaded myself, or
some random video I clicked on while doing browsing. I almost never really want
to return and continue watching the same video. The quality level has to be
at least an order of magnitude greater, and, the density of such videos in the
overall pool has to be much greater, given that any video you watch automatically
ends up here. I think we can reintroduce something like this that is  result
of deliberate action from the user, but its no urgent now, so I think we should
just disable it.

## Popular on Joystream

I do not think this really makes sense here. This ranking will be very stable from day to day, hence we would end up with a very static lineup in a primary visual location like this. Could some curation driven make most sense as the first and most prominent visual location? Something using the ranked 1,2,3 display format we already have?

## Most popular Category section

- Would require knowing total number of views for each category. Not easy to do.
- Would require getting ranked list of videos by views in a category. Not easy to do.
- Seems like, if we want this, it could be hard-coded, we don't have that many categories,
and the top category by views will not be very dynamic.

All in all I a think this category focus may not be all that useful here, it could make sense if we knew the user cared about a particular category, but just privileging a category as a mode of discovery globally seems arbitrary.

## Top 10 this week

Would require adding a new API, but could work.

## Random category

I don't think this is useful, let's drop.

## Official Joystream update

Should be easy, and is useful for the project.

## Discover channels

Should be fine, but the criterion is not explicit, we have to pick either followers, or views, or some explicit way to combine them. I suggest going by followers, it's very straight forward.

## Random category

I don't think this is useful, let's drop.

## All channels

Let's rename to "All content", but this is a nice final filler.

# POPULAR

## Top 10 on hype today

I think daily rankings will be based on very little data with our current level of traffic, so weekly would make more sense. Would require introducing some new API in Orion, but it could work fine.

## Popular videos

Seems straight forward.

## Most viewed playlists

Probably also fine, but we cant ship this before we actually have playlists. In either way, I think playlists should be below channels, channels are more important engagement items.

## Discover new channels

Again metric is not clear, probably just using followers is best.

# NEW & NOTEWORTHY

## Recent and fresh content

Once the number of videos uploaded per day gets a bit bigger (its already >100 on some days), this will get super slow with our current infrastructure, because we need to fetch traffic stat of all these videos and rank. Alternatively, we would need to introduce an API call where we can send a bunch of videos, and get the top x back in terms of their view count over some time period. The alternative would be to have curators pick.

**Decision needed**

## Promising new channels

This rule is too complex to easily implement with current Orion, if we just simplify to last N channels with at least Y videos, we can do it just using our query node, and it would give a pretty decent effect of showing recent non-empty channels.

## Videos you might have missed

Too complex, and its not even informed by what the viewer has actually seen, so lets drop

# Browse channels

## Top 10 Channels

Seems fine.

## Promising new channels

Change to same as on the HOME screen.

## Channels in your language

This rule was very complex, perhaps just going with top channels, by #videos, in your language, is sufficient.

## Popular channels

This seems very similar to 10 channels really, is it needed? I would say drop.

**Comment by KubaMikolajczyk** [comment]
@bedeho 
Feedback above was implemented into designs 👆 The video content pages were divided into separate pages in figma along with the components.

📄 Pages:
**Home** : [Link to home](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=10080%3A354864)
**Popular** : [Link to popular](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9105%3A233873)
**New&Noteworthy** : [Link to new&noteworthy](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9105%3A235186)
**Browse channels** : [Link to browse channels](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=8408%3A3917)

⚙️ Components:
**Video section** : [Link](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9064%3A665)
**Video hero** : [Link](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9050%3A226840)
**Page cta card** : [Link](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9097%3A178)
**Channel section** : [Link](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=10114%3A287590)
**Channel card** : [Link](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=8321%3A210163)

### Few propositions:
1.On all pages (except home) - As we are currently focusing on Main, Popular, New&Noteworthy and Browse channels pages and leave discover pages for later implementation - in page cta cards (on other page than home) we can link temporarly to home as well instead of linking to discovery which we dont have yet
![image](https://user-images.githubusercontent.com/31144205/124102150-6750db80-da60-11eb-9466-d82596d61d67.png)
on home we would show all 3 of those
![image](https://user-images.githubusercontent.com/31144205/124103534-a895bb00-da61-11eb-82ac-6ba07e2cbb9a.png)

2. Home page - has a second version for the case when user is following at least one channel or more and this would feature a followed channels section showcasing newest content from those channels in randomized order
![image](https://user-images.githubusercontent.com/31144205/124102637-d4fd0780-da60-11eb-9060-60f61fd36648.png)

3. Home page - Discover new channels on the main page could be curated channels to elevate content of the highest quality - not the ones with the most followers (we already have popular channels section in popular page using that logic)
![image](https://user-images.githubusercontent.com/31144205/124102930-17bedf80-da61-11eb-8087-eee3561f1807.png)

4. Popular page - we had top 10 on hype today - the proposition was to change it to top 10 on hype this week / but we already have such section on the main page - maybe we could present top 10 this month instead 
![image](https://user-images.githubusercontent.com/31144205/124103311-708e7800-da61-11eb-860e-23e635c630d7.png)

5. New&Noteworthy page - we had a section fresh and new content & decided to let it be curated - i proposed an idea how this could work and a new naming for this section as it would be more accurate
![image](https://user-images.githubusercontent.com/31144205/124103887-03c7ad80-da62-11eb-8d10-acbf2dcaf054.png)

**Comment by bedeho** [comment]
Lets go with that, great job :)
