### ISSUE TITLE
Chrome can't upload or reproduce .mov videos?

### ISSUE THREAD

**Issue by eldiegod** [Joystream/atlas#981]
Investigate/find a possible fix.

Context by Adam-netguru designer:
"I'm unable to upload a mov file using Chrome, as the the uploader "accepts any format supported by your browser". With Firefox, on the other hand, I was able to upload a mov file. So my understanding is that Chrome does not accept mov files and Firefox does. Ok, fair enough so far.

And so once the file was uploaded on Firefox (here it is: https://play.joystream.org/video/2096) it came as a surprise to me that I was also able to play it in Chrome. I thought: how come? Haven't I, as a user, just been told that Chrome wants nothing to do with mov files?"

**Comment by drillprop** [comment]
We should possibly make some changes in `src/utils/video.ts`. When a user is adding the video, we are running [canPlayType](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType) to check if the video is valid. It turns out this method could return the wrong value. Found this on StackOverflow: https://stackoverflow.com/questions/60893202/how-come-canplaytypevideo-mov-returns-an-empty-string-but-i-can-still-play

**Comment by eldiegod** [comment]
Yes, that seems to be the issue indeed, we might have to find another way to check that
